from PySide6.QtWidgets import QFrame, QGraphicsDropShadowEffect
from PySide6.QtGui import QColor
from PySide6.QtCore import Qt, Property
class Paper:
    def __init__(self, parent, elevation, color, radius): ...
    def _blur_for_elevation(self, elevation: int): ...
    def getElevation(self): ...
    def setElevation(self, value: int): ...
    def getColor(self): ...
    def setColor(self, color): ...