# coding: utf-8

"""
    Fiscal document service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class RecipientRequest(BaseModel):
    """
    RecipientRequest
    """ # noqa: E501
    type: StrictStr = Field(description="Type of the recipient.")
    id: Annotated[int, Field(strict=True, ge=1)] = Field(description="ID of the recipient, references guestId, contactId, groupId, etc. depending on type.")
    tax_document_source: Optional[StrictStr] = Field(default=None, description="Source of the tax document number.", alias="taxDocumentSource")
    __properties: ClassVar[List[str]] = ["type", "id", "taxDocumentSource"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['GUEST', 'CONTACT', 'GROUP', 'COMPANY', 'GROUP_PROFILE', 'GROUP_PROFILE_CONTACT']):
            raise ValueError("must be one of enum values ('GUEST', 'CONTACT', 'GROUP', 'COMPANY', 'GROUP_PROFILE', 'GROUP_PROFILE_CONTACT')")
        return value

    @field_validator('tax_document_source')
    def tax_document_source_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['GUEST_TAX_ID', 'GUEST_DOCUMENT_NUMBER']):
            raise ValueError("must be one of enum values ('GUEST_TAX_ID', 'GUEST_DOCUMENT_NUMBER')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RecipientRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RecipientRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "id": obj.get("id"),
            "taxDocumentSource": obj.get("taxDocumentSource")
        })
        return _obj


