from typing import Optional, List
from PySide6.QtWidgets import QApplication, QWidget, QVBoxLayout, QScrollArea, QProgressBar, QLabel
from PySide6.QtCore import Qt, Signal, Slot, QTimer
class Scrollbar:
    def __init__(self, autoHide: Optional[bool], children: Optional[List], maxHeight: int, maximumHeight: int, fixedHeight: int, sx: object, ref: object): ...
    def init_ui(self): ...
    def _set_children(self): ...