import uuid
from typing import Optional, Union, Dict, List, Callable
from PySide6.QtWidgets import QHBoxLayout, QWidget
from PySide6.QtCore import Qt, QSize
from qtmui.hooks import State
from qtmui.material.styles import useTheme
from ..utils.validate_params import _validate_param
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
class ListItemAvatar:
    def __init__(self, children: Optional[Union[State, QWidget, List[QWidget]]], classes: Optional[Union[State, Dict]], sx: Optional[Union[State, List, Dict, Callable, str]], **kwargs): ...
    def _set_children(self, value): ...
    def _get_children(self): ...
    def _set_classes(self, value): ...
    def _get_classes(self): ...
    def _set_sx(self, value): ...
    def _get_sx(self): ...
    def _init_ui(self): ...
    def _apply_sx(self, sx): ...
    def _apply_classes(self, classes): ...