import asyncio
import threading
from functools import lru_cache
from typing import Callable
from qtmui.material.styles import useTheme
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
from qtmui.utils.data import deep_merge
class TextFieldStyleMixin:
    def __init__(self, **kwargs): ...
    def style_set_sx_dict(cls, sx): ...
    def style_set_owner_state(cls, kwargs: dict): ...
    def style_get_sx_qss(cls, sxStr: str, className: str): ...
    def style_schedule_set_stylesheet(self): ...
    def style_render_stylesheet_async(self): ...
    def style_get_stylesheet(cls, styledConfig: str, _variant: str, _size: str, _theme_mode: str, _multiple: str, _multiline: str, _renderTags: str, _focused: str): ...
    def style_render_stylesheet(self): ...
    def style_set_stylesheet(self): ...
    def style_apply_stylesheet(self, stylesheet): ...