from typing import Optional, Union, Callable
from PySide6.QtWidgets import QSizePolicy, QHBoxLayout, QFrame
from PySide6.QtCore import Signal
from qtmui.hooks import State
from qtmui.common.ui_functions import clear_layout
from ..button.button import Button
from ..button.loading_button import LoadingButton
from ..qss_name import *
class SubmitButton:
    def __init__(self, type: str, loading: Optional[State], **kwargs): ...
    def _initUi(self): ...
    def _updateLoading(self, value): ...
    def __onClick(self): ...