from typing import Optional, Union, Dict, List, Callable
import uuid
from PySide6.QtWidgets import QFrame, QWidget, QGraphicsDropShadowEffect, QVBoxLayout, QLabel
from PySide6.QtGui import QColor
from PySide6.QtCore import Qt, Property
from qtmui.material.system.color_manipulator import rgbaToQColor
from qtmui.material.typography import Typography
from qtmui.hooks import State
from qtmui.material.styles import useTheme
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
class Paper:
    def __init__(self, parent, children: Optional[Union[State, str, QWidget, List[QWidget]]], classes, component: Optional[Union[State, QWidget]], elevation: Union[State, int], square: Union[State, bool], sx: Optional[Union[State, List, Dict, Callable, str]], variant: Union[State, str], color, *args, **kwargs): ...
    def _blur_for_elevation(self, elevation: int): ...
    def _update_style(self, component_styled): ...
    def getElevation(self): ...
    def setElevation(self, value): ...
    def getVariant(self): ...
    def setVariant(self, value): ...
    def getSquare(self): ...
    def setSquare(self, value: bool): ...
    def getColor(self): ...
    def setColor(self, color): ...
    def getSX(self): ...
    def setSX(self, sx): ...