from PySide6.QtWidgets import QApplication, QFrame, QLabel, QVBoxLayout, QWidget, QSizePolicy, QLineEdit, QLayout, QLayoutItem, QScrollArea, QPushButton
from PySide6.QtCore import Qt, QRect, QSize, QPoint, QTimer
class FlowLayout:
    def __init__(self, parent, children, margin, hSpacing, vSpacing, alignment): ...
    def __del__(self): ...
    def addItem(self, item): ...
    def count(self): ...
    def itemAt(self, index): ...
    def takeAt(self, index): ...
    def expandingDirections(self): ...
    def hasHeightForWidth(self): ...
    def heightForWidth(self, width): ...
    def setGeometry(self, rect): ...
    def sizeHint(self): ...
    def minimumSize(self): ...
    def doLayout(self, rect, testOnly): ...
    def _alignItems(self, row_items, available_width, start_x, y, rect): ...
class FlowWidget:
    def __init__(self, parent, children): ...