import _abc
import typing
from csp_lib.manager.command.schema import CommandRecord, CommandStatus
from typing import Any, ClassVar

__all__ = ['CommandRepository', 'MongoCommandRepository']

class CommandRepository(typing.Protocol):
    __parameters__: ClassVar[tuple] = ...
    _is_protocol: ClassVar[bool] = ...
    __abstractmethods__: ClassVar[frozenset] = ...
    _abc_impl: ClassVar[_abc._abc_data] = ...
    __protocol_attrs__: ClassVar[set] = ...
    def create(self, record: CommandRecord) -> str: ...
    def update_status(self, command_id: str, status: CommandStatus, result: dict[str, Any] | None = ..., error_message: str | None = ...) -> bool: ...
    def get(self, command_id: str) -> CommandRecord | None: ...
    def list_by_device(self, device_id: str, limit: int = ...) -> list[CommandRecord]: ...
    @classmethod
    def __subclasshook__(cls, other): ...
    def __init__(self, *args, **kwargs) -> None: ...

class MongoCommandRepository:
    COLLECTION_NAME: ClassVar[str] = ...
    def __init__(self, db: AsyncIOMotorDatabase, collection: str = ...) -> None: ...
    def create(self, record: CommandRecord) -> str: ...
    def update_status(self, command_id: str, status: CommandStatus, result: dict[str, Any] | None = ..., error_message: str | None = ...) -> bool: ...
    def get(self, command_id: str) -> CommandRecord | None: ...
    def list_by_device(self, device_id: str, limit: int = ...) -> list[CommandRecord]: ...
