# coding: utf-8

"""
"""


## NOTE: This file is auto generated by the swagger code generator program.
## Do not edit the file manually.

import pprint
import re  # noqa: F401
import six
from typing import TYPE_CHECKING

import enum

class InfoContainerType(str, enum.Enum):
    ACQUISITIONS = "acquisitions"
    ANALYSES = "analyses"
    COLLECTIONS = "collections"
    CONTAINERS = "containers"
    PROJECTS = "projects"
    SESSIONS = "sessions"
    SUBJECTS = "subjects"
    FILES = "files"

    def __str__(self):
        return self.value
