# coding: utf-8

"""
"""


## NOTE: This file is auto generated by the swagger code generator program.
## Do not edit the file manually.

import pprint
import re  # noqa: F401
import six
from typing import TYPE_CHECKING

class ZipfileMemberInfo(object):

    swagger_types = {
        'path': 'str',
        'size': 'int',
        'timestamp': 'datetime',
        'comment': 'str'
    }

    attribute_map = {
        'path': 'path',
        'size': 'size',
        'timestamp': 'timestamp',
        'comment': 'comment'
    }

    rattribute_map = {
        'path': 'path',
        'size': 'size',
        'timestamp': 'timestamp',
        'comment': 'comment'
    }

    def __init__(self, path=None, size=None, timestamp=None, comment=None):  # noqa: E501
        """ZipfileMemberInfo - a model defined in Swagger"""
        super(ZipfileMemberInfo, self).__init__()

        self._path = None
        self._size = None
        self._timestamp = None
        self._comment = None
        self.discriminator = None
        self.alt_discriminator = None

        self.path = path
        self.size = size
        self.timestamp = timestamp
        self.comment = comment

    @property
    def path(self):
        """Gets the path of this ZipfileMemberInfo.


        :return: The path of this ZipfileMemberInfo.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this ZipfileMemberInfo.


        :param path: The path of this ZipfileMemberInfo.  # noqa: E501
        :type: str
        """

        self._path = path

    @property
    def size(self):
        """Gets the size of this ZipfileMemberInfo.


        :return: The size of this ZipfileMemberInfo.
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this ZipfileMemberInfo.


        :param size: The size of this ZipfileMemberInfo.  # noqa: E501
        :type: int
        """

        self._size = size

    @property
    def timestamp(self):
        """Gets the timestamp of this ZipfileMemberInfo.


        :return: The timestamp of this ZipfileMemberInfo.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this ZipfileMemberInfo.


        :param timestamp: The timestamp of this ZipfileMemberInfo.  # noqa: E501
        :type: datetime
        """

        self._timestamp = timestamp

    @property
    def comment(self):
        """Gets the comment of this ZipfileMemberInfo.


        :return: The comment of this ZipfileMemberInfo.
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this ZipfileMemberInfo.


        :param comment: The comment of this ZipfileMemberInfo.  # noqa: E501
        :type: str
        """

        self._comment = comment


    @staticmethod
    def positional_to_model(value):
        """Converts a positional argument to a model value"""
        return value

    def return_value(self):
        """Unwraps return value from model"""
        return self

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ZipfileMemberInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other

    # Container emulation
    def __getitem__(self, key):
        """Returns the value of key"""
        key = self._map_key(key)
        return getattr(self, key)

    def __setitem__(self, key, value):
        """Sets the value of key"""
        key = self._map_key(key)
        setattr(self, key, value)

    def __contains__(self, key):
        """Checks if the given value is a key in this object"""
        key = self._map_key(key, raise_on_error=False)
        return key is not None

    def keys(self):
        """Returns the list of json properties in the object"""
        return self.__class__.rattribute_map.keys()

    def values(self):
        """Returns the list of values in the object"""
        for key in self.__class__.attribute_map.keys():
            yield getattr(self, key)

    def items(self):
        """Returns the list of json property to value mapping"""
        for key, prop in self.__class__.rattribute_map.items():
            yield key, getattr(self, prop)

    def get(self, key, default=None):
        """Get the value of the provided json property, or default"""
        key = self._map_key(key, raise_on_error=False)
        if key:
            return getattr(self, key, default)
        return default

    def _map_key(self, key, raise_on_error=True):
        result = self.__class__.rattribute_map.get(key)
        if result is None:
            if raise_on_error:
                raise AttributeError('Invalid attribute name: {}'.format(key))
            return None
        return '_' + result
