import uuid
from typing import Optional, Callable, Union, List, Dict
from PySide6.QtWidgets import QWidget, QVBoxLayout, QFrame, QSizePolicy, QCalendarWidget
from PySide6.QtCore import Signal, QSize
from qtmui.material.styles import useTheme
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
from qtmui.i18n.use_translation import i18n
from qtmui.hooks import useEffect
class DateTimePicker:
    def __init__(self, anchorEl: QWidget): ...
    def reTranslation(self): ...
    def __init_ui(self): ...
    def _set_stylesheet(self): ...