from typing import Callable
from PySide6.QtCore import QAbstractTableModel, Qt, Signal, QModelIndex
from PySide6.QtGui import QColor, QFont
from qtmui.material.styles import useTheme
from qtmui.i18n.use_translation import translate, i18n
class DataGridModel:
    def headerData(self, section: int, orientation: Qt.Orientation, role: int): ...
    def __init__(self, parent, columns, rows): ...
    def retranslateUi(self): ...
    def restranUi(self): ...
    def __set_stylesheet(self): ...
    def rowCount(self, n): ...
    def columnCount(self, n): ...
    def flags(self, index: QModelIndex): ...
    def supportedDropActions(self): ...
    def _thread_set_index_model(self, index, widget): ...
    def data(self, index, role): ...
    def setData(self, index, value, role): ...
    def update_item(self, row, col, value): ...
    def change_color(self, row, column, color): ...