from typing import Optional, Union, Callable, Dict, Any, List
from PySide6.QtCore import QSize, Qt, Signal, QPoint, QRectF, QPointF, QPropertyAnimation, Property
from PySide6.QtGui import QColor, QPainter, QPainterPath, QMouseEvent
from PySide6.QtWidgets import QProxyStyle, QSlider, QWidget, QFrame, QHBoxLayout, QVBoxLayout, QSizePolicy
from ...common.style_sheet import FluentStyleSheet, themeColor
from ...common.overload import singledispatchmethod
from .sliders import DoubleSlider, RangeSlider, DoubleRangeSlider, MultiHandleRangeSlider, LabeledSlider, LabeledRangeSlider, LabeledDoubleSlider, LabeledDoubleRangeSlider
from qtmui.hooks import State
from qtmui.material.styles import useTheme
class Slider:
    def __init__(self, ariaLabel: Optional[str], ariaLabelledby: Optional[str], ariaValuetext: Optional[str], classes: Optional[Dict[str, Any]], color: Optional[str], components: Optional[Dict[str, Any]], componentsProps: Optional[Dict[str, Any]], defaultValue: Optional[Union[int, float, List[Union[int, float]]]], disabled: Optional[bool], disableSwap: Optional[bool], getAriaLabel: Optional[Callable[Any, str]], getAriaValueText: Optional[Callable[Any, str]], marks: Optional[Union[bool, List[Dict[str, Any]]]], max: Optional[Union[int, float]], min: Optional[Union[int, float]], name: Optional[str], onChange: Optional[Callable[Any, Any]], onChangeCommitted: Optional[Callable[Any, Any]], orientation: Optional[str], scale: Optional[Callable[Any, Any]], shiftStep: Optional[Union[int, float]], size: Optional[str], slotProps: Optional[Dict[str, Any]], slots: Optional[Dict[str, Any]], step: Optional[Union[int, float, Any]], sx: Optional[Union[Dict, Callable, str, List[Any]]], tabIndex: Optional[int], track: Optional[Union[str, bool]], value: Optional[Union[int, float, List[Union[int, float]]]], valueLabelDisplay: Optional[str], valueLabelFormat: Optional[Union[str, Callable[Any, Any]]], *args, **kwargs): ...
class SliderHandle:
    def __init__(self, parent: QSlider): ...
    def radius(self): ...
    def radius(self, r): ...
    def enterEvent(self, e): ...
    def leaveEvent(self, e): ...
    def mousePressEvent(self, e): ...
    def mouseReleaseEvent(self, e): ...
    def _startAni(self, radius): ...
    def paintEvent(self, e): ...
class ClickableSlider:
    def mousePressEvent(self, e): ...
class HollowHandleStyle:
    def __init__(self, config: dict): ...
    def subControlRect(self, cc, opt, sc, widget): ...
    def drawComplexControl(self, cc, opt, painter, widget): ...