from enum import Enum
from PySide6.QtCore import Qt
from PySide6.QtGui import QPainter, QColor
from PySide6.QtWidgets import QCheckBox, QStyle, QStyleOptionButton, QWidget
from ...common.icon import FluentIconBase, Theme, getIconColor
from ...common.style_sheet import FluentStyleSheet, isDarkTheme, ThemeColor, themeColor
from ...common.overload import singledispatchmethod
class CheckBoxIcon:
    def path(self, theme): ...
class CheckBoxState:
class CheckBox:
    def __init__(self, parent: QWidget): ...
    def _(self, text: str, parent: QWidget): ...
    def mousePressEvent(self, e): ...
    def mouseReleaseEvent(self, e): ...
    def enterEvent(self, e): ...
    def leaveEvent(self, e): ...
    def _borderColor(self): ...
    def _backgroundColor(self): ...
    def _state(self): ...
    def paintEvent(self, e): ...