FLOOR = {
    "amethyst brick floor",
    "amethyst dirt",
    "amethyst mineable",
    "amethyst rune",
    "brick floor",
    "citrine rune",
    "coal mineable",
    "copper brick floor",
    "copper door",
    "copper door open",
    "copper mineable",
    "dirt",
    "glass floor",
    "ice",
    "iron mineable",
    "lava",
    "lava rune",
    "lavastone brick floor",
    "lavastone floor",
    "log floor",
    "moist dirt",
    "mushroom door",
    "mushroom door open",
    "mushroom floor",
    "pebble",
    "rail 0",
    "rail 1",
    "rail 2",
    "rail 3",
    "rail 4",
    "rail 5",
    "sand",
    "sapphire rune",
    "slime door",
    "slime door open",
    "slime floor",
    "snow",
    "stone brick floor",
    "stone floor",
    "tin mineable",
    "void",
    "water",
    "wood door",
    "wood door open",
    "wood floor",
}
FLOOR_TYPE = {
    "ice": "block",
    "lava": "fluid",
    "void": "block",
    "water": "fluid",
}
FLOOR_DAMAGE = {
    "lava": 3,
    "water": 1,
}