SOIL_STRENGTH = {
    "snow": 0.85,
    "dirt": 1,
    "moist dirt": 1.25,
    "amethyst dirt": 1.4,
}
GROW_TIME = {
    "amethyst mineable": 120,
    "bluebell": 400,
    "caelium sapling": 200,
    "caelium treeling": 250,
    "carrot": 160,
    "coal sapling": 200,
    "coal treeling": 250,
    "copper pit": 600,
    "copper sapling": 200,
    "copper treeling": 250,
    "furless rabbit": 120,
    "lava": 150,
    "potato": 240,
    "quartz child": 40,
    "rabbit child": 200,
    "sapling": 80,
    "sapphire treeling": 200,
    "sapphire tree": 250,
    "slime summon": 40,
    "spore": 120,
    "tin sapling": 200,
    "tin treeling": 250,
    "treeling": 100,
    "water": 60,
}
GROW_TILES = {
    "amethyst mineable": {"kind": "amethyst"},
    "bluebell": {"kind": "bluebell grown", "inventory": {"bluebell": 2}},
    "caelium sapling": {"kind": "caelium treeling", "inventory": {"raw caelium": 1, "caelium sapling": 1, "log": 1}},
    "caelium treeling": {"kind": "caelium tree", "inventory": {"raw caelium": 2, "caelium ingot": 1, "caelium sapling": 1, "log": 2}},
    "carrot": {"kind": "carrot grown", "inventory": {"carrot": 2}},
    "coal sapling": {"kind": "coal treeling", "inventory": {"coal": 1, "coal sapling": 1, "log": 1}},
    "coal treeling": {"kind": "coal tree", "inventory": {"coal": 3, "coal sapling": 1, "log": 1}},
    "copper pit": {"kind": "copper pit grown", "inventory": {"copper ingot": 1}},
    "copper sapling": {"kind": "copper treeling", "inventory": {"raw copper": 1, "copper sapling": 1, "log": 1}},
    "copper treeling": {"kind": "copper tree", "inventory": {"raw copper": 2, "copper ingot": 1, "copper sapling": 1, "log": 2}},
    "furless rabbit": {"kind": "rabbit adult", "inventory": {"rabbit fur": 1, "rabbit meat": 1}},
    "lava": {"floor": "lavastone floor", "kind": "lavastone"},
    "potato": {"kind": "potato grown", "inventory": {"potato": 2}},
    "quartz child": {"kind": "quartz adult"},
    "rabbit child": {"kind": "rabbit adult", "inventory": {"rabbit fur": 1, "rabbit meat": 1}},
    "sapling": {"kind": "treeling", "inventory": {"sapling": 1, "log": 1}},
    "sapphire sapling": {"kind": "sapphire treeling", "inventory": {"sapphire": 1, "sapphire sapling": 1, "log": 1}},
    "sapphire treeling": {"kind": "sapphire tree", "inventory": {"sapphire": 2, "sapphire sapling": 1, "log": 2}},
    "slime summon": {"kind": "slime prince", "inventory": {"slife crystal": 1, "slime shaper": 1}},
    "spore": {"kind": "mushroom", "inventory": {"spore": 2}},
    "tin sapling": {"kind": "tin treeling", "inventory": {"raw tin": 1, "tin sapling": 1, "log": 1}},
    "tin treeling": {"kind": "tin tree", "inventory": {"raw tin": 2, "tin ingot": 1, "tin sapling": 1, "log": 2}},
    "treeling": {"kind": "tree", "inventory": {"sapling": 2, "log": 2}},
    "water": {"floor": "ice"},
}
GROW_REQUIREMENT = {
    "bluebell": 1.25,
    "caelium sapling": 1.25,
    "caelium treeling": 1.4,
    "copper sapling": 1,
    "copper treeling": 1.25,
    "potato": 1,
    "sapphire sapling": 1.4,
    "sapphire treeling": 1.5,
    "tin sapling": 1.25,
    "tin treeling": 1.4,
}
GROW_DIRT_IGNORE = {
    "copper pit",
    "furless rabbit",
    "quartz child",
    "rabbit child",
    "slime summon",
}
GROW_FROM = {
    "bluebell grown": "bluebell",
    "caelium tree": "caelium sapling",
    "carrot grown": "carrot",
    "coal tree": "coal sapling",
    "copper tree": "copper sapling",
    "mushroom": "spore",
    "potato grown": "potato",
    "sapphire tree": "sapphire sapling",
    "tin tree": "tin sapling",
    "tree": "sapling", 
}