import os
import sys
from typing import Any, Callable, Dict, Optional, Union
import uuid
from PySide6.QtWidgets import QTextEdit, QMainWindow, QVBoxLayout, QFrame, QStatusBar, QToolBar, QFileDialog, QComboBox, QFontComboBox, QMessageBox
from PySide6.QtCore import QSize, Qt
from PySide6.QtGui import QImage, QTextDocument, QAction, QFont, QKeySequence, QActionGroup
from PySide6.QtPrintSupport import QPrintDialog
from ..system.color_manipulator import alpha
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
from qtmui.hooks import useEffect
from qtmui.material.styles import useTheme
from qtmui.i18n.use_translation import translate, i18n
from ..py_iconify import PyIconify
from ...qtmui_assets import QTMUI_ASSETS
def hexuuid(): ...
def splitext(p): ...
class TextEdit:
    def canInsertFromMimeData(self, source): ...
    def insertFromMimeData(self, source): ...
class Editor:
    def __init__(self, id: Optional[str], placeholder: Optional[str], value: Optional[Any], onChange: Optional[Callable], simple: Optional[bool], sx: Optional[Union[Callable, str, Dict]], *args, **kwargs): ...
    def _set_stylesheet(self): ...
    def block_signals(self, objects, b): ...
    def update_format(self): ...
    def dialog_critical(self, s): ...
    def file_open(self): ...
    def file_save(self): ...
    def file_saveas(self): ...
    def file_print(self): ...
    def update_title(self): ...
    def edit_toggle_wrap(self): ...