from django.urls import path

from netbox.views.generic import ObjectChangeLogView

from nbxsync.models import *
from nbxsync.views import *


urlpatterns = [
    path('', ZabbixServerListView.as_view(), name='zabbixserver_list'),
    # Zabbix Server
    path('zabbixserver/', ZabbixServerListView.as_view(), name='zabbixserver_list'),
    path('zabbixserver/add/', ZabbixServerEditView.as_view(), name='zabbixserver_add'),
    path('zabbixserver/import/', ZabbixServerBulkImportView.as_view(), name='zabbixserver_bulk_import'),
    path('zabbixserver/edit/', ZabbixServerBulkEditView.as_view(), name='zabbixserver_bulk_edit'),
    path('zabbixserver/delete/', ZabbixServerBulkDeleteView.as_view(), name='zabbixserver_bulk_delete'),
    path('zabbixserver/<int:pk>/', ZabbixServerView.as_view(), name='zabbixserver'),
    path('zabbixserver/<int:pk>/edit/', ZabbixServerEditView.as_view(), name='zabbixserver_edit'),
    path('zabbixserver/<int:pk>/delete/', ZabbixServerDeleteView.as_view(), name='zabbixserver_delete'),
    path('zabbixserver/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='zabbixserver_changelog', kwargs={'model': ZabbixServer}),
    path('zabbixserver/<int:pk>/templates/', ZabbixServerTemplatesView.as_view(), name='zabbixserver_templates'),
    path('zabbixserver/<int:pk>/templates/sync/', TriggerTemplateSyncJobView.as_view(), name='zabbixserver_templatessync'),
    # Zabbix Server Assignment
    path('zabbixserverassignment/', ZabbixServerAssignmentListView.as_view(), name='zabbixserverassignment_list'),
    path('zabbixserverassignment/add/', ZabbixServerAssignmentEditView.as_view(), name='zabbixserverassignment_add'),
    path('zabbixserverassignment/edit/', ZabbixServerAssignmentBulkEditView.as_view(), name='zabbixserverassignment_bulk_edit'),
    path('zabbixserverassignment/import/', ZabbixServerAssignmentBulkImportView.as_view(), name='zabbixserverassignment_bulk_import'),
    path('zabbixserverassignment/delete/', ZabbixServerAssignmentBulkDeleteView.as_view(), name='zabbixserverassignment_bulk_delete'),
    path('zabbixserverassignment/<int:pk>/', ZabbixServerAssignmentView.as_view(), name='zabbixserverassignment'),
    path('zabbixserverassignment/<int:pk>/edit/', ZabbixServerAssignmentEditView.as_view(), name='zabbixserverassignment_edit'),
    path('zabbixserverassignment/<int:pk>/delete/', ZabbixServerAssignmentDeleteView.as_view(), name='zabbixserverassignment_delete'),
    path('zabbixserverassignment/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='zabbixserverassignment_changelog', kwargs={'model': ZabbixServerAssignment}),
    # Zabbix Template
    path('zabbixtemplate/', ZabbixTemplateListView.as_view(), name='zabbixtemplate_list'),
    path('zabbixtemplate/add/', ZabbixTemplateEditView.as_view(), name='zabbixtemplate_add'),
    path('zabbixtemplate/edit/', ZabbixTemplateBulkEditView.as_view(), name='zabbixtemplate_bulk_edit'),
    path('zabbixtemplate/import/', ZabbixTemplateBulkImportView.as_view(), name='zabbixtemplate_bulk_import'),
    path('zabbixtemplate/delete/', ZabbixTemplateBulkDeleteView.as_view(), name='zabbixtemplate_bulk_delete'),
    path('zabbixtemplate/<int:pk>/', ZabbixTemplateView.as_view(), name='zabbixtemplate'),
    path('zabbixtemplate/<int:pk>/edit/', ZabbixTemplateEditView.as_view(), name='zabbixtemplate_edit'),
    path('zabbixtemplate/<int:pk>/delete/', ZabbixTemplateDeleteView.as_view(), name='zabbixtemplate_delete'),
    path('zabbixtemplate/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='zabbixtemplate_changelog', kwargs={'model': ZabbixTemplate}),
    path('zabbixtemplate/<int:pk>/macros/', ZabbixTemplateMacrosView.as_view(), name='zabbixtemplate_macros'),
    # Zabbix Template Assignment
    path('zabbixtemplateassignment/', ZabbixTemplateAssignmentListView.as_view(), name='zabbixtemplateassignment_list'),
    path('zabbixtemplateassignment/add/', ZabbixTemplateAssignmentEditView.as_view(), name='zabbixtemplateassignment_add'),
    path('zabbixtemplateassignment/<int:pk>/', ZabbixTemplateAssignmentView.as_view(), name='zabbixtemplateassignment'),
    path('zabbixtemplateassignment/<int:pk>/edit/', ZabbixTemplateAssignmentEditView.as_view(), name='zabbixtemplateassignment_edit'),
    path('zabbixtemplateassignment/<int:pk>/delete/', ZabbixTemplateAssignmentDeleteView.as_view(), name='zabbixtemplateassignment_delete'),
    path('zabbixtemplateassignment/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='zabbixtemplateassignment_changelog', kwargs={'model': ZabbixTemplateAssignment}),
    # Zabbix Macro
    path('zabbixmacro/', ZabbixMacroListView.as_view(), name='zabbixmacro_list'),
    path('zabbixmacro/add/', ZabbixMacroEditView.as_view(), name='zabbixmacro_add'),
    path('zabbixmacro/edit/', ZabbixMacroBulkEditView.as_view(), name='zabbixmacro_bulk_edit'),
    path('zabbixmacro/delete/', ZabbixMacroBulkDeleteView.as_view(), name='zabbixmacro_bulk_delete'),
    path('zabbixmacro/<int:pk>/', ZabbixMacroView.as_view(), name='zabbixmacro'),
    path('zabbixmacro/<int:pk>/edit/', ZabbixMacroEditView.as_view(), name='zabbixmacro_edit'),
    path('zabbixmacro/<int:pk>/delete/', ZabbixMacroDeleteView.as_view(), name='zabbixmacro_delete'),
    path('zabbixmacro/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='zabbixmacro_changelog', kwargs={'model': ZabbixMacro}),
    # Zabbix Macro Assignment
    path('zabbixmacroassignment/', ZabbixMacroAssignmentListView.as_view(), name='zabbixmacroassignment_list'),
    path('zabbixmacroassignment/add/', ZabbixMacroAssignmentEditView.as_view(), name='zabbixmacroassignment_add'),
    path('zabbixmacroassignment/edit/', ZabbixMacroAssignmentBulkEditView.as_view(), name='zabbixmacroassignment_bulk_edit'),
    path('zabbixmacroassignment/delete/', ZabbixMacroAssignmentBulkDeleteView.as_view(), name='zabbixmacroassignment_bulk_delete'),
    path('zabbixmacroassignment/<int:pk>/', ZabbixMacroAssignmentView.as_view(), name='zabbixmacroassignment'),
    path('zabbixmacroassignment/<int:pk>/edit/', ZabbixMacroAssignmentEditView.as_view(), name='zabbixmacroassignment_edit'),
    path('zabbixmacroassignment/<int:pk>/delete/', ZabbixMacroAssignmentDeleteView.as_view(), name='zabbixmacroassignment_delete'),
    path('zabbixmacroassignment/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='zabbixmacroassignment_changelog', kwargs={'model': ZabbixMacroAssignment}),
    # Zabbix Tag
    path('zabbixtag/', ZabbixTagListView.as_view(), name='zabbixtag_list'),
    path('zabbixtag/add/', ZabbixTagEditView.as_view(), name='zabbixtag_add'),
    path('zabbixtag/edit/', ZabbixTagBulkEditView.as_view(), name='zabbixtag_bulk_edit'),
    path('zabbixtag/delete/', ZabbixTagBulkDeleteView.as_view(), name='zabbixtag_bulk_delete'),
    path('zabbixtag/<int:pk>/', ZabbixTagView.as_view(), name='zabbixtag'),
    path('zabbixtag/<int:pk>/edit/', ZabbixTagEditView.as_view(), name='zabbixtag_edit'),
    path('zabbixtag/<int:pk>/delete/', ZabbixTagDeleteView.as_view(), name='zabbixtag_delete'),
    path('zabbixtag/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='zabbixtag_changelog', kwargs={'model': ZabbixTag}),
    # Zabbix Tag Assignment
    path('zabbixtagassignment/', ZabbixTagAssignmentListView.as_view(), name='zabbixtagassignment_list'),
    path('zabbixtagassignment/add/', ZabbixTagAssignmentEditView.as_view(), name='zabbixtagassignment_add'),
    path('zabbixtagassignment/edit/', ZabbixTagAssignmentBulkEditView.as_view(), name='zabbixtagassignment_bulk_edit'),
    path('zabbixtagassignment/delete/', ZabbixTagAssignmentBulkDeleteView.as_view(), name='zabbixtagassignment_bulk_delete'),
    path('zabbixtagassignment/<int:pk>/', ZabbixTagAssignmentView.as_view(), name='zabbixtagassignment'),
    path('zabbixtagassignment/<int:pk>/edit/', ZabbixTagAssignmentEditView.as_view(), name='zabbixtagassignment_edit'),
    path('zabbixtagassignment/<int:pk>/delete/', ZabbixTagAssignmentDeleteView.as_view(), name='zabbixtagassignment_delete'),
    path('zabbixtagassignment/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='zabbixtagassignment_changelog', kwargs={'model': ZabbixTagAssignment}),
    # Zabbix Host Interface
    path('zabbixhostinterface/', ZabbixHostInterfaceListView.as_view(), name='zabbixhostinterface_list'),
    path('zabbixhostinterface/add/', ZabbixHostInterfaceEditView.as_view(), name='zabbixhostinterface_add'),
    path('zabbixhostinterface/edit/', ZabbixHostInterfaceBulkEditView.as_view(), name='zzabbixhostinterface_bulk_edit'),
    path('zabbixhostinterface/delete/', ZabbixHostInterfaceBulkDeleteView.as_view(), name='zabbixhostinterface_bulk_delete'),
    path('zabbixhostinterface/<int:pk>/', ZabbixHostInterfaceView.as_view(), name='zabbixhostinterface'),
    path('zabbixhostinterface/<int:pk>/edit/', ZabbixHostInterfaceEditView.as_view(), name='zabbixhostinterface_edit'),
    path('zabbixhostinterface/<int:pk>/delete/', ZabbixHostInterfaceDeleteView.as_view(), name='zabbixhostinterface_delete'),
    path('zabbixhostinterface/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='zabbixhostinterface_changelog', kwargs={'model': ZabbixHostInterface}),
    # Zabbix Proxy
    path('zabbixproxy/', ZabbixProxyListView.as_view(), name='zabbixproxy_list'),
    path('zabbixproxy/add/', ZabbixProxyEditView.as_view(), name='zabbixproxy_add'),
    path('zabbixproxy/edit/', ZabbixProxyBulkEditView.as_view(), name='zabbixproxy_bulk_edit'),
    path('zabbixproxy/delete/', ZabbixProxyBulkDeleteView.as_view(), name='zabbixproxy_bulk_delete'),
    path('zabbixproxy/<int:pk>/', ZabbixProxyView.as_view(), name='zabbixproxy'),
    path('zabbixproxy/<int:pk>/sync/', TriggerProxySyncJobView.as_view(), name='zabbixproxy_sync'),
    path('zabbixproxy/<int:pk>/edit/', ZabbixProxyEditView.as_view(), name='zabbixproxy_edit'),
    path('zabbixproxy/<int:pk>/delete/', ZabbixProxyDeleteView.as_view(), name='zabbixproxy_delete'),
    path('zabbixproxy/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='zabbixproxy_changelog', kwargs={'model': ZabbixProxy}),
    # Zabbix Proxy Group
    path('zabbixproxygroup/', ZabbixProxyGroupListView.as_view(), name='zabbixproxygroup_list'),
    path('zabbixproxygroup/add/', ZabbixProxyGroupEditView.as_view(), name='zabbixproxygroup_add'),
    path('zabbixproxygroup/edit/', ZabbixProxyGroupBulkEditView.as_view(), name='zabbixproxygroup_bulk_edit'),
    path('zabbixproxygroup/delete/', ZabbixProxyGroupBulkDeleteView.as_view(), name='zabbixproxygroup_bulk_delete'),
    path('zabbixproxygroup/<int:pk>/', ZabbixProxyGroupView.as_view(), name='zabbixproxygroup'),
    path('zabbixproxygroup/<int:pk>/sync/', TriggerProxyGroupSyncJobView.as_view(), name='zabbixproxygroup_sync'),
    path('zabbixproxygroup/<int:pk>/edit/', ZabbixProxyGroupEditView.as_view(), name='zabbixproxygroup_edit'),
    path('zabbixproxygroup/<int:pk>/delete/', ZabbixProxyGroupDeleteView.as_view(), name='zabbixproxygroup_delete'),
    path('zabbixproxygroup/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='zabbixproxygroup_changelog', kwargs={'model': ZabbixProxyGroup}),
    # Zabbix Hostgroup
    path('zabbixhostgroup/', ZabbixHostgroupListView.as_view(), name='zabbixhostgroup_list'),
    path('zabbixhostgroup/add/', ZabbixHostgroupEditView.as_view(), name='zabbixhostgroup_add'),
    path('zabbixhostgroup/import/', ZabbixHostgroupBulkImportView.as_view(), name='zabbixhostgroup_bulk_import'),
    path('zabbixhostgroup/edit/', ZabbixHostgroupBulkEditView.as_view(), name='zabbixhostgroup_bulk_edit'),
    path('zabbixhostgroup/delete/', ZabbixHostgroupBulkDeleteView.as_view(), name='zabbixhostgroup_bulk_delete'),
    path('zabbixhostgroup/<int:pk>/', ZabbixHostgroupView.as_view(), name='zabbixhostgroup'),
    path('zabbixhostgroup/<int:pk>/edit/', ZabbixHostgroupEditView.as_view(), name='zabbixhostgroup_edit'),
    path('zabbixhostgroup/<int:pk>/delete/', ZabbixHostgroupDeleteView.as_view(), name='zabbixhostgroup_delete'),
    path('zabbixhostgroup/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='zabbixhostgroup_changelog', kwargs={'model': ZabbixHostgroup}),
    # Zabbix Hostgroup Assignment
    path('zabbixhostgroupassignment/', ZabbixHostgroupAssignmentListView.as_view(), name='zabbixhostgroupassignment_list'),
    path('zabbixhostgroupassignment/add/', ZabbixHostgroupAssignmentEditView.as_view(), name='zabbixhostgroupassignment_add'),
    path('zabbixhostgroupassignment/edit/', ZabbixHostgroupAssignmentBulkEditView.as_view(), name='zabbixhostgroupassignment_bulk_edit'),
    path('zabbixhostgroupassignment/delete/', ZabbixHostgroupAssignmentBulkDeleteView.as_view(), name='zabbixhostgroupassignment_bulk_delete'),
    path('zabbixhostgroupassignment/<int:pk>/', ZabbixHostgroupAssignmentView.as_view(), name='zabbixhostgroupassignment'),
    path('zabbixhostgroupassignment/<int:pk>/edit/', ZabbixHostgroupAssignmentEditView.as_view(), name='zabbixhostgroupassignment_edit'),
    path('zabbixhostgroupassignment/<int:pk>/delete/', ZabbixHostgroupAssignmentDeleteView.as_view(), name='zabbixhostgroupassignment_delete'),
    path('zabbixhostgroupassignment/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='zabbixhostgroupassignment_changelog', kwargs={'model': ZabbixHostgroupAssignment}),
    # Zabbix HostInventory
    path('zabbixhostinventory/', ZabbixHostInventoryListView.as_view(), name='zabbixhostinventory_list'),
    path('zabbixhostinventory/add/', ZabbixHostInventoryEditView.as_view(), name='zabbixhostinventory_add'),
    path('zabbixhostinventory/edit/', ZabbixHostInventoryBulkEditView.as_view(), name='zabbixhostinventory_bulk_edit'),
    path('zabbixhostinventory/delete/', ZabbixHostInventoryBulkDeleteView.as_view(), name='zabbixhostinventory_bulk_delete'),
    path('zabbixhostinventory/<int:pk>/', ZabbixHostInventoryView.as_view(), name='zabbixhostinventory'),
    path('zabbixhostinventory/<int:pk>/edit/', ZabbixHostInventoryEditView.as_view(), name='zabbixhostinventory_edit'),
    path('zabbixhostinventory/<int:pk>/delete/', ZabbixHostInventoryDeleteView.as_view(), name='zabbixhostinventory_delete'),
    path('zabbixhostinventory/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='zabbixhostinventory_changelog', kwargs={'model': ZabbixHostInventory}),
    # Zabbix Maintenance
    path('zabbixmaintenance/', ZabbixMaintenanceListView.as_view(), name='zabbixmaintenance_list'),
    path('zabbixmaintenance/add/', ZabbixMaintenanceEditView.as_view(), name='zabbixmaintenance_add'),
    path('zabbixmaintenance/edit/', ZabbixMaintenanceBulkEditView.as_view(), name='zabbixmaintenance_bulk_edit'),
    path('zabbixmaintenance/delete/', ZabbixMaintenanceBulkDeleteView.as_view(), name='zabbixmaintenance_bulk_delete'),
    path('zabbixmaintenance/<int:pk>/', ZabbixMaintenanceView.as_view(), name='zabbixmaintenance'),
    path('zabbixmaintenance/<int:pk>/sync/', TriggerMaintenanceSyncJobView.as_view(), name='zabbixmaintenance_sync'),
    path('zabbixmaintenance/<int:pk>/edit/', ZabbixMaintenanceEditView.as_view(), name='zabbixmaintenance_edit'),
    path('zabbixmaintenance/<int:pk>/delete/', ZabbixMaintenanceDeleteView.as_view(), name='zabbixmaintenance_delete'),
    path('zabbixmaintenance/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='zabbixmaintenance_changelog', kwargs={'model': ZabbixMaintenance}),
    # Zabbix Maintenance Period
    path('zabbixmaintenanceperiod/', ZabbixMaintenancePeriodListView.as_view(), name='zabbixmaintenanceperiod_list'),
    path('zabbixmaintenanceperiod/add/', ZabbixMaintenancePeriodEditView.as_view(), name='zabbixmaintenanceperiod_add'),
    path('zabbixmaintenanceperiod/edit/', ZabbixMaintenancePeriodBulkEditView.as_view(), name='zabbixmaintenanceperiod_bulk_edit'),
    path('zabbixmaintenanceperiod/delete/', ZabbixMaintenancePeriodBulkDeleteView.as_view(), name='zabbixmaintenanceperiod_bulk_delete'),
    path('zabbixmaintenanceperiod/<int:pk>/', ZabbixMaintenancePeriodView.as_view(), name='zabbixmaintenanceperiod'),
    path('zabbixmaintenanceperiod/<int:pk>/edit/', ZabbixMaintenancePeriodEditView.as_view(), name='zabbixmaintenanceperiod_edit'),
    path('zabbixmaintenanceperiod/<int:pk>/delete/', ZabbixMaintenancePeriodDeleteView.as_view(), name='zabbixmaintenanceperiod_delete'),
    path('zabbixmaintenanceperiod/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='zabbixmaintenanceperiod_changelog', kwargs={'model': ZabbixMaintenancePeriod}),
    # Zabbix Maintenance Object Assignment
    path('zabbixmaintenanceobjectassignment/', ZabbixMaintenanceObjectAssignmentListView.as_view(), name='zabbixmaintenanceobjectassignment_list'),
    path('zabbixmaintenanceobjectassignment/add/', ZabbixMaintenanceObjectAssignmentEditView.as_view(), name='zabbixmaintenanceobjectassignment_add'),
    path('zabbixmaintenanceobjectassignment/edit/', ZabbixMaintenanceObjectAssignmentBulkEditView.as_view(), name='zabbixmaintenanceobjectassignment_bulk_edit'),
    path('zabbixmaintenanceobjectassignment/delete/', ZabbixMaintenanceObjectAssignmentBulkDeleteView.as_view(), name='zabbixmaintenanceobjectassignment_bulk_delete'),
    path('zabbixmaintenanceobjectassignment/<int:pk>/', ZabbixMaintenanceObjectAssignmentView.as_view(), name='zabbixmaintenanceobjectassignment'),
    path('zabbixmaintenanceobjectassignment/<int:pk>/edit/', ZabbixMaintenanceObjectAssignmentEditView.as_view(), name='zabbixmaintenanceobjectassignment_edit'),
    path('zabbixmaintenanceobjectassignment/<int:pk>/delete/', ZabbixMaintenanceObjectAssignmentDeleteView.as_view(), name='zabbixmaintenanceobjectassignment_delete'),
    path('zabbixmaintenanceobjectassignment/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='zabbixmaintenanceobjectassignment_changelog', kwargs={'model': ZabbixMaintenanceObjectAssignment}),
    # Zabbix Maintenance Tag Assignment
    path('zabbixmaintenancetagassignment/', ZabbixMaintenanceTagAssignmentListView.as_view(), name='zabbixmaintenancetagassignment_list'),
    path('zabbixmaintenancetagassignment/add/', ZabbixMaintenanceTagAssignmentEditView.as_view(), name='zabbixmaintenancetagassignment_add'),
    path('zabbixmaintenancetagassignment/edit/', ZabbixMaintenanceTagAssignmentBulkEditView.as_view(), name='zabbixmaintenancetagassignment_bulk_edit'),
    path('zabbixmaintenancetagassignment/delete/', ZabbixMaintenanceTagAssignmentBulkDeleteView.as_view(), name='zabbixmaintenancetagassignment_bulk_delete'),
    path('zabbixmaintenancetagassignment/<int:pk>/', ZabbixMaintenanceTagAssignmentView.as_view(), name='zabbixmaintenancetagassignment'),
    path('zabbixmaintenancetagassignment/<int:pk>/edit/', ZabbixMaintenanceTagAssignmentEditView.as_view(), name='zabbixmaintenancetagassignment_edit'),
    path('zabbixmaintenancetagassignment/<int:pk>/delete/', ZabbixMaintenanceTagAssignmentDeleteView.as_view(), name='zabbixmaintenancetagassignment_delete'),
    path('zabbixmaintenancetagassignment/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='zabbixmaintenancetagassignment_changelog', kwargs={'model': ZabbixMaintenanceTagAssignment}),
    # Zabbix Configuration Group
    path('zabbixconfigurationgroup/', ZabbixConfigurationGroupListView.as_view(), name='zabbixconfigurationgroup_list'),
    path('zabbixconfigurationgroup/add/', ZabbixConfigurationGroupEditView.as_view(), name='zabbixconfigurationgroup_add'),
    path('zabbixconfigurationgroup/edit/', ZabbixConfigurationGroupBulkEditView.as_view(), name='zabbixconfigurationgroup_bulk_edit'),
    path('zabbixconfigurationgroup/delete/', ZabbixConfigurationGroupBulkDeleteView.as_view(), name='zabbixconfigurationgroup_bulk_delete'),
    path('zabbixconfigurationgroup/<int:pk>/', ZabbixConfigurationGroupView.as_view(), name='zabbixconfigurationgroup'),
    path('zabbixconfigurationgroup/<int:pk>/edit/', ZabbixConfigurationGroupEditView.as_view(), name='zabbixconfigurationgroup_edit'),
    path('zabbixconfigurationgroup/<int:pk>/delete/', ZabbixConfigurationGroupDeleteView.as_view(), name='zabbixconfigurationgroup_delete'),
    path('zabbixconfigurationgroup/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='zabbixconfigurationgroup_changelog', kwargs={'model': ZabbixConfigurationGroup}),
    path('zabbixconfigurationgroup/<int:pk>/sync', TriggerZabbicConfigurationgroupSyncJobView.as_view(), name='zabbixconfigurationgroup_sync'),
    # Zabbix Configuration Group Assignment
    path('zabbixconfigurationgroupassignment/', ZabbixConfigurationGroupAssignmentListView.as_view(), name='zabbixconfigurationgroupassignment_list'),
    path('zabbixconfigurationgroupassignment/add/', ZabbixConfigurationGroupAssignmentEditView.as_view(), name='zabbixconfigurationgroupassignment_add'),
    path('zabbixconfigurationgroupassignment/edit/', ZabbixConfigurationGroupAssignmentBulkEditView.as_view(), name='zabbixconfigurationgroupassignment_bulk_edit'),
    path('zabbixconfigurationgroupassignment/delete/', ZabbixConfigurationGroupAssignmentBulkDeleteView.as_view(), name='zabbixconfigurationgroupassignment_bulk_delete'),
    path('zabbixconfigurationgroupassignment/<int:pk>/', ZabbixConfigurationGroupAssignmentView.as_view(), name='zabbixconfigurationgroupassignment'),
    path('zabbixconfigurationgroupassignment/<int:pk>/edit/', ZabbixConfigurationGroupAssignmentEditView.as_view(), name='zabbixconfigurationgroupassignment_edit'),
    path('zabbixconfigurationgroupassignment/<int:pk>/delete/', ZabbixConfigurationGroupAssignmentDeleteView.as_view(), name='zabbixconfigurationgroupassignment_delete'),
    path('zabbixconfigurationgroupassignment/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='zabbixconfigurationgroupassignment_changelog', kwargs={'model': ZabbixConfigurationGroupAssignment}),
    # Sync Device/VM Object
    path('zabbixhost/<str:objtype>/<int:pk>/sync', TriggerHostSyncJobView.as_view(), name='zabbixhost_sync'),
    path('zabbixhost/<str:objtype>/<int:pk>/sync-info/', ZabbixSyncInfoModalView.as_view(), name='zabbixhost_info'),
    # Zabbix Operational View
    path('zabbixhost/<str:objtype>/<int:pk>/problems', ZabbixHostProblemsView.as_view(), name='zabbixhost_problems'),
    path('zabbixhost/<str:objtype>/<int:pk>/events', ZabbixHostEventsView.as_view(), name='zabbixhost_events'),
]
