from typing import Optional, Union, Callable
from .qtrangeslider._labeled import QRangeSlider, QDoubleSlider, QDoubleRangeSlider, QLabeledSlider, QLabeledRangeSlider, QLabeledDoubleSlider, QLabeledDoubleRangeSlider
from PySide6.QtCore import Qt
from qtmui.material.styles import useTheme
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
from qtmui.hooks import State
def getColor(_color: str, theme): ...
class SliderBase:
    def _setValue(self, value): ...
class RangeSlider:
    def __init__(self, color: str, size: str, areaLabel: str, getAreaLabel: Callable, disabled: bool, step: Optional[Union[int, float, Any]], orientation: str, onChange: Callable, value, min: int, max: int): ...
class MultiHandleRangeSlider:
    def __init__(self, color: str, size: str, areaLabel: str, getAreaLabel: Callable, disabled: bool, step: Optional[Union[int, float, Any]], orientation: str, onChange: Callable, min: int, max: int, value): ...
class DoubleSlider:
    def __init__(self, color: str, size: str, areaLabel: str, getAreaLabel: Callable, disabled: bool, step: Optional[Union[int, float, Any]], orientation: str, onChange: Callable, min: int, max: int, value: float): ...
class DoubleRangeSlider:
    def __init__(self, color: str, size: str, areaLabel: str, getAreaLabel: Callable, disabled: bool, step: Optional[Union[int, float, Any]], orientation: str, onChange: Callable, min: int, max: int, value): ...
class LabeledSlider:
    def __init__(self, color: str, size: str, areaLabel: str, getAreaLabel: Callable, disabled: bool, step: Optional[Union[int, float, Any]], orientation: str, onChange: Callable, min: int, max: int, value: int): ...
class LabeledRangeSlider:
    def __init__(self, color: str, size: str, areaLabel: str, getAreaLabel: Callable, disabled: bool, step: Optional[Union[int, float, Any]], orientation: str, onChange: Callable, value, min: int, max: int): ...
class LabeledDoubleSlider:
    def __init__(self, color: str, size: str, areaLabel: str, getAreaLabel: Callable, disabled: bool, step: Optional[Union[int, float, Any]], orientation: str, onChange: Callable, min: float, max: float, value: float, singleStep: Optional[Union[int, float]]): ...
class LabeledDoubleRangeSlider:
    def __init__(self, color: str, size: str, areaLabel: str, getAreaLabel: Callable, disabled: bool, step: Optional[Union[int, float, Any]], orientation: str, onChange: Callable, min: float, max: float, value, singleStep: Optional[Union[int, float]]): ...