import asyncio
from functools import lru_cache
import uuid
from typing import Optional, Callable, Any, Dict, Union
from PySide6.QtWidgets import QPlainTextEdit, QHBoxLayout
from PySide6.QtCore import QTimer
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
from qtmui.utils.translator import getTranslatedText
from ..widget_base import PyWidgetBase
from qtmui.material.styles import useTheme
from qtmui.hooks import State, useEffect
from qtmui.i18n.use_translation import i18n
class TFPlainTextEditMultiple:
    def __init__(self, parent, label: Optional[Union[str, State, Callable]], onChange: Optional[Callable], children: Optional[list], sx: Optional[Union[Dict, Callable, str]], variant: str, defautLine: int, size: str, **kwargs): ...
    def _init_ui(self): ...
    def enterEvent(self, event): ...
    def leaveEvent(self, event): ...
    def mousePressEvent(self, event): ...
    def mouseReleaseEvent(self, event): ...
    def focusInEvent(self, event): ...
    def focusOutEvent(self, event): ...