from __future__ import annotations
import asyncio
import functools
import inspect
import weakref
from asyncio import iscoroutine, iscoroutinefunction
from typing import TYPE_CHECKING, Any, Concatenate, Generic, Literal, cast
from qtmui.redux.basic_types import NOT_SET, Action, Args, AutoAwait, AutorunOptionsType, ComparatorOutput, Event, ReturnType, SelectorOutput, State, T
from qtmui.redux.utils import call_func, signature_without_selector
class AwaitableWrapper:
    value: Any
    def __init__(self, coro: Coroutine[Any, Any, T]): ...
    def __await__(self): ...
    def close(self): ...
    def awaited(self): ...
    def __repr__(self): ...
class Autorun:
    def __init__(self: Autorun): ...
    def _create_task(self: Autorun, coro: Coroutine[Any, Any, Any]): ...
    def react(self: Autorun, state: State): ...
    def unsubscribe(self: Autorun[State, Action, Event, SelectorOutput, ComparatorOutput, Args, ReturnType], _: Any): ...
    def inform_subscribers(self: Autorun[State, Action, Event, SelectorOutput, ComparatorOutput, Args, ReturnType]): ...
    def check(self: Autorun[State, Action, Event, SelectorOutput, ComparatorOutput, Args, ReturnType], state: State): ...
    def call(self: Autorun[State, Action, Event, SelectorOutput, ComparatorOutput, Args, ReturnType], *args, **kwargs): ...
    def __call__(self: Autorun[State, Action, Event, SelectorOutput, ComparatorOutput, Args, ReturnType], *args, **kwargs): ...
    def __repr__(self: Autorun[State, Action, Event, SelectorOutput, ComparatorOutput, Args, ReturnType]): ...
    def value(self: Autorun[State, Action, Event, SelectorOutput, ComparatorOutput, Args, ReturnType]): ...
    def subscribe(self: Autorun[State, Action, Event, SelectorOutput, ComparatorOutput, Args, ReturnType], callback: Callable[Any, Any]): ...
    def __get__(self: Autorun[State, Action, Event, SelectorOutput, ComparatorOutput, Args, ReturnType], obj: Any, _: Any): ...