from PySide6.QtCore import Signal, Qt
from PySide6.QtWidgets import QHeaderView, QLineEdit
class HeaderFilter:
    def __init__(self, parent): ...
    def setFilterBoxes(self, count): ...
    def sizeHint(self): ...
    def updateGeometries(self): ...
    def adjustPositions(self): ...
    def filterText(self, index): ...
    def setFilterText(self, index, text): ...
    def clearFilters(self): ...