from typing import Callable
from PySide6.QtCore import QSize, QEvent, Signal, QRect
from PySide6.QtGui import QIcon, QColor, QBrush
from PySide6.QtWidgets import QStyledItemDelegate, QStyle, QStyleOptionButton
from .icon import icon_firefox_disabled
from ..utils.icon import icon_base64_to_pixmap
class StyledItemDelegate:
    def __init__(self, parent, column: int, styledOption: object, styledOptions: list, onMousePressed: Callable): ...
    def split_rect(self, rect, num_divisions): ...
    def point_in_rects(self, point, rects): ...
    def editorEvent(self, event, model, option, index): ...
    def paint(self, painter, option, index): ...