import sys
from qtmui.material.qtmui_app import QtMuiApp
from qtmui.material.chip import Chip
from PySide6.QtCore import Qt, QMargins, QPoint, QRect, QSize
from PySide6.QtWidgets import QLayout, QPushButton, QSizePolicy, QFrame
class Window:
    def __init__(self): ...
class FlowLayout:
    def __init__(self, parent, margin): ...
    def __del__(self): ...
    def addItem(self, item): ...
    def count(self): ...
    def itemAt(self, index): ...
    def takeAt(self, index): ...
    def expandingDirections(self): ...
    def hasHeightForWidth(self): ...
    def heightForWidth(self, width): ...
    def setGeometry(self, rect): ...
    def sizeHint(self): ...
    def minimumSize(self): ...
    def _do_layout(self, rect, test_only): ...