from setuptools import setup

setup(name='ilt-panphon',
      version='0.20.1',
      description='Tools for using the International Phonetic Alphabet with phonological features',
      url='https://github.com/nrc-ilt/panphon',
      long_description=open('README.md', encoding='utf-8').read(),
      long_description_content_type='text/markdown',
      author='David R. Mortensen',
      author_email='dmortens@cs.cmu.edu',
      maintainer='Eric Joanis',
      maintainer_email='Eric.Joanis@nrc-cnrc.gc.ca',
      license='MIT',
      python_requires='>=3.8.0',
      install_requires=['setuptools<80',
                        'unicodecsv',
                        'PyYAML',
                        'regex',
                        'numpy>=1.20.2',
                        'ilt-editdistance',
                        'munkres'],
      scripts=['panphon/bin/validate_ipa.py',
               'panphon/bin/align_wordlists.py',
               'panphon/bin/generate_ipa_all.py'],
      packages=['panphon'],
      package_dir={'panphon': 'panphon'},
      package_data={'panphon': ['data/*.csv', 'data/*.yml']},
      zip_safe=True,
      classifiers=['Operating System :: OS Independent',
                   'Programming Language :: Python :: 3',
                   'Topic :: Software Development :: Libraries :: Python Modules',
                   'Topic :: Text Processing :: Linguistic']
      )
