
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util
import jneqsim.neqsim.process.equipment
import jneqsim.neqsim.process.equipment.valve
import jneqsim.neqsim.process.logic
import jneqsim.neqsim.process.logic.sis
import typing



class HIPPSLogic(jneqsim.neqsim.process.logic.ProcessLogic):
    def __init__(self, string: typing.Union[java.lang.String, str], votingLogic: jneqsim.neqsim.process.logic.sis.VotingLogic): ...
    def activate(self) -> None: ...
    def addPressureSensor(self, detector: jneqsim.neqsim.process.logic.sis.Detector) -> None: ...
    def deactivate(self) -> None: ...
    def execute(self, double: float) -> None: ...
    def getName(self) -> java.lang.String: ...
    def getPressureSensor(self, int: int) -> jneqsim.neqsim.process.logic.sis.Detector: ...
    def getState(self) -> jneqsim.neqsim.process.logic.LogicState: ...
    def getStatusDescription(self) -> java.lang.String: ...
    def getTargetEquipment(self) -> java.util.List[jneqsim.neqsim.process.equipment.ProcessEquipmentInterface]: ...
    def getTimeSinceTrip(self) -> float: ...
    def hasEscalated(self) -> bool: ...
    def isActive(self) -> bool: ...
    def isComplete(self) -> bool: ...
    def isTripped(self) -> bool: ...
    def linkToEscalationLogic(self, processLogic: jneqsim.neqsim.process.logic.ProcessLogic, double: float) -> None: ...
    def reset(self) -> bool: ...
    def setIsolationValve(self, throttlingValve: jneqsim.neqsim.process.equipment.valve.ThrottlingValve) -> None: ...
    def setOverride(self, boolean: bool) -> None: ...
    def setValveClosureTime(self, double: float) -> None: ...
    def toString(self) -> java.lang.String: ...
    def update(self, *double: float) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.neqsim.process.logic.hipps")``.

    HIPPSLogic: typing.Type[HIPPSLogic]
