from typing import List, Optional, Dict, Any
from PySide6.QtCore import Qt, QRectF, QPropertyAnimation, QEasingCurve, Property, Signal, QSize, QEvent
from PySide6.QtGui import QPainter, QColor, QPen, QFont
from PySide6.QtWidgets import QWidget, QLabel, QVBoxLayout, QHBoxLayout, QPushButton, QSizePolicy, QApplication, QFrame
def lighten_color(qcolor: QColor, factor: float): ...
def darken_color(qcolor: QColor, factor: float): ...
class RadialSegment:
    def __init__(self, index: int, name: str, value: float, base_value: float, color: QColor, thickness: int, radius: int, parent): ...
    def getAnimatedValue(self): ...
    def setAnimatedValue(self, v): ...
    def enterEvent(self, event): ...
    def leaveEvent(self, event): ...
    def mousePressEvent(self, event): ...
    def setValue(self, v: float, animate: bool): ...
    def paintEvent(self, event): ...
class ChartRadialBar:
    def __init__(self, series: Optional[List[float]], options: Optional[Dict[str, Any]], width: Optional[int], height: Optional[int], dir: str, type: str, total: Optional[int], parent): ...
    def _on_segment_hovered(self, idx: int): ...
    def _on_segment_unhovered(self, idx: int): ...
    def _on_segment_clicked(self, idx: int): ...
    def _on_toggle(self, idx: int, checked: bool): ...
    def _show_total(self): ...
    def eventFilter(self, obj, event): ...