DaVinci MCP Professional: davinci_mcp.server.DaVinciMCPServer Class Reference
davinci_mcp.server.DaVinciMCPServer Class Reference
Public Member Functions
None __init__ (self)
None run (self)
Public Attributes
server = Server("davinci-resolve-mcp")
resolve_client = DaVinciResolveClient()
Protected Member Functions
None _register_handlers (self)
None _register_tools (self)
None _register_resources (self)
Any _call_tool (self, str name, Dict[str, Any] arguments)
Any _read_resource (self, str uri)
Detailed Description
DaVinci Resolve MCP Server.
Provides a clean interface between MCP clients and DaVinci Resolve
through organized tools and resources.
Definition at line 24 of file server.py.
Constructor & Destructor Documentation
__init__()
None davinci_mcp.server.DaVinciMCPServer.__init__ (self)
Definition at line 32 of file server.py.
Member Function Documentation
_call_tool()
Any davinci_mcp.server.DaVinciMCPServer._call_tool (self, str name, Dict[str, Any] arguments) protected
Call a specific tool.
Definition at line 114 of file server.py.
References resolve_client.
Referenced by _register_handlers().
_read_resource()
Any davinci_mcp.server.DaVinciMCPServer._read_resource (self, str uri) protected
Read a specific resource.
Definition at line 173 of file server.py.
References resolve_client.
Referenced by _register_handlers().
_register_handlers()
None davinci_mcp.server.DaVinciMCPServer._register_handlers (self) protected
Register MCP server handlers.
Definition at line 43 of file server.py.
References _call_tool(), _read_resource(), and resolve_client.
_register_resources()
None davinci_mcp.server.DaVinciMCPServer._register_resources (self) protected
Register resource implementations.
Definition at line 109 of file server.py.
_register_tools()
None davinci_mcp.server.DaVinciMCPServer._register_tools (self) protected
Register tool implementations.
Definition at line 104 of file server.py.
run()
None davinci_mcp.server.DaVinciMCPServer.run (self)
Run the MCP server.
Definition at line 205 of file server.py.
References run(), and server.
Referenced by run().
Member Data Documentation
resolve_client
davinci_mcp.server.DaVinciMCPServer.resolve_client = DaVinciResolveClient()
Definition at line 34 of file server.py.
Referenced by _call_tool(), _read_resource(), and _register_handlers().
server
davinci_mcp.server.DaVinciMCPServer.server = Server("davinci-resolve-mcp")
Definition at line 33 of file server.py.
Referenced by run().
The documentation for this class was generated from the following file:
davinci_mcp/server.py