DaVinci MCP Professional: davinci_mcp.resolve_client.DaVinciResolveClient Class Reference
davinci_mcp.resolve_client.DaVinciResolveClient Class Reference
Public Member Functions
None __init__ (self)
None connect (self)
None disconnect (self)
bool is_connected (self)
str get_version (self)
str get_current_page (self)
bool switch_page (self, str page)
List[str] list_projects (self)
Optional[str] get_current_project_name (self)
bool open_project (self, str name)
bool create_project (self, str name)
List[str] list_timelines (self)
Optional[str] get_current_timeline_name (self)
bool create_timeline (self, str name)
bool switch_timeline (self, str name)
List[Dict[str, Any]] list_media_clips (self)
bool import_media (self, str file_path)
Protected Member Functions
None _ensure_connected (self)
Any _ensure_project (self)
Protected Attributes
Optional[Any] _resolve = None
Optional[Any] _project_manager = None
Optional[Any] _current_project = None
bool _is_connected = False
Detailed Description
A clean interface to the DaVinci Resolve API.
This class handles the connection to DaVinci Resolve and provides
organized methods for interacting with projects, timelines, media, etc.
Definition at line 32 of file resolve_client.py.
Constructor & Destructor Documentation
__init__()
None davinci_mcp.resolve_client.DaVinciResolveClient.__init__ (self)
Definition at line 40 of file resolve_client.py.
Member Function Documentation
_ensure_connected()
None davinci_mcp.resolve_client.DaVinciResolveClient._ensure_connected (self) protected
Ensure we're connected to Resolve.
Definition at line 101 of file resolve_client.py.
References _is_connected.
Referenced by _ensure_project(), create_project(), get_current_page(), get_version(), list_projects(), open_project(), and switch_page().
_ensure_project()
Any davinci_mcp.resolve_client.DaVinciResolveClient._ensure_project (self) protected
Ensure we have a current project.
Definition at line 106 of file resolve_client.py.
References _current_project, _ensure_connected(), and _project_manager.
Referenced by create_timeline(), get_current_project_name(), get_current_timeline_name(), import_media(), list_media_clips(), list_timelines(), and switch_timeline().
connect()
None davinci_mcp.resolve_client.DaVinciResolveClient.connect (self)
Connect to DaVinci Resolve.
Definition at line 46 of file resolve_client.py.
References _current_project, _is_connected, _project_manager, and _resolve.
create_project()
bool davinci_mcp.resolve_client.DaVinciResolveClient.create_project (self, str name)
Create a new project.
Definition at line 183 of file resolve_client.py.
References _current_project, _ensure_connected(), _project_manager, and list_projects().
create_timeline()
bool davinci_mcp.resolve_client.DaVinciResolveClient.create_timeline (self, str name)
Create a new timeline.
Definition at line 226 of file resolve_client.py.
References _ensure_project().
disconnect()
None davinci_mcp.resolve_client.DaVinciResolveClient.disconnect (self)
Disconnect from DaVinci Resolve.
Definition at line 89 of file resolve_client.py.
References _current_project, _is_connected, _project_manager, and _resolve.
get_current_page()
str davinci_mcp.resolve_client.DaVinciResolveClient.get_current_page (self)
Get the current page (Edit, Color, Fusion, etc.).
Definition at line 127 of file resolve_client.py.
References _ensure_connected(), and _resolve.
get_current_project_name()
Optional[str] davinci_mcp.resolve_client.DaVinciResolveClient.get_current_project_name (self)
Get the name of the currently open project.
Definition at line 156 of file resolve_client.py.
References _ensure_project().
get_current_timeline_name()
Optional[str] davinci_mcp.resolve_client.DaVinciResolveClient.get_current_timeline_name (self)
Get the name of the current timeline.
Definition at line 217 of file resolve_client.py.
References _ensure_project().
get_version()
str davinci_mcp.resolve_client.DaVinciResolveClient.get_version (self)
Get DaVinci Resolve version.
Definition at line 120 of file resolve_client.py.
References _ensure_connected(), and _resolve.
import_media()
bool davinci_mcp.resolve_client.DaVinciResolveClient.import_media (self, str file_path)
Import a media file into the media pool.
Definition at line 284 of file resolve_client.py.
References _ensure_project().
is_connected()
bool davinci_mcp.resolve_client.DaVinciResolveClient.is_connected (self)
Check if connected to DaVinci Resolve.
Definition at line 97 of file resolve_client.py.
References _is_connected.
list_media_clips()
List[Dict[str, Any]] davinci_mcp.resolve_client.DaVinciResolveClient.list_media_clips (self)
List all clips in the media pool root folder.
Definition at line 258 of file resolve_client.py.
References _ensure_project().
list_projects()
List[str] davinci_mcp.resolve_client.DaVinciResolveClient.list_projects (self)
List all projects in the current database.
Definition at line 147 of file resolve_client.py.
References _ensure_connected(), and _project_manager.
Referenced by create_project(), and open_project().
list_timelines()
List[str] davinci_mcp.resolve_client.DaVinciResolveClient.list_timelines (self)
List all timelines in the current project.
Definition at line 203 of file resolve_client.py.
References _ensure_project().
open_project()
bool davinci_mcp.resolve_client.DaVinciResolveClient.open_project (self, str name)
Open a project by name.
Definition at line 164 of file resolve_client.py.
References _current_project, _ensure_connected(), _project_manager, and list_projects().
switch_page()
bool davinci_mcp.resolve_client.DaVinciResolveClient.switch_page (self, str page)
Switch to a specific page.
Definition at line 134 of file resolve_client.py.
References _ensure_connected(), and _resolve.
switch_timeline()
bool davinci_mcp.resolve_client.DaVinciResolveClient.switch_timeline (self, str name)
Switch to a timeline by name.
Definition at line 241 of file resolve_client.py.
References _ensure_project().
Member Data Documentation
_current_project
Optional[Any] davinci_mcp.resolve_client.DaVinciResolveClient._current_project = None protected
Definition at line 43 of file resolve_client.py.
Referenced by _ensure_project(), connect(), create_project(), disconnect(), and open_project().
_is_connected
bool davinci_mcp.resolve_client.DaVinciResolveClient._is_connected = False protected
Definition at line 44 of file resolve_client.py.
Referenced by _ensure_connected(), connect(), disconnect(), and is_connected().
_project_manager
Optional[Any] davinci_mcp.resolve_client.DaVinciResolveClient._project_manager = None protected
Definition at line 42 of file resolve_client.py.
Referenced by _ensure_project(), connect(), create_project(), disconnect(), list_projects(), and open_project().
_resolve
Optional[Any] davinci_mcp.resolve_client.DaVinciResolveClient._resolve = None protected
Definition at line 41 of file resolve_client.py.
Referenced by connect(), disconnect(), get_current_page(), get_version(), and switch_page().
The documentation for this class was generated from the following file:
davinci_mcp/resolve_client.py