DaVinci MCP Professional: davinci_mcp.utils.platform Namespace Reference
davinci_mcp.utils.platform Namespace Reference
Functions
str get_platform ()
Dict[str, Path] get_resolve_paths ()
bool setup_resolve_environment ()
Dict[str, bool] check_resolve_installation ()
bool check_resolve_running ()
Detailed Description
Platform detection and environment setup utilities.
Function Documentation
check_resolve_installation()
Dict[str, bool] davinci_mcp.utils.platform.check_resolve_installation ()
Check if DaVinci Resolve is properly installed.
Definition at line 74 of file platform.py.
References get_resolve_paths().
check_resolve_running()
bool davinci_mcp.utils.platform.check_resolve_running ()
Check if DaVinci Resolve is currently running.
Definition at line 85 of file platform.py.
References get_platform().
get_platform()
str davinci_mcp.utils.platform.get_platform ()
Get the current platform name.
Definition at line 12 of file platform.py.
Referenced by check_resolve_running(), and get_resolve_paths().
get_resolve_paths()
Dict[str, Path] davinci_mcp.utils.platform.get_resolve_paths ()
Get platform-specific paths for DaVinci Resolve scripting API.
Definition at line 25 of file platform.py.
References get_platform().
Referenced by check_resolve_installation(), and setup_resolve_environment().
setup_resolve_environment()
bool davinci_mcp.utils.platform.setup_resolve_environment ()
Set up environment variables for DaVinci Resolve scripting.
Definition at line 55 of file platform.py.
References get_resolve_paths().