DaVinci MCP Professional: davinci_mcp.cli Namespace Reference
davinci_mcp.cli Namespace Reference
Functions
None print_status (str message, str status="INFO")
bool check_prerequisites ()
None main (bool debug=False, bool skip_checks=False)
Variables
_original_stdout = sys.stdout
_original_stderr = sys.stderr
level
format
logger = logging.getLogger(__name__)
Detailed Description
Command line interface for DaVinci Resolve MCP Server.
Function Documentation
check_prerequisites()
bool davinci_mcp.cli.check_prerequisites ()
Check if prerequisites are met.
Definition at line 58 of file cli.py.
References print_status().
Referenced by main().
main()
None davinci_mcp.cli.main (bool debug = False, bool skip_checks = False)
Start the DaVinci Resolve MCP Server.
Definition at line 99 of file cli.py.
References check_prerequisites(), main(), and print_status().
Referenced by main().
print_status()
None davinci_mcp.cli.print_status (str message, str status = "INFO")
Print a colored status message.
Definition at line 46 of file cli.py.
Referenced by check_prerequisites(), and main().
Variable Documentation
_original_stderr
davinci_mcp.cli._original_stderr = sys.stderr protected
Definition at line 24 of file cli.py.
_original_stdout
davinci_mcp.cli._original_stdout = sys.stdout protected
Definition at line 23 of file cli.py.
format
davinci_mcp.cli.format
Definition at line 38 of file cli.py.
level
davinci_mcp.cli.level
Definition at line 37 of file cli.py.
logger
davinci_mcp.cli.logger = logging.getLogger(__name__)
Definition at line 43 of file cli.py.