tags = {
    "step_name": "step_name",
    "step_num": "step_num",
    "bed_temp": "TIC02",
    "pressure": "PIC01",
    "n2_mfc_smLmin": "FIC01",
    "co2_mfc_smLmin": "FIC02",
    "h2_mfc_smLmin": "FIC03",
    "n2_gc_conc_pct": "N2",
    "co2_gc_conc_pct": "CO2",
    "h2_gc_conc_pct": "H2",
    "ch3oh_gc_conc_pct": "CH3OH",
    "dme_gc_conc_pct": "DME",
    "co_gc_conc_pct": "CO",
    "ch4_gc_conc_pct": "CH4",
    "c2h4_gc_conc_pct": "C2H4",
    "c3h6_gc_conc_pct": "C3H6",
    "c4h8_gc_conc_pct": "C4H8",
    "c5h10_gc_conc_pct": "C5H10",
    "c2h6_gc_conc_pct": "C2H6",
    "c3h8_gc_conc_pct": "C3H8",
    "c4h10_gc_conc_pct": "C4H10",
    "c5h12_gc_conc_pct": "C5H12",
}
