import _abc
import csp_lib.controller.core.command
import csp_lib.controller.core.strategy
import dataclasses
from csp_lib.controller.core.command import Command as Command, ConfigMixin as ConfigMixin
from csp_lib.controller.core.context import StrategyContext as StrategyContext
from csp_lib.controller.core.execution import ExecutionConfig as ExecutionConfig, ExecutionMode as ExecutionMode
from csp_lib.controller.core.strategy import Strategy as Strategy
from typing import ClassVar

class FPConfig(csp_lib.controller.core.command.ConfigMixin):
    f_base: ClassVar[float] = ...
    f1: ClassVar[float] = ...
    f2: ClassVar[float] = ...
    f3: ClassVar[float] = ...
    f4: ClassVar[float] = ...
    f5: ClassVar[float] = ...
    f6: ClassVar[float] = ...
    p1: ClassVar[float] = ...
    p2: ClassVar[float] = ...
    p3: ClassVar[float] = ...
    p4: ClassVar[float] = ...
    p5: ClassVar[float] = ...
    p6: ClassVar[float] = ...
    __dataclass_params__: ClassVar[dataclasses._DataclassParams] = ...
    __dataclass_fields__: ClassVar[dict] = ...
    __match_args__: ClassVar[tuple] = ...
    def get_absolute_frequencies(self) -> tuple[float, float, float, float, float, float]: ...
    def validate(self) -> None: ...
    def __replace__(self, **changes): ...
    def __init__(self, f_base: float = ..., f1: float = ..., f2: float = ..., f3: float = ..., f4: float = ..., f5: float = ..., f6: float = ..., p1: float = ..., p2: float = ..., p3: float = ..., p4: float = ..., p5: float = ..., p6: float = ...) -> None: ...
    def __eq__(self, other) -> bool: ...

class FPStrategy(csp_lib.controller.core.strategy.Strategy):
    __abstractmethods__: ClassVar[frozenset] = ...
    _abc_impl: ClassVar[_abc._abc_data] = ...
    def __init__(self, config: FPConfig | None = ...) -> None: ...
    def execute(self, context: StrategyContext) -> Command: ...
    def _calculate_power(self, frequency: float) -> float: ...
    @staticmethod
    def _interpolate(x: float, x1: float, x2: float, y1: float, y2: float) -> float: ...
    def update_config(self, config: FPConfig) -> None: ...
    @property
    def config(self): ...
    @property
    def execution_config(self): ...
