from PySide6.QtWidgets import QApplication
from PySide6.QtCore import QThreadPool, QByteArray, Qt
from PySide6.QtGui import QPixmap, QIcon
from qtmui.material.styles import theme_store
from qtmui.hooks.use_routes import router_store
def iconFromBase64(base64): ...
class QtMuiApp:
    def __init__(self, *args, **kwargs): ...
    def focus_changed(self, old_widget, new_widget): ...
    def close_all_widgets(self): ...