import uuid
from PySide6.QtWidgets import QFrame, QVBoxLayout, QWidget, QSizePolicy, QLayout, QScrollArea
from PySide6.QtCore import Qt, QRect, QSize, QPoint, QTimer
from ..chip import Chip
class FlowLayout:
    def __init__(self, parent, margin, spacing): ...
    def addItem(self, item): ...
    def count(self): ...
    def itemAt(self, index): ...
    def takeAt(self, index): ...
    def expandingDirections(self): ...
    def hasHeightForWidth(self): ...
    def heightForWidth(self, width): ...
    def setGeometry(self, rect): ...
    def sizeHint(self): ...
    def minimumSize(self): ...
    def doLayout(self, rect, testOnly): ...
class MultiSelectFrame:
    def __init__(self, parent, maxHeight): ...
    def add_widget(self, widget): ...
    def remove_all_items(self): ...
    def remove_item(self, label): ...
    def handleDelete(self): ...
    def updateSize(self): ...
    def resizeEvent(self, event): ...
    def scrollToBottom(self): ...
class CheckboxGroup:
    def __init__(self, context, children: list): ...
    def resizeEvent(self, event): ...