import uuid
from typing import Optional, Union, Dict, Callable, List
from PySide6.QtWidgets import QWidget, QHBoxLayout, QSizePolicy
from PySide6.QtCore import Qt
from qtmui.hooks import State, useEffect
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
from qtmui.material.styles import useTheme
from ..utils.validate_params import _validate_param
class DialogActions:
    def __init__(self, children: Optional[Union[State, QWidget, List[QWidget]]], classes: Optional[Union[State, Dict]], disableSpacing: Union[State, bool], sx: Optional[Union[State, Dict, Callable, str]], ref: Optional[Union[State, object]], **kwargs): ...
    def _set_children(self, value): ...
    def _get_children(self): ...
    def _set_classes(self, value): ...
    def _get_classes(self): ...
    def _set_disableSpacing(self, value): ...
    def _get_disableSpacing(self): ...
    def _set_sx(self, value): ...
    def _get_sx(self): ...
    def _set_ref(self, value): ...
    def _get_ref(self): ...
    def forward_ref(self, ref): ...
    def _update_spacing(self): ...
    def _add_children_to_layout(self): ...
    def _set_stylesheet(self, component_styled): ...
    def _connect_signals(self): ...
    def _on_children_changed(self): ...
    def _on_classes_changed(self): ...
    def _on_disableSpacing_changed(self): ...
    def _on_sx_changed(self): ...
    def _on_ref_changed(self): ...
    def _clear_layout(self): ...
    def _on_destroyed(self): ...