# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WalletPaymentInit.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from igap_bot.proto import Request_pb2 as Request__pb2
from igap_bot.proto import Response_pb2 as Response__pb2
from igap_bot.proto import Global_pb2 as Global__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WalletPaymentInit.proto',
  package='proto',
  syntax='proto3',
  serialized_pb=_b('\n\x17WalletPaymentInit.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\x1a\x0cGlobal.proto\"\x9d\x01\n\x11WalletPaymentInit\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\x12!\n\x08language\x18\x02 \x01(\x0e\x32\x0f.proto.Language\x12\x0b\n\x03jwt\x18\x03 \x01(\t\x12\x12\n\nto_user_id\x18\x04 \x01(\x04\x12\x0e\n\x06\x61mount\x18\x05 \x01(\x04\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\"a\n\x19WalletPaymentInitResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12\r\n\x05token\x18\x02 \x01(\t\x12\x12\n\npublic_key\x18\x03 \x01(\tB(\n\x0enet.iGap.protoB\x16ProtoWalletPaymentInitb\x06proto3')
  ,
  dependencies=[Request__pb2.DESCRIPTOR,Response__pb2.DESCRIPTOR,Global__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_WALLETPAYMENTINIT = _descriptor.Descriptor(
  name='WalletPaymentInit',
  full_name='proto.WalletPaymentInit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='proto.WalletPaymentInit.request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='language', full_name='proto.WalletPaymentInit.language', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='jwt', full_name='proto.WalletPaymentInit.jwt', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='to_user_id', full_name='proto.WalletPaymentInit.to_user_id', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='amount', full_name='proto.WalletPaymentInit.amount', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='proto.WalletPaymentInit.description', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=237,
)


_WALLETPAYMENTINITRESPONSE = _descriptor.Descriptor(
  name='WalletPaymentInitResponse',
  full_name='proto.WalletPaymentInitResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='proto.WalletPaymentInitResponse.response', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='proto.WalletPaymentInitResponse.token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='public_key', full_name='proto.WalletPaymentInitResponse.public_key', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=336,
)

_WALLETPAYMENTINIT.fields_by_name['request'].message_type = Request__pb2._REQUEST
_WALLETPAYMENTINIT.fields_by_name['language'].enum_type = Global__pb2._LANGUAGE
_WALLETPAYMENTINITRESPONSE.fields_by_name['response'].message_type = Response__pb2._RESPONSE
DESCRIPTOR.message_types_by_name['WalletPaymentInit'] = _WALLETPAYMENTINIT
DESCRIPTOR.message_types_by_name['WalletPaymentInitResponse'] = _WALLETPAYMENTINITRESPONSE

WalletPaymentInit = _reflection.GeneratedProtocolMessageType('WalletPaymentInit', (_message.Message,), dict(
  DESCRIPTOR = _WALLETPAYMENTINIT,
  __module__ = 'WalletPaymentInit_pb2'
  # @@protoc_insertion_point(class_scope:proto.WalletPaymentInit)
  ))
_sym_db.RegisterMessage(WalletPaymentInit)

WalletPaymentInitResponse = _reflection.GeneratedProtocolMessageType('WalletPaymentInitResponse', (_message.Message,), dict(
  DESCRIPTOR = _WALLETPAYMENTINITRESPONSE,
  __module__ = 'WalletPaymentInit_pb2'
  # @@protoc_insertion_point(class_scope:proto.WalletPaymentInitResponse)
  ))
_sym_db.RegisterMessage(WalletPaymentInitResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\016net.iGap.protoB\026ProtoWalletPaymentInit'))
# @@protoc_insertion_point(module_scope)
