import asyncio
from functools import lru_cache
import inspect
import threading
import uuid
import time
from typing import Optional, Callable, Any, Dict, Union, List
from PySide6.QtWidgets import QVBoxLayout, QWidget, QHBoxLayout, QPlainTextEdit, QLineEdit, QApplication, QStyledItemDelegate, QSizePolicy, QPushButton, QSpinBox, QDoubleSpinBox, QGraphicsOpacityEffect, QFrame, QGroupBox
from PySide6.QtCore import Qt, QPoint, Signal, QDate, QTime, QTimer, QEvent, QSize
from PySide6.QtGui import QCursor
from qtmui.hooks import State
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
from qtmui.material.list_view.list_view import ListView
from qtmui.utils.data import deep_merge
from qtmui.utils.translator import getTranslatedText
from ..li import Li
from ..menu import Menu
from ..menu_item import MenuItem
from .flow_layout import FlowLayout
from .tags_view import TagsView
from ..picker import DatePicker, TimePicker, AMTimePicker, ZhDatePicker, CalendarPicker, ColorPicker
from qtmui.hooks import useState
from qtmui.material.styles import useTheme
from qtmui.i18n.use_translation import translate, i18n
from ..utils._misc import signals_blocked
from ..utils.functions import _get_fn_args
from ...qtmui_assets import QTMUI_ASSETS
from ..py_iconify import PyIconify
from .py_combobox import PyComboBox
from .py_date_edit import PyDateEdit
from .py_date_time_edit import PyDateTimeEdit
from .py_dial import PyDial
from .py_double_spinbox import PyDoubleSpinBox
from .py_font_combobox import PyFontComboBox
from .tf_line_edit import TFLineEdit
from .tf_line_edit_multiple import TFLineEditMultiple
from .py_plaintext_edit import PyPlainTextEdit
from .py_plaintext_edit_multiple import PyPlainTextEditMultiple
from .py_spin_box import PySpinBox
from .py_text_edit import PyTextEdit
from .py_time_edit import PyTimeEdit
from ..widget_base import PyWidgetBase
from ._validate import ValidateMixin
class TextField:
    def __init__(self, parent, *args, **kwargs): ...
    def _connect_signals_props(self): ...
    def __init_ui(self): ...
    def _onDestroy(self, obj): ...
    def _onThemeChanged(self): ...
    def _scheduleSetupDefaultTags(self): ...
    def _scheduleSetStyleSheet(self): ...
    def _scheduleSetupSelectMode(self): ...
    def _setup_select_mode(self): ...
    def _setSxDict(cls, sx): ...
    def _setKwargs(cls, kwargs: dict): ...
    def _getSxQss(cls, sxStr: str, className: str): ...
    def _setStyleSheet(self): ...
    def _getStylesheet(cls, styledConfig: str, _variant: str, _size: str, _theme_mode: str, _multiple: str, _multiline: str, _renderTags: str, _focused: str): ...
    def _render_stylesheet(self): ...
    def _update_stylesheet(self, stylesheet): ...
    def _create_menu(self): ...
    def onFocusIn(self, event): ...
    def onFocusInMultiple(self, event): ...
    def onFocusOut(self, event): ...
    def onMouseEnter(self, event): ...
    def onMouseLeave(self, event): ...
    def onMouseRelease(self, event): ...
    def onMultipleInputFieldClicked(self, event): ...
    def onChange(self, value): ...
    def _set_state(self, stateValue: dict): ...
    def _set_data(self, value, valueChanged, setText): ...
    def _set_text(self): ...
    def _set_slot(self, data): ...
    def _on_text_changed(self, s): ...
    def _render_search_menu_items(self, search_options_results): ...
    def validate_type_int(self): ...
    def _setupy_input_type(self): ...
    def _set_date_picker(self, date: QDate): ...
    def _set_time_picker(self, time: QTime): ...
    def _setup_input_props(self): ...
    def _on_clear_text(self): ...
    def _update_popup_position(self): ...
    def _hide_popup(self): ...
    def _btn_select_toggle_popup(self, e): ...
    def _toggle_popup(self, e): ...
    def _show_popup(self, search): ...
    def _updatePopupPosition(self): ...
    def _on_menu_item_selected(self, key): ...
    def _about_to_hide(self): ...
    def getTagProps(self, index): ...
    def _on_tag_deleted(self, index): ...
    def _update_selected_options(self, key, option): ...
    def _setup_tags(self, key, option): ...
    def _selected_change(self, data): ...
    def _show_label(self): ...
    def _set_translated_label(self): ...
    def _hide_label(self): ...
    def _set_hovered_prop(self): ...
    def _set_focused_prop(self): ...
    def _set_multiple_has_value_prop(self, state): ...
    def _set_prop_has_start_adornment(self, state: bool): ...
    def setup_action_frame_and_adornment(self): ...
    def leaveEvent(self, event): ...
    def resizeEvent(self, event): ...
    def showEvent(self, event): ...
    def eventFilter(self, obj, event): ...