from PySide6.QtCore import QSize, Qt, Signal, QPoint, QRectF, QPointF, QPropertyAnimation, Property
from PySide6.QtGui import QColor, QPainter, QPainterPath, QMouseEvent
from PySide6.QtWidgets import QProxyStyle, QSlider, QWidget
from ...common.style_sheet import FluentStyleSheet, themeColor
from ...common.overload import singledispatchmethod
from qtmui.material.styles import useTheme
class SliderHandle:
    def __init__(self, parent: QSlider): ...
    def radius(self): ...
    def radius(self, r): ...
    def enterEvent(self, e): ...
    def leaveEvent(self, e): ...
    def mousePressEvent(self, e): ...
    def mouseReleaseEvent(self, e): ...
    def _startAni(self, radius): ...
    def paintEvent(self, e): ...
class Slider:
    def __init__(self, parent: QWidget, valueLabelDisplay: str, style): ...
    def _(self, orientation: Qt.Orientation, valueLabelDisplay: str, parent: QWidget, style): ...
    def _postInit(self): ...
    def setOrientation(self, orientation: Qt.Orientation): ...
    def mousePressEvent(self, e: QMouseEvent): ...
    def mouseMoveEvent(self, e: QMouseEvent): ...
    def grooveLength(self): ...
    def _adjustHandlePos(self): ...
    def _posToValue(self, pos: QPoint): ...
    def paintEvent(self, e): ...
    def _drawHorizonGroove(self, painter: QPainter): ...
    def _drawVerticalGroove(self, painter: QPainter): ...
    def resizeEvent(self, e): ...
class ClickableSlider:
    def mousePressEvent(self, e): ...
class HollowHandleStyle:
    def __init__(self, config: dict): ...
    def subControlRect(self, cc, opt, sc, widget): ...
    def drawComplexControl(self, cc, opt, painter, widget): ...