from PySide6.QtWidgets import QWidget, QApplication
from PySide6.QtCore import QTimer
from PySide6.QtGui import QPainter, QColor
import sys
import random
from qtmui.material.styles import useTheme
def alpha(color: QColor, alpha: float): ...
class LinearDeterminate:
    def __init__(self, key: str, color: str, value: float): ...
    def update_progress(self): ...
    def paintEvent(self, event): ...