from PySide6.QtWidgets import QWidget, QVBoxLayout, QLabel
from PySide6.QtCore import Property, Slot
from ...material._common.widget_model import WidgetModel
from qtmui.material.styles import useTheme
from ..qss_name import *
class RHFHidden:
    def __init__(self, name: str, id: str, model: WidgetModel, helperText: str): ...
    def on_model_data_changed(self): ...
    def set_value(self, value): ...
    def set_helper_text(self, text): ...
    def set_error_text(self, text): ...
    def stateSignal(self): ...
    def stateSignal(self, value): ...
    def state(self, state): ...