"""Type stubs for _rapcsv Rust extension module."""

from typing import Coroutine, Any, List, Optional

class Reader:
    def __init__(self, path: str) -> None: ...
    def read_row(self) -> Coroutine[Any, Any, List[str]]: ...
    def __aenter__(self) -> Coroutine[Any, Any, "Reader"]: ...
    def __aexit__(
        self,
        exc_type: Optional[Any],
        exc_val: Optional[Any],
        exc_tb: Optional[Any],
    ) -> Coroutine[Any, Any, None]: ...

class Writer:
    def __init__(self, path: str) -> None: ...
    def write_row(self, row: List[str]) -> Coroutine[Any, Any, None]: ...
    def close(self) -> Coroutine[Any, Any, None]: ...
    def __aenter__(self) -> Coroutine[Any, Any, "Writer"]: ...
    def __aexit__(
        self,
        exc_type: Optional[Any],
        exc_val: Optional[Any],
        exc_tb: Optional[Any],
    ) -> Coroutine[Any, Any, None]: ...

class CSVError(Exception):
    def __init__(self, message: str) -> None: ...

class CSVFieldCountError(Exception):
    def __init__(self, message: str) -> None: ...