from clustercomputers._proto.clustercomputers.world.rpc import get_active_world_subscriptions_request_pb2 as _get_active_world_subscriptions_request_pb2
from clustercomputers._proto.clustercomputers.world.rpc import get_active_world_subscriptions_response_pb2 as _get_active_world_subscriptions_response_pb2
from clustercomputers._proto.clustercomputers.world.rpc import get_pending_world_actions_request_pb2 as _get_pending_world_actions_request_pb2
from clustercomputers._proto.clustercomputers.world.rpc import get_pending_world_actions_response_pb2 as _get_pending_world_actions_response_pb2
from clustercomputers._proto.clustercomputers.world.rpc import send_world_result_request_pb2 as _send_world_result_request_pb2
from clustercomputers._proto.clustercomputers.world.rpc import send_world_result_response_pb2 as _send_world_result_response_pb2
from clustercomputers._proto.clustercomputers.world.rpc import send_world_subscription_update_request_pb2 as _send_world_subscription_update_request_pb2
from clustercomputers._proto.clustercomputers.world.rpc import send_world_subscription_update_response_pb2 as _send_world_subscription_update_response_pb2
from clustercomputers._proto.clustercomputers.world.rpc import subscribe_world_actions_request_pb2 as _subscribe_world_actions_request_pb2
from clustercomputers._proto.clustercomputers.world.rpc import subscribe_world_actions_response_pb2 as _subscribe_world_actions_response_pb2
from clustercomputers._proto.clustercomputers.world.rpc import subscribe_world_subscription_requests_request_pb2 as _subscribe_world_subscription_requests_request_pb2
from clustercomputers._proto.clustercomputers.world.rpc import subscribe_world_subscription_requests_response_pb2 as _subscribe_world_subscription_requests_response_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
