##############################################################################
#
#         License**
#
##############################################################################
{
    'name': 'Sistema de gestión Editorial',
    'version': "17.0.1.4.0",
    'summary': 'Módulo de gestión para entidades del mundo del libro',
    'description': 'Módulo de gestión para entidades del mundo del libro',
    'category': 'Industries',
    'author': 'Colectivo DEVCONTROL',
    'author_email': 'devcontrol@sindominio.net',
    'maintainer': 'Colectivo DEVCONTROL',
    'company': 'Colectivo DEVCONTROL',
    'website': 'https://framagit.org/devcontrol',
    'depends': [
        'account',
        'account_invoice_pricelist',
        'base',
        'contacts',
        'l10n_es',
        'product',
        'point_of_sale',
        'purchase',
        'sale',
        'sale_management',
        'sale_purchase',
        'sale_stock',
        'stock',
        'product_logistics_uom',
        'product_dimension',
    ],
    'data': [
        'data/initial_data.xml',
        'data/purchase_deposit_data.xml',
        'data/ddaa_data.xml',
        'data/promocion_data.xml',
        'wizards/liquidation_lines/liquidation_lines.xml',
        'wizards/info_message/info_message_wizard.xml',
        'wizards/negative_ddaa_order/negative_ddaa_order_wizard.xml',
        'views/messages/ddaa_order_continuation.xml',
        'views/res_partner_editorial_view.xml',
        'views/res_partner_type_editorial_view.xml',
        'views/liquidacion_editorial_view.xml',
        'views/sales_liquidation_view.xml',
        'views/purchases_liquidation_view.xml',
        'views/purchase_order_editorial_view.xml',
        'views/ddaa/ddaa_conditions_for_authorship.xml',
        'views/ddaa/ddaa_order_editorial_view.xml',
        'views/ddaa/products.xml',
        'views/product_editorial_view.xml',
        'views/stock_picking_internal_search.xml',
        'views/sale_order_editorial_view.xml',
        'views/stock_picking_editorial_view.xml',
        'views/stock_quant_editorial_view.xml',
        'views/report_purchaseorder_document_editorial_view.xml',
        'views/report_purchasequotation_document_editorial_view.xml',
        'views/report_stockpicking_operations_document_editorial_view.xml',
        'views/report_saleorder_document_editorial_view.xml',
        'views/report_invoice_document_editorial_view.xml',
        'views/res_config_settings_editorial_view.xml',
        'views/product_pricelist_editorial_view.xml',
        'views/product_tag_editorial_view.xml',
        'views/stock_location_route_form_editorial_view.xml',
        'views/menu_items.xml',
        'views/menu_items/contact.xml',
        'views/menu_items/ddaa.xml',
        'views/menu_items/product.xml',
        'security/ir.model.access.csv',
    ],
    'assets': {
        'web.assets_backend': [
            'gestion_editorial/static/src/**/*',
        ],
    },
    'pre_init_hook': 'pre_init_hook',
    'post_init_hook': 'post_init_hook',
    'license': 'OPL-1',
    'price': 0,
    'currency': 'EUR',
    'installable': True,
    'application': True,
    'auto_install': False,
}
