from typing import Protocol


class ConsolePort(Protocol):
    """Port for console output operations."""

    def info(self, msg: str) -> None: ...
    def warn(self, msg: str) -> None: ...
    def echo(self, msg: str) -> None: ...
    def confirm(self, msg: str, default: bool = True) -> bool: ...
