import asyncio
from functools import lru_cache
import uuid
from typing import Optional, Callable, Any, Dict, Union
from PySide6.QtWidgets import QDial, QHBoxLayout
from PySide6.QtCore import QTimer
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
from .py_input_base import MuiInputBase
from qtmui.material.styles import useTheme
from qtmui.hooks import State
from qtmui.i18n.use_translation import translate
class PyDial:
    def __init__(self, parent, label: Optional[str], onChange: Optional[Callable], children: Optional[list], sx: Optional[Union[Dict, Callable, str]], variant: str, size: str, **kwargs): ...
    def _init_ui(self): ...
    def _onDestroy(self, obj): ...
    def _onThemeChanged(self): ...
    def _scheduleSetStyleSheet(self): ...
    def _get_stylesheet(cls, _variant: str, _size: str, _theme_mode: str): ...
    def _set_stylesheet(self, component_styled): ...
    def enterEvent(self, event): ...
    def leaveEvent(self, event): ...
    def mousePressEvent(self, event): ...
    def mouseReleaseEvent(self, event): ...
    def focusInEvent(self, event): ...
    def focusOutEvent(self, event): ...