import asyncio
import uuid
from typing import Optional, Callable, Any, Dict, Union
from PySide6.QtWidgets import QLineEdit, QHBoxLayout, QGroupBox
from PySide6.QtCore import QTimer
from qtmui.i18n.use_translation import i18n, translate
from qtmui.material.styles import useTheme
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
from qtmui.hooks import State
class MuiInput:
    def __init__(self, disabled: Optional[Union[State, str]], label: Optional[Union[State, str]], hiddenLabel: bool, focused: Optional[Union[State, bool]], hovered: Optional[Union[State, bool]], children: Optional[list], multiple: bool, multiline: bool, renderTags: Optional[Callable], size: Optional[Union[str]], sx: Optional[Union[Dict, Callable, str]], value: Optional[Union[State, object]], **kwargs): ...
    def _init_ui(self): ...
    def _onDestroy(self, obj): ...
    def _onThemeChanged(self): ...
    def _scheduleSetStyleSheet(self): ...
    def _set_stylesheet(self, component_styled): ...
    def _show_label(self): ...
    def _set_translated_label(self): ...
    def _hide_label(self): ...
    def _set_hovered_prop(self): ...
    def _set_focused_prop(self): ...
    def _set_multiple_has_value_prop(self, state): ...