from typing import Optional, Callable
class TFInputBase:
    def __init__(self, parent, onMouseEnter: Optional[Callable], onMouseLeave: Optional[Callable], onMousePress: Optional[Callable], onMouseRelease: Optional[Callable], onFocusIn: Optional[Callable], onFocusOut: Optional[Callable], tooltip: Optional[str], tooltipPlacement: Optional[str], tooltipLeaveDelay: Optional[int], *args, **kwargs): ...
    def _setUpUi(self, **kwargs): ...
    def enterEvent(self, event): ...
    def leaveEvent(self, event): ...
    def mousePressEvent(self, event): ...
    def mouseReleaseEvent(self, event): ...
    def focusInEvent(self, event): ...
    def focusOutEvent(self, event): ...