HUMA_FINANCE_DOMAIN_NAME = "huma.finance"
SERVER_ALLOW_ORIGIN_REGEX = (
    r"^https://pr-\d+\.d382yqc38xh8lk\.amplifyapp\.com"
    r"|https://master\.d382yqc38xh8lk\.amplifyapp\.com"
    r"|https://pr-\d+\.d20vuzdx6qyd8u\.amplifyapp\.com"
    r"|https://pr-\d+\.d8xz2ktp6ypg3\.amplifyapp\.com"
    r"|https://admin-testnet\.d3916bhqsqthjl\.amplifyapp\.com"
    r"|https://admin-develop\.d3916bhqsqthjl\.amplifyapp\.com"
    r"|https://devnet\.admin\.huma\.finance"
    r"|https://staging\.admin\.huma\.finance"
    r"|https://admin\.huma\.finance"
    r"|https://dev-testnet\.x\.huma\.finance"
    r"|https://dev\.x\.huma\.finance"
    r"|https://x\.huma\.finance"
    r"|https://institutional\.huma\.finance"
    r"|https://inst\.huma\.finance"
    r"|https://dev\.app\.huma\.finance"
    r"|https://dev-testnet\.app\.huma\.finance"
    r"|https://dev\.testnet\.app\.huma\.finance"
    r"|https://dev\.testnet\.huma\.finance"
    r"|https://testnet\.app\.huma\.finance"
    r"|https://testnet-campaigns\.app\.huma\.finance"
    r"|https://campaigns\.app\.huma\.finance"
    r"|https://app\.huma\.finance"
    r"|https://dev\.testnet\.campaign-points\.huma\.finance"
    r"|https://testnet\.campaign-points\.huma\.finance"
    r"|https://dev\.mainnet\.campaign-points\.huma\.finance"
    r"|https://testnet\.campaign-points\.huma\.finance"
    r"|https://devnet\.solapp\.huma\.finance"
    r"|https://dev\.devnet\.solapp\.huma\.finance"
    r"|https://local\.bulla\.network:1234"
    r"|https://dev\.bulla\.network"
    r"|https://banker\.bulla\.network"
    r"|https://dev-testnet\.claim\.huma\.finance"
    r"|https://dev\.claim\.huma\.finance"
    r"|https://claim\.huma\.finance"
    r"|https://dev\.presale\.huma\.finance"
    r"|https://presale\.huma\.finance"
    # Safe wallets require https even for localhost.
    r"|https?://localhost:\d+$"
)

WALLET_TOKEN_KEY_PREFIX = "id_token"
ACCOUNT_TOKEN_KEY = "account_token"
