import csp_lib.modbus.enums
import dataclasses
from csp_lib.modbus.enums import ByteOrder, RegisterOrder
from csp_lib.modbus.types.base import ModbusDataType
from typing import Any, ClassVar, Iterable

__all__ = ['ModbusDecoder', 'ModbusEncoder']

class ModbusDecoder:
    byte_order: ClassVar[csp_lib.modbus.enums.ByteOrder] = ...
    register_order: ClassVar[csp_lib.modbus.enums.RegisterOrder] = ...
    __dataclass_params__: ClassVar[dataclasses._DataclassParams] = ...
    __dataclass_fields__: ClassVar[dict] = ...
    __match_args__: ClassVar[tuple] = ...
    def apply(self, value: Iterable[Any]) -> Any: ...
    def __replace__(self, **changes): ...
    def __init__(self, data_type: ModbusDataType, byte_order: ByteOrder = ..., register_order: RegisterOrder = ...) -> None: ...
    def __eq__(self, other) -> bool: ...

class ModbusEncoder:
    byte_order: ClassVar[csp_lib.modbus.enums.ByteOrder] = ...
    register_order: ClassVar[csp_lib.modbus.enums.RegisterOrder] = ...
    __dataclass_params__: ClassVar[dataclasses._DataclassParams] = ...
    __dataclass_fields__: ClassVar[dict] = ...
    __match_args__: ClassVar[tuple] = ...
    def apply(self, value: Any) -> list[int]: ...
    def __replace__(self, **changes): ...
    def __init__(self, data_type: ModbusDataType, byte_order: ByteOrder = ..., register_order: RegisterOrder = ...) -> None: ...
    def __eq__(self, other) -> bool: ...
