from collections.abc import Callable

__all__ = ['decorate_return_types', 'update_annotations', 'update_docstring', 'wraps']

def decorate_return_types(text: str) -> str: ...
def update_annotations(annotations: dict[str, str]) -> dict[str, str]: ...
def update_docstring(docstring: str | None) -> str: ...
def wraps(func: Callable[..., object]) -> Callable[[_F], _F]: ...
