ATTRIBUTES = {
    "basic belt 0": {"transport", "table"},
    "basic belt 1": {"transport", "table"},
    "basic belt 2": {"transport", "table"},
    "basic belt 3": {"transport", "table"},
    "basic belt 4": {"transport", "table"},
    "basic belt 5": {"transport", "table"},
    "basic belt 6": {"transport", "table"},
    "basic belt 7": {"transport", "table"},
    "basic belt 8": {"transport", "table"},
    "basic belt 9": {"transport", "table"},
    "basic belt 10": {"transport", "table"},
    "basic belt 11": {"transport", "table"},
    "basic merger 0": {"transport"},
    "basic merger 1": {"transport"},
    "basic merger 2": {"transport"},
    "basic merger 3": {"transport"},
    "basic splitter 0": {"transport"},
    "basic splitter 1": {"transport"},
    "basic splitter 2": {"transport"},
    "basic splitter 3": {"transport"},
    "basic toolbench": {"open", "craft"},
    "bronze harvester": {"open", "machine", "harvester"},
    "burner drill": {"open", "machine", "drill"},
    "caelium sieve": {"open", "machine"},
    "campfire": {"open", "craft"},
    "composter": {"open", "machine"},
    "connector": {"open", "connected"},
    "copper anvil": {"open", "craft"},
    "copper boiler": {"open", "machine"},
    "copper constructor": {"open", "craft"},
    "copper press": {"open", "machine"},
    "destroyed void crate": {"open", "store"},
    "drill": {"drill"},
    "dye bench": {"open", "craft"},
    "furless rabbit": {"animal", "creature"},
    "furnace": {"open", "machine"},
    "left": {"point"},
    "mana constructor": {"open", "machine"},
    "mana converter": {"open", "machine"},
    "mana deconstructor": {"open", "machine"},
    "manual press": {"open", "craft"},
    "masonry bench": {"open", "craft"},
    "mushroom shaper": {"open", "craft"},
    "mushroom table": {"store", "table"},
    "packager bench": {"open", "craft"},
    "player": {"open", "craft"},
    "quartz adult": {"enemy", "creature"},
    "quartz altar": {"open", "craft"},
    "quartz child": {"enemy", "creature"},
    "rabbit adult": {"animal", "creature"},
    "rabbit child": {"animal", "creature"},
    "sawbench": {"open", "craft"},
    "sewbench": {"open", "craft"},
    "skeleton": {"enemy", "creature"},
    "slime": {"enemy", "creature"},
    "slime prince": {"enemy", "creature"},
    "slime shaper": {"open", "craft"},
    "slime table": {"store", "table"},
    "small barrel": {"open", "store"},
    "small crate": {"open", "store"},
    "steam constructor": {"open", "machine"},
    "steam crusher": {"open", "machine"},
    "steam drill": {"open", "machine", "drill"},
    "steam furnace": {"open", "machine"},
    "steam part assembler": {"open", "machine"},
    "steam pump": {"open", "machine"},
    "tree constructor": {"open", "craft"},
    "up": {"point"},
    "void converter": {"open", "craft"},
    "void crate": {"open", "store"},
    "wood crucible": {"open", "machine"},
    "wooden bed": {"sleep"},
    "wooden sieve": {"open", "machine"},
    "wooden table": {"store", "table"},
    "workbench": {"open", "craft"},
}
