# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 1.3.0
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from mixpeek.models.trigger_execution_history_item import TriggerExecutionHistoryItem
from typing import Optional, Set
from typing_extensions import Self

class SharedClustersTriggersModelsTriggerHistoryResponse(BaseModel):
    """
    Response for trigger execution history.
    """ # noqa: E501
    trigger_id: StrictStr = Field(description="Trigger ID")
    executions: List[TriggerExecutionHistoryItem] = Field(description="Execution history")
    total: StrictInt = Field(description="Total executions")
    offset: StrictInt = Field(description="Current offset")
    limit: StrictInt = Field(description="Current limit")
    __properties: ClassVar[List[str]] = ["trigger_id", "executions", "total", "offset", "limit"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SharedClustersTriggersModelsTriggerHistoryResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in executions (list)
        _items = []
        if self.executions:
            for _item_executions in self.executions:
                if _item_executions:
                    _items.append(_item_executions.to_dict())
            _dict['executions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SharedClustersTriggersModelsTriggerHistoryResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "trigger_id": obj.get("trigger_id"),
            "executions": [TriggerExecutionHistoryItem.from_dict(_item) for _item in obj["executions"]] if obj.get("executions") is not None else None,
            "total": obj.get("total"),
            "offset": obj.get("offset"),
            "limit": obj.get("limit")
        })
        return _obj


