
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2026-01-21T11:49:41-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "63ac9a63f9549380f07bf90d8c5f0d80db38bb53",
 "version": "3.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
