import os
from dotenv import load_dotenv
from typing import Optional

load_dotenv()

URI_CONNECTION_DB_VILLACRUZ: Optional[str]= os.getenv("URL_SQLSERVER_VILLACRUZ_VPS_SMARTERASP", "No definida: URL_SQLSERVER_VILLACRUZ_VPS_SMARTERASP")
URI_CONNECTION_DB_CASTILLO: Optional[str]= os.getenv("URL_SQLSERVER_CASTILLO_VPS_SMARTERASP", "No definida: URL_SQLSERVER_VILLACRUZ_VPS_SMARTERASP")
URI_CONNECTION_DB_ALQUIVENTAS: Optional[str]= os.getenv("URL_SQLSERVER_ALQUIVENTAS_VPS_SMARTERASP", "No definida: URL_SQLSERVER_VILLACRUZ_VPS_SMARTERASP")
URI_CONNECTION_DB_LIVIN: Optional[str]= os.getenv("URL_SQLSERVER_LIVIN_VPS_SMARTERASP", "No definida: URL_SQLSERVER_VILLACRUZ_VPS_SMARTERASP")
