import uuid
from PySide6.QtWidgets import QFrame, QHBoxLayout, QVBoxLayout, QLabel, QPushButton, QApplication
from PySide6.QtGui import QCursor, Qt, QIcon
from PySide6.QtCore import Signal, QSize
from qtmui.material.styles import useTheme
from qtmui.hooks import State
from ...common.functions import *
from ...common.json_settings import Settings
from .py_div import PyDiv
from .py_title_button import PyTitleButton
class TitleBar:
    def __init__(self, logo_image, logo_width, buttons, dark_one, bgColor, div_color, btn_bgColor, btn_bgColor_hover, btn_bgColor_pressed, icon_color, icon_color_hover, icon_color_pressed, icon_color_active, context_color, text_foreground, radius, font_family, title_size, is_custom_title_bar, maximumHeight: int, children): ...
    def _set_stylesheet(self, background): ...
    def add_menus(self, parameters): ...
    def btn_clicked(self): ...
    def btn_released(self): ...
    def set_title(self, title): ...
    def maximize_restore(self, e): ...
    def setup_ui(self): ...
    def _autorun_set_theme(self): ...