from proalgotrader_core.enums.symbols.stock_type import StockType
from proalgotrader_core.enums.symbols.index_type import IndexType


class SymbolType:
    Stock = StockType()
    Index = IndexType()

    NIFTY_50 = [
        Stock.SBIN,
        Stock.ADANIENT,
        Stock.TATASTEEL,
        Stock.ONGC,
        Stock.POWERGRID,
        Stock.NTPC,
        Stock.ITC,
        Stock.COALINDIA,
        Stock.UPL,
        Stock.WIPRO,
        Stock.HINDALCO,
        Stock.HDFCLIFE,
        Stock.BPCL,
        Stock.SBIN,
        Stock.JSWSTEEL,
        Stock.TATAMOTORS,
        Stock.ICICIBANK,
        Stock.AXISBANK,
        Stock.BHARTIARTL,
        Stock.TATACONSUM,
        Stock.TECHM,
        Stock.ADANIPORTS,
        Stock.HDFCBANK,
        Stock.CIPLA,
        Stock.SBILIFE,
        Stock.BAJAJFINSV,
        Stock.INDUSINDBK,
        Stock.INFY,
        Stock.SUNPHARMA,
        Stock.HCLTECH,
        Stock.KOTAKBANK,
        Stock.M_M,
        Stock.GRASIM,
        Stock.HINDUNILVR,
        Stock.NESTLEIND,
        Stock.ASIANPAINT,
        Stock.RELIANCE,
        Stock.ADANIENT,
        Stock.DIVISLAB,
        Stock.LT,
        Stock.TITAN,
        Stock.EICHERMOT,
        Stock.TCS,
        Stock.HEROMOTOCO,
        Stock.BRITANNIA,
        Stock.LTIM,
        Stock.APOLLOHOSP,
        Stock.DRREDDY,
        Stock.BAJFINANCE,
        Stock.BAJAJ_AUTO,
        Stock.ULTRACEMCO,
        Stock.MARUTI,
    ]
