import dataclasses
import enum
from typing import ClassVar

__all__ = ['AlarmDefinition', 'AlarmLevel', 'HysteresisConfig', 'NO_HYSTERESIS']

class AlarmLevel(enum.IntEnum):
    _new_member_: ClassVar[builtin_function_or_method] = ...
    _use_args_: ClassVar[bool] = ...
    _member_names_: ClassVar[list] = ...
    _member_map_: ClassVar[dict] = ...
    _value2member_map_: ClassVar[dict] = ...
    _hashable_values_: ClassVar[list] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value_repr_: ClassVar[wrapper_descriptor] = ...
    INFO: ClassVar[AlarmLevel] = ...
    WARNING: ClassVar[AlarmLevel] = ...
    ALARM: ClassVar[AlarmLevel] = ...
    __format__: ClassVar[method_descriptor] = ...
    @staticmethod
    def _generate_next_value_(name, start, count, last_values): ...
    @classmethod
    def __init__(cls, value) -> None: ...

class HysteresisConfig:
    activate_threshold: ClassVar[int] = ...
    clear_threshold: ClassVar[int] = ...
    __dataclass_params__: ClassVar[dataclasses._DataclassParams] = ...
    __dataclass_fields__: ClassVar[dict] = ...
    __match_args__: ClassVar[tuple] = ...
    def __post_init__(self) -> None: ...
    def __replace__(self, **changes): ...
    def __hash__(self) -> int: ...
    def __init__(self, activate_threshold: int = ..., clear_threshold: int = ...) -> None: ...
    def __eq__(self, other) -> bool: ...
    def __setattr__(self, name, value): ...
    def __delattr__(self, name): ...
NO_HYSTERESIS: HysteresisConfig

class AlarmDefinition:
    level: ClassVar[AlarmLevel] = ...
    hysteresis: ClassVar[HysteresisConfig] = ...
    description: ClassVar[str] = ...
    __dataclass_params__: ClassVar[dataclasses._DataclassParams] = ...
    __dataclass_fields__: ClassVar[dict] = ...
    __match_args__: ClassVar[tuple] = ...
    def __hash__(self) -> int: ...
    def __replace__(self, **changes): ...
    def __init__(self, code: str, name: str, level: AlarmLevel = ..., hysteresis: HysteresisConfig = ..., description: str = ...) -> None: ...
    def __eq__(self, other) -> bool: ...
    def __setattr__(self, name, value): ...
    def __delattr__(self, name): ...
