import dataclasses
import enum
from csp_lib.equipment.alarm.definition import AlarmDefinition
from datetime import datetime
from typing import ClassVar

__all__ = ['AlarmEventType', 'AlarmEvent', 'AlarmState', 'AlarmStateManager']

class AlarmEventType(enum.Enum):
    _new_member_: ClassVar[builtin_function_or_method] = ...
    _use_args_: ClassVar[bool] = ...
    _member_names_: ClassVar[list] = ...
    _member_map_: ClassVar[dict] = ...
    _value2member_map_: ClassVar[dict] = ...
    _hashable_values_: ClassVar[list] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _member_type_: ClassVar[type[object]] = ...
    _value_repr_: ClassVar[None] = ...
    TRIGGERED: ClassVar[AlarmEventType] = ...
    CLEARED: ClassVar[AlarmEventType] = ...
    @staticmethod
    def _generate_next_value_(name, start, count, last_values): ...
    @classmethod
    def __init__(cls, value) -> None: ...

class AlarmEvent:
    __dataclass_params__: ClassVar[dataclasses._DataclassParams] = ...
    __dataclass_fields__: ClassVar[dict] = ...
    __match_args__: ClassVar[tuple] = ...
    def __replace__(self, **changes): ...
    def __init__(self, event_type: AlarmEventType, alarm: AlarmDefinition, timestamp: datetime = ...) -> None: ...
    def __eq__(self, other) -> bool: ...

class AlarmState:
    is_active: ClassVar[bool] = ...
    activate_count: ClassVar[int] = ...
    clear_count: ClassVar[int] = ...
    activated_at: ClassVar[None] = ...
    cleared_at: ClassVar[None] = ...
    last_triggered_at: ClassVar[None] = ...
    __dataclass_params__: ClassVar[dataclasses._DataclassParams] = ...
    __dataclass_fields__: ClassVar[dict] = ...
    __match_args__: ClassVar[tuple] = ...
    def update(self, is_triggered: bool) -> AlarmEvent | None: ...
    def force_clear(self) -> AlarmEvent | None: ...
    def __replace__(self, **changes): ...
    def __init__(self, definition: AlarmDefinition, is_active: bool = ..., activate_count: int = ..., clear_count: int = ..., activated_at: datetime | None = ..., cleared_at: datetime | None = ..., last_triggered_at: datetime | None = ...) -> None: ...
    def __eq__(self, other) -> bool: ...
    @property
    def duration(self): ...

class AlarmStateManager:
    def __init__(self) -> None: ...
    def register_alarm(self, alarm: AlarmDefinition) -> AlarmState: ...
    def register_alarms(self, alarms: list[AlarmDefinition]) -> list[AlarmState]: ...
    def update(self, evaluations: dict[str, bool]) -> list[AlarmEvent]: ...
    def clear_alarm(self, code: str) -> AlarmEvent | None: ...
    def get_active_alarms(self) -> list[AlarmState]: ...
    def get_state(self, code: str) -> AlarmState | None: ...
    def has_protection_alarm(self) -> bool: ...
    def reset(self) -> None: ...
