import dataclasses
from typing import Any, ClassVar

__all__ = ['RedisCommandAdapter', 'CommandResult']

class CommandResult:
    action: ClassVar[None] = ...
    point_name: ClassVar[None] = ...
    value: ClassVar[None] = ...
    error_message: ClassVar[None] = ...
    __dataclass_params__: ClassVar[dataclasses._DataclassParams] = ...
    __dataclass_fields__: ClassVar[dict] = ...
    __match_args__: ClassVar[tuple] = ...
    def to_dict(self) -> dict[str, Any]: ...
    def __replace__(self, **changes): ...
    def __hash__(self) -> int: ...
    def __init__(self, command_id: str, device_id: str, status: str, action: str | None = ..., point_name: str | None = ..., value: Any = ..., error_message: str | None = ...) -> None: ...
    def __eq__(self, other) -> bool: ...
    def __setattr__(self, name, value): ...
    def __delattr__(self, name): ...

class RedisCommandAdapter:
    DEFAULT_COMMAND_CHANNEL: ClassVar[str] = ...
    DEFAULT_RESULT_CHANNEL: ClassVar[str] = ...
    def __init__(self, redis_client: Redis, manager: WriteCommandManager, command_channel: str | None = ..., result_channel: str | None = ...) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def _listen_loop(self) -> None: ...
    def _handle_message(self, data: str | bytes) -> None: ...
    def _execute_action(self, data: dict[str, Any]) -> CommandResult: ...
    def _execute_write(self, data: dict[str, Any]) -> CommandResult: ...
    def _publish_result(self, result: CommandResult) -> None: ...
    @property
    def is_running(self): ...
