from _typeshed import Incomplete
from typing import Iterator

OTHER_OP_TYPES = complex | int | float
OP_TYPES: Incomplete

class QuadraticRing:
    D: int
    den: int
    absD: int
    def __init__(self, D: int) -> None: ...
    def __call__(self, a: int = 0, b: int = 0) -> QuadInt: ...
    def from_obj(self, n: complex) -> QuadInt: ...
    def from_ab(self, a: int, b: int) -> QuadInt: ...

class QuadInt:
    ring: QuadraticRing
    a: int
    b: int
    def __init__(self, ring: QuadraticRing, a: int = 0, b: int = 0) -> None: ...
    @property
    def real(self) -> int: ...
    @property
    def imag(self) -> int: ...
    def assert_same_ring(self, other: QuadInt): ...
    def __add__(self, other: OP_TYPES) -> QuadInt: ...
    def __radd__(self, other: OTHER_OP_TYPES) -> QuadInt: ...
    def __sub__(self, other: OP_TYPES) -> QuadInt: ...
    def __rsub__(self, other: OTHER_OP_TYPES) -> QuadInt: ...
    def __neg__(self) -> QuadInt: ...
    def __pos__(self) -> QuadInt: ...
    def __mul__(self, other: OP_TYPES) -> QuadInt: ...
    def __rmul__(self, other: OTHER_OP_TYPES) -> QuadInt: ...
    def __divmod__(self, other: OP_TYPES) -> tuple['QuadInt', 'QuadInt']: ...
    def __truediv__(self, other: OP_TYPES) -> QuadInt: ...
    def __rtruediv__(self, other: OTHER_OP_TYPES) -> QuadInt: ...
    def __floordiv__(self, other: OP_TYPES) -> QuadInt: ...
    def __rfloordiv__(self, other: OTHER_OP_TYPES) -> QuadInt: ...
    def __mod__(self, other: QuadInt) -> QuadInt: ...
    def __pow__(self, exp: float) -> QuadInt: ...
    def conjugate(self) -> QuadInt: ...
    def __abs__(self) -> int: ...
    def __iter__(self) -> Iterator[int]: ...
    def __bool__(self) -> bool: ...

def make_quadint(D: int) -> QuadraticRing: ...

complexint: Incomplete
