"""Tyche transform functions."""

from tyche_transforms.transforms import (
    abs_scalar,
    avg,
    cdd,
    convert_m_to_mm,
    cumulative_to_increment,
    daily_average,
    daily_max,
    daily_min,
    daily_sum,
    date_first,
    date_max,
    hdd,
    convert_kelvin_to_celsius,
    index_of_max_value,
    max_value,
    min_value,
    runlen_gt,
    runlen_lt,
    subtract_v,
    sum_value,
    TRANSFORM_REGISTRY,
)

__all__ = [
    "abs_scalar",
    "avg",
    "cdd",
    "convert_m_to_mm",
    "cumulative_to_increment",
    "daily_average",
    "daily_max",
    "daily_min",
    "daily_sum",
    "date_first",
    "date_max",
    "hdd",
    "convert_kelvin_to_celsius",
    "index_of_max_value",
    "max_value",
    "min_value",
    "runlen_gt",
    "runlen_lt",
    "subtract_v",
    "sum_value",
    "TRANSFORM_REGISTRY",
]
