import sys
import random
from PySide6.QtWidgets import QMainWindow, QVBoxLayout, QApplication, QWidget
from PySide6.QtCore import Qt, QVariantAnimation
from PySide6.QtGui import QPen, QPainter, QColor
from qtmui.material.styles import useTheme
def get_color_from_label(color): ...
class NomalProgress:
    def __init__(self, key: str, color: str): ...
    def initUI(self): ...
    def startAnime(self): ...
    def updateProgress(self, value): ...
    def paintEvent(self, event): ...