from __future__ import annotations
import os
import re
import hashlib
from typing import Optional, Callable
from functools import lru_cache
from PySide6.QtWidgets import QFrame, QLabel, QVBoxLayout, QSizePolicy
from PySide6.QtCore import Qt, QUrl, Signal, QSize, QRect, QTimer, QFileInfo
from PySide6.QtGui import QPixmap, QPainter, QPainterPath
from PySide6.QtNetwork import QNetworkAccessManager, QNetworkRequest, QNetworkReply
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
from qtmui.utils.data import deep_merge
from qtmui.hooks import State, useEffect
from qtmui.material.styles import useTheme
_pixmap_cache: dict[str, QPixmap]
_network_manager: Optional[QNetworkAccessManager]
def get_network_manager(): ...
class Skeleton:
    def __init__(self, parent): ...
class Image:
    def __init__(self, src: str, alt: str, ratio: Any, objectFit: str, loading: str, sx: Any, **kwargs): ...
    def _get_sx(self): ...
    def _setSxDict(cls, sx): ...
    def _getStyleSheet(cls, styledConfig: str): ...
    def _getSxQss(cls, sxStr: str, className: str): ...
    def _setSx(cls, sx): ...
    def _setKwargs(cls, kwargs: dict): ...
    def _setStyleSheet(self): ...
    def _parse_ratio(self, ratio: Optional[str]): ...
    def _extract_border_radius(self, sx: Any): ...
    def _apply_ratio_placeholder(self): ...
    def load(self): ...
    def _handle_reply(self): ...
    def _resolve_url(self, src: str): ...
    def _apply_pixmap(self, pixmap: QPixmap): ...
    def _rounded_pixmap(self, src_pix: QPixmap, radius: int): ...
    def _update_display(self): ...
    def resizeEvent(self, event): ...
    def __del__(self): ...
    def clear_cache(): ...