import _abc
import abc
import typing
from typing import ClassVar

__all__ = ['GridControllerProtocol', 'GridControllerBase']

class GridControllerProtocol(typing.Protocol):
    __parameters__: ClassVar[tuple] = ...
    _is_protocol: ClassVar[bool] = ...
    __abstractmethods__: ClassVar[frozenset] = ...
    _abc_impl: ClassVar[_abc._abc_data] = ...
    __protocol_attrs__: ClassVar[set] = ...
    _is_runtime_protocol: ClassVar[bool] = ...
    __non_callable_proto_members__: ClassVar[set] = ...
    def set_strategy(self, strategy: Strategy | None) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    @classmethod
    def __subclasshook__(cls, other): ...
    def __init__(self, *args, **kwargs) -> None: ...

class GridControllerBase(abc.ABC):
    __abstractmethods__: ClassVar[frozenset] = ...
    _abc_impl: ClassVar[_abc._abc_data] = ...
    def _build_context(self) -> StrategyContext: ...
    def _send_command(self, command: Command) -> None: ...
