ZABCDRECORD_TABLE: str = """CREATE TABLE ZABCDRECORD (
    Z_PK INTEGER PRIMARY KEY,
    ZUNIQUEID VARCHAR,
    ZFIRSTNAME VARCHAR,
    ZLASTNAME VARCHAR,
    ZMIDDLENAME VARCHAR,
    ZNICKNAME VARCHAR
)"""

ZABCDPHONENUMBER_TABLE: str = """CREATE TABLE ZABCDPHONENUMBER (
    Z_PK INTEGER PRIMARY KEY,
    ZOWNER INTEGER NOT NULL,
    ZFULLNUMBER VARCHAR NOT NULL,
    ZLABEL VARCHAR
)"""

ZABCDEMAILADDRESS_TABLE: str = """CREATE TABLE ZABCDEMAILADDRESS (
    Z_PK INTEGER PRIMARY KEY,
    ZOWNER INTEGER NOT NULL,
    ZADDRESS VARCHAR NOT NULL,
    ZLABEL VARCHAR
)"""


def get_tables() -> dict[str, str]:
    return {
        "ZABCDRECORD": ZABCDRECORD_TABLE,
        "ZABCDPHONENUMBER": ZABCDPHONENUMBER_TABLE,
        "ZABCDEMAILADDRESS": ZABCDEMAILADDRESS_TABLE,
    }


def get_indexes() -> list[str]:
    return [
        "CREATE INDEX ZABCDPHONENUMBER_ZOWNER_INDEX ON ZABCDPHONENUMBER(ZOWNER)",
        "CREATE INDEX ZABCDEMAILADDRESS_ZOWNER_INDEX ON ZABCDEMAILADDRESS(ZOWNER)",
    ]
