from csp_lib.equipment.transport.writer import WriteResult
from csp_lib.manager.command.repository import CommandRepository
from csp_lib.manager.command.schema import CommandSource, WriteCommand
from typing import Any

__all__ = ['WriteCommandManager']

class WriteCommandManager:
    def __init__(self, repository: CommandRepository) -> None: ...
    def register_device(self, device: AsyncModbusDevice) -> None: ...
    def unregister_device(self, device_id: str) -> None: ...
    def get_device(self, device_id: str) -> AsyncModbusDevice | None: ...
    def execute(self, command: WriteCommand) -> WriteResult: ...
    def execute_from_dict(self, data: dict[str, Any], source: CommandSource = ...) -> WriteResult: ...
    @property
    def registered_device_ids(self): ...
