import asyncio
from functools import lru_cache
import threading
from typing import Callable, Optional, Union, Dict, List, Any
from PySide6.QtWidgets import QFrame, QSpacerItem, QSizePolicy, QWidget, QGraphicsDropShadowEffect, QBoxLayout, QApplication
from PySide6.QtCore import Qt, QTimer, Signal, QRunnable, QThreadPool
from PySide6.QtGui import QColor, QPainter
import uuid
import re
from qtmui.hooks import State
from qtmui.material.styles import useTheme
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
from qtmui.material.widget_base import PyWidgetBase
from qtmui.utils.data import deep_merge
from qtmui.configs import LOAD_WIDGET_ASYNC
from ..layouts.flow_layout import FlowLayout
from qtmui.material.utils.sx_helper import padding_to_qmargins_args, get_sx_dict, get_padding_tuple
from qtmui.material.utils.style_decorator import StyleDecorator
from ..utils.validate_params import _validate_param
class Stack:
    def __init__(self, parent: Optional[QWidget], direction: Optional[Union[State, str, dict]], spacing: Optional[Union[State, int, float, dict]], divider: Optional[Union[State, Callable, QWidget, bool]], hightLight: Optional[Union[State, bool]], key: Optional[Union[State, str]], alignItems: Optional[Union[State, str]], justifyContent: Optional[Union[State, str]], flexWrap: Optional[Union[State, str]], flexGrow: Optional[Union[State, int]], children: Optional[Union[State, List[QWidget]]], variant: Optional[Union[State, str]], sx: Optional[Union[State, Callable, str, Dict]], asynRenderQss: Optional[Union[State, bool]], **kwargs): ...
    def _set_direction(self, value): ...
    def _get_direction(self): ...
    def _set_spacing(self, value): ...
    def _get_spacing(self): ...
    def _get_list_padding(self): ...
    def _set_divider(self, value): ...
    def _get_divider(self): ...
    def _set_hightLight(self, value): ...
    def _get_hightLight(self): ...
    def _set_key(self, value): ...
    def _get_key(self): ...
    def _set_alignItems(self, value): ...
    def _get_alignItems(self): ...
    def _set_justifyContent(self, value): ...
    def _get_justifyContent(self): ...
    def _set_flexWrap(self, value): ...
    def _get_flexWrap(self): ...
    def _set_flexGrow(self, value): ...
    def _get_flexGrow(self): ...
    def _set_children(self, value): ...
    def _get_children(self): ...
    def _set_variant(self, value): ...
    def _get_variant(self): ...
    def _set_sx(self, value): ...
    def _init_ui(self): ...
    def _onDestroy(self, obj): ...
    def _onThemeChanged(self): ...
    def _scheduleSetStyleSheet(self): ...
    def _getStyleSheet(cls, objectName: str, styledConfig: str): ...
    def _renderStylesheet(self): ...
    def _setSx(cls, sx): ...
    def _setKwargs(cls, kwargs: dict): ...
    def _getSxQss(cls, sxStr: str, className: str): ...
    def _updateStylesheet(self, stylesheet): ...
    def _setStyleSheet(self): ...
    def _connect_signals(self): ...
    def _update_layout(self): ...
    def _update_spacing(self): ...
    def _update_highlight(self): ...
    def _update_flex_wrap(self): ...
    def _update_children(self): ...
    def _update_variant(self): ...
    def _change_direction(self): ...
    def _setup_layout(self): ...
    def _clear_layout(self): ...
    def _clear_widgets(self): ...
    def _on_destroyed(self): ...
    def _add_widget(self, index, widget: QWidget): ...
    def _add_widget_with_alignment_and_flex_shrink(self, layout: QBoxLayout, widget: QWidget): ...
    def _get_align_self(self, widget: QWidget): ...
    def _get_flex_grow(self, widget: QWidget): ...
    def _get_flex_shrink(self, widget: QWidget): ...
    def _get_flex_basis(self, widget: QWidget): ...
    def _get_direction_enum(self, direction): ...
    def _change_direction(self): ...
    def _create_divider(self): ...
    def _parse_alignment(self, alignItems): ...
    def _resolve_breakpoint_value(self, config_dict, current_bp): ...
    def _get_breakpoint(self): ...
    def _schedule_repaint(self): ...
    def showEvent(self, event): ...
    def resizeEvent(self, event): ...
    def paintEvent(self, arg__1): ...