import _abc
import csp_lib.modbus.enums
import dataclasses
import typing
from csp_lib.modbus.enums import ByteOrder, FunctionCode, RegisterOrder
from csp_lib.modbus.types.base import ModbusDataType
from typing import Any, ClassVar

__all__ = ['ValueValidator', 'PointDefinition', 'PointMetadata', 'ReadPoint', 'WritePoint', 'RangeValidator', 'EnumValidator', 'CompositeValidator']

class ValueValidator(typing.Protocol):
    __parameters__: ClassVar[tuple] = ...
    _is_protocol: ClassVar[bool] = ...
    __abstractmethods__: ClassVar[frozenset] = ...
    _abc_impl: ClassVar[_abc._abc_data] = ...
    __protocol_attrs__: ClassVar[set] = ...
    def validate(self, value: Any) -> bool: ...
    def get_error_message(self, value: Any) -> str: ...
    @classmethod
    def __subclasshook__(cls, other): ...
    def __init__(self, *args, **kwargs) -> None: ...

class PointDefinition:
    function_code: ClassVar[None] = ...
    byte_order: ClassVar[csp_lib.modbus.enums.ByteOrder] = ...
    register_order: ClassVar[csp_lib.modbus.enums.RegisterOrder] = ...
    __dataclass_params__: ClassVar[dataclasses._DataclassParams] = ...
    __dataclass_fields__: ClassVar[dict] = ...
    __match_args__: ClassVar[tuple] = ...
    def __replace__(self, **changes): ...
    def __hash__(self) -> int: ...
    def __init__(self, name: str, address: int, data_type: ModbusDataType, function_code: FunctionCode | None = ..., byte_order: ByteOrder = ..., register_order: RegisterOrder = ...) -> None: ...
    def __eq__(self, other) -> bool: ...
    def __setattr__(self, name, value): ...
    def __delattr__(self, name): ...

class PointMetadata:
    unit: ClassVar[None] = ...
    description: ClassVar[None] = ...
    __dataclass_params__: ClassVar[dataclasses._DataclassParams] = ...
    __dataclass_fields__: ClassVar[dict] = ...
    __match_args__: ClassVar[tuple] = ...
    def __replace__(self, **changes): ...
    def __hash__(self) -> int: ...
    def __init__(self, unit: str | None = ..., description: str | None = ...) -> None: ...
    def __eq__(self, other) -> bool: ...
    def __setattr__(self, name, value): ...
    def __delattr__(self, name): ...

class ReadPoint(PointDefinition):
    pipeline: ClassVar[None] = ...
    read_group: ClassVar[str] = ...
    metadata: ClassVar[None] = ...
    __dataclass_params__: ClassVar[dataclasses._DataclassParams] = ...
    __dataclass_fields__: ClassVar[dict] = ...
    __match_args__: ClassVar[tuple] = ...
    def __post_init__(self) -> None: ...
    def __replace__(self, **changes): ...
    def __hash__(self) -> int: ...
    def __init__(self, name: str, address: int, data_type: ModbusDataType, function_code: FunctionCode | None = ..., byte_order: ByteOrder = ..., register_order: RegisterOrder = ..., pipeline: ProcessingPipeline | None = ..., read_group: str = ..., metadata: PointMetadata | None = ...) -> None: ...
    def __eq__(self, other) -> bool: ...
    def __setattr__(self, name, value): ...
    def __delattr__(self, name): ...

class WritePoint(PointDefinition):
    validator: ClassVar[None] = ...
    __dataclass_params__: ClassVar[dataclasses._DataclassParams] = ...
    __dataclass_fields__: ClassVar[dict] = ...
    __match_args__: ClassVar[tuple] = ...
    def __post_init__(self) -> None: ...
    def __replace__(self, **changes): ...
    def __hash__(self) -> int: ...
    def __init__(self, name: str, address: int, data_type: ModbusDataType, function_code: FunctionCode | None = ..., byte_order: ByteOrder = ..., register_order: RegisterOrder = ..., validator: ValueValidator | None = ...) -> None: ...
    def __eq__(self, other) -> bool: ...
    def __setattr__(self, name, value): ...
    def __delattr__(self, name): ...

class RangeValidator:
    min_value: ClassVar[None] = ...
    max_value: ClassVar[None] = ...
    __dataclass_params__: ClassVar[dataclasses._DataclassParams] = ...
    __dataclass_fields__: ClassVar[dict] = ...
    __match_args__: ClassVar[tuple] = ...
    def validate(self, value: Any) -> bool: ...
    def get_error_message(self, value: Any) -> str: ...
    def __replace__(self, **changes): ...
    def __hash__(self) -> int: ...
    def __init__(self, min_value: float | None = ..., max_value: float | None = ...) -> None: ...
    def __eq__(self, other) -> bool: ...
    def __setattr__(self, name, value): ...
    def __delattr__(self, name): ...

class EnumValidator:
    __dataclass_params__: ClassVar[dataclasses._DataclassParams] = ...
    __dataclass_fields__: ClassVar[dict] = ...
    __match_args__: ClassVar[tuple] = ...
    def validate(self, value: Any) -> bool: ...
    def get_error_message(self, value: Any) -> str: ...
    def __replace__(self, **changes): ...
    def __hash__(self) -> int: ...
    def __init__(self, allowed_values: tuple[Any, ...]) -> None: ...
    def __eq__(self, other) -> bool: ...
    def __setattr__(self, name, value): ...
    def __delattr__(self, name): ...

class CompositeValidator:
    __dataclass_params__: ClassVar[dataclasses._DataclassParams] = ...
    __dataclass_fields__: ClassVar[dict] = ...
    __match_args__: ClassVar[tuple] = ...
    def validate(self, value: Any) -> bool: ...
    def get_error_message(self, value: Any) -> str: ...
    def __replace__(self, **changes): ...
    def __hash__(self) -> int: ...
    def __init__(self, validators: tuple[ValueValidator, ...]) -> None: ...
    def __eq__(self, other) -> bool: ...
    def __setattr__(self, name, value): ...
    def __delattr__(self, name): ...
