from typing import Any

from socketio._types import ErrorArgs

class SocketIOError(Exception): ...
class ConnectionError(SocketIOError): ...

class ConnectionRefusedError(ConnectionError):
    error_args: ErrorArgs
    def __init__(self, *args: Any) -> None: ...

class TimeoutError(SocketIOError): ...
class BadNamespaceError(SocketIOError): ...
class DisconnectedError(SocketIOError): ...
