"""CLI模板模块

包含所有用于项目初始化和代码生成的模板。

模板组织结构:
- project/: 项目初始化模板（pyproject.toml, .env, settings.py等）
- generators/: 代码生成模板（test, builder, repository, api_client等）
"""

# 导出所有项目模板
# 导出所有代码生成模板
from .generators import (
    ENV_BASE_TEMPLATE,
    ENV_DEV_TEMPLATE,
    ENV_EXAMPLE_TEMPLATE,
    ENV_PROD_TEMPLATE,
    ENV_TEST_TEMPLATE,
    GEN_API_CLIENT_TEMPLATE,
    GEN_BUILDER_TEMPLATE,
    GEN_GRAPHQL_CLIENT_TEMPLATE,
    GEN_REDIS_FIXTURE_TEMPLATE,
    GEN_REPOSITORY_TEMPLATE,
    GEN_TEST_COMPLETE_TEMPLATE,
    GEN_TEST_GRAPHQL_TEMPLATE,
    GEN_TEST_REDIS_TEMPLATE,
    GEN_TEST_TEMPLATE,
    SETTINGS_ENHANCED_TEMPLATE,
)

# 导出增强功能模板（从project中导入）
from .project import (
    BASE_API_TEMPLATE,
    CONFTEST_TEMPLATE,
    CONSTANTS_ERROR_CODES_TEMPLATE,
    DATA_CLEANERS_TEMPLATE,
    DOCS_API_TEMPLATE,
    EDITORCONFIG_TEMPLATE,
    ENHANCED_GITIGNORE_TEMPLATE,
    EXAMPLE_API_TEMPLATE,
    FIXTURES_INIT_TEMPLATE,
    FULL_CONFTEST_TEMPLATE,  # v3.45.0
    FULL_SETTINGS_TEMPLATE,  # v3.45.0
    GITATTRIBUTES_TEMPLATE,
    GITIGNORE_TEMPLATE,
    MODELS_REQUESTS_EXAMPLE_TEMPLATE,
    MODELS_RESPONSES_EXAMPLE_TEMPLATE,
    PYPROJECT_TOML_TEMPLATE,
    README_API_TEMPLATE,
    README_FULL_TEMPLATE,
    README_UI_TEMPLATE,
    SCRIPT_FETCH_SWAGGER_TEMPLATE,
    SCRIPT_RUN_TESTS_TEMPLATE,
    # API项目模板
    SETTINGS_TEMPLATE,
    TEST_EXAMPLE_TEMPLATE,
    UI_APP_ACTIONS_TEMPLATE,  # v3.45.0
    # UI项目模板
    UI_CONFTEST_TEMPLATE,
    UI_FIXTURES_INIT_TEMPLATE,
    UI_PAGE_OBJECT_TEMPLATE,
    # UI项目模板
    UI_SETTINGS_TEMPLATE,
    UI_TEST_EXAMPLE_TEMPLATE,
    UTILS_CONVERTERS_TEMPLATE,
    UTILS_VALIDATORS_TEMPLATE,
    VSCODE_EXTENSIONS_TEMPLATE,
    VSCODE_SETTINGS_TEMPLATE,
)

__all__ = [
    # 基础配置文件
    "GITIGNORE_TEMPLATE",
    "GITATTRIBUTES_TEMPLATE",
    "EDITORCONFIG_TEMPLATE",
    "README_API_TEMPLATE",
    "README_UI_TEMPLATE",
    "README_FULL_TEMPLATE",
    "PYPROJECT_TOML_TEMPLATE",
    "VSCODE_SETTINGS_TEMPLATE",
    "VSCODE_EXTENSIONS_TEMPLATE",
    # API项目模板
    "SETTINGS_TEMPLATE",
    "CONFTEST_TEMPLATE",
    "FIXTURES_INIT_TEMPLATE",
    "BASE_API_TEMPLATE",
    "DATA_CLEANERS_TEMPLATE",
    "TEST_EXAMPLE_TEMPLATE",
    "MODELS_REQUESTS_EXAMPLE_TEMPLATE",
    "MODELS_RESPONSES_EXAMPLE_TEMPLATE",
    "EXAMPLE_API_TEMPLATE",
    # UI项目模板
    "UI_SETTINGS_TEMPLATE",
    "UI_CONFTEST_TEMPLATE",
    "UI_PAGE_OBJECT_TEMPLATE",
    "UI_TEST_EXAMPLE_TEMPLATE",
    "UI_FIXTURES_INIT_TEMPLATE",
    "UI_APP_ACTIONS_TEMPLATE",  # v3.45.0
    "FULL_CONFTEST_TEMPLATE",  # v3.45.0
    "FULL_SETTINGS_TEMPLATE",  # v3.45.0
    # 增强功能模板
    "UTILS_VALIDATORS_TEMPLATE",
    "UTILS_CONVERTERS_TEMPLATE",
    "CONSTANTS_ERROR_CODES_TEMPLATE",
    "ENHANCED_GITIGNORE_TEMPLATE",
    "SCRIPT_RUN_TESTS_TEMPLATE",
    "SCRIPT_FETCH_SWAGGER_TEMPLATE",
    "DOCS_API_TEMPLATE",
    # 代码生成模板
    "GEN_TEST_TEMPLATE",
    "GEN_TEST_COMPLETE_TEMPLATE",
    "GEN_BUILDER_TEMPLATE",
    "GEN_REPOSITORY_TEMPLATE",
    "GEN_API_CLIENT_TEMPLATE",
    "SETTINGS_ENHANCED_TEMPLATE",
    "ENV_BASE_TEMPLATE",
    "ENV_DEV_TEMPLATE",
    "ENV_TEST_TEMPLATE",
    "ENV_PROD_TEMPLATE",
    "ENV_EXAMPLE_TEMPLATE",
    # v3.35.5+ GraphQL 和 Redis 模板
    "GEN_GRAPHQL_CLIENT_TEMPLATE",
    "GEN_TEST_GRAPHQL_TEMPLATE",
    "GEN_REDIS_FIXTURE_TEMPLATE",
    "GEN_TEST_REDIS_TEMPLATE",
]
