from mars_patcher.constants.enemies import EnemyType
from mars_patcher.mf.constants.sprites import SpriteIdMF

ENEMY_TYPES_MF = {
    SpriteIdMF.HORNOAD: EnemyType.GROUND,
    SpriteIdMF.HALZYN: EnemyType.FLYING,
    SpriteIdMF.ZEBESIAN_WALL: EnemyType.WALL,
    SpriteIdMF.HORNOAD_SPAWNER: EnemyType.GROUND,
    SpriteIdMF.MOTO: EnemyType.GROUND,
    SpriteIdMF.YAMEBA: EnemyType.FLYING,
    SpriteIdMF.ZEELA: EnemyType.CRAWLING,
    SpriteIdMF.SKREE_UNUSED: EnemyType.CEILING,
    SpriteIdMF.ZOMBIE: EnemyType.GROUND,
    SpriteIdMF.GEEMER: EnemyType.CRAWLING,
    SpriteIdMF.WAVER: EnemyType.FLYING,
    SpriteIdMF.SCISER: EnemyType.CRAWLING,
    SpriteIdMF.SIDEHOPPER: EnemyType.GROUND_CEILING,
    SpriteIdMF.DESSGEEGA: EnemyType.GROUND_CEILING,
    SpriteIdMF.ZORO: EnemyType.CRAWLING,
    SpriteIdMF.KIHUNTER_FLYING: EnemyType.FLYING,
    SpriteIdMF.KIHUNTER_GROUND: EnemyType.GROUND,
    SpriteIdMF.REO: EnemyType.FLYING,
    SpriteIdMF.NAMIHE: EnemyType.WALL,
    SpriteIdMF.FUNE: EnemyType.WALL,
    SpriteIdMF.BLUE_ZORO: EnemyType.CRAWLING,
    SpriteIdMF.GERUDA: EnemyType.FLYING,
    SpriteIdMF.SKULTERA_LARGE: EnemyType.FLYING,
    SpriteIdMF.SKULTERA_SMALL_ONLY: EnemyType.FLYING,
    SpriteIdMF.SOVA: EnemyType.CRAWLING,
    SpriteIdMF.YARD: EnemyType.CRAWLING,
    SpriteIdMF.EVIR: EnemyType.FLYING,
    SpriteIdMF.BULL: EnemyType.FLYING,
    SpriteIdMF.MEMU: EnemyType.FLYING,
    SpriteIdMF.GERUBOSS: EnemyType.CEILING,
    SpriteIdMF.CHOOT: EnemyType.GROUND,
    SpriteIdMF.ZEBESIAN_GROUND: EnemyType.GROUND,
    SpriteIdMF.RIPPER: EnemyType.FLYING,
    SpriteIdMF.RED_ZEELA: EnemyType.CRAWLING,
    SpriteIdMF.OWTCH: EnemyType.CRAWLING,
    SpriteIdMF.GENESIS: EnemyType.GROUND,
    SpriteIdMF.PUYO: EnemyType.GROUND,
    SpriteIdMF.FAKE_ENERGY_TANK: EnemyType.GROUND,
    SpriteIdMF.FAKE_MISSILE_TANK: EnemyType.GROUND,
    SpriteIdMF.ZEBESIAN_AQUA: EnemyType.FLYING,
    SpriteIdMF.ZEBESIAN_PRE_AQUA: EnemyType.GROUND,
    SpriteIdMF.SKULTERA_SMALL: EnemyType.FLYING,
    SpriteIdMF.POWAMP: EnemyType.FLYING,
    SpriteIdMF.ZOZORO: EnemyType.CRAWLING,
}
