# coding: utf-8

"""
    Cloudbeds API v2

    <p>Welcome to the documentation for <strong>Cloudbeds API Version v2</strong>! If you are looking to learn how to use the Cloudbeds API to access guest information, reservations, or similar data for your Cloudbeds customers, then you've come to the right place.</p><p>In this document you will find all the API methods we provide along with explanations for parameters and response examples.</p><p>If you have questions about different implementation steps (e.g. how to implement OAuth 2.0), please refer to our <a href='https://integrations.cloudbeds.com/hc/en-us'>Integrations Portal</a>.</p><p>Be sure to <a href='https://go.pardot.com/l/308041/2018-07-24/qb2lg'>subscribe</a> to the monthly Cloudbeds API announcement mailing list to receive information on new additions and improvements to the Cloudbeds API and related developer tools.</p><p><strong>Endpoint:</strong> https://api.cloudbeds.com/{method}</p><p><strong>HTTPS:</strong> Our API requires HTTPS. We'll respond with an appropriate error if you're not using it.</p><p><strong>Request Format:</strong> HTTP GET, POST and PUT (Content-Type: application/x-www-form-urlencoded)</p><p><strong>Response Format:</strong> JSON</p><p><strong>Response Header:</strong> X-Request-ID is added to response headers in all calls to help accelerate support and troubleshooting.</p><p><strong><a href='https://integrations.cloudbeds.com/hc/en-us/articles/14104678058267-API-Documentation#postman-collection'><img src='https://run.pstmn.io/button.svg' alt='Run in Postman'></a></strong> use this link to access our Public collection in Postman.</p>

    The version of the OpenAPI document: v2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from cloudbeds_pms.models.money_schema import MoneySchema
from cloudbeds_pms.models.reservation_commission_response_schema_estimated_commission_from_source import ReservationCommissionResponseSchemaEstimatedCommissionFromSource
from typing import Optional, Set
from typing_extensions import Self

class ReservationCommissionResponseSchema(BaseModel):
    """
    ReservationCommissionResponseSchema
    """ # noqa: E501
    id: StrictStr
    property_id: StrictStr = Field(alias="propertyId")
    reservation_id: StrictStr = Field(alias="reservationId")
    effective_commission: MoneySchema = Field(alias="effectiveCommission")
    effective_commission_type: StrictStr = Field(alias="effectiveCommissionType")
    estimated_commission_from_source: Optional[ReservationCommissionResponseSchemaEstimatedCommissionFromSource] = Field(default=None, alias="estimatedCommissionFromSource")
    estimated_commissionable_revenue: Optional[ReservationCommissionResponseSchemaEstimatedCommissionFromSource] = Field(default=None, alias="estimatedCommissionableRevenue")
    channel_commission: Optional[ReservationCommissionResponseSchemaEstimatedCommissionFromSource] = Field(default=None, alias="channelCommission")
    channel_commission_type: Optional[StrictStr] = Field(default=None, alias="channelCommissionType")
    source_commission_percentage: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="sourceCommissionPercentage")
    created_at: StrictStr = Field(alias="createdAt")
    updated_at: Optional[StrictStr] = Field(alias="updatedAt")
    __properties: ClassVar[List[str]] = ["id", "propertyId", "reservationId", "effectiveCommission", "effectiveCommissionType", "estimatedCommissionFromSource", "estimatedCommissionableRevenue", "channelCommission", "channelCommissionType", "sourceCommissionPercentage", "createdAt", "updatedAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReservationCommissionResponseSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of effective_commission
        if self.effective_commission:
            _dict['effectiveCommission'] = self.effective_commission.to_dict()
        # override the default output from pydantic by calling `to_dict()` of estimated_commission_from_source
        if self.estimated_commission_from_source:
            _dict['estimatedCommissionFromSource'] = self.estimated_commission_from_source.to_dict()
        # override the default output from pydantic by calling `to_dict()` of estimated_commissionable_revenue
        if self.estimated_commissionable_revenue:
            _dict['estimatedCommissionableRevenue'] = self.estimated_commissionable_revenue.to_dict()
        # override the default output from pydantic by calling `to_dict()` of channel_commission
        if self.channel_commission:
            _dict['channelCommission'] = self.channel_commission.to_dict()
        # set to None if estimated_commission_from_source (nullable) is None
        # and model_fields_set contains the field
        if self.estimated_commission_from_source is None and "estimated_commission_from_source" in self.model_fields_set:
            _dict['estimatedCommissionFromSource'] = None

        # set to None if estimated_commissionable_revenue (nullable) is None
        # and model_fields_set contains the field
        if self.estimated_commissionable_revenue is None and "estimated_commissionable_revenue" in self.model_fields_set:
            _dict['estimatedCommissionableRevenue'] = None

        # set to None if channel_commission (nullable) is None
        # and model_fields_set contains the field
        if self.channel_commission is None and "channel_commission" in self.model_fields_set:
            _dict['channelCommission'] = None

        # set to None if channel_commission_type (nullable) is None
        # and model_fields_set contains the field
        if self.channel_commission_type is None and "channel_commission_type" in self.model_fields_set:
            _dict['channelCommissionType'] = None

        # set to None if source_commission_percentage (nullable) is None
        # and model_fields_set contains the field
        if self.source_commission_percentage is None and "source_commission_percentage" in self.model_fields_set:
            _dict['sourceCommissionPercentage'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updatedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReservationCommissionResponseSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "propertyId": obj.get("propertyId"),
            "reservationId": obj.get("reservationId"),
            "effectiveCommission": MoneySchema.from_dict(obj["effectiveCommission"]) if obj.get("effectiveCommission") is not None else None,
            "effectiveCommissionType": obj.get("effectiveCommissionType"),
            "estimatedCommissionFromSource": ReservationCommissionResponseSchemaEstimatedCommissionFromSource.from_dict(obj["estimatedCommissionFromSource"]) if obj.get("estimatedCommissionFromSource") is not None else None,
            "estimatedCommissionableRevenue": ReservationCommissionResponseSchemaEstimatedCommissionFromSource.from_dict(obj["estimatedCommissionableRevenue"]) if obj.get("estimatedCommissionableRevenue") is not None else None,
            "channelCommission": ReservationCommissionResponseSchemaEstimatedCommissionFromSource.from_dict(obj["channelCommission"]) if obj.get("channelCommission") is not None else None,
            "channelCommissionType": obj.get("channelCommissionType"),
            "sourceCommissionPercentage": obj.get("sourceCommissionPercentage"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


