from typing import Dict, List
from itertools import groupby
from PySide6.QtCore import Qt, QObject, Signal
from PySide6.QtWidgets import QWidget, QStackedWidget
class RouteItem:
    def __init__(self, stacked: QStackedWidget, routeKey: str): ...
    def __eq__(self, other): ...
class StackedHistory:
    def __init__(self, stacked: QStackedWidget): ...
    def __len__(self): ...
    def isEmpty(self): ...
    def push(self, routeKey: str): ...
    def pop(self): ...
    def remove(self, routeKey: str): ...
    def top(self): ...
    def setDefaultRouteKey(self, routeKey: str): ...
    def goToTop(self): ...
class Router:
    def __init__(self, parent): ...
    def setDefaultRouteKey(self, stacked: QStackedWidget, routeKey: str): ...
    def push(self, stacked: QStackedWidget, routeKey: str): ...
    def pop(self): ...
    def remove(self, routeKey: str): ...