import asyncio
from typing import Callable, Optional, Union, Dict, Any
from PySide6.QtGui import QPainter, QPen, QIcon
from PySide6.QtCore import Qt, QSize, Signal, QTimer, QEvent
from PySide6.QtWidgets import QAbstractButton
from ..system.color_manipulator import hex_string_to_qcolor
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
from ..button.button import Button
from ..py_iconify import Iconify
from qtmui.hooks import State
from qtmui.material.styles import useTheme
from qtmui.i18n.use_translation import translate, i18n
from ..utils.functions import _get_fn_args
from ...qtmui_assets import QTMUI_ASSETS
from ..utils.validate_params import _validate_param
class Checkbox:
    def __init__(self, checked: Optional[Union[State, bool]], checkedIcon: Optional[Union[State, str, Iconify]], classes: Optional[Union[State, Dict]], color: Union[State, str], defaultChecked: Optional[Union[State, bool]], disabled: Union[State, bool], disableGutters: Union[State, bool], disableRipple: Union[State, bool], icon: Optional[Union[State, str, Iconify]], id: Optional[Union[State, str]], indeterminate: Union[State, bool], indeterminateIcon: Optional[Union[State, str, Iconify]], inputProps: Optional[Union[State, Dict]], onChange: Optional[Union[State, Callable]], required: Union[State, bool], size: Union[State, str], slotProps: Optional[Union[State, Dict]], slots: Optional[Union[State, Dict]], state: Optional[Union[State, bool]], sx: Optional[Union[State, Dict, Callable, str]], value: Optional[Union[State, Any]], *args, **kwargs): ...
    def _getChecked(self): ...
    def _set_checkedIcon(self, value): ...
    def _get_checkedIcon(self): ...
    def _set_classes(self, value): ...
    def _get_classes(self): ...
    def _set_color(self, value): ...
    def _get_color(self): ...
    def _set_defaultChecked(self, value): ...
    def _get_defaultChecked(self): ...
    def _set_disabled(self, value): ...
    def _get_disabled(self): ...
    def _set_disableGutters(self, value): ...
    def _get_disableGutters(self): ...
    def _set_disableRipple(self, value): ...
    def _get_disableRipple(self): ...
    def _set_icon(self, value): ...
    def _get_icon(self): ...
    def _set_id(self, value): ...
    def _get_id(self): ...
    def _set_indeterminate(self, value): ...
    def _get_indeterminate(self): ...
    def _set_indeterminateIcon(self, value): ...
    def _get_indeterminateIcon(self): ...
    def _set_inputProps(self, value): ...
    def _get_inputProps(self): ...
    def _set_onChange(self, value): ...
    def _get_onChange(self): ...
    def _set_required(self, value): ...
    def _get_required(self): ...
    def _set_size(self, value): ...
    def _get_size(self): ...
    def _set_slotProps(self, value): ...
    def _get_slotProps(self): ...
    def _set_slots(self, value): ...
    def _get_slots(self): ...
    def _set_state(self, value): ...
    def _get_state(self): ...
    def _set_sx(self, value): ...
    def _get_sx(self): ...
    def _set_value(self, value): ...
    def _get_value(self): ...
    def _connectCheckboxStates(self): ...
    def _onCheckedStateChanged(self, state): ...
    def _init_ui(self): ...
    def _setCheckboxStylesheet(self, component_styled): ...
    def onClick(self): ...