from typing import Callable, List, Optional, Union, Dict, Any
from qtmui.hooks import State
from PySide6.QtCore import Qt, QSize, Signal, QPoint, QPointF, QRectF, QEasingCurve, QPropertyAnimation, QSequentialAnimationGroup, Slot, Property
from PySide6.QtWidgets import QCheckBox, QWidget
from PySide6.QtGui import QColor, QBrush, QPaintEvent, QPen, QPainter
from qtmui.material.styles import useTheme
from ..widget_base import PyWidgetBase
from ..utils.validate_params import _validate_param
class Switch:
    def __init__(self, parent, label: Optional[Union[str, State, Callable]], disabled: Union[State, bool], defaultChecked: Union[State, bool], checked: Union[State, bool], onChange: Optional[Union[State, Callable, Any]], highlight: Union[State, bool], left: Union[State, bool], color: Optional[Union[State, str, Any]], size: Optional[Union[State, str, Any]], onClick: Optional[Union[State, Callable, Any]], checkedIcon: Optional[Union[State, QWidget, Any]], icon: Optional[Union[State, QWidget, Any]], classes: Optional[Union[State, Dict, Any]], sx: Optional[Union[State, List, Dict, Callable, Any]], disableRipple: Union[State, bool], edge: Optional[Union[State, str, bool, Any]], id: Optional[Union[State, str, Any]], inputProps: Optional[Union[State, Dict, Any]], inputRef: Optional[Union[State, Any, Any]], required: Union[State, bool], slotProps: Optional[Union[State, Dict, Any]], slots: Optional[Union[State, Dict, Any]], value: Optional[Union[State, Any, Any]], **kwargs): ...
    def _init_ui(self): ...
    def _set_stylesheet(self): ...
    def sizeHint(self): ...
    def hitButton(self, pos: QPoint): ...
    def setup_animation(self, value): ...
    def paintEvent(self, e: QPaintEvent): ...
    def handle_position(self): ...
    def handle_position(self, pos): ...
    def pulse_radius(self): ...
    def pulse_radius(self, pos): ...