import dataclasses
from datetime import datetime
from typing import Any, AsyncHandler as AsyncHandler, Callable, ClassVar

__all__ = ['AsyncHandler', 'ValueChangePayload', 'ReadCompletePayload', 'DeviceEventEmitter', 'ConnectedPayload', 'DisconnectPayload', 'ReadErrorPayload', 'WriteCompletePayload', 'WriteErrorPayload', 'DeviceAlarmPayload', 'EVENT_CONNECTED', 'EVENT_DISCONNECTED', 'EVENT_READ_COMPLETE', 'EVENT_READ_ERROR', 'EVENT_VALUE_CHANGE', 'EVENT_ALARM_TRIGGERED', 'EVENT_ALARM_CLEARED', 'EVENT_WRITE_COMPLETE', 'EVENT_WRITE_ERROR']

EVENT_CONNECTED: str
EVENT_DISCONNECTED: str
EVENT_READ_COMPLETE: str
EVENT_READ_ERROR: str
EVENT_VALUE_CHANGE: str
EVENT_ALARM_TRIGGERED: str
EVENT_ALARM_CLEARED: str
EVENT_WRITE_COMPLETE: str
EVENT_WRITE_ERROR: str

class ValueChangePayload:
    __dataclass_params__: ClassVar[dataclasses._DataclassParams] = ...
    __dataclass_fields__: ClassVar[dict] = ...
    __match_args__: ClassVar[tuple] = ...
    def __replace__(self, **changes): ...
    def __hash__(self) -> int: ...
    def __init__(self, device_id: str, point_name: str, old_value: Any, new_value: Any, timestamp: datetime = ...) -> None: ...
    def __eq__(self, other) -> bool: ...
    def __setattr__(self, name, value): ...
    def __delattr__(self, name): ...

class ConnectedPayload:
    __dataclass_params__: ClassVar[dataclasses._DataclassParams] = ...
    __dataclass_fields__: ClassVar[dict] = ...
    __match_args__: ClassVar[tuple] = ...
    def __replace__(self, **changes): ...
    def __hash__(self) -> int: ...
    def __init__(self, device_id: str, timestamp: datetime = ...) -> None: ...
    def __eq__(self, other) -> bool: ...
    def __setattr__(self, name, value): ...
    def __delattr__(self, name): ...

class ReadErrorPayload:
    __dataclass_params__: ClassVar[dataclasses._DataclassParams] = ...
    __dataclass_fields__: ClassVar[dict] = ...
    __match_args__: ClassVar[tuple] = ...
    def __replace__(self, **changes): ...
    def __hash__(self) -> int: ...
    def __init__(self, device_id: str, error: str, consecutive_failures: int, timestamp: datetime = ...) -> None: ...
    def __eq__(self, other) -> bool: ...
    def __setattr__(self, name, value): ...
    def __delattr__(self, name): ...

class WriteCompletePayload:
    __dataclass_params__: ClassVar[dataclasses._DataclassParams] = ...
    __dataclass_fields__: ClassVar[dict] = ...
    __match_args__: ClassVar[tuple] = ...
    def __replace__(self, **changes): ...
    def __hash__(self) -> int: ...
    def __init__(self, device_id: str, point_name: str, value: Any, timestamp: datetime = ...) -> None: ...
    def __eq__(self, other) -> bool: ...
    def __setattr__(self, name, value): ...
    def __delattr__(self, name): ...

class WriteErrorPayload:
    __dataclass_params__: ClassVar[dataclasses._DataclassParams] = ...
    __dataclass_fields__: ClassVar[dict] = ...
    __match_args__: ClassVar[tuple] = ...
    def __replace__(self, **changes): ...
    def __hash__(self) -> int: ...
    def __init__(self, device_id: str, point_name: str, value: Any, error: str, timestamp: datetime = ...) -> None: ...
    def __eq__(self, other) -> bool: ...
    def __setattr__(self, name, value): ...
    def __delattr__(self, name): ...

class DisconnectPayload:
    __dataclass_params__: ClassVar[dataclasses._DataclassParams] = ...
    __dataclass_fields__: ClassVar[dict] = ...
    __match_args__: ClassVar[tuple] = ...
    def __replace__(self, **changes): ...
    def __hash__(self) -> int: ...
    def __init__(self, device_id: str, reason: str, consecutive_failures: int, timestamp: datetime = ...) -> None: ...
    def __eq__(self, other) -> bool: ...
    def __setattr__(self, name, value): ...
    def __delattr__(self, name): ...

class DeviceAlarmPayload:
    __dataclass_params__: ClassVar[dataclasses._DataclassParams] = ...
    __dataclass_fields__: ClassVar[dict] = ...
    __match_args__: ClassVar[tuple] = ...
    def __replace__(self, **changes): ...
    def __hash__(self) -> int: ...
    def __init__(self, device_id: str, alarm_event: AlarmEvent, timestamp: datetime = ...) -> None: ...
    def __eq__(self, other) -> bool: ...
    def __setattr__(self, name, value): ...
    def __delattr__(self, name): ...

class ReadCompletePayload:
    __dataclass_params__: ClassVar[dataclasses._DataclassParams] = ...
    __dataclass_fields__: ClassVar[dict] = ...
    __match_args__: ClassVar[tuple] = ...
    def __replace__(self, **changes): ...
    def __hash__(self) -> int: ...
    def __init__(self, device_id: str, values: dict[str, Any], duration_ms: float, timestamp: datetime = ...) -> None: ...
    def __eq__(self, other) -> bool: ...
    def __setattr__(self, name, value): ...
    def __delattr__(self, name): ...

class DeviceEventEmitter:
    def __init__(self, max_queue_size: int = ...) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def on(self, event: str, handler: AsyncHandler) -> Callable[[], None]: ...
    def emit(self, event: str, payload: Any = ...) -> None: ...
    def emit_await(self, event: str, payload: Any = ...) -> None: ...
    def has_listeners(self, event: str) -> bool: ...
    def clear(self, event: str | None = ...) -> None: ...
    def _worker(self) -> None: ...
    def _process_event(self, event: str, payload: Any) -> None: ...
    @property
    def queue_size(self): ...

# Names in __all__ with no definition:
#   AsyncHandler
