import sys
from PySide6 import QtWidgets, QtCore, QtGui
from PySide6.QtCore import QFile, QFileInfo, Qt, QByteArray, QTextStream, QStringDecoder
from PySide6.QtGui import QStandardItem, QStandardItemModel
from PySide6.QtWidgets import QApplication, QHeaderView, QTableView, QAbstractItemView
class FreezeTableWidget:
    def __init__(self, model): ...
    def init(self): ...
    def updateSectionWidth(self, logicalIndex, oldSize, newSize): ...
    def updateSectionHeight(self, logicalIndex, oldSize, newSize): ...
    def resizeEvent(self, event): ...
    def moveCursor(self, cursorAction, modifiers): ...
    def scrollTo(self, index, hint): ...
    def updateFrozenTableGeometry(self): ...
def main(args): ...