import sys
import math
import re
from PySide6.QtWidgets import QApplication, QWidget, QPushButton, QVBoxLayout, QGraphicsEffect, QGraphicsScene, QGraphicsPixmapItem, QGraphicsBlurEffect
from PySide6.QtCore import Qt, QRectF, QPointF, Property, QPropertyAnimation, QEasingCurve, QTimer, QObject
from PySide6.QtGui import QPainter, QColor, QPainterPath, QConicalGradient, QPixmap, QImage
def _parse_px(token: str): ...
def _parse_color(token: str): ...
class BoxShadowSpec:
    def __init__(self, x, y, blur, spread, color, inset): ...
def parse_box_shadow(value: str): ...
class ShadowEffect:
    def __init__(self, parent, *args, **kwargs): ...
    def _initShadow(self, parent): ...
    def setBoxShadow(self, value: str): ...
    def boundingRectFor(self, rect: QRectF): ...
    def _get_dpr(self): ...
    def _make_shadow_key(self, src_rect: QRectF, dpr: float, s: BoxShadowSpec): ...
    def _rebuild_shadow_cache(self): ...
    def _draw_inset_shadow(self, painter: QPainter, src_rect: QRectF, s: BoxShadowSpec): ...