from typing import Optional, Dict, List, Callable, Union
from PySide6.QtCore import QObject, QPoint, QSize, QPropertyAnimation, QParallelAnimationGroup, QAbstractAnimation, QTimer, Qt, QEasingCurve
from PySide6.QtWidgets import QWidget, QVBoxLayout, QScrollArea
from .anim_effect import AnimEffect
from .anim_easing_curve_type import chooseEasing
class AnimationController:
    def __init__(self, widget: QWidget, variants: Dict, parent): ...
    def apply_initial(self, variants): ...
    def play(self, delay_ms: int): ...
    def onDestroy(self): ...