from typing import Callable
from PySide6.QtWidgets import QToolButton, QColorDialog, QDialogButtonBox, QGridLayout, QSpinBox
from PySide6.QtCore import Slot, Qt
from qtmui.material.styles import useTheme
from qtmui.i18n.use_translation import translate, i18n
class ColorPicker:
    def __init__(self, tooltip: str, onChange: Callable): ...
    def initUI(self): ...
    def reTranslation(self): ...
    def _set_color(self, color): ...
    def _set_theme(self): ...
    def on_click(self): ...
    def openColorDialog(self): ...