from math import cos, pi
from PySide6.QtWidgets import QGraphicsEffect
from PySide6.QtCore import Property, QPointF, QPoint, Qt, QRectF
from PySide6.QtGui import QPainter, QPixmap, QLinearGradient, QColor, QBrush, QGradient
from qtmui.material.styles import useTheme
class AnimEffect:
    def __init__(self, parent, src: str, variants: dict): ...
    def getOffsetX(self): ...
    def setOffsetX(self, val): ...
    def getOffsetY(self): ...
    def setOffsetY(self, val): ...
    def getAngle(self): ...
    def setAngle(self, val): ...
    def getRotationX(self): ...
    def setRotationX(self, val): ...
    def getRotationY(self): ...
    def setRotationY(self, val): ...
    def getScaleX(self): ...
    def setScaleX(self, val): ...
    def getScaleY(self): ...
    def setScaleY(self, val): ...
    def getOpacity(self): ...
    def setOpacity(self, val): ...
    def getScale(self): ...
    def setScale(self, v): ...
    def getBgProgress(self): ...
    def setBgProgress(self, v): ...
    def _resolve_colors(self, colors): ...
    def _generate_colors(self): ...
    def _draw_background_gradient(self, painter: QPainter, w: int, h: int): ...
    def draw(self, painter: QPainter): ...