import sys
from PySide6.QtCore import Qt, Property, QPropertyAnimation
from PySide6.QtGui import QPainter, QLinearGradient, QColor, QGradient
from PySide6.QtWidgets import QApplication, QGraphicsEffect, QMainWindow, QWidget, QVBoxLayout, QFrame
class BackgroundPanEffect:
    def __init__(self, variant, colors, duration, ease, parent): ...
    def _detect_direction(v): ...
    def getProgress(self): ...
    def setProgress(self, v): ...
    def draw(self, painter: QPainter): ...