from collections import deque
from enum import Enum
from math import cos, pi, ceil
from PySide6.QtCore import QDateTime, Qt, QTimer, QPoint
from PySide6.QtGui import QWheelEvent
from PySide6.QtWidgets import QApplication, QScrollArea, QAbstractScrollArea
class SmoothScroll:
    def __init__(self, widget, orient): ...
    def setSmoothMode(self, smoothMode): ...
    def wheelEvent(self, e): ...
    def __smoothMove(self): ...
    def __subDelta(self, delta, stepsLeft): ...
class SmoothMode: