from typing import Callable, Dict, Any, Optional, Union
class SimpleStyleFunction:
    def __init__(self, func: Callable[Any, dict]): ...
    def __call__(self, props: dict): ...
class SxConfigRecord:
    def __init__(self, css_property: Optional[str], theme_key: Optional[str], transform: Optional[TransformFunction], style: Optional[SimpleStyleFunction]): ...
def default_style_function(props: dict): ...
defaultSxConfig: SxConfig