import asyncio
from typing import Callable, Optional, Union
from PySide6.QtWidgets import QHBoxLayout
from PySide6.QtCore import Qt, QTimer
from qtmui.hooks import State
from .button import Button
from .loading_icon import LoadingIcon
from ..py_svg_widget import PySvgWidget
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
from qtmui.material.styles import useTheme
from qtmui.i18n.use_translation import translate, i18n
class LoadingButton:
    def __init__(self, type: str, loading: bool, loadingPosition: str, loadingIndicator: Optional[Union[str, State, Callable]], color: str, *args, **kwargs): ...
    def _init_ui(self): ...
    def _onDestroy(self, obj): ...
    def _onThemeChanged(self): ...
    def _scheduleSetStyleSheet(self): ...
    def __set_loading_button_svg_stylesheet(self, _theme): ...