import uuid
from typing import Optional, Union, List, Callable, Any
from PySide6.QtWidgets import QVBoxLayout, QWidget, QFrame, QSizePolicy
from PySide6.QtCore import Qt
from ..typography import Typography
from ..box import Box
from ..spacer import VSpacer
from ..list import ListItemAvatar
from ..avatar import Avatar
class StepLabel:
    def __init__(self, children: Optional[Union[str, QWidget]], classes: Optional[dict], componentsProps: Optional[dict], completed: bool, error: bool, icon: Optional[Union[str, QWidget]], index: Optional[int], optional: Optional[Union[str, QWidget]], slotProps: Optional[dict], slots: Optional[dict], StepIconComponent: Optional[Any], StepIconProps: Optional[dict], sx: Optional[Union[List[Union[Callable, dict, bool]], Callable, dict, bool]], text: Optional[str], width: Optional[int], *args, **kwargs): ...
    def _init_ui(self): ...
    def generate_stylesheet(self): ...
    def set_error(self, error: bool): ...
    def get_error(self): ...
    def set_icon(self, icon: Union[str, QWidget]): ...
    def get_icon(self): ...
    def set_optional(self, optional: Union[str, QWidget]): ...
    def get_optional(self): ...
    def set_children(self, children: Union[str, QWidget]): ...
    def get_children(self): ...
    def update_ui(self): ...