from typing import Any, Optional, List
from qtmui.material.utils.validate_params import _validate_param
class ValidatedAttr:
    def __init__(self): ...
    def __set_name__(self, owner, name): ...
    def __get__(self, instance, owner): ...
    def __set__(self, instance, value): ...