import _abc
import abc
from typing import ClassVar

__all__ = ['AsyncModbusClientBase']

class AsyncModbusClientBase(abc.ABC):
    __abstractmethods__: ClassVar[frozenset] = ...
    _abc_impl: ClassVar[_abc._abc_data] = ...
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def is_connected(self) -> bool: ...
    def read_coils(self, address: int, count: int, unit_id: int = ...) -> list[bool]: ...
    def read_discrete_inputs(self, address: int, count: int, unit_id: int = ...) -> list[bool]: ...
    def read_holding_registers(self, address: int, count: int, unit_id: int = ...) -> list[int]: ...
    def read_input_registers(self, address: int, count: int, unit_id: int = ...) -> list[int]: ...
    def write_single_coil(self, address: int, value: bool, unit_id: int = ...) -> None: ...
    def write_single_register(self, address: int, value: int, unit_id: int = ...) -> None: ...
    def write_multiple_coils(self, address: int, values: list[bool], unit_id: int = ...) -> None: ...
    def write_multiple_registers(self, address: int, values: list[int], unit_id: int = ...) -> None: ...
    def __aenter__(self) -> AsyncModbusClientBase: ...
    def __aexit__(self, exc_type, exc_val, exc_tb) -> None: ...
