import _abc
import csp_lib.modbus.types.base
from csp_lib.modbus.enums import ByteOrder, RegisterOrder
from typing import ClassVar

__all__ = ['Int16', 'UInt16', 'Int32', 'UInt32', 'Int64', 'UInt64', 'Float32', 'Float64']

class Int16(csp_lib.modbus.types.base.ModbusDataType):
    __abstractmethods__: ClassVar[frozenset] = ...
    _abc_impl: ClassVar[_abc._abc_data] = ...
    def encode(self, value: int, byte_order: ByteOrder, register_order: RegisterOrder) -> list[int]: ...
    def decode(self, registers: list[int], byte_order: ByteOrder, register_order: RegisterOrder) -> int: ...
    @property
    def register_count(self): ...

class UInt16(csp_lib.modbus.types.base.ModbusDataType):
    __abstractmethods__: ClassVar[frozenset] = ...
    _abc_impl: ClassVar[_abc._abc_data] = ...
    def encode(self, value: int, byte_order: ByteOrder, register_order: RegisterOrder) -> list[int]: ...
    def decode(self, registers: list[int], byte_order: ByteOrder, register_order: RegisterOrder) -> int: ...
    @property
    def register_count(self): ...

class Int32(csp_lib.modbus.types.base.ModbusDataType):
    __abstractmethods__: ClassVar[frozenset] = ...
    _abc_impl: ClassVar[_abc._abc_data] = ...
    def encode(self, value: int, byte_order: ByteOrder, register_order: RegisterOrder) -> list[int]: ...
    def decode(self, registers: list[int], byte_order: ByteOrder, register_order: RegisterOrder) -> int: ...
    @property
    def register_count(self): ...

class UInt32(csp_lib.modbus.types.base.ModbusDataType):
    __abstractmethods__: ClassVar[frozenset] = ...
    _abc_impl: ClassVar[_abc._abc_data] = ...
    def encode(self, value: int, byte_order: ByteOrder, register_order: RegisterOrder) -> list[int]: ...
    def decode(self, registers: list[int], byte_order: ByteOrder, register_order: RegisterOrder) -> int: ...
    @property
    def register_count(self): ...

class UInt64(csp_lib.modbus.types.base.ModbusDataType):
    __abstractmethods__: ClassVar[frozenset] = ...
    _abc_impl: ClassVar[_abc._abc_data] = ...
    def encode(self, value: int, byte_order: ByteOrder, register_order: RegisterOrder) -> list[int]: ...
    def decode(self, registers: list[int], byte_order: ByteOrder, register_order: RegisterOrder) -> int: ...
    @property
    def register_count(self): ...

class Int64(csp_lib.modbus.types.base.ModbusDataType):
    __abstractmethods__: ClassVar[frozenset] = ...
    _abc_impl: ClassVar[_abc._abc_data] = ...
    def encode(self, value: int, byte_order: ByteOrder, register_order: RegisterOrder) -> list[int]: ...
    def decode(self, registers: list[int], byte_order: ByteOrder, register_order: RegisterOrder) -> int: ...
    @property
    def register_count(self): ...

class Float32(csp_lib.modbus.types.base.ModbusDataType):
    __abstractmethods__: ClassVar[frozenset] = ...
    _abc_impl: ClassVar[_abc._abc_data] = ...
    def encode(self, value: float, byte_order: ByteOrder, register_order: RegisterOrder) -> list[int]: ...
    def decode(self, registers: list[int], byte_order: ByteOrder, register_order: RegisterOrder) -> float: ...
    @property
    def register_count(self): ...

class Float64(csp_lib.modbus.types.base.ModbusDataType):
    __abstractmethods__: ClassVar[frozenset] = ...
    _abc_impl: ClassVar[_abc._abc_data] = ...
    def encode(self, value: float, byte_order: ByteOrder, register_order: RegisterOrder) -> list[int]: ...
    def decode(self, registers: list[int], byte_order: ByteOrder, register_order: RegisterOrder) -> float: ...
    @property
    def register_count(self): ...
