from weakref import ref
import random
from PySide6.QtGui import QPen, QPainter, QColor, QPixmap, QIcon
from PySide6.QtCore import Qt, QVariantAnimation, QRectF, QEasingCurve, QSize
from PySide6.QtWidgets import QApplication, QPushButton
from qtmui.material.styles import useTheme
class Arc:
    def __init__(self): ...
class LoadingIcon:
    def __init__(self, button: QPushButton, diameter, parent): ...
    def startAnime(self): ...
    def updatePixmap(self, value): ...
    def stopAnimation(self): ...