import asyncio
from functools import lru_cache
import inspect
import threading
import uuid
import time
from typing import Optional, Callable, Any, Dict, Union, List
from PySide6.QtWidgets import QVBoxLayout, QWidget, QHBoxLayout, QPlainTextEdit, QLineEdit, QApplication, QStyledItemDelegate, QSizePolicy, QPushButton, QSpinBox, QDoubleSpinBox, QGraphicsOpacityEffect, QFrame, QGroupBox
from PySide6.QtCore import Qt, QPoint, Signal, QDate, QTime, QTimer, QEvent, QSize
from PySide6.QtGui import QCursor
from qtmui.hooks import State
from qtmui.utils.translator import getTranslatedText
from ..li import Li
from ..menu import Menu
from ..menu_item import MenuItem
from .flow_layout import FlowLayout
from .tags_view import TagsView
from ..picker import DatePicker, TimePicker, AMTimePicker, ZhDatePicker, CalendarPicker, ColorPicker
from qtmui.hooks import useState
from qtmui.material.styles import useTheme
from qtmui.i18n.use_translation import translate, i18n
from ..utils._misc import signals_blocked
from ..utils.functions import _get_fn_args
from ...qtmui_assets import QTMUI_ASSETS
from ..py_iconify import PyIconify
from .py_combobox import PyComboBox
from .py_date_edit import PyDateEdit
from .py_date_time_edit import PyDateTimeEdit
from .py_dial import PyDial
from .py_double_spinbox import PyDoubleSpinBox
from .py_font_combobox import PyFontComboBox
from .py_line_edit import PyLineEdit
from .py_line_edit_multiple import PyLineEditMultiple
from .py_plaintext_edit import PyPlainTextEdit
from .py_plaintext_edit_multiple import PyPlainTextEditMultiple
from .py_spin_box import PySpinBox
from .py_text_edit import PyTextEdit
from .py_time_edit import PyTimeEdit
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
from ..widget_base import PyWidgetBase
from ..utils.validate_params import _validate_param
class TextField:
    def __init__(self, key: str, autoComplete: Optional[Union[State, bool, str]], autoFocus: Optional[Union[State, bool]], classes: Optional[Union[State, Dict]], color: Optional[Union[State, str]], defaultValue: Optional[Union[State, object]], disabled: Optional[Union[State, bool]], error: Optional[Union[State, bool]], FormHelperTextProps: Optional[Union[State, Dict]], fullWidth: Optional[Union[State, bool]], helperText: Optional[Union[State, str]], id: Optional[Union[State, str]], InputLabelProps: Optional[Union[State, Dict]], inputProps: Optional[Union[State, Dict]], InputProps: Optional[Union[State, Dict]], inputRef: Optional[Union[State, object]], inputValue: Optional[Union[State, object]], label: Optional[Union[State, str, Callable]], max: Optional[Union[State, int, float]], margin: Optional[Union[State, str]], maxRows: Optional[Union[State, int, str]], min: Optional[Union[State, int, float]], minRows: Optional[Union[State, int, str]], multiline: Optional[Union[State, bool]], multiple: Optional[Union[State, bool]], menuHeight: Optional[Union[State, int]], name: Optional[Union[State, str]], getOptionLabel: Optional[Union[State, Callable]], onChange: Optional[Union[State, Callable]], onInputChange: Optional[Union[State, Callable]], onMousePress: Optional[Union[State, Callable]], options: Optional[Union[State, object]], hiddenLabel: Optional[Union[State, bool]], placeholder: Optional[Union[State, str]], required: Optional[Union[State, bool]], rows: Optional[Union[State, int, str]], select: Optional[Union[State, bool]], selected: Optional[Union[State, bool]], selectOptions: Optional[Union[State, List]], SelectProps: Optional[Union[State, Dict]], size: Optional[Union[State, str]], slotProps: Optional[Union[State, Dict]], slots: Optional[Union[State, Dict]], sx: Optional[Union[State, Dict, Callable, str]], step: Optional[Union[State, int, float]], renderSelectOptions: Optional[Union[State, Callable]], renderOption: Optional[Union[State, Callable]], renderValue: Optional[Union[State, Callable]], renderTags: Optional[Union[State, Callable]], type: Optional[Union[State, str]], treeView: Optional[Union[State, bool]], value, variant: Optional[Union[State, str]], *args, **kwargs): ...
    def _set_autoComplete(self, value): ...
    def _get_autoComplete(self): ...
    def _set_autoFocus(self, value): ...
    def _get_autoFocus(self): ...
    def _set_classes(self, value): ...
    def _get_classes(self): ...
    def _set_color(self, value): ...
    def _get_color(self): ...
    def _set_defaultValue(self, value): ...
    def _get_defaultValue(self): ...
    def _set_disabled(self, value): ...
    def _get_disabled(self): ...
    def _set_error(self, value): ...
    def _get_error(self): ...
    def _set_FormHelperTextProps(self, value): ...
    def _get_FormHelperTextProps(self): ...
    def _set_fullWidth(self, value): ...
    def _get_fullWidth(self): ...
    def _set_helperText(self, value): ...
    def _get_helperText(self): ...
    def _set_id(self, value): ...
    def _get_id(self): ...
    def _set_InputLabelProps(self, value): ...
    def _set_InputValue(self, value): ...
    def _get_InputValue(self): ...
    def _get_InputLabelProps(self): ...
    def _set_inputProps(self, value): ...
    def _get_inputProps(self): ...
    def _set_InputProps(self, value): ...
    def _get_InputProps(self): ...
    def _set_inputRef(self, value): ...
    def _get_inputRef(self): ...
    def _set_label(self, value): ...
    def _get_label(self): ...
    def _set_max(self, value): ...
    def _get_max(self): ...
    def _set_margin(self, value): ...
    def _get_margin(self): ...
    def _set_maxRows(self, value): ...
    def _get_maxRows(self): ...
    def _set_min(self, value): ...
    def _get_min(self): ...
    def _set_minRows(self, value): ...
    def _get_minRows(self): ...
    def _set_multiline(self, value): ...
    def _get_multiline(self): ...
    def _set_multiple(self, value): ...
    def _get_multiple(self): ...
    def _set_menuHeight(self, value): ...
    def _get_menuHeight(self): ...
    def _set_name(self, value): ...
    def _get_name(self): ...
    def _set_getOptionLabel(self, value): ...
    def _get_getOptionLabel(self): ...
    def _set_onChange(self, value): ...
    def _set_onInputChange(self, value): ...
    def _get_onInputChange(self): ...
    def _set_onMousePress(self, value): ...
    def _get_onMousePress(self): ...
    def _set_options(self, value): ...
    def _get_options(self): ...
    def _set_hiddenLabel(self, value): ...
    def _get_hiddenLabel(self): ...
    def _set_placeholder(self, value): ...
    def _get_placeholder(self): ...
    def _set_required(self, value): ...
    def _get_required(self): ...
    def _set_rows(self, value): ...
    def _get_rows(self): ...
    def _set_select(self, value): ...
    def _get_select(self): ...
    def _set_selected(self, value): ...
    def _get_selected(self): ...
    def _set_selectOptions(self, value): ...
    def _get_selectOptions(self): ...
    def _set_SelectProps(self, value): ...
    def _get_SelectProps(self): ...
    def _set_size(self, value): ...
    def _get_size(self): ...
    def _set_slotProps(self, value): ...
    def _get_slotProps(self): ...
    def _set_slots(self, value): ...
    def _get_slots(self): ...
    def _set_sx(self, value): ...
    def _get_sx(self): ...
    def _set_step(self, value): ...
    def _get_step(self): ...
    def _set_renderSelectOptions(self, value): ...
    def _get_renderSelectOptions(self): ...
    def _set_renderOption(self, value): ...
    def _get_renderOption(self): ...
    def _set_renderValue(self, value): ...
    def _get_renderValue(self): ...
    def _set_renderTags(self, value): ...
    def _get_renderTags(self): ...
    def _set_type(self, value): ...
    def _get_type(self): ...
    def _set_treeView(self, value): ...
    def _get_treeView(self): ...
    def _validate_value(self, value): ...
    def _get_value(self): ...
    def _set_variant(self, value): ...
    def _get_variant(self): ...
    def _connect_signals_props(self): ...
    def __init_ui(self): ...
    def _get_stylesheet(cls, _variant: str, _size: str, _theme_mode: str, _multiple: str, _multiline: str, _renderTags: str): ...
    def _set_stylesheet(self, component_styled): ...
    def _set_state(self, stateValue: dict): ...
    def _set_data(self, value, valueChanged, setText): ...
    def _set_text(self): ...
    def _set_slot(self, data): ...
    def _on_text_changed(self, s): ...
    def _render_search_menu_items(self, search_options_results): ...
    def validate_type_int(self): ...
    def _setupy_input_type(self): ...
    def _set_date_picker(self, date: QDate): ...
    def _set_time_picker(self, time: QTime): ...
    def _setup_input_props(self): ...
    def _on_clear_text(self): ...
    def _update_popup_position(self): ...
    def _hide_popup(self): ...
    def _btn_select_toggle_popup(self, e): ...
    def _toggle_popup(self, e): ...
    def _show_popup(self, search): ...
    def _on_menu_item_selected(self, key): ...
    def _on_create_menu(self): ...
    def _create_menu(self): ...
    def _about_to_hide(self): ...
    def getTagProps(self, index): ...
    def _on_tag_deleted(self, index): ...
    def _update_selected_options(self, key, option): ...
    def _setup_tags(self, key, option): ...
    def _selected_change(self, data): ...
    def _show_label(self): ...
    def _set_translated_label(self): ...
    def _hide_label(self): ...
    def _set_hovered_prop(self): ...
    def _set_focused_prop(self): ...
    def _set_multiple_has_value_prop(self, state): ...
    def _set_filled_has_value_prop(self, state: bool): ...
    def _set_filled_foucusin_prop(self, state: bool): ...
    def _set_prop_has_start_adornment(self, state: bool): ...
    def leaveEvent(self, event): ...
    def setup_action_frame_and_adornment(self): ...
    def resizeEvent(self, event): ...
    def eventFilter(self, obj, event): ...