from typing import Callable, Dict, Union
import uuid
from qtmui.hooks import State
from PySide6.QtWidgets import QVBoxLayout, QWidget, QSizePolicy, QFrame
from PySide6.QtCore import Qt, Signal, QSize
from qtmui.material.widget_base import PyWidgetBase
from .utils.validate_params import _validate_param
from .styles.create_theme.components.get_qss_styles import get_qss_style
from .styles import useTheme
class Section:
    def __init__(self, key, children, sx, *args, **kwargs): ...
    def add_widget(self, element: QWidget): ...
    def _set_sx(self, value): ...
    def _set_stylesheet(self): ...
    def showEvent(self, e): ...
    def resizeEvent(self, event): ...