"""
    Sample metadata API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 7.13.4
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from metamist.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)
from ..model_utils import OpenApiModel
from metamist.exceptions import ApiAttributeError



class ProjectInsightsSummary(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            'project': (int,),  # noqa: E501
            'dataset': (str,),  # noqa: E501
            'sequencing_type': (str,),  # noqa: E501
            'sequencing_technology': (str,),  # noqa: E501
            'total_families': (int,),  # noqa: E501
            'total_participants': (int,),  # noqa: E501
            'total_samples': (int,),  # noqa: E501
            'total_sequencing_groups': (int,),  # noqa: E501
            'total_crams': (int,),  # noqa: E501
            'latest_annotate_dataset': (bool, date, datetime, dict, float, int, list, str, none_type,),  # noqa: E501
            'latest_snv_es_index': (bool, date, datetime, dict, float, int, list, str, none_type,),  # noqa: E501
            'latest_sv_es_index': (bool, date, datetime, dict, float, int, list, str, none_type,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'project': 'project',  # noqa: E501
        'dataset': 'dataset',  # noqa: E501
        'sequencing_type': 'sequencing_type',  # noqa: E501
        'sequencing_technology': 'sequencing_technology',  # noqa: E501
        'total_families': 'total_families',  # noqa: E501
        'total_participants': 'total_participants',  # noqa: E501
        'total_samples': 'total_samples',  # noqa: E501
        'total_sequencing_groups': 'total_sequencing_groups',  # noqa: E501
        'total_crams': 'total_crams',  # noqa: E501
        'latest_annotate_dataset': 'latest_annotate_dataset',  # noqa: E501
        'latest_snv_es_index': 'latest_snv_es_index',  # noqa: E501
        'latest_sv_es_index': 'latest_sv_es_index',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, project, dataset, sequencing_type, sequencing_technology, total_families, total_participants, total_samples, total_sequencing_groups, total_crams, latest_annotate_dataset, latest_snv_es_index, latest_sv_es_index, *args, **kwargs):  # noqa: E501
        """ProjectInsightsSummary - a model defined in OpenAPI

        Args:
            project (int):
            dataset (str):
            sequencing_type (str):
            sequencing_technology (str):
            total_families (int):
            total_participants (int):
            total_samples (int):
            total_sequencing_groups (int):
            total_crams (int):
            latest_annotate_dataset (bool, date, datetime, dict, float, int, list, str, none_type):
            latest_snv_es_index (bool, date, datetime, dict, float, int, list, str, none_type):
            latest_sv_es_index (bool, date, datetime, dict, float, int, list, str, none_type):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.project = project
        self.dataset = dataset
        self.sequencing_type = sequencing_type
        self.sequencing_technology = sequencing_technology
        self.total_families = total_families
        self.total_participants = total_participants
        self.total_samples = total_samples
        self.total_sequencing_groups = total_sequencing_groups
        self.total_crams = total_crams
        self.latest_annotate_dataset = latest_annotate_dataset
        self.latest_snv_es_index = latest_snv_es_index
        self.latest_sv_es_index = latest_sv_es_index
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, project, dataset, sequencing_type, sequencing_technology, total_families, total_participants, total_samples, total_sequencing_groups, total_crams, latest_annotate_dataset, latest_snv_es_index, latest_sv_es_index, *args, **kwargs):  # noqa: E501
        """ProjectInsightsSummary - a model defined in OpenAPI

        Args:
            project (int):
            dataset (str):
            sequencing_type (str):
            sequencing_technology (str):
            total_families (int):
            total_participants (int):
            total_samples (int):
            total_sequencing_groups (int):
            total_crams (int):
            latest_annotate_dataset (bool, date, datetime, dict, float, int, list, str, none_type):
            latest_snv_es_index (bool, date, datetime, dict, float, int, list, str, none_type):
            latest_sv_es_index (bool, date, datetime, dict, float, int, list, str, none_type):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.project = project
        self.dataset = dataset
        self.sequencing_type = sequencing_type
        self.sequencing_technology = sequencing_technology
        self.total_families = total_families
        self.total_participants = total_participants
        self.total_samples = total_samples
        self.total_sequencing_groups = total_sequencing_groups
        self.total_crams = total_crams
        self.latest_annotate_dataset = latest_annotate_dataset
        self.latest_snv_es_index = latest_snv_es_index
        self.latest_sv_es_index = latest_sv_es_index
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
