"""Listado de barrios permitidos para el servicio MLS Acrecer.

Esta lista se utiliza para filtrar o validar barrios en los procesos
relacionados con la API de Acrecer. La normalización de los nombres (mayúsculas,
acentos, etc.) puede ser necesaria antes de su uso.
"""
BARRIOS = [
    "Abadia",
    "Aeropuerto",
    "Aeropuerto Jose María Cordoba",
    "Aguacatala",
    "Alcala",
    "Alcalá",
    "ALEJANDRIA",
    "Alejandría",
    "Almeria",
    "Almería",
    "Alto De Las Flores",
    "Alto De Palmas",
    "ALTOS DEL POBLADO",
    "Altos Del Poblado Cola Del Zorro",
    "Asdesillas",
    "Asdesillas Sabaneta",
    "Astorga",
    "Asturias",
    "AVENIDA LAS VEGAS",
    "AVES MARIA",
    "Aves María",
    "BARICHARA",
    "BARRIO COLOMBIA",
    "BARRIO MESA",
    "Barrio Mesa Envigado",
    "BELEN LA CASTELLANA",
    "Belen La Gloria",
    "Belén Malibú",
    "Belen Rosales",
    "Benedictinos",
    "Bosques De Zuñiga",
    "Bosques De Zúñiga",
    "Calasanz",
    "Calle Larga",
    "Calle Nueva",
    "Callejon Del Banco",
    "Callejón Del Banco",
    "Camino Verde",
    "Carlos E. Restrepo",
    "CASTROPOL",
    "CENTRAL MAYORISTA",
    "CENTRO DE ENVIGADO",
    "Centro De La Moda",
    "CIUDAD DEL RIO",
    "Ciudad Del Río",
    "Cola Del Zorro",
    "Conquistadores",
    "CRISTO REY",
    "Cumbres",
    "Don Diego",
    "EL CAMPESTRE",
    "El Campestre La Frontera",
    "El Carmelo",
    "El Carmelo Sabaneta",
    "El Chingui",
    "El Chinguí",
    "El Chocho",
    "EL DORADO",
    "El Dorado Envigado",
    "EL ESCOBERO",
    "El Esmeraldal",
    "El Nogal",
    "El Nogal  Los Almendros",
    "El Poblado",
    "EL POBLADO LOMA DEL INDIO",
    "El Portal",
    "El Retiro",
    "El Retiro Campestre",
    "El Salado Envigado",
    "El tablazo",
    "El Tablazo Oriente",
    "El Tesoro",
    "El Trianon",
    "El Trianón",
    "EL VELÓDROMO",
    "El Vergel",
    "El Yarumo",
    "Entreamigos",
    "ENVIGADO",
    "Estadio",
    "FLORESTA",
    "Florida Nueva",
    "Galerias",
    "Gualanday",
    "GUALANDAYES",
    "Guanteros",
    "GUAYABAL",
    "INTERCONTINENTAL",
    "Intermedia",
    "Jardines",
    "La Abadia",
    "La Abadía",
    "LA AGUACATALA",
    "La Alameda",
    "La Aldea",
    "La Aldea La Estrella",
    "La Almería",
    "LA AMÉRICA",
    "La Asomadera",
    "La Calera",
    "La Castellana",
    "LA CEJA",
    "LA COLA DEL ZORRO",
    "LA CONCHA",
    "La Cuenca",
    "La Doctora",
    "LA ESTRELLA",
    "La Fe",
    "La Floresta",
    "La Florida El Poblado",
    "La Florida Sabaneta",
    "La Frontera",
    "La Frontera  Campestre",
    "LA FRONTERA M",
    "La Inferior",
    "La Loma Del Indio",
    "La Magnolia",
    "La Mayorista",
    "La Mina",
    "LA MOTA",
    "La Paz",
    "LA SALLE",
    "La Sebastiana",
    "La Somer",
    "La Tablaza",
    "LA TOMATERA",
    "La VisitaciÃ³n",
    "La Visitacion",
    "La Visitación",
    "La Visitacion Los Gonzalez",
    "LAGOS DE LA DOCTORA",
    "Lalinde",
    "Las Acacias",
    "Las Acacias Laureles",
    "Las Antillas",
    "Las Casitas envigado",
    "Las Lomas",
    "Las Lomas 1",
    "Las Lomas 2",
    "Las Lomitas",
    "Las Margaritas",
    "LAS PALMAS",
    "Las Palmas Envigado",
    "LAS PALMAS M",
    "Las Palmas Medellín",
    "LAS SANTAS",
    "LAS VEGAS",
    "LAURELES",
    "laureles el nogal",
    "Laureles Medellín",
    "Llano Grande",
    "Llanogrande",
    "Lleras",
    "Loma Benedictinos",
    "Loma de la Esmeralda",
    "Loma De Las Brujas",
    "Loma De Las Santas",
    "LOMA DE LOS BENEDICTINOS",
    "Loma De Los Gonzalez",
    "LOMA DE LOS MESA",
    "Loma de los Parra",
    "LOMA DE LOS PARRAS",
    "Loma De San Jose",
    "Loma De San Julian",
    "Loma De San Julián",
    "Loma Del Atravesado",
    "Loma Del Atravesado ",
    "Loma Del Barro",
    "Loma Del Campestre",
    "LOMA DEL CHOCHO",
    "Loma Del Encierro",
    "Loma Del Escobero",
    "Loma Del Escobero Envigado",
    "Loma Del Esmeraldal",
    "LOMA DEL INDIO",
    "LOMA EL ATRAVEZADO",
    "Loma El Encierro",
    "Loma Los Gonzalez",
    "Loma San Jose",
    "Loma San José Sabaneta",
    "Loma San Julián",
    "Lopez de Mesa",
    "Los Balsos",
    "Los Balsos 1",
    "Los Balsos 2",
    "Los Bolsos",
    "Los Colegios",
    "LOS CONQUISTADORES",
    "LOS GONZALEZ",
    "Los Naranjos",
    "Los Naranjos Itagui",
    "LOS PARRA",
    "MALIBU",
    "Mall La Sebastiana",
    "Manila",
    "Mayorca",
    "Mesa",
    "Milán Vallejuelos",
    "MILLA DE ORO",
    "Miraflores la ceja",
    "NOGAL - LOS ALMENDROS",
    "Nogal Los Almendros",
    "NUEVO POBLADO",
    "Otra Parte",
    "Otraparte",
    "OVIEDO",
    "Parque De Envigado",
    "Parque Lleras",
    "Parque Poblado",
    "Parque Rionegro",
    "Parque Sabaneta",
    "Patio Bonito",
    "Poblado",
    "Poblado Altos Del Poblado",
    "Poblado Altos Delpoblado",
    "Poblado Del Sur",
    "Pontevedra",
    "Pontezuela",
    "Primavera",
    "Primavera Envigado",
    "Provenza",
    "RIONEGRO",
    "Riveras Del Retiro",
    "Rosales",
    "SABANETA",
    "Sajonia",
    "San Agustin",
    "San Agustín",
    "San Diego",
    "San Fernando",
    "San Joaquin",
    "SAN JOAQUÍN",
    "San Joaquín Laureles",
    "San Joaquín Sabaneta",
    "San José Envigado",
    "SAN JULIAN",
    "San Lucas",
    "San Marcos",
    "San Mateo Envigado",
    "San Rafael Envigado",
    "San Remo",
    "Santa Ana",
    "Santa Ana Sabaneta",
    "Santa Fe",
    "Santa Fé",
    "SANTA MARIA DE LOS ANGELES",
    "Santa María De Los Ángeles",
    "Santa Monica",
    "SANTA MÓNICA",
    "Santa Mónica ",
    "Señorial",
    "Sierra Morena",
    "Simon Bolivar",
    "SIMÓN BOLÍVAR",
    "SURAMERICA",
    "Suramérica",
    "Suramérica Itagui",
    "Suramérica La Estrella",
    "Suramericana",
    "TRANSVERSAL INFERIOR",
    "Transversal Intermedia",
    "TRANSVERSAL SUPERIOR",
    "TRES ESQUINAS",
    "Trianon",
    "Vegas De San José",
    "Vegas Del Poblado",
    "Vereda El Chuscal",
    "Vereda El Escobero",
    "Vereda El Guamito",
    "Vereda El Tablazo",
    "Vereda El Yarumo",
    "Vereda Fontibon La Laja",
    "Vereda La Fe",
    "Vereda Llano Grande",
    "Vereda Llanogrande",
    "Vereda Los Alticos San Antonio De Pereira",
    "Vereda Los Salados",
    "Vereda Ojo De Agua",
    "Vereda Pantanillo",
    "Vereda Pontezuela",
    "Veredad Don Diego",
    "Villa Carlota",
    "Villa Grande",
    "Villagrande",
    "Villas de Rionegro",
    "VIZCAYA",
    "Yarumito",
    "ZUÑIGA",
    "Zúñiga",
]

