from _typeshed import Incomplete
from typing import Iterator

OTHER_OP_TYPES = int | float
OP_TYPES: Incomplete

class hurwitzint:
    a: int
    b: int
    c: int
    d: int
    def __init__(self, a: int = 0, b: int = 0, c: int = 0, d: int = 0, *, half: bool = False) -> None: ...
    @property
    def is_lipschitz(self) -> bool: ...
    @property
    def den(self) -> int: ...
    def conjugate(self) -> hurwitzint: ...
    def components2(self) -> tuple[int, int, int, int]: ...
    def __add__(self, other: OP_TYPES) -> hurwitzint: ...
    def __radd__(self, other: OTHER_OP_TYPES) -> hurwitzint: ...
    def __sub__(self, other: OP_TYPES) -> hurwitzint: ...
    def __rsub__(self, other: OTHER_OP_TYPES) -> hurwitzint: ...
    def __neg__(self) -> hurwitzint: ...
    def __pos__(self) -> hurwitzint: ...
    def __mul__(self, other: OP_TYPES) -> hurwitzint: ...
    def __rmul__(self, other: OTHER_OP_TYPES) -> hurwitzint: ...
    def __pow__(self, exp: int) -> hurwitzint: ...
    def __divmod__(self, other: OP_TYPES) -> tuple['hurwitzint', 'hurwitzint']: ...
    def __truediv__(self, other: OP_TYPES) -> hurwitzint: ...
    def __rtruediv__(self, other: OTHER_OP_TYPES) -> hurwitzint: ...
    def __floordiv__(self, other: OP_TYPES) -> hurwitzint: ...
    def __rfloordiv__(self, other: OTHER_OP_TYPES) -> hurwitzint: ...
    def __mod__(self, other: OP_TYPES) -> hurwitzint: ...
    def rdivmod(self, other: OP_TYPES) -> tuple['hurwitzint', 'hurwitzint']: ...
    def rtruediv(self, other: OP_TYPES) -> hurwitzint: ...
    def rfloordiv(self, other: OP_TYPES) -> hurwitzint: ...
    def rmod(self, other: OP_TYPES) -> hurwitzint: ...
    def __abs__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __iter__(self) -> Iterator[int]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

def rdivmod(a: hurwitzint, b: OP_TYPES) -> tuple['hurwitzint', 'hurwitzint']: ...
