import asyncio
from functools import lru_cache
from typing import Callable, Optional, Union, Dict, Any
from PySide6.QtGui import QPainter, QPen, QIcon
from PySide6.QtCore import Qt, QSize, Signal, QTimer, QEvent
from PySide6.QtWidgets import QPushButton
from ..system.color_manipulator import hex_string_to_qcolor
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
from qtmui.material.py_iconify import Iconify
from qtmui.hooks import State, useEffect
from qtmui.material.styles import useTheme
from qtmui.i18n.use_translation import translate, i18n
from ..utils.functions import _get_fn_args
from ...qtmui_assets import QTMUI_ASSETS
from ..utils.validate_params import _validate_param
class Checkbox:
    def __init__(self, key: str, checked: Optional[Union[State, bool]], checkedIcon: Optional[Union[State, str, Iconify]], color: Union[State, str], defaultChecked: Optional[Union[State, bool]], disabled: Union[State, bool], disableGutters: Union[State, bool], disableRipple: Union[State, bool], icon: Optional[Union[State, str, Iconify]], indeterminate: Union[State, bool], indeterminateIcon: Optional[Union[State, str, Iconify]], inputProps: Optional[Union[State, Dict]], onChange: Optional[Union[State, Callable]], required: Union[State, bool], size: Union[State, str], slotProps: Optional[Union[State, Dict]], slots: Optional[Union[State, Dict]], state: Optional[Union[State, bool]], sx: Optional[Union[State, Dict, Callable, str]], value: Optional[Union[State, Any]], *args, **kwargs): ...
    def _get_checked(self): ...
    def _init_ui(self): ...
    def onClicked(self): ...
    def _connectStates(self): ...
    def _setCheckedState(self, state): ...
    def _updateIcon(self): ...
    def _setSx(cls, sx): ...
    def _setKwargs(cls, kwargs: dict): ...
    def _getSxQss(cls, sxStr: str, className: str): ...
    def _getStyleSheet(cls, objectName, _styledConfig: str, _size: str, _color: str, _theme_mode: str): ...
    def _setStyleSheet(self): ...