"""Port for console user interaction."""

from typing import Protocol


class ConsolePort(Protocol):
    """Contract for console output and user interaction."""

    def info(self, msg: str) -> None: ...
    def warn(self, msg: str) -> None: ...
    def echo(self, msg: str) -> None: ...
    def confirm(self, msg: str, default: bool = True) -> bool: ...
