# coding: utf-8

"""
    hedera Solution API

    Repository for Active Research Datasets

    The version of the OpenAPI document: 1.2.0-SNAPSHOT
    Contact: eresearch-opensource@unige.ch
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hedera_api_client.api.index_settings_api import IndexSettingsApi


class TestIndexSettingsApi(unittest.TestCase):
    """IndexSettingsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IndexSettingsApi()

    def tearDown(self) -> None:
        pass

    def test_index_settings_by_id_delete(self) -> None:
        """Test case for index_settings_by_id_delete

        """
        pass

    def test_index_settings_by_id_get(self) -> None:
        """Test case for index_settings_by_id_get

        """
        pass

    def test_index_settings_by_id_update(self) -> None:
        """Test case for index_settings_by_id_update

        """
        pass

    def test_index_settings_create(self) -> None:
        """Test case for index_settings_create

        """
        pass

    def test_index_settings_delete_all(self) -> None:
        """Test case for index_settings_delete_all

        """
        pass

    def test_index_settings_delete_list(self) -> None:
        """Test case for index_settings_delete_list

        """
        pass

    def test_index_settings_list(self) -> None:
        """Test case for index_settings_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
