from typing import Optional, Union, Callable, Any, Dict, List
import uuid
from PySide6.QtWidgets import QApplication, QPushButton, QVBoxLayout, QWidget, QSizePolicy
from PySide6.QtGui import QPainter, QColor, QBrush, QLinearGradient, QPainterPath
from PySide6.QtCore import QPropertyAnimation, QObject, Qt, QRect, Property, QEasingCurve
from ..widget_base import PyWidgetBase
from qtmui.material.styles import useTheme
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
from qtmui.hooks import State
from ..utils.validate_params import _validate_param
class RippleEffect:
    def __init__(self, parent): ...
    def rectX1(self): ...
    def setRectX1(self, rectX1): ...
    def opacity(self): ...
    def setOpacity(self, opacity): ...
    def brush_color(self): ...
    def setBrushColor(self, brush_color): ...
class Skeleton:
    def __init__(self, animation: Union[State, str, bool], children: Optional[Union[State, QWidget]], classes: Optional[Union[State, Dict]], component: Optional[Union[State, type]], height: Optional[Union[State, int, str]], sx: Optional[Union[State, List, Dict, Callable]], variant: Optional[Union[State, str]], width: Optional[Union[State, int, str]], key: Optional[Union[State, str]], color: Optional[Union[State, str]], fullwidth: Union[State, bool], custom_radius: Optional[Union[State, int]], duration: Union[State, int], startColorAt: Union[State, QColor], endColorAt: Union[State, QColor], *args, **kwargs): ...
    def _set_animation(self, value): ...
    def _get_animation(self): ...
    def _set_children(self, value): ...
    def _get_children(self): ...
    def _set_classes(self, value): ...
    def _get_classes(self): ...
    def _set_component(self, value): ...
    def _get_component(self): ...
    def _set_height(self, value): ...
    def _get_height(self): ...
    def _set_sx(self, value): ...
    def _get_sx(self): ...
    def _set_variant(self, value): ...
    def _get_variant(self): ...
    def _set_width(self, value): ...
    def _get_width(self): ...
    def _set_key(self, value): ...
    def _get_key(self): ...
    def _set_color(self, value): ...
    def _get_color(self): ...
    def _set_fullwidth(self, value): ...
    def _get_fullwidth(self): ...
    def _set_custom_radius(self, value): ...
    def _get_custom_radius(self): ...
    def _set_duration(self, value): ...
    def _get_duration(self): ...
    def _set_startColorAt(self, value): ...
    def _get_startColorAt(self): ...
    def _set_endColorAt(self, value): ...
    def _get_endColorAt(self): ...
    def _init_ui(self): ...
    def slot_set_stylesheet(self, value): ...
    def _set_stylesheet(self, component_styled): ...
    def set_animation_mode(self, animation): ...
    def paintEvent(self, event): ...