from csp_lib.equipment.transport.base import ReadGroup
from typing import Any, Sequence

__all__ = ['GroupReader']

class GroupReader:
    def __init__(self, client: AsyncModbusClientBase, unit_id: int = ..., address_offset: int = ..., max_concurrent_reads: int = ...) -> None: ...
    def read(self, group: ReadGroup) -> dict[str, Any]: ...
    def read_many(self, groups: Sequence[ReadGroup]) -> dict[str, Any]: ...
    def _read_from_device(self, group: ReadGroup) -> list[int] | list[bool]: ...
    def _decode(self, group: ReadGroup, raw_data: list[int] | list[bool]) -> dict[str, Any]: ...
