from csp_lib.equipment.transport.base import ReadGroup
from typing import Sequence

__all__ = ['ReadScheduler']

class ReadScheduler:
    def __init__(self, always_groups: Sequence[ReadGroup] | None = ..., rotating_groups: Sequence[Sequence[ReadGroup]] | None = ...) -> None: ...
    def get_next_groups(self) -> list[ReadGroup]: ...
    def peek_next_groups(self) -> list[ReadGroup]: ...
    def reset(self) -> None: ...
    @property
    def current_rotating_index(self): ...
    @property
    def rotating_count(self): ...
    @property
    def has_rotating(self): ...
