# coding: utf-8

"""
    hedera Solution API

    Repository for Active Research Datasets

    The version of the OpenAPI document: 1.2.1
    Contact: eresearch-opensource@unige.ch
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from hedera_api_client.models.cors import Cors
from hedera_api_client.models.download_token import DownloadToken
from typing import Optional, Set
from typing_extensions import Self

class Security(BaseModel):
    """
    Security
    """ # noqa: E501
    download_token_life_time_minutes: Optional[StrictInt] = Field(default=None, alias="downloadTokenLifeTimeMinutes")
    cipher_password: Optional[StrictStr] = Field(default=None, alias="cipherPassword")
    cors: Optional[Cors] = None
    download_token: Optional[DownloadToken] = Field(default=None, alias="downloadToken")
    __properties: ClassVar[List[str]] = ["downloadTokenLifeTimeMinutes", "cipherPassword", "cors", "downloadToken"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Security from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of cors
        if self.cors:
            _dict['cors'] = self.cors.to_dict()
        # override the default output from pydantic by calling `to_dict()` of download_token
        if self.download_token:
            _dict['downloadToken'] = self.download_token.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Security from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "downloadTokenLifeTimeMinutes": obj.get("downloadTokenLifeTimeMinutes"),
            "cipherPassword": obj.get("cipherPassword"),
            "cors": Cors.from_dict(obj["cors"]) if obj.get("cors") is not None else None,
            "downloadToken": DownloadToken.from_dict(obj["downloadToken"]) if obj.get("downloadToken") is not None else None
        })
        return _obj


