from typing import Callable
from functools import wraps
import json
def merge_dicts(*dict_args): ...
def deep_merge(a, b): ...
def convert_sx_params_to_str(func): ...
def convert_sx_params_to_dict(func): ...