from typing import Any, Callable, Dict, List, Optional, Tuple, Union

from com.inductiveautomation.factorypmi.application import FPMIWindow
from com.inductiveautomation.factorypmi.application.script.builtin import (
    ClientPrintUtilities,
    VisionUtilities,
)
from com.inductiveautomation.ignition.common import Dataset
from com.inductiveautomation.ignition.common.i18n.keyboard import KeyboardLayout
from java.awt import Color, Component
from java.awt.image import BufferedImage
from java.org.jdesktop.core.animation.timing import Animator
from java.util import EventObject, Locale
from javax.swing import JComponent, JFrame, JPopupMenu

ACCL_NONE: int
ACCL_CONSTANT: int
ACCL_FAST_TO_SLOW: int
ACCL_SLOW_TO_FAST: int
ACCL_EASE: int
COORD_DESIGNER: int
COORD_SCREEN: int
LANDSCAPE: int
PORTRAIT: int
CLIENT_FLAG: int
DESIGNER_FLAG: int
FULLSCREEN_FLAG: int
PREVIEW_FLAG: int
SSL_FLAG: int
CONNECTION_MODE_DISCONNECTED: int
CONNECTION_MODE_READ_ONLY: int
CONNECTION_MODE_READ_WRITE: int

def beep() -> None: ...
def centerWindow(arg: Union[str, unicode, FPMIWindow]) -> None: ...
def closeDesktop(handle: Union[str, unicode]) -> None: ...
def closeParentWindow(event: EventObject) -> None: ...
def closeWindow(arg: Union[str, unicode, FPMIWindow]) -> None: ...
def color(*args: Any) -> Color: ...
def createImage(component: Component) -> BufferedImage: ...
def createPopupMenu(
    itemNames: List[Union[str, unicode]], itemFunctions: List[Callable[..., Any]]
) -> JPopupMenu: ...
def createPrintJob(component: Component) -> ClientPrintUtilities.JythonPrintJob: ...
def desktop(handle: Union[str, unicode, None] = ...) -> VisionUtilities: ...
def exit(force: bool = ...) -> None: ...
def exportCSV(
    filename: Union[str, unicode], showHeaders: bool, dataset: Dataset
) -> Union[str, unicode]: ...
def exportExcel(
    filename: Union[str, unicode],
    showHeaders: bool,
    dataset: Union[Dataset, List[Dataset]],
    nullsEmpty: bool = ...,
) -> Union[str, unicode]: ...
def exportHTML(
    filename: Union[str, unicode],
    showHeaders: bool,
    dataset: Dataset,
    title: Union[str, unicode],
) -> Union[str, unicode]: ...
def findWindow(path: Union[str, unicode]) -> List[FPMIWindow]: ...
def getAvailableLocales() -> List[Union[str, unicode]]: ...
def getAvailableTerms() -> List[Union[str, unicode]]: ...
def getClientId() -> unicode: ...
def getConnectTimeout() -> int: ...
def getConnectionMode() -> int: ...
def getCurrentDesktop() -> Union[str, unicode]: ...
def getCurrentWindow() -> Union[str, unicode]: ...
def getDesktopHandles() -> List[Union[str, unicode]]: ...
def getEdition() -> Union[str, unicode]: ...
def getExternalIpAddress() -> Union[str, unicode]: ...
def getGatewayAddress() -> unicode: ...
def getInactivitySeconds() -> long: ...
def getKeyboardLayouts() -> List[KeyboardLayout]: ...
def getLocale() -> Union[str, unicode]: ...
def getOpenedWindowNames() -> Tuple[Union[str, unicode], ...]: ...
def getOpenedWindows() -> Tuple[FPMIWindow, ...]: ...
def getParentWindow(event: EventObject) -> FPMIWindow: ...
def getReadTimeout() -> int: ...
def getRoles() -> Tuple[Union[str, unicode], ...]: ...
def getScreenIndex() -> int: ...
def getScreens() -> List[Tuple[Union[str, unicode], int, int]]: ...
def getSibling(event: EventObject, name: Union[str, unicode]) -> FPMIWindow: ...
def getSystemFlags() -> int: ...
def getUsername() -> Union[str, unicode]: ...
def getWindow(name: Union[str, unicode]) -> FPMIWindow: ...
def getWindowNames() -> Tuple[Union[str, unicode], ...]: ...
def goBack() -> FPMIWindow: ...
def goForward() -> FPMIWindow: ...
def goHome() -> FPMIWindow: ...
def invokeLater(function: Callable[..., Any], delay: int = ...) -> None: ...
def isOverlaysEnabled() -> bool: ...
def isScreenLocked() -> bool: ...
def isTouchscreenMode() -> bool: ...
def lockScreen(obscure: bool = ...) -> None: ...
def logout() -> None: ...
def openDesktop(
    screen: int = ...,
    handle: Union[str, unicode, None] = ...,
    title: Union[str, unicode, None] = ...,
    width: Optional[int] = ...,
    height: Optional[int] = ...,
    x: int = ...,
    y: int = ...,
    windows: Optional[List[Union[str, unicode]]] = ...,
) -> JFrame: ...
def openFile(
    extension: Union[str, unicode, None] = ...,
    defaultLocation: Union[str, unicode, None] = ...,
) -> Union[str, unicode, None]: ...
def openFiles(
    extension: Union[str, unicode, None] = ...,
    defaultLocation: Union[str, unicode, None] = ...,
) -> Optional[List[Union[str, unicode]]]: ...
def openURL(url: Union[str, unicode], useApplet: Optional[bool] = ...) -> None: ...
def openWindow(
    path: Union[str, unicode], params: Optional[Dict[Union[str, unicode], Any]] = ...
) -> FPMIWindow: ...
def openWindowInstance(
    path: Union[str, unicode], params: Optional[Dict[Union[str, unicode], Any]] = ...
) -> FPMIWindow: ...
def playSoundClip(wav: Any, volume: float = ..., wait: bool = ...) -> None: ...
def printToImage(
    component: Component, filename: Union[str, unicode, None] = ...
) -> None: ...
def refreshBinding(
    component: JComponent, propertyName: Union[str, unicode]
) -> bool: ...
def retarget(
    project: Union[str, unicode],
    addresses: Optional[Union[str, unicode, List[Union[str, unicode]]]] = ...,
    params: Optional[Dict[Union[str, unicode], Any]] = ...,
    windows: Optional[List[Union[str, unicode]]] = ...,
) -> None: ...
def saveFile(
    filename: Union[str, unicode],
    extension: Union[str, unicode, None] = ...,
    typeDesc: Union[str, unicode, None] = ...,
) -> Union[str, unicode, None]: ...
def setConnectTimeout(connectTimeout: int) -> None: ...
def setConnectionMode(mode: int) -> None: ...
def setLocale(locale: Union[str, unicode, Locale]) -> None: ...
def setOverlaysEnabled(enabled: bool) -> None: ...
def setReadTimeout(readTimeout: int) -> None: ...
def setTouchscreenMode(enabled: bool) -> None: ...
def setScreenIndex(index: int) -> None: ...
def showColorInput(
    initialColor: Color, dialogTitle: Union[str, unicode] = ...
) -> Color: ...
def showConfirm(
    message: Union[str, unicode],
    title: Union[str, unicode] = ...,
    allowCancel: bool = ...,
) -> Optional[bool]: ...
def showDiagnostics() -> None: ...
def showError(
    message: Union[str, unicode], title: Union[str, unicode] = ...
) -> None: ...
def showInput(
    message: Union[str, unicode], defaultText: Union[str, unicode] = ...
) -> Union[str, unicode, None]: ...
def showMessage(
    message: Union[str, unicode], title: Union[str, unicode] = ...
) -> None: ...
def showNumericKeypad(
    initialValue: Union[float, int, long],
    fontSize: Optional[int] = ...,
    usePasswordMode: bool = ...,
) -> Union[float, int, long]: ...
def showPasswordInput(
    message: Union[str, unicode],
    title: Union[str, unicode] = ...,
    echoChar: Union[str, unicode] = ...,
) -> Union[str, unicode, None]: ...
def showTouchscreenKeyboard(
    initialText: Union[str, unicode],
    fontSize: Optional[int] = ...,
    passwordMode: bool = ...,
) -> Union[str, unicode]: ...
def showWarning(
    message: Union[str, unicode], title: Union[str, unicode] = ...
) -> None: ...
def swapTo(
    path: Union[str, unicode], params: Optional[Dict[Union[str, unicode], Any]] = ...
) -> FPMIWindow: ...
def swapWindow(
    arg: Union[str, unicode, EventObject],
    swapToPath: Union[str, unicode],
    params: Optional[Dict[Union[str, unicode], Any]] = ...,
) -> FPMIWindow: ...
def switchUser(
    username: Union[str, unicode],
    password: Union[str, unicode],
    event: EventObject,
    hideError: bool = ...,
) -> bool: ...
def transform(
    component: JComponent,
    newX: Optional[int] = ...,
    newY: Optional[int] = ...,
    newWidth: Optional[int] = ...,
    newHeight: Optional[int] = ...,
    duration: int = ...,
    callback: Optional[Callable[..., Any]] = ...,
    framesPerSecond: int = ...,
    acceleration: Optional[int] = ...,
    coordSpace: Optional[int] = ...,
) -> Animator: ...
def unlockScreen() -> None: ...
def updateProject() -> None: ...
