# src/napcat/types/__init__.py
from .events import (
    GroupMessageEvent,
    HeartbeatEvent,
    LifecycleMetaEvent,
    MessageEvent,
    MessageSender,
    MetaEvent,
    NapCatEvent,
    PrivateMessageEvent,
    UnknownEvent,
    FriendRequestEvent,
    GroupRequestEvent,
    RequestEvent,
    HeartbeatStatus,
    # Notice Events
    BotOfflineEvent,
    FriendAddNoticeEvent,
    FriendPokeEvent,
    FriendRecallNoticeEvent,
    GroupAdminNoticeEvent,
    GroupBanEvent,
    GroupCardEvent,
    GroupDecreaseEvent,
    GroupEssenceEvent,
    GroupGrayTipEvent,
    GroupIncreaseEvent,
    GroupMsgEmojiLikeEvent,
    GroupNameEvent,
    GroupNoticeEvent,
    GroupPokeEvent,
    GroupRecallNoticeEvent,
    GroupTitleEvent,
    GroupUploadFile,
    GroupUploadNoticeEvent,
    InputStatusEvent,
    MsgEmojiLike,
    NoticeEvent,
    PokeEvent,
    ProfileLikeEvent,
    UnknownNoticeEvent,
)

from .messages import (
    MessageAt,
    MessageContext,
    MessageCustomMusic,
    MessageData,
    MessageDice,
    MessageFace,
    MessageFile,
    MessageForward,
    MessageIdMusic,
    MessageImage,
    MessageJson,
    MessageMFace,
    MessageMarkdown,
    MessageNode,
    MessagePoke,
    MessageRPS,
    MessageRecord,
    MessageReply,
    MessageText,
    MessageVideo,
    MessageSegmentType
)

from .messages import MessageSegment, UnknownMessageSegment

__all__ = [
    # events (most used)
    # Base
    "NapCatEvent",
    "UnknownEvent",
    # Meta Events
    "MetaEvent",
    "LifecycleMetaEvent",
    "HeartbeatEvent",
    "HeartbeatStatus",
    # Message Events
    "MessageEvent",
    "PrivateMessageEvent",
    "GroupMessageEvent",
    "MessageSender",
    # Request Events
    "RequestEvent",
    "FriendRequestEvent",
    "GroupRequestEvent",
    # Notice Events
    "BotOfflineEvent",
    "FriendAddNoticeEvent",
    "FriendPokeEvent",
    "FriendRecallNoticeEvent",
    "GroupAdminNoticeEvent",
    "GroupBanEvent",
    "GroupCardEvent",
    "GroupDecreaseEvent",
    "GroupEssenceEvent",
    "GroupGrayTipEvent",
    "GroupIncreaseEvent",
    "GroupMsgEmojiLikeEvent",
    "GroupNameEvent",
    "GroupNoticeEvent",
    "GroupPokeEvent",
    "GroupRecallNoticeEvent",
    "GroupTitleEvent",
    "GroupUploadFile",
    "GroupUploadNoticeEvent",
    "InputStatusEvent",
    "MsgEmojiLike",
    "NoticeEvent",
    "PokeEvent",
    "ProfileLikeEvent",
    "UnknownNoticeEvent",
    # message segments
    "MessageSegment",
    "UnknownMessageSegment",
    "MessageAt",
    "MessageContext",
    "MessageCustomMusic",
    "MessageData",
    "MessageDice",
    "MessageFace",
    "MessageFile",
    "MessageForward",
    "MessageIdMusic",
    "MessageImage",
    "MessageJson",
    "MessageMFace",
    "MessageMarkdown",
    "MessageNode",
    "MessagePoke",
    "MessageRPS",
    "MessageRecord",
    "MessageReply",
    "MessageText",
    "MessageVideo",
    "MessageSegmentType",
]
