# coding: utf-8

"""
    Skyledge API

    Sky Ledge is an operational insights platform that gives you the visibility and control you need to minimise inefficiencies, oversight, theft, and ultimately, unnecessary costs associated with your operations.

    The version of the OpenAPI document: 1.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skyledge_sdk.models.control_room_event_response import ControlRoomEventResponse

class TestControlRoomEventResponse(unittest.TestCase):
    """ControlRoomEventResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ControlRoomEventResponse:
        """Test ControlRoomEventResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ControlRoomEventResponse`
        """
        model = ControlRoomEventResponse()
        if include_optional:
            return ControlRoomEventResponse(
                id = '',
                event_type_id = '',
                title = '',
                description = '',
                importance_level = 56,
                qualifier = '',
                location = {
                    'key' : null
                    },
                created_at = '',
                last_modified_at = '',
                recorded_at = '',
                root_recorded_at = '',
                external_urls = {
                    'key' : ''
                    },
                dynamic_attributes = {
                    'key' : null
                    },
                cleared = True,
                linked_assets = [
                    skyledge_sdk.models.linked_asset_response.LinkedAssetResponse(
                        id = '', 
                        asset_identifier = '', )
                    ],
                linked_places = [
                    skyledge_sdk.models.linked_place_response.LinkedPlaceResponse(
                        id = '', 
                        place_type_id = '', 
                        place_identifier = '', 
                        place_relationship = '', )
                    ],
                state = 'ACTIVE'
            )
        else:
            return ControlRoomEventResponse(
                id = '',
                event_type_id = '',
                title = '',
                description = '',
                importance_level = 56,
                qualifier = '',
                created_at = '',
                last_modified_at = '',
                recorded_at = '',
                root_recorded_at = '',
                external_urls = {
                    'key' : ''
                    },
                dynamic_attributes = {
                    'key' : null
                    },
                cleared = True,
                linked_assets = [
                    skyledge_sdk.models.linked_asset_response.LinkedAssetResponse(
                        id = '', 
                        asset_identifier = '', )
                    ],
                linked_places = [
                    skyledge_sdk.models.linked_place_response.LinkedPlaceResponse(
                        id = '', 
                        place_type_id = '', 
                        place_identifier = '', 
                        place_relationship = '', )
                    ],
        )
        """

    def testControlRoomEventResponse(self):
        """Test ControlRoomEventResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
