from __future__ import annotations
import asyncio
from dataclasses import dataclass
from typing import Callable, Generic, TypeVar
from qtmui.redux import BaseAction
class _Waiter:
    predicate: Callable[Any, bool]
    future: asyncio.Future[A]
class ActionBus:
    def __init__(self): ...
    def publish(self, action: BaseAction): ...
    def clear(self): ...
    def add_listener(self, fn: Callable[Any, Any]): ...
    def remove_listener(self, lid: int): ...