# This file was auto-generated by Fern from our API Definition.

import typing

TransactionType = typing.Union[
    typing.Literal[
        "bankAccountToBankAccount",
        "bankAccountToMailedCheck",
        "bankAccountToPrintedCheck",
        "bankAccountToWallet",
        "cardToBankAccount",
        "cardToWallet",
        "walletToBankAccount",
        "walletToWallet",
        "custom",
        "offPlatform",
    ],
    typing.Any,
]
