from typing import Callable
from PySide6.QtWidgets import QFrame, QHBoxLayout, QSizePolicy
from PySide6.QtCore import Signal
from qtmui.hooks import State
from ..checkbox.checkbox import Checkbox
class ListItemCheckbox:
    def __init__(self, alignItems, autoFocus, children, classes, component, dense, disabled, disableGutters, divider, focusVisibleClassName, key, minHeight, onClick: Callable, selected, sx, size, parent, selectedKey: State, **kwargs): ...
    def _get_align_items_style(self, alignItems): ...
    def _apply_sx(self, sx): ...
    def focusInEvent(self, event): ...
    def mouseReleaseEvent(self, event): ...