from pydantic import GetCoreSchemaHandler as GetCoreSchemaHandler
from pydantic_core import core_schema

class ServiceIDPrefix(str):
    def __new__(cls, value: str) -> ServiceIDPrefix: ...
    @classmethod
    def __get_pydantic_core_schema__(cls, source: type, handler: GetCoreSchemaHandler) -> core_schema.CoreSchema: ...
    def match(self, value: str) -> bool: ...
