from enum import StrEnum


class Code(StrEnum):
    PROCESS_SUCCESS_CODE = "DB_0004"
    UNAUTHORIZATED_CODE = "DB_ERROR_0006"
    REQUEST_NOT_COMPLETED_CODE = "DB_ERROR_9999"
    DATA_NOT_FOUND_CODE = "DB_ERROR_0404"
    APP_ERROR_CODE = "DB_ERROR_APP"
    INVALID_REQUEST_PARAMS_CODE = "DB_WARNING_INVALID_REQUEST_PARAMS"
    MISSING_FIELD_ERROR_CODE = "DB_WARNING_MISSING_FIELD"
    DATABASE_ERROR_CODE = "DB_WARNING_DATABASE_ERROR"
    HTTP_ERROR_CODE = "DB_ERROR_HTTP"
    AZURE_ERROR_CODE = "DB_ERROR_AZURE"
    INVALID_FORMAT_CODE = "DB_WARNING_INVALID_FORMAT"
    REQUEST_VALIDATION_ERROR_CODE = "DB_WARNING_REQUEST_VALIDATION"
