"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk.models.components import (
    achwithdrawal as components_achwithdrawal,
    achwithdrawalcreate as components_achwithdrawalcreate,
    httpmetadata as components_httpmetadata,
    status as components_status,
)
from ascend_sdk.types import BaseModel
from ascend_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AchWithdrawalsCreateAchWithdrawalRequestTypedDict(TypedDict):
    account_id: str
    r"""The account id."""
    ach_withdrawal_create: components_achwithdrawalcreate.AchWithdrawalCreateTypedDict


class AchWithdrawalsCreateAchWithdrawalRequest(BaseModel):
    account_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The account id."""

    ach_withdrawal_create: Annotated[
        components_achwithdrawalcreate.AchWithdrawalCreate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class AchWithdrawalsCreateAchWithdrawalResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    ach_withdrawal: NotRequired[components_achwithdrawal.AchWithdrawalTypedDict]
    r"""OK"""
    status: NotRequired[components_status.StatusTypedDict]
    r"""INVALID_ARGUMENT: The request has an invalid argument."""


class AchWithdrawalsCreateAchWithdrawalResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    ach_withdrawal: Optional[components_achwithdrawal.AchWithdrawal] = None
    r"""OK"""

    status: Optional[components_status.Status] = None
    r"""INVALID_ARGUMENT: The request has an invalid argument."""
