"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk.models.components import (
    httpmetadata as components_httpmetadata,
    investigation as components_investigation,
    investigationupdate as components_investigationupdate,
    status as components_status,
)
from ascend_sdk.types import BaseModel
from ascend_sdk.utils import (
    FieldMetadata,
    PathParamMetadata,
    QueryParamMetadata,
    RequestMetadata,
)
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class InvestigationServiceUpdateInvestigationRequestTypedDict(TypedDict):
    investigation_id: str
    r"""The investigation id."""
    investigation_update: components_investigationupdate.InvestigationUpdateTypedDict
    update_mask: NotRequired[str]
    r"""The list of fields to update. Updatable Fields:
    - identity_verification
    - investigation_request_state
    - watchlist_matches
    - watchlist_id
    - watchlist_item_id
    - match_state
    - exclude_from_screening
    - comment
    """


class InvestigationServiceUpdateInvestigationRequest(BaseModel):
    investigation_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The investigation id."""

    investigation_update: Annotated[
        components_investigationupdate.InvestigationUpdate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    update_mask: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The list of fields to update. Updatable Fields:
    - identity_verification
    - investigation_request_state
    - watchlist_matches
    - watchlist_id
    - watchlist_item_id
    - match_state
    - exclude_from_screening
    - comment
    """


class InvestigationServiceUpdateInvestigationResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    investigation: NotRequired[components_investigation.InvestigationTypedDict]
    r"""OK"""
    status: NotRequired[components_status.StatusTypedDict]
    r"""INVALID_ARGUMENT: The request is not valid, additional information may be present in the BadRequest details.
    FAILED_PRECONDITION: The request is not valid, additional information may be present in the BadRequest details.
    """


class InvestigationServiceUpdateInvestigationResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    investigation: Optional[components_investigation.Investigation] = None
    r"""OK"""

    status: Optional[components_status.Status] = None
    r"""INVALID_ARGUMENT: The request is not valid, additional information may be present in the BadRequest details.
    FAILED_PRECONDITION: The request is not valid, additional information may be present in the BadRequest details.
    """
