import uuid
from typing import List, Union, Optional, Dict, TYPE_CHECKING, Callable
from PySide6.QtGui import QAction
from PySide6.QtWidgets import QTableWidget, QHeaderView, QWidget, QTableWidgetItem, QApplication, QTableWidget, QWidget, QTableWidgetItem, QProxyStyle, QStyleOption, QHBoxLayout
from PySide6.QtCore import Qt, Property, QRect
from typing import TYPE_CHECKING, Callable
from qtmui.hooks import useState, useEffect
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
from qtmui.material.styles import useTheme
from ....i18n.use_translation import translate, i18n
from .table_base import TableBase
class TableWidget:
    def __init__(self, fullWidth: bool, isBorderVisible: bool, tableHead: list, children: list, sortingEnabled: bool, size: str, sx: Optional[Union[Callable, str, Dict]]): ...
    def _init_ui(self): ...
    def _set_stylesheet(self, _theme): ...
    def update_data(self, rows): ...
    def setCurrentCell(self, row: int, column: int, command): ...
    def setCurrentItem(self, item: QTableWidgetItem, command): ...
    def setCurrentCell(self, row: int, column: int, command): ...
    def setCurrentItem(self, item: QTableWidgetItem, command): ...
    def isSelectRightClickedRow(self): ...
    def setSelectRightClickedRow(self, isSelect: bool): ...