# coding: utf-8

"""
    Archive ouverte UNIGE API

    Repository for UNIGE publications

    The version of the OpenAPI document: 2.2.8
    Contact: eresearch@unige.ch
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aou_api.models.search_condition import SearchCondition

class TestSearchCondition(unittest.TestCase):
    """SearchCondition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchCondition:
        """Test SearchCondition
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchCondition`
        """
        model = SearchCondition()
        if include_optional:
            return SearchCondition(
                type = 'MATCH',
                search_operator = 'AND',
                boolean_clause_type = 'MUST',
                var_field = '',
                multi_match_fields = [
                    ''
                    ],
                value = '',
                terms = [
                    ''
                    ],
                upper_value = '',
                lower_value = '',
                nested_conditions = [
                    aou_api.models.search_condition.SearchCondition(
                        type = 'MATCH', 
                        search_operator = 'AND', 
                        boolean_clause_type = 'MUST', 
                        field = '', 
                        multi_match_fields = [
                            ''
                            ], 
                        value = '', 
                        terms = [
                            ''
                            ], 
                        upper_value = '', 
                        lower_value = '', 
                        nested_conditions = [
                            aou_api.models.search_condition.SearchCondition(
                                type = 'MATCH', 
                                search_operator = 'AND', 
                                boolean_clause_type = 'MUST', 
                                field = '', 
                                value = '', 
                                upper_value = '', 
                                lower_value = '', )
                            ], )
                    ]
            )
        else:
            return SearchCondition(
        )
        """

    def testSearchCondition(self):
        """Test SearchCondition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
