[
  {
    "oid": "test_pg_gen_19877332-6fd7-455c-b7b5-9e3dc90560ac_0",
    "name": "HelloWorldApp",
    "categoryType": "Application",
    "category": "PythonApp",
    "dropclass": "dlg.apps.simple.HelloWorldApp",
    "storage": "PythonApp",
    "rank": [
      0
    ],
    "reprodata": {},
    "loop_ctx": null,
    "weight": 1,
    "num_cpus": 1,
    "applicationArgs": {
      "hello": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "09b9f140-837d-40eb-99b9-060a5559ce15",
        "name": "hello",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "OutputPort",
        "value": ""
      }
    },
    "constraintParams": {
      "execution_time": {
        "defaultValue": "0",
        "description": "Estimated execution time",
        "encoding": "pickle",
        "id": "f4298e4c-93d0-4eaf-a22a-95a5ad8714f1",
        "name": "execution_time",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Float",
        "usage": "NoPort",
        "value": 1
      },
      "num_cpus": {
        "defaultValue": "0",
        "description": "Number of cores used",
        "encoding": "pickle",
        "id": "5e8d42b7-0273-4c50-8384-b348d23f4eed",
        "name": "num_cpus",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Integer",
        "usage": "NoPort",
        "value": 1
      }
    },
    "componentParams": {
      "greet": {
        "defaultValue": "",
        "description": "What appears after 'Hello '",
        "encoding": "pickle",
        "id": "f8934cab-0c8e-4aa7-b6dc-96fa1c84de0e",
        "name": "greet",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "Everybody"
      },
      "dropclass": {
        "defaultValue": "",
        "description": "Application class",
        "encoding": "pickle",
        "id": "44bc9b98-aceb-4650-bea7-34de6dd533bf",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.apps.simple.HelloWorldApp"
      },
      "group_start": {
        "defaultValue": "false",
        "description": "Component is start of a group",
        "encoding": "pickle",
        "id": "1ca81fba-2204-467c-a53a-803422fd358f",
        "name": "group_start",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      }
    },
    "fields": [
      {
        "defaultValue": "",
        "description": "What appears after 'Hello '",
        "encoding": "pickle",
        "id": "f8934cab-0c8e-4aa7-b6dc-96fa1c84de0e",
        "name": "greet",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "Everybody"
      },
      {
        "defaultValue": "",
        "description": "Application class",
        "encoding": "pickle",
        "id": "44bc9b98-aceb-4650-bea7-34de6dd533bf",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.apps.simple.HelloWorldApp"
      },
      {
        "defaultValue": "0",
        "description": "Estimated execution time",
        "encoding": "pickle",
        "id": "f4298e4c-93d0-4eaf-a22a-95a5ad8714f1",
        "name": "execution_time",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Float",
        "usage": "NoPort",
        "value": 1
      },
      {
        "defaultValue": "0",
        "description": "Number of cores used",
        "encoding": "pickle",
        "id": "5e8d42b7-0273-4c50-8384-b348d23f4eed",
        "name": "num_cpus",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Integer",
        "usage": "NoPort",
        "value": 1
      },
      {
        "defaultValue": "false",
        "description": "Component is start of a group",
        "encoding": "pickle",
        "id": "1ca81fba-2204-467c-a53a-803422fd358f",
        "name": "group_start",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "09b9f140-837d-40eb-99b9-060a5559ce15",
        "name": "hello",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "OutputPort",
        "value": ""
      }
    ],
    "greet": "Everybody",
    "execution_time": 1,
    "group_start": false,
    "hello": "",
    "iid": "0",
    "lg_key": "19877332-6fd7-455c-b7b5-9e3dc90560ac",
    "outputPorts": {
      "09b9f140-837d-40eb-99b9-060a5559ce15": {
        "type": "OutputPort",
        "name": "hello",
        "target_id": "f3ebe6e1-7f28-4f3e-aa7c-874cd40a2a24"
      }
    },
    "inputPorts": {},
    "outputs": [
      {
        "test_pg_gen_f3ebe6e1-7f28-4f3e-aa7c-874cd40a2a24_0": "hello"
      }
    ],
    "node": "10.128.0.12",
    "island": "10.128.0.11",
    "humanReadableKey": "1_0"
  },
  {
    "oid": "test_pg_gen_f3ebe6e1-7f28-4f3e-aa7c-874cd40a2a24_0",
    "name": "hello",
    "categoryType": "Data",
    "category": "File",
    "dropclass": "dlg.data.drops.file.FileDROP",
    "storage": "File",
    "rank": [
      0
    ],
    "reprodata": {},
    "loop_ctx": null,
    "weight": 5,
    "applicationArgs": {
      "hello": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "9bf94db3-c563-4141-8dde-20b843e3d82d",
        "name": "hello",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "InputOutput",
        "value": ""
      }
    },
    "constraintParams": {
      "data_volume": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "eccb6226-9cde-448d-965f-f302e4b028d2",
        "name": "data_volume",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "5"
      }
    },
    "componentParams": {
      "dropclass": {
        "defaultValue": "",
        "description": "Data class",
        "encoding": "pickle",
        "id": "a1594e7b-b8f3-4ab3-b751-9de6164cc553",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.data.drops.file.FileDROP"
      },
      "group_end": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "bb2d3b17-a43a-4970-954d-23c8a2000814",
        "name": "group_end",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "0"
      },
      "check_filepath_exists": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "1ec0a800-01f5-4fff-a8b5-3f709db28567",
        "name": "check_filepath_exists",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "1"
      },
      "filepath": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "43018b55-80d7-4c55-86c6-d69160be0d8e",
        "name": "filepath",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "hello.txt"
      },
      "dirname": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "fd18cb97-00d4-4a19-a483-ca6e25f7e927",
        "name": "dirname",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": ""
      },
      "persist": {
        "defaultValue": "true",
        "description": "Specifies whether this data component contains data that should not be deleted after execution",
        "encoding": "pickle",
        "id": "bf71b9bc-679c-44c4-b447-1ec55117ba41",
        "name": "persist",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      }
    },
    "fields": [
      {
        "defaultValue": "",
        "description": "Data class",
        "encoding": "pickle",
        "id": "a1594e7b-b8f3-4ab3-b751-9de6164cc553",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.data.drops.file.FileDROP"
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "eccb6226-9cde-448d-965f-f302e4b028d2",
        "name": "data_volume",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "5"
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "bb2d3b17-a43a-4970-954d-23c8a2000814",
        "name": "group_end",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "0"
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "1ec0a800-01f5-4fff-a8b5-3f709db28567",
        "name": "check_filepath_exists",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "1"
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "43018b55-80d7-4c55-86c6-d69160be0d8e",
        "name": "filepath",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "hello.txt"
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "fd18cb97-00d4-4a19-a483-ca6e25f7e927",
        "name": "dirname",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": ""
      },
      {
        "defaultValue": "true",
        "description": "Specifies whether this data component contains data that should not be deleted after execution",
        "encoding": "pickle",
        "id": "bf71b9bc-679c-44c4-b447-1ec55117ba41",
        "name": "persist",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "9bf94db3-c563-4141-8dde-20b843e3d82d",
        "name": "hello",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "InputOutput",
        "value": ""
      }
    ],
    "data_volume": "5",
    "group_end": "0",
    "check_filepath_exists": "1",
    "filepath": "hello.txt",
    "dirname": "",
    "persist": false,
    "hello": "",
    "iid": "0",
    "lg_key": "f3ebe6e1-7f28-4f3e-aa7c-874cd40a2a24",
    "outputPorts": {},
    "inputPorts": {
      "9bf94db3-c563-4141-8dde-20b843e3d82d": {
        "type": "InputOutput",
        "name": "hello",
        "source_id": "19877332-6fd7-455c-b7b5-9e3dc90560ac"
      }
    },
    "port_map": {
      "hello": "hello"
    },
    "producers": [
      {
        "test_pg_gen_19877332-6fd7-455c-b7b5-9e3dc90560ac_0": "hello"
      }
    ],
    "node": "10.128.0.12",
    "island": "10.128.0.11",
    "humanReadableKey": "2_0"
  }
]