[
  {
    "oid": "test_pg_gen_e7c8f312-d267-4837-b29c-69c5f8bfb0dc_0",
    "name": "glob",
    "categoryType": "Application",
    "category": "PythonApp",
    "dropclass": "dlg.apps.pyfunc.PyFuncApp",
    "storage": "PythonApp",
    "rank": [
      0
    ],
    "reprodata": {},
    "loop_ctx": null,
    "weight": 5,
    "num_cpus": 1,
    "applicationArgs": {
      "func_name": {
        "defaultValue": "",
        "description": "Python function name",
        "encoding": "pickle",
        "id": "ea7b23bb-eb5d-48b4-a631-6224178a9b92",
        "name": "func_name",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "glob.glob"
      },
      "func_code": {
        "defaultValue": "",
        "description": "Python function code, e.g. 'def function_name(args): return args'",
        "encoding": "pickle",
        "id": "d69fe71d-b9fe-41ff-90fa-de1cbeb6b3c7",
        "name": "func_code",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      "input_parser": {
        "defaultValue": "pickle",
        "description": "Input port parsing technique",
        "encoding": "pickle",
        "id": "06226ab1-8b6e-44d1-b865-d803dba800be",
        "name": "input_parser",
        "options": [
          "pickle",
          "eval",
          "npy",
          "path",
          "dataurl"
        ],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Select",
        "usage": "NoPort",
        "value": "eval"
      },
      "output_parser": {
        "defaultValue": "",
        "description": "output port parsing technique",
        "encoding": "pickle",
        "id": "1b40a8ec-6dc7-4b43-8a10-7ea64d583195",
        "name": "output_parser",
        "options": [
          "",
          "pickle",
          "eval",
          "npy"
        ],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Select",
        "usage": "NoPort",
        "value": "eval"
      },
      "pathname": {
        "defaultValue": "",
        "description": "",
        "encoding": "utf-8",
        "id": "f82a000e-8cae-4cce-8f3c-d8b79fbd3d39",
        "name": "pathname",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "InputPort",
        "value": ""
      },
      "recursive": {
        "defaultValue": "false",
        "description": "",
        "encoding": "utf-8",
        "id": "a27dc73b-201d-40c0-8c02-4a8da9f4a455",
        "name": "recursive",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "InputPort",
        "value": false
      }
    },
    "constraintParams": {
      "execution_time": {
        "defaultValue": "0",
        "description": "Estimated execution time",
        "encoding": "pickle",
        "id": "726ef150-d760-4e7e-b929-c764635dff5f",
        "name": "execution_time",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "Float",
        "usage": "NoPort",
        "value": 5
      },
      "num_cpus": {
        "defaultValue": "0",
        "description": "Number of cores used",
        "encoding": "pickle",
        "id": "3811a1ab-62a6-4b52-985f-3c615fad7ac8",
        "name": "num_cpus",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "Integer",
        "usage": "NoPort",
        "value": 1
      }
    },
    "componentParams": {
      "persist": {
        "defaultValue": "false",
        "description": "Specifies whether this data component contains data that should not be deleted after execution",
        "encoding": "pickle",
        "id": "84241283-d3f6-4489-b501-7b039b810b32",
        "name": "persist",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      "streaming": {
        "defaultValue": "false",
        "description": "Specifies whether this data component streams input and output data",
        "encoding": "pickle",
        "id": "2a8130eb-a14b-4f3c-b87a-65253d12acb7",
        "name": "streaming",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      "dropclass": {
        "defaultValue": "",
        "description": "Application class",
        "encoding": "pickle",
        "id": "ec1638fa-bc97-4ee5-b5f5-61811cd9c469",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.apps.pyfunc.PyFuncApp"
      },
      "group_start": {
        "defaultValue": "false",
        "description": "Is this node the start of a group?",
        "encoding": "pickle",
        "id": "a7f1c2f8-178c-43c6-a02e-50189c1d013a",
        "name": "group_start",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      "input_error_threshold": {
        "defaultValue": "0",
        "description": "The allowed failure rate of the inputs (in percent), before this component goes to ERROR state and is not executed",
        "encoding": "pickle",
        "id": "f54ad120-b068-4509-a7dc-122d78f0fd8c",
        "name": "input_error_threshold",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Integer",
        "usage": "NoPort",
        "value": 0
      },
      "n_tries": {
        "defaultValue": "0",
        "description": "Specifies the number of times the 'run' method will be executed before finally giving up",
        "encoding": "pickle",
        "id": "d89115e5-fa9e-4fc3-b0ce-ae6e0d1623e5",
        "name": "n_tries",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Integer",
        "usage": "NoPort",
        "value": 1
      },
      "content": {
        "defaultValue": "",
        "description": "",
        "encoding": "utf-8",
        "id": "8b8bf43c-ecd9-4bb9-b196-00fe5d107628",
        "name": "content",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "OutputPort",
        "value": ""
      }
    },
    "fields": [
      {
        "defaultValue": "false",
        "description": "Specifies whether this data component contains data that should not be deleted after execution",
        "encoding": "pickle",
        "id": "84241283-d3f6-4489-b501-7b039b810b32",
        "name": "persist",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      {
        "defaultValue": "false",
        "description": "Specifies whether this data component streams input and output data",
        "encoding": "pickle",
        "id": "2a8130eb-a14b-4f3c-b87a-65253d12acb7",
        "name": "streaming",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      {
        "defaultValue": "",
        "description": "Application class",
        "encoding": "pickle",
        "id": "ec1638fa-bc97-4ee5-b5f5-61811cd9c469",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.apps.pyfunc.PyFuncApp"
      },
      {
        "defaultValue": "0",
        "description": "Estimated execution time",
        "encoding": "pickle",
        "id": "726ef150-d760-4e7e-b929-c764635dff5f",
        "name": "execution_time",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "Float",
        "usage": "NoPort",
        "value": 5
      },
      {
        "defaultValue": "0",
        "description": "Number of cores used",
        "encoding": "pickle",
        "id": "3811a1ab-62a6-4b52-985f-3c615fad7ac8",
        "name": "num_cpus",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "Integer",
        "usage": "NoPort",
        "value": 1
      },
      {
        "defaultValue": "false",
        "description": "Is this node the start of a group?",
        "encoding": "pickle",
        "id": "a7f1c2f8-178c-43c6-a02e-50189c1d013a",
        "name": "group_start",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      {
        "defaultValue": "0",
        "description": "The allowed failure rate of the inputs (in percent), before this component goes to ERROR state and is not executed",
        "encoding": "pickle",
        "id": "f54ad120-b068-4509-a7dc-122d78f0fd8c",
        "name": "input_error_threshold",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Integer",
        "usage": "NoPort",
        "value": 0
      },
      {
        "defaultValue": "0",
        "description": "Specifies the number of times the 'run' method will be executed before finally giving up",
        "encoding": "pickle",
        "id": "d89115e5-fa9e-4fc3-b0ce-ae6e0d1623e5",
        "name": "n_tries",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Integer",
        "usage": "NoPort",
        "value": 1
      },
      {
        "defaultValue": "",
        "description": "Python function name",
        "encoding": "pickle",
        "id": "ea7b23bb-eb5d-48b4-a631-6224178a9b92",
        "name": "func_name",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "glob.glob"
      },
      {
        "defaultValue": "",
        "description": "Python function code, e.g. 'def function_name(args): return args'",
        "encoding": "pickle",
        "id": "d69fe71d-b9fe-41ff-90fa-de1cbeb6b3c7",
        "name": "func_code",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      {
        "defaultValue": "pickle",
        "description": "Input port parsing technique",
        "encoding": "pickle",
        "id": "06226ab1-8b6e-44d1-b865-d803dba800be",
        "name": "input_parser",
        "options": [
          "pickle",
          "eval",
          "npy",
          "path",
          "dataurl"
        ],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Select",
        "usage": "NoPort",
        "value": "eval"
      },
      {
        "defaultValue": "",
        "description": "output port parsing technique",
        "encoding": "pickle",
        "id": "1b40a8ec-6dc7-4b43-8a10-7ea64d583195",
        "name": "output_parser",
        "options": [
          "",
          "pickle",
          "eval",
          "npy"
        ],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Select",
        "usage": "NoPort",
        "value": "eval"
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "utf-8",
        "id": "f82a000e-8cae-4cce-8f3c-d8b79fbd3d39",
        "name": "pathname",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "InputPort",
        "value": ""
      },
      {
        "defaultValue": "false",
        "description": "",
        "encoding": "utf-8",
        "id": "a27dc73b-201d-40c0-8c02-4a8da9f4a455",
        "name": "recursive",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "InputPort",
        "value": false
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "utf-8",
        "id": "8b8bf43c-ecd9-4bb9-b196-00fe5d107628",
        "name": "content",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "OutputPort",
        "value": ""
      }
    ],
    "persist": false,
    "streaming": false,
    "execution_time": 5,
    "group_start": false,
    "input_error_threshold": 0,
    "n_tries": 1,
    "func_name": "glob.glob",
    "func_code": "",
    "input_parser": "eval",
    "output_parser": "eval",
    "pathname": "",
    "recursive": false,
    "content": "",
    "iid": "0",
    "lg_key": "e7c8f312-d267-4837-b29c-69c5f8bfb0dc",
    "outputPorts": {
      "8b8bf43c-ecd9-4bb9-b196-00fe5d107628": {
        "type": "OutputPort",
        "name": "content",
        "target_id": "4f9c0432-2515-4e38-8dcb-61d968d981cc"
      }
    },
    "inputPorts": {
      "f82a000e-8cae-4cce-8f3c-d8b79fbd3d39": {
        "type": "InputPort",
        "name": "pathname",
        "source_id": "90756f41-6b98-42b5-9570-b5f2658be497"
      },
      "a27dc73b-201d-40c0-8c02-4a8da9f4a455": {
        "type": "InputPort",
        "name": "recursive",
        "source_id": "230ed0fa-2d23-4177-913c-091386addbc2"
      }
    },
    "inputs": [
      {
        "test_pg_gen_90756f41-6b98-42b5-9570-b5f2658be497_0": "pathname"
      },
      {
        "test_pg_gen_230ed0fa-2d23-4177-913c-091386addbc2_0": "recursive"
      }
    ],
    "outputs": [
      {
        "test_pg_gen_4f9c0432-2515-4e38-8dcb-61d968d981cc_0": "content"
      }
    ],
    "node": "10.128.0.12",
    "island": "10.128.0.11",
    "humanReadableKey": "1_0"
  },
  {
    "oid": "test_pg_gen_230ed0fa-2d23-4177-913c-091386addbc2_0",
    "name": "recursive",
    "categoryType": "Data",
    "category": "File",
    "dropclass": "dlg.data.drops.file.FileDROP",
    "storage": "File",
    "rank": [
      0
    ],
    "reprodata": {},
    "loop_ctx": null,
    "weight": 5,
    "applicationArgs": {
      "recursive": {
        "defaultValue": "false",
        "description": "",
        "encoding": "pickle",
        "id": "c3441383-e511-4899-bfe7-fc27e46a9dc7",
        "name": "recursive",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "InputOutput",
        "value": false
      }
    },
    "constraintParams": {
      "data_volume": {
        "defaultValue": "0",
        "description": "Estimated size of the data contained in this node",
        "encoding": "pickle",
        "id": "6bd3e835-4e12-4005-94c0-156cf4f01aac",
        "name": "data_volume",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Float",
        "usage": "NoPort",
        "value": 5
      }
    },
    "componentParams": {
      "persist": {
        "defaultValue": "false",
        "description": "Specifies whether this data component contains data that should not be deleted after execution",
        "encoding": "pickle",
        "id": "d85ea11d-64b5-4dfe-9249-2b89aa18045d",
        "name": "persist",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      "streaming": {
        "defaultValue": "false",
        "description": "Specifies whether this data component streams input and output data",
        "encoding": "pickle",
        "id": "5bb622c3-27a5-4b12-8f60-a5e8b87518c6",
        "name": "streaming",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      "group_end": {
        "defaultValue": "false",
        "description": "Is this node the end of a group?",
        "encoding": "pickle",
        "id": "d08c4c93-d74a-4aab-bf72-b56cfe441825",
        "name": "group_end",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": true,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      "check_filepath_exists": {
        "defaultValue": "false",
        "description": "Perform a check to make sure the file path exists before proceeding with the application",
        "encoding": "pickle",
        "id": "22bf6813-77bf-41f9-8014-97ff24cf362a",
        "name": "check_filepath_exists",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      "filepath": {
        "defaultValue": "",
        "description": "Path to the file for this node",
        "encoding": "pickle",
        "id": "0bee18c6-4089-4e37-8a3e-ccaa066993ce",
        "name": "filepath",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      "dirname": {
        "defaultValue": "",
        "description": "Path to the file for this node",
        "encoding": "pickle",
        "id": "9dd731ac-1852-45bd-977f-5a4c4d6c1499",
        "name": "dirname",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      "dropclass": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "dea4a767-0f08-4921-bf49-58c1349f1733",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.data.drops.file.FileDROP"
      }
    },
    "fields": [
      {
        "defaultValue": "false",
        "description": "Specifies whether this data component contains data that should not be deleted after execution",
        "encoding": "pickle",
        "id": "d85ea11d-64b5-4dfe-9249-2b89aa18045d",
        "name": "persist",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      {
        "defaultValue": "false",
        "description": "Specifies whether this data component streams input and output data",
        "encoding": "pickle",
        "id": "5bb622c3-27a5-4b12-8f60-a5e8b87518c6",
        "name": "streaming",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      {
        "defaultValue": "0",
        "description": "Estimated size of the data contained in this node",
        "encoding": "pickle",
        "id": "6bd3e835-4e12-4005-94c0-156cf4f01aac",
        "name": "data_volume",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Float",
        "usage": "NoPort",
        "value": 5
      },
      {
        "defaultValue": "false",
        "description": "Is this node the end of a group?",
        "encoding": "pickle",
        "id": "d08c4c93-d74a-4aab-bf72-b56cfe441825",
        "name": "group_end",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": true,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      {
        "defaultValue": "false",
        "description": "Perform a check to make sure the file path exists before proceeding with the application",
        "encoding": "pickle",
        "id": "22bf6813-77bf-41f9-8014-97ff24cf362a",
        "name": "check_filepath_exists",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      {
        "defaultValue": "",
        "description": "Path to the file for this node",
        "encoding": "pickle",
        "id": "0bee18c6-4089-4e37-8a3e-ccaa066993ce",
        "name": "filepath",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      {
        "defaultValue": "",
        "description": "Path to the file for this node",
        "encoding": "pickle",
        "id": "9dd731ac-1852-45bd-977f-5a4c4d6c1499",
        "name": "dirname",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      {
        "defaultValue": "false",
        "description": "",
        "encoding": "pickle",
        "id": "c3441383-e511-4899-bfe7-fc27e46a9dc7",
        "name": "recursive",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "InputOutput",
        "value": false
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "dea4a767-0f08-4921-bf49-58c1349f1733",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.data.drops.file.FileDROP"
      }
    ],
    "persist": false,
    "streaming": false,
    "data_volume": 5,
    "group_end": false,
    "check_filepath_exists": false,
    "filepath": "",
    "dirname": "",
    "recursive": false,
    "iid": "0",
    "lg_key": "230ed0fa-2d23-4177-913c-091386addbc2",
    "outputPorts": {},
    "inputPorts": {
      "c3441383-e511-4899-bfe7-fc27e46a9dc7": {
        "type": "InputOutput",
        "name": "recursive",
        "source_id": "92d00e38-4875-45a2-ad97-01e39fc2d1dd"
      }
    },
    "port_map": {
      "recursive": "recursive"
    },
    "producers": [
      {
        "test_pg_gen_92d00e38-4875-45a2-ad97-01e39fc2d1dd_0": "recursive"
      }
    ],
    "consumers": [
      {
        "test_pg_gen_e7c8f312-d267-4837-b29c-69c5f8bfb0dc_0": "recursive"
      }
    ],
    "node": "10.128.0.12",
    "island": "10.128.0.11",
    "humanReadableKey": "2_0"
  },
  {
    "oid": "test_pg_gen_92d00e38-4875-45a2-ad97-01e39fc2d1dd_0",
    "name": "generate",
    "categoryType": "Application",
    "category": "BashShellApp",
    "dropclass": "dlg.apps.bash_shell_app.BashShellApp",
    "storage": "BashShellApp",
    "rank": [
      0
    ],
    "reprodata": {},
    "loop_ctx": null,
    "weight": 5,
    "num_cpus": 1,
    "applicationArgs": {
      "recursive": {
        "defaultValue": "false",
        "description": "",
        "encoding": "path",
        "id": "84777fe6-f52c-4dac-a270-e602d7e91258",
        "name": "recursive",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": true,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "OutputPort",
        "value": false
      }
    },
    "constraintParams": {
      "execution_time": {
        "defaultValue": "0",
        "description": "Estimated execution time",
        "encoding": "pickle",
        "id": "7e0f6d2e-4ca1-46e5-b367-bf6235350af3",
        "name": "execution_time",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "Float",
        "usage": "NoPort",
        "value": 5
      },
      "num_cpus": {
        "defaultValue": "0",
        "description": "Number of cores used",
        "encoding": "pickle",
        "id": "90b6b10b-e0a0-4d2b-841d-ef5cc9e760ce",
        "name": "num_cpus",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "Integer",
        "usage": "NoPort",
        "value": 1
      }
    },
    "componentParams": {
      "persist": {
        "defaultValue": "false",
        "description": "Specifies whether this data component contains data that should not be deleted after execution",
        "encoding": "pickle",
        "id": "ffed3d6c-8fc3-483e-b17e-9a82e0bea1a9",
        "name": "persist",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      "streaming": {
        "defaultValue": "false",
        "description": "Specifies whether this data component streams input and output data",
        "encoding": "pickle",
        "id": "ca3acee1-37bf-4273-8367-5fd44de3a37c",
        "name": "streaming",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      "command": {
        "defaultValue": "",
        "description": "The command to be executed",
        "encoding": "pickle",
        "id": "8cb23a9d-ac5f-4b36-93f5-822dcf926ebf",
        "name": "command",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "echo \"True\" > {recursive}"
      },
      "input_redirection": {
        "defaultValue": "",
        "description": "The command line argument that specifies the input into this application",
        "encoding": "pickle",
        "id": "376a64bf-d69a-4a36-88fa-197696c2a3c3",
        "name": "input_redirection",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      "output_redirection": {
        "defaultValue": "",
        "description": "The command line argument that specifies the output from this application",
        "encoding": "pickle",
        "id": "d7db3c01-ccbc-48f6-a921-02019db7961a",
        "name": "output_redirection",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      "command_line_arguments": {
        "defaultValue": "",
        "description": "Additional command line arguments to be added to the command line to be executed",
        "encoding": "pickle",
        "id": "167dc56d-5881-408a-bc35-19471aa6ac42",
        "name": "command_line_arguments",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      "paramValueSeparator": {
        "defaultValue": "",
        "description": "Separator character(s) between parameters on the command line",
        "encoding": "pickle",
        "id": "260c81e0-b6a6-4326-8ebd-73399b8d9831",
        "name": "paramValueSeparator",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": " "
      },
      "argumentPrefix": {
        "defaultValue": "",
        "description": "Prefix to each keyed argument on the command line",
        "encoding": "pickle",
        "id": "931b5c12-d49f-42b5-9247-1807999a1ad8",
        "name": "argumentPrefix",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "--"
      },
      "group_start": {
        "defaultValue": "false",
        "description": "Is this node the start of a group?",
        "encoding": "pickle",
        "id": "e8b6e543-290d-433d-b7c8-fc310d9e9f5b",
        "name": "group_start",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      "dropclass": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "d7bb52fe-6473-4b95-a627-bc78dc3f1519",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.apps.bash_shell_app.BashShellApp"
      }
    },
    "fields": [
      {
        "defaultValue": "false",
        "description": "Specifies whether this data component contains data that should not be deleted after execution",
        "encoding": "pickle",
        "id": "ffed3d6c-8fc3-483e-b17e-9a82e0bea1a9",
        "name": "persist",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      {
        "defaultValue": "false",
        "description": "Specifies whether this data component streams input and output data",
        "encoding": "pickle",
        "id": "ca3acee1-37bf-4273-8367-5fd44de3a37c",
        "name": "streaming",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      {
        "defaultValue": "",
        "description": "The command to be executed",
        "encoding": "pickle",
        "id": "8cb23a9d-ac5f-4b36-93f5-822dcf926ebf",
        "name": "command",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "echo \"True\" > {recursive}"
      },
      {
        "defaultValue": "false",
        "description": "",
        "encoding": "path",
        "id": "84777fe6-f52c-4dac-a270-e602d7e91258",
        "name": "recursive",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": true,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "OutputPort",
        "value": false
      },
      {
        "defaultValue": "",
        "description": "The command line argument that specifies the input into this application",
        "encoding": "pickle",
        "id": "376a64bf-d69a-4a36-88fa-197696c2a3c3",
        "name": "input_redirection",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      {
        "defaultValue": "",
        "description": "The command line argument that specifies the output from this application",
        "encoding": "pickle",
        "id": "d7db3c01-ccbc-48f6-a921-02019db7961a",
        "name": "output_redirection",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      {
        "defaultValue": "",
        "description": "Additional command line arguments to be added to the command line to be executed",
        "encoding": "pickle",
        "id": "167dc56d-5881-408a-bc35-19471aa6ac42",
        "name": "command_line_arguments",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      {
        "defaultValue": "",
        "description": "Separator character(s) between parameters on the command line",
        "encoding": "pickle",
        "id": "260c81e0-b6a6-4326-8ebd-73399b8d9831",
        "name": "paramValueSeparator",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": " "
      },
      {
        "defaultValue": "",
        "description": "Prefix to each keyed argument on the command line",
        "encoding": "pickle",
        "id": "931b5c12-d49f-42b5-9247-1807999a1ad8",
        "name": "argumentPrefix",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "--"
      },
      {
        "defaultValue": "0",
        "description": "Estimated execution time",
        "encoding": "pickle",
        "id": "7e0f6d2e-4ca1-46e5-b367-bf6235350af3",
        "name": "execution_time",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "Float",
        "usage": "NoPort",
        "value": 5
      },
      {
        "defaultValue": "0",
        "description": "Number of cores used",
        "encoding": "pickle",
        "id": "90b6b10b-e0a0-4d2b-841d-ef5cc9e760ce",
        "name": "num_cpus",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "Integer",
        "usage": "NoPort",
        "value": 1
      },
      {
        "defaultValue": "false",
        "description": "Is this node the start of a group?",
        "encoding": "pickle",
        "id": "e8b6e543-290d-433d-b7c8-fc310d9e9f5b",
        "name": "group_start",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "d7bb52fe-6473-4b95-a627-bc78dc3f1519",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.apps.bash_shell_app.BashShellApp"
      }
    ],
    "persist": false,
    "streaming": false,
    "command": "echo \"True\" > {recursive}",
    "recursive": false,
    "input_redirection": "",
    "output_redirection": "",
    "command_line_arguments": "",
    "paramValueSeparator": " ",
    "argumentPrefix": "--",
    "execution_time": 5,
    "group_start": false,
    "iid": "0",
    "lg_key": "92d00e38-4875-45a2-ad97-01e39fc2d1dd",
    "outputPorts": {
      "84777fe6-f52c-4dac-a270-e602d7e91258": {
        "type": "OutputPort",
        "name": "recursive",
        "target_id": "230ed0fa-2d23-4177-913c-091386addbc2"
      }
    },
    "inputPorts": {},
    "outputs": [
      {
        "test_pg_gen_230ed0fa-2d23-4177-913c-091386addbc2_0": "recursive"
      }
    ],
    "node": "10.128.0.12",
    "island": "10.128.0.11",
    "humanReadableKey": "3_0"
  },
  {
    "oid": "test_pg_gen_b988ed98-e11b-4bcb-b561-d90ead73debe_0",
    "name": "output",
    "categoryType": "Application",
    "category": "BashShellApp",
    "dropclass": "dlg.apps.bash_shell_app.BashShellApp",
    "storage": "BashShellApp",
    "rank": [
      0
    ],
    "reprodata": {},
    "loop_ctx": null,
    "weight": 5,
    "num_cpus": 1,
    "applicationArgs": {
      "input_redirection": {
        "defaultValue": "",
        "description": "The command line argument that specifies the input into this application",
        "encoding": "pickle",
        "id": "09d0e983-ea4a-4b5e-b5cc-f2dc4be39033",
        "name": "input_redirection",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      "content": {
        "defaultValue": "",
        "description": "",
        "encoding": "path",
        "id": "3a2e3ac4-f343-46bb-ad65-9e87fe22c88e",
        "name": "content",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": true,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "InputOutput",
        "value": ""
      }
    },
    "constraintParams": {
      "execution_time": {
        "defaultValue": "0",
        "description": "Estimated execution time",
        "encoding": "pickle",
        "id": "3d992e3b-7def-4320-bd56-64b300a52e27",
        "name": "execution_time",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "Float",
        "usage": "NoPort",
        "value": 5
      },
      "num_cpus": {
        "defaultValue": "0",
        "description": "Number of cores used",
        "encoding": "pickle",
        "id": "d60e43fa-1a95-4124-995a-79d6551c2ddd",
        "name": "num_cpus",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "Integer",
        "usage": "NoPort",
        "value": 1
      }
    },
    "componentParams": {
      "persist": {
        "defaultValue": "false",
        "description": "Specifies whether this data component contains data that should not be deleted after execution",
        "encoding": "pickle",
        "id": "8dc25832-7230-44b6-a557-c664e176a07d",
        "name": "persist",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      "streaming": {
        "defaultValue": "false",
        "description": "Specifies whether this data component streams input and output data",
        "encoding": "pickle",
        "id": "aff341ba-e0ea-4aaf-bbed-2adcdf1d7865",
        "name": "streaming",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      "command": {
        "defaultValue": "",
        "description": "The command to be executed",
        "encoding": "pickle",
        "id": "46ab01db-3289-4b2f-a84a-741772544bcb",
        "name": "command",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "cat {content}"
      },
      "output_redirection": {
        "defaultValue": "",
        "description": "The command line argument that specifies the output from this application",
        "encoding": "pickle",
        "id": "d22b5628-f846-4403-87a1-d09a7b30ba66",
        "name": "output_redirection",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      "command_line_arguments": {
        "defaultValue": "",
        "description": "Additional command line arguments to be added to the command line to be executed",
        "encoding": "pickle",
        "id": "2fd26094-d7b1-49cc-83ad-c53bb2868e2f",
        "name": "command_line_arguments",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      "paramValueSeparator": {
        "defaultValue": "",
        "description": "Separator character(s) between parameters on the command line",
        "encoding": "pickle",
        "id": "30d0d15d-7470-4741-9456-d81919e42b57",
        "name": "paramValueSeparator",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": " "
      },
      "argumentPrefix": {
        "defaultValue": "",
        "description": "Prefix to each keyed argument on the command line",
        "encoding": "pickle",
        "id": "7133e918-0863-42af-b469-c4cf5f69418f",
        "name": "argumentPrefix",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "--"
      },
      "group_start": {
        "defaultValue": "false",
        "description": "Is this node the start of a group?",
        "encoding": "pickle",
        "id": "bb59ca03-989b-4bc8-a960-324bdbd15ccd",
        "name": "group_start",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      "input_error_threshold": {
        "defaultValue": "0",
        "description": "the allowed failure rate of the inputs (in percent), before this component goes to ERROR state and is not executed",
        "encoding": "pickle",
        "id": "c2fc8700-9156-4a8f-bf0a-98351261adab",
        "name": "input_error_threshold",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Integer",
        "usage": "NoPort",
        "value": 0
      },
      "n_tries": {
        "defaultValue": "0",
        "description": "Specifies the number of times the 'run' method will be executed before finally giving up",
        "encoding": "pickle",
        "id": "c79c6ea9-4450-46fc-998d-0b793be13c9c",
        "name": "n_tries",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Integer",
        "usage": "NoPort",
        "value": 1
      },
      "dropclass": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "9f16b288-2e64-44ee-8094-8b184094a1be",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.apps.bash_shell_app.BashShellApp"
      }
    },
    "fields": [
      {
        "defaultValue": "false",
        "description": "Specifies whether this data component contains data that should not be deleted after execution",
        "encoding": "pickle",
        "id": "8dc25832-7230-44b6-a557-c664e176a07d",
        "name": "persist",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      {
        "defaultValue": "false",
        "description": "Specifies whether this data component streams input and output data",
        "encoding": "pickle",
        "id": "aff341ba-e0ea-4aaf-bbed-2adcdf1d7865",
        "name": "streaming",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      {
        "defaultValue": "",
        "description": "The command to be executed",
        "encoding": "pickle",
        "id": "46ab01db-3289-4b2f-a84a-741772544bcb",
        "name": "command",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "cat {content}"
      },
      {
        "defaultValue": "",
        "description": "The command line argument that specifies the input into this application",
        "encoding": "pickle",
        "id": "09d0e983-ea4a-4b5e-b5cc-f2dc4be39033",
        "name": "input_redirection",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      {
        "defaultValue": "",
        "description": "The command line argument that specifies the output from this application",
        "encoding": "pickle",
        "id": "d22b5628-f846-4403-87a1-d09a7b30ba66",
        "name": "output_redirection",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      {
        "defaultValue": "",
        "description": "Additional command line arguments to be added to the command line to be executed",
        "encoding": "pickle",
        "id": "2fd26094-d7b1-49cc-83ad-c53bb2868e2f",
        "name": "command_line_arguments",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      {
        "defaultValue": "",
        "description": "Separator character(s) between parameters on the command line",
        "encoding": "pickle",
        "id": "30d0d15d-7470-4741-9456-d81919e42b57",
        "name": "paramValueSeparator",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": " "
      },
      {
        "defaultValue": "",
        "description": "Prefix to each keyed argument on the command line",
        "encoding": "pickle",
        "id": "7133e918-0863-42af-b469-c4cf5f69418f",
        "name": "argumentPrefix",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "--"
      },
      {
        "defaultValue": "0",
        "description": "Estimated execution time",
        "encoding": "pickle",
        "id": "3d992e3b-7def-4320-bd56-64b300a52e27",
        "name": "execution_time",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "Float",
        "usage": "NoPort",
        "value": 5
      },
      {
        "defaultValue": "0",
        "description": "Number of cores used",
        "encoding": "pickle",
        "id": "d60e43fa-1a95-4124-995a-79d6551c2ddd",
        "name": "num_cpus",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "Integer",
        "usage": "NoPort",
        "value": 1
      },
      {
        "defaultValue": "false",
        "description": "Is this node the start of a group?",
        "encoding": "pickle",
        "id": "bb59ca03-989b-4bc8-a960-324bdbd15ccd",
        "name": "group_start",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      {
        "defaultValue": "0",
        "description": "the allowed failure rate of the inputs (in percent), before this component goes to ERROR state and is not executed",
        "encoding": "pickle",
        "id": "c2fc8700-9156-4a8f-bf0a-98351261adab",
        "name": "input_error_threshold",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Integer",
        "usage": "NoPort",
        "value": 0
      },
      {
        "defaultValue": "0",
        "description": "Specifies the number of times the 'run' method will be executed before finally giving up",
        "encoding": "pickle",
        "id": "c79c6ea9-4450-46fc-998d-0b793be13c9c",
        "name": "n_tries",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Integer",
        "usage": "NoPort",
        "value": 1
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "path",
        "id": "3a2e3ac4-f343-46bb-ad65-9e87fe22c88e",
        "name": "content",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": true,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "InputOutput",
        "value": ""
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "9f16b288-2e64-44ee-8094-8b184094a1be",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.apps.bash_shell_app.BashShellApp"
      }
    ],
    "persist": false,
    "streaming": false,
    "command": "cat {content}",
    "input_redirection": "",
    "output_redirection": "",
    "command_line_arguments": "",
    "paramValueSeparator": " ",
    "argumentPrefix": "--",
    "execution_time": 5,
    "group_start": false,
    "input_error_threshold": 0,
    "n_tries": 1,
    "content": "",
    "iid": "0",
    "lg_key": "b988ed98-e11b-4bcb-b561-d90ead73debe",
    "outputPorts": {},
    "inputPorts": {
      "3a2e3ac4-f343-46bb-ad65-9e87fe22c88e": {
        "type": "InputOutput",
        "name": "content",
        "source_id": "4f9c0432-2515-4e38-8dcb-61d968d981cc"
      }
    },
    "inputs": [
      {
        "test_pg_gen_4f9c0432-2515-4e38-8dcb-61d968d981cc_0": "content"
      }
    ],
    "node": "10.128.0.12",
    "island": "10.128.0.11",
    "humanReadableKey": "4_0"
  },
  {
    "oid": "test_pg_gen_90756f41-6b98-42b5-9570-b5f2658be497_0",
    "name": "pathname",
    "categoryType": "Data",
    "category": "File",
    "dropclass": "dlg.data.drops.file.FileDROP",
    "storage": "File",
    "rank": [
      0
    ],
    "reprodata": {},
    "loop_ctx": null,
    "weight": 5,
    "applicationArgs": {
      "content": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "a64b0f82-9f7f-40dc-b3bf-ecab0632cde3",
        "name": "content",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "InputPort",
        "value": ""
      },
      "pathname": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "eaf21119-5bc7-45b1-980d-d6c6d428dedc",
        "name": "pathname",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "OutputPort",
        "value": ""
      }
    },
    "constraintParams": {
      "data_volume": {
        "defaultValue": "0",
        "description": "Estimated size of the data contained in this node",
        "encoding": "pickle",
        "id": "cf0c326c-3a34-423b-a807-959faa909410",
        "name": "data_volume",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Float",
        "usage": "NoPort",
        "value": 5
      }
    },
    "componentParams": {
      "persist": {
        "defaultValue": "false",
        "description": "Specifies whether this data component contains data that should not be deleted after execution",
        "encoding": "pickle",
        "id": "130eb270-d782-4a54-86fb-39b76914b2f6",
        "name": "persist",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      "streaming": {
        "defaultValue": "false",
        "description": "Specifies whether this data component streams input and output data",
        "encoding": "pickle",
        "id": "d7cd1f3b-3a54-45d6-a7a1-3026d66cf2a5",
        "name": "streaming",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      "group_end": {
        "defaultValue": "false",
        "description": "Is this node the end of a group?",
        "encoding": "pickle",
        "id": "78dfda0d-4e08-49ca-a330-814e8eb70dde",
        "name": "group_end",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      "dropclass": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "1d6ea47f-3868-4920-b3dc-0771dd22089c",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.data.drops.file.FileDROP"
      }
    },
    "fields": [
      {
        "defaultValue": "false",
        "description": "Specifies whether this data component contains data that should not be deleted after execution",
        "encoding": "pickle",
        "id": "130eb270-d782-4a54-86fb-39b76914b2f6",
        "name": "persist",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      {
        "defaultValue": "false",
        "description": "Specifies whether this data component streams input and output data",
        "encoding": "pickle",
        "id": "d7cd1f3b-3a54-45d6-a7a1-3026d66cf2a5",
        "name": "streaming",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      {
        "defaultValue": "0",
        "description": "Estimated size of the data contained in this node",
        "encoding": "pickle",
        "id": "cf0c326c-3a34-423b-a807-959faa909410",
        "name": "data_volume",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Float",
        "usage": "NoPort",
        "value": 5
      },
      {
        "defaultValue": "false",
        "description": "Is this node the end of a group?",
        "encoding": "pickle",
        "id": "78dfda0d-4e08-49ca-a330-814e8eb70dde",
        "name": "group_end",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "a64b0f82-9f7f-40dc-b3bf-ecab0632cde3",
        "name": "content",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "InputPort",
        "value": ""
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "eaf21119-5bc7-45b1-980d-d6c6d428dedc",
        "name": "pathname",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "OutputPort",
        "value": ""
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "1d6ea47f-3868-4920-b3dc-0771dd22089c",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.data.drops.file.FileDROP"
      }
    ],
    "persist": false,
    "streaming": false,
    "data_volume": 5,
    "group_end": false,
    "content": "",
    "pathname": "",
    "iid": "0",
    "lg_key": "90756f41-6b98-42b5-9570-b5f2658be497",
    "outputPorts": {
      "eaf21119-5bc7-45b1-980d-d6c6d428dedc": {
        "type": "OutputPort",
        "name": "pathname",
        "target_id": "e7c8f312-d267-4837-b29c-69c5f8bfb0dc"
      }
    },
    "inputPorts": {
      "a64b0f82-9f7f-40dc-b3bf-ecab0632cde3": {
        "type": "InputPort",
        "name": "content",
        "source_id": "d82796af-40ef-4d07-b5c8-423714511c73"
      }
    },
    "port_map": {
      "content": "content"
    },
    "producers": [
      {
        "test_pg_gen_d82796af-40ef-4d07-b5c8-423714511c73_0": "content"
      }
    ],
    "consumers": [
      {
        "test_pg_gen_e7c8f312-d267-4837-b29c-69c5f8bfb0dc_0": "pathname"
      }
    ],
    "node": "10.128.0.12",
    "island": "10.128.0.11",
    "humanReadableKey": "5_0"
  },
  {
    "oid": "test_pg_gen_d82796af-40ef-4d07-b5c8-423714511c73_0",
    "name": "generate",
    "categoryType": "Application",
    "category": "BashShellApp",
    "dropclass": "dlg.apps.bash_shell_app.BashShellApp",
    "storage": "BashShellApp",
    "rank": [
      0
    ],
    "reprodata": {},
    "loop_ctx": null,
    "weight": 5,
    "num_cpus": 1,
    "applicationArgs": {
      "content": {
        "defaultValue": "",
        "description": " The port carrying the content read from the URL.",
        "encoding": "path",
        "id": "41b66724-e51b-43d2-8c5b-1dd58dc97cfd",
        "name": "content",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": true,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "OutputPort",
        "value": ""
      }
    },
    "constraintParams": {
      "execution_time": {
        "defaultValue": "0",
        "description": "Estimated execution time",
        "encoding": "pickle",
        "id": "c0e8a800-6215-44ef-a09c-504c6f41cae2",
        "name": "execution_time",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "Float",
        "usage": "NoPort",
        "value": 5
      },
      "num_cpus": {
        "defaultValue": "0",
        "description": "Number of cores used",
        "encoding": "pickle",
        "id": "0b14046f-f424-45e7-bcfe-75399c545a99",
        "name": "num_cpus",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "Integer",
        "usage": "NoPort",
        "value": 1
      }
    },
    "componentParams": {
      "persist": {
        "defaultValue": "false",
        "description": "Specifies whether this data component contains data that should not be deleted after execution",
        "encoding": "pickle",
        "id": "7794b8fb-2a1f-4ca3-a7d1-9e8dede1fa32",
        "name": "persist",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      "streaming": {
        "defaultValue": "false",
        "description": "Specifies whether this data component streams input and output data",
        "encoding": "pickle",
        "id": "67d6e01e-c538-4860-855c-0721bae57b0e",
        "name": "streaming",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      "command": {
        "defaultValue": "",
        "description": "The command to be executed",
        "encoding": "pickle",
        "id": "265320dd-c313-4d56-9f0d-aa9c4f3c28c6",
        "name": "command",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "echo \"'**'\" > {content}"
      },
      "input_redirection": {
        "defaultValue": "",
        "description": "The command line argument that specifies the input into this application",
        "encoding": "pickle",
        "id": "8088cb8c-38bc-4c0d-aa44-e3134e47cc4d",
        "name": "input_redirection",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      "output_redirection": {
        "defaultValue": "",
        "description": "The command line argument that specifies the output from this application",
        "encoding": "pickle",
        "id": "0f4df668-351c-4646-b981-9384c17cc109",
        "name": "output_redirection",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      "command_line_arguments": {
        "defaultValue": "",
        "description": "Additional command line arguments to be added to the command line to be executed",
        "encoding": "pickle",
        "id": "7cec596a-3971-470a-9e14-6b76c840d392",
        "name": "command_line_arguments",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      "paramValueSeparator": {
        "defaultValue": "",
        "description": "Separator character(s) between parameters on the command line",
        "encoding": "pickle",
        "id": "a648ad60-94fa-484e-b358-de955fdbcdf5",
        "name": "paramValueSeparator",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": " "
      },
      "argumentPrefix": {
        "defaultValue": "",
        "description": "Prefix to each keyed argument on the command line",
        "encoding": "pickle",
        "id": "27049e6f-0839-484e-a3c7-109ac580e11c",
        "name": "argumentPrefix",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "--"
      },
      "group_start": {
        "defaultValue": "false",
        "description": "Is this node the start of a group?",
        "encoding": "pickle",
        "id": "93f68246-32b5-4879-b4c0-f01f3bf1ea48",
        "name": "group_start",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      "input_error_threshold": {
        "defaultValue": "0",
        "description": "the allowed failure rate of the inputs (in percent), before this component goes to ERROR state and is not executed",
        "encoding": "pickle",
        "id": "24ed9677-0ef2-4aeb-a656-9143d4aa0bf6",
        "name": "input_error_threshold",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Integer",
        "usage": "NoPort",
        "value": 0
      },
      "n_tries": {
        "defaultValue": "0",
        "description": "Specifies the number of times the 'run' method will be executed before finally giving up",
        "encoding": "pickle",
        "id": "f5f31133-305c-48c6-98fd-693ebe4441b6",
        "name": "n_tries",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Integer",
        "usage": "NoPort",
        "value": 1
      },
      "dropclass": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "42d33199-1102-4e98-afde-8921afc47052",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.apps.bash_shell_app.BashShellApp"
      },
      "New Parameter": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "bd0085cc-a805-4eff-bd8c-240be2c6761e",
        "name": "New Parameter",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      }
    },
    "fields": [
      {
        "defaultValue": "false",
        "description": "Specifies whether this data component contains data that should not be deleted after execution",
        "encoding": "pickle",
        "id": "7794b8fb-2a1f-4ca3-a7d1-9e8dede1fa32",
        "name": "persist",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      {
        "defaultValue": "false",
        "description": "Specifies whether this data component streams input and output data",
        "encoding": "pickle",
        "id": "67d6e01e-c538-4860-855c-0721bae57b0e",
        "name": "streaming",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      {
        "defaultValue": "",
        "description": "The command to be executed",
        "encoding": "pickle",
        "id": "265320dd-c313-4d56-9f0d-aa9c4f3c28c6",
        "name": "command",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "echo \"'**'\" > {content}"
      },
      {
        "defaultValue": "",
        "description": "The command line argument that specifies the input into this application",
        "encoding": "pickle",
        "id": "8088cb8c-38bc-4c0d-aa44-e3134e47cc4d",
        "name": "input_redirection",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      {
        "defaultValue": "",
        "description": "The command line argument that specifies the output from this application",
        "encoding": "pickle",
        "id": "0f4df668-351c-4646-b981-9384c17cc109",
        "name": "output_redirection",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      {
        "defaultValue": "",
        "description": "Additional command line arguments to be added to the command line to be executed",
        "encoding": "pickle",
        "id": "7cec596a-3971-470a-9e14-6b76c840d392",
        "name": "command_line_arguments",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      {
        "defaultValue": "",
        "description": "Separator character(s) between parameters on the command line",
        "encoding": "pickle",
        "id": "a648ad60-94fa-484e-b358-de955fdbcdf5",
        "name": "paramValueSeparator",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": " "
      },
      {
        "defaultValue": "",
        "description": "Prefix to each keyed argument on the command line",
        "encoding": "pickle",
        "id": "27049e6f-0839-484e-a3c7-109ac580e11c",
        "name": "argumentPrefix",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "--"
      },
      {
        "defaultValue": "0",
        "description": "Estimated execution time",
        "encoding": "pickle",
        "id": "c0e8a800-6215-44ef-a09c-504c6f41cae2",
        "name": "execution_time",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "Float",
        "usage": "NoPort",
        "value": 5
      },
      {
        "defaultValue": "0",
        "description": "Number of cores used",
        "encoding": "pickle",
        "id": "0b14046f-f424-45e7-bcfe-75399c545a99",
        "name": "num_cpus",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "Integer",
        "usage": "NoPort",
        "value": 1
      },
      {
        "defaultValue": "false",
        "description": "Is this node the start of a group?",
        "encoding": "pickle",
        "id": "93f68246-32b5-4879-b4c0-f01f3bf1ea48",
        "name": "group_start",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      {
        "defaultValue": "0",
        "description": "the allowed failure rate of the inputs (in percent), before this component goes to ERROR state and is not executed",
        "encoding": "pickle",
        "id": "24ed9677-0ef2-4aeb-a656-9143d4aa0bf6",
        "name": "input_error_threshold",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Integer",
        "usage": "NoPort",
        "value": 0
      },
      {
        "defaultValue": "0",
        "description": "Specifies the number of times the 'run' method will be executed before finally giving up",
        "encoding": "pickle",
        "id": "f5f31133-305c-48c6-98fd-693ebe4441b6",
        "name": "n_tries",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Integer",
        "usage": "NoPort",
        "value": 1
      },
      {
        "defaultValue": "",
        "description": " The port carrying the content read from the URL.",
        "encoding": "path",
        "id": "41b66724-e51b-43d2-8c5b-1dd58dc97cfd",
        "name": "content",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": true,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "OutputPort",
        "value": ""
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "42d33199-1102-4e98-afde-8921afc47052",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.apps.bash_shell_app.BashShellApp"
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "bd0085cc-a805-4eff-bd8c-240be2c6761e",
        "name": "New Parameter",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      }
    ],
    "persist": false,
    "streaming": false,
    "command": "echo \"'**'\" > {content}",
    "input_redirection": "",
    "output_redirection": "",
    "command_line_arguments": "",
    "paramValueSeparator": " ",
    "argumentPrefix": "--",
    "execution_time": 5,
    "group_start": false,
    "input_error_threshold": 0,
    "n_tries": 1,
    "content": "",
    "New Parameter": "",
    "iid": "0",
    "lg_key": "d82796af-40ef-4d07-b5c8-423714511c73",
    "outputPorts": {
      "41b66724-e51b-43d2-8c5b-1dd58dc97cfd": {
        "type": "OutputPort",
        "name": "content",
        "target_id": "90756f41-6b98-42b5-9570-b5f2658be497"
      }
    },
    "inputPorts": {},
    "outputs": [
      {
        "test_pg_gen_90756f41-6b98-42b5-9570-b5f2658be497_0": "content"
      }
    ],
    "node": "10.128.0.12",
    "island": "10.128.0.11",
    "humanReadableKey": "6_0"
  },
  {
    "oid": "test_pg_gen_4f9c0432-2515-4e38-8dcb-61d968d981cc_0",
    "name": "result",
    "categoryType": "Data",
    "category": "File",
    "dropclass": "dlg.data.drops.file.FileDROP",
    "storage": "File",
    "rank": [
      0
    ],
    "reprodata": {},
    "loop_ctx": null,
    "weight": 5,
    "applicationArgs": {
      "filepath": {
        "defaultValue": "",
        "description": "File path for this file. In many cases this does not need to be specified. If it has a \\/ at the end it will be treated as a directory name and the filename will be generated. If it does not have a \\/, the last part will be treated as a filename. If filepath does not start with \\/ (relative path) then the session directory will be prepended to make the path absolute.\"",
        "encoding": "pickle",
        "id": "2f6bd9b1-ce75-472b-a291-2c59f0d01066",
        "name": "filepath",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "InputOutput",
        "value": ""
      },
      "dummy": {
        "defaultValue": "",
        "description": "Dummy port",
        "encoding": "pickle",
        "id": "49dcc6b7-e5d1-433f-af74-196772b3a558",
        "name": "dummy",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Object",
        "usage": "NoPort",
        "value": ""
      }
    },
    "constraintParams": {
      "data_volume": {
        "defaultValue": "5",
        "description": "Estimated size of the data contained in this node",
        "encoding": "pickle",
        "id": "1e23a909-d059-4beb-b90b-875a71770a37",
        "name": "data_volume",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Float",
        "usage": "NoPort",
        "value": 5
      }
    },
    "componentParams": {
      "check_filepath_exists": {
        "defaultValue": "False",
        "description": "Perform a check to make sure the file path exists before proceeding with the application",
        "encoding": "pickle",
        "id": "de39f29d-3c24-40c6-a026-03dedb6dd5cd",
        "name": "check_filepath_exists",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      "dropclass": {
        "defaultValue": "dlg.data.drops.file.FileDROP",
        "description": "Drop class",
        "encoding": "pickle",
        "id": "b529f643-5647-4973-ac91-d62eed7fa2b9",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.data.drops.file.FileDROP"
      },
      "streaming": {
        "defaultValue": "False",
        "description": "Specifies whether this data component streams input and output data",
        "encoding": "pickle",
        "id": "243e078f-a557-461f-a726-44a79dec08cb",
        "name": "streaming",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      "persist": {
        "defaultValue": "True",
        "description": "Specifies whether this data component contains data that should not be deleted after execution",
        "encoding": "pickle",
        "id": "78452750-c468-41b7-81a9-01383c7f4686",
        "name": "persist",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": true
      },
      "group_end": {
        "defaultValue": "False",
        "description": "Is this node the end of a group?",
        "encoding": "pickle",
        "id": "8d2f701d-1a4c-4954-836f-188b6463e45a",
        "name": "group_end",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      }
    },
    "fields": [
      {
        "defaultValue": "",
        "description": "File path for this file. In many cases this does not need to be specified. If it has a \\/ at the end it will be treated as a directory name and the filename will be generated. If it does not have a \\/, the last part will be treated as a filename. If filepath does not start with \\/ (relative path) then the session directory will be prepended to make the path absolute.\"",
        "encoding": "pickle",
        "id": "2f6bd9b1-ce75-472b-a291-2c59f0d01066",
        "name": "filepath",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "InputOutput",
        "value": ""
      },
      {
        "defaultValue": "False",
        "description": "Perform a check to make sure the file path exists before proceeding with the application",
        "encoding": "pickle",
        "id": "de39f29d-3c24-40c6-a026-03dedb6dd5cd",
        "name": "check_filepath_exists",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      {
        "defaultValue": "dlg.data.drops.file.FileDROP",
        "description": "Drop class",
        "encoding": "pickle",
        "id": "b529f643-5647-4973-ac91-d62eed7fa2b9",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.data.drops.file.FileDROP"
      },
      {
        "defaultValue": "False",
        "description": "Specifies whether this data component streams input and output data",
        "encoding": "pickle",
        "id": "243e078f-a557-461f-a726-44a79dec08cb",
        "name": "streaming",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      {
        "defaultValue": "True",
        "description": "Specifies whether this data component contains data that should not be deleted after execution",
        "encoding": "pickle",
        "id": "78452750-c468-41b7-81a9-01383c7f4686",
        "name": "persist",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": true
      },
      {
        "defaultValue": "5",
        "description": "Estimated size of the data contained in this node",
        "encoding": "pickle",
        "id": "1e23a909-d059-4beb-b90b-875a71770a37",
        "name": "data_volume",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Float",
        "usage": "NoPort",
        "value": 5
      },
      {
        "defaultValue": "False",
        "description": "Is this node the end of a group?",
        "encoding": "pickle",
        "id": "8d2f701d-1a4c-4954-836f-188b6463e45a",
        "name": "group_end",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      {
        "defaultValue": "",
        "description": "Dummy port",
        "encoding": "pickle",
        "id": "49dcc6b7-e5d1-433f-af74-196772b3a558",
        "name": "dummy",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Object",
        "usage": "NoPort",
        "value": ""
      }
    ],
    "filepath": "",
    "check_filepath_exists": false,
    "streaming": false,
    "persist": true,
    "data_volume": 5,
    "group_end": false,
    "dummy": "",
    "iid": "0",
    "lg_key": "4f9c0432-2515-4e38-8dcb-61d968d981cc",
    "outputPorts": {},
    "inputPorts": {
      "2f6bd9b1-ce75-472b-a291-2c59f0d01066": {
        "type": "InputOutput",
        "name": "filepath",
        "source_id": "e7c8f312-d267-4837-b29c-69c5f8bfb0dc"
      }
    },
    "port_map": {
      "filepath": "content"
    },
    "producers": [
      {
        "test_pg_gen_e7c8f312-d267-4837-b29c-69c5f8bfb0dc_0": "filepath"
      }
    ],
    "consumers": [
      {
        "test_pg_gen_b988ed98-e11b-4bcb-b561-d90ead73debe_0": "filepath"
      }
    ],
    "node": "10.128.0.12",
    "island": "10.128.0.11",
    "humanReadableKey": "7_0"
  }
]