"""
    Opal API

    Your Home For Developer Resources.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import opal_security
from opal_security.models.tag import Tag
globals()['Tag'] = Tag
from opal_security.models.tags_list import TagsList


class TestTagsList(unittest.TestCase):
    """TagsList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTagsList(self):
        """Test TagsList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TagsList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
