# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.add_bundle_resource_request import AddBundleResourceRequest

class TestAddBundleResourceRequest(unittest.TestCase):
    """AddBundleResourceRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddBundleResourceRequest:
        """Test AddBundleResourceRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddBundleResourceRequest`
        """
        model = AddBundleResourceRequest()
        if include_optional:
            return AddBundleResourceRequest(
                resource_id = '72e75a6f-7183-48c5-94ff-6013f213314b',
                access_level_remote_id = 'arn:aws:iam::590304332660:role/AdministratorAccess',
                access_level_name = 'AdministratorAccess'
            )
        else:
            return AddBundleResourceRequest(
                resource_id = '72e75a6f-7183-48c5-94ff-6013f213314b',
        )
        """

    def testAddBundleResourceRequest(self):
        """Test AddBundleResourceRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
