RECIPES = {
    "basic toolbench": (
        (("flint axe", 1), (("flint", 2), ("stick", 3))),
        (("flint pickaxe", 1), (("flint", 2), ("stick", 3))),
        (("flint shovel", 1), (("flint", 1), ("stick", 2))),
        (("flint sword", 1), (("flint", 1), ("ice", 1), ("stick", 2))),
        (("rock axe", 1), (("handle", 1), ("rock", 4))),
        (("rock pickaxe", 1), (("handle", 1), ("rock", 4))),
        (("rock shovel", 1), (("handle", 1), ("rock", 3))),
        (("rock sword", 1), (("handle", 1), ("ice", 1), ("rock", 4))),
        (("copper axe", 1), (("handle", 1), ("slime crystal", 2), ("copper ingot", 3))),
        (("copper pickaxe", 1), (("handle", 1), ("slime crystal", 2), ("copper ingot", 3))),
        (("copper shovel", 1), (("handle", 1), ("slime crystal", 1), ("copper ingot", 2))),
        (("copper sword", 1), (("handle", 1), ("slime crystal", 1), ("ice", 1), ("copper ingot", 3))),
        (("iron axe", 1), (("silver handle", 1), ("iron ingot", 3))),
        (("iron pickaxe", 1), (("silver handle", 1), ("iron ingot", 3))),
        (("iron shovel", 1), (("silver handle", 1), ("iron ingot", 2))),
        (("iron sword", 1), (("silver handle", 1), ("lava", 1), ("iron ingot", 3))),
    ),
    "burner drill": (
        (("amethyst", 1), (("fuel", 4), ("amethyst mineable", 1))),
        (("coal", 1), (("fuel", 2), ("coal mineable", 1))),
        (("raw copper", 1), (("fuel", 4), ("copper mineable", 1))),
    ),
    "caelium sieve": (
        (("caelium leaf sift", 1), (("caelium leaf", 1), ("water fluid", 1))),
        (("coal leaf sift", 1), (("coal leaf", 1), ("water fluid", 1))),
        (("copper leaf sift", 1), (("copper leaf", 1), ("water fluid", 1))),
        (("sapphire leaf sift", 1), (("caelium leaf", 1), ("water fluid", 1))),
        (("tin leaf sift", 1), (("tin leaf", 1), ("water fluid", 1))),
        (("raw caelium", 1), (("caelium acorn", 1), ("water fluid", 1))),
        (("coal", 4), (("coal acorn", 1), ("water fluid", 1))),
        (("raw copper", 4), (("copper acorn", 1), ("water fluid", 1))),
        (("sapphire", 1), (("sapphire acorn", 1), ("water fluid", 1))),
        (("raw tin", 4), (("tin acorn", 1), ("water fluid", 1))),
    ),
    "campfire": (
        (("brick", 2), (("clay", 1),)),
        (("copper needle", 1), (("raw copper", 2),)),
        (("glass", 1), (("sand", 3),)),
        (("life crystal", 1), (("slime crystal", 2), ("copper ingot", 3), ("ice", 1))),
        (("mushroom stew", 2), (("carrot", 1), ("mushroom", 3), ("water", 2))),
        (("roasted mushroom", 1), (("mushroom", 1), ("stick", 1))),
        (("roasted rabbit meat", 1), (("rabbit meat", 1),)),
        (("slime summon", 1), (("slime crystal", 3), ("life crystal", 1))),
        (("stone", 1), (("rock", 1),)),
        (("torch", 1), (("stick", 1), ("coal", 1))),
        (("water", 1), (("bowl", 1), ("ice", 1))),
    ),
    "composter": (
        (("dirt", 1), (("compost", 4),)),
        (("fertilizer", 1), (("compost", 12), ("dirt", 1))),
        (("pebble", 1), (("compost", 6),)),
        (("flint", 1), (("compost", 10), ("pebble", 1))),
        (("moist dirt", 2), (("fertilizer", 1), ("dirt", 2), ("water", 1))),
    ),
    "copper anvil": (
        (("basic belt 0", 4), (("bronze machine casing", 1), ("copper shaft", 1), ("copper sheet", 1))),
        (("basic merger 0", 1), (("basic belt 0", 2), ("tin gear", 1))),
        (("basic splitter 0", 1), (("basic belt 0", 2), ("copper gear", 1))),
        (("bronze gear", 1), (("bronze ingot", 4),)),
        (("bronze machine casing", 2), (("bronze block", 1),)),
        (("burner drill", 4), (("copper ingot", 2), ("copper gear", 2), ("rock pickaxe", 1))),
        (("copper constructor", 1), (("copper sheet", 1), ("copper shaft", 1), ("copper gear", 2), ("tin ingot", 4))),
        (("copper gear", 1), (("copper ingot", 4),)),
        (("copper press", 1), (("copper block", 1), ("copper shaft", 1), ("tin ingot", 1))),
        (("copper shaft", 1), (("copper ingot", 1),)),
        (("copper wrench", 1), (("copper gear", 1), ("copper shaft", 1))),
        (("drill", 1), (("copper gear", 1), ("copper shaft", 1), ("stone brick", 1))),
        (("rail 0", 4), (("copper shaft", 1), ("pebble", 1), ("wood fence 0", 1))),
        (("tin gear", 1), (("tin ingot", 4),)),
    ),
    "copper boiler": (
        (("steam fluid", 5), (("water fluid", 5), ("coal", 2))),
    ),
    "copper constructor": (
        (("bronze harvester", 4), (("bronze machine casing", 2), ("leaf", 4))),
        (("construction arm", 1), (("bronze machine casing", 1), ("iron ingot", 1), ("gold ingot", 1))),
        (("construction chamber", 1), (("bronze machine casing", 1), ("copper gear", 1), ("copper shaft", 1))),
        (("copper boiler", 4), (("copper gear", 1), ("copper sheet", 5), ("copper ingot", 2), ("tin ingot", 2))),
        (("copper tank", 1), (("copper sheet", 4), ("copper shaft", 1))),
        (("crushing chamber", 1), (("bronze machine casing", 1), ("copper tank", 1))),
        (("crushing wheel", 1), (("bronze machine casing", 1), ("copper gear", 1), ("copper shaft", 1)),),
        (("lavastone furnace accelerator", 1), (("furnace accelerator", 1), ("lavastone brick", 2), ("bronze machine casing", 1))),
        (("lead furnace accelerator", 1), (("furnace accelerator", 1), ("lead ingot", 2), ("bronze machine casing", 1))),
        (("silver tank", 1), (("copper tank", 1), ("silver ingot", 2), ("bronze machine casing", 1))),
        (("steam constructor", 4), (("bronze machine casing", 2), ("copper gear", 4))),
        (("steam crusher", 4), (("bronze machine casing", 2), ("tin gear", 2))),
        (("steam drill", 4), (("gold ingot", 1), ("bronze gear", 1), ("burner drill", 4))),
        (("steam furnace", 4), (("furnace", 4), ("lavastone brick", 4), ("copper wrench", 1))),
        (("steam part assembler", 4), (("bronze machine casing", 2), ("basic belt 0", 4))),
        (("steam pump", 4), (("bronze machine casing", 2), ("copper tank", 2))),
    ),
    "copper press": (
        (("copper sheet", 1), (("copper ingot", 1), ("fuel", 8))),
    ),
    "dye bench": (
        (("black dye", 1), (("coal", 1),)),
        (("blue dye", 1), (("bluebell", 1),)),
        (("brown dye", 1), (("mushroom", 2),)),
        (("red dye", 1), (("ruby", 1),)),
        (("white dye", 1), (("quartz", 1),)),
        (("yellow dye", 1), (("citrine", 1))),
    ),
    "furnace": (
        (("copper ingot", 1), (("raw copper", 1), ("fuel", 8))),
        (("glass", 1), (("sand", 2), ("fuel", 8))),
        (("lavastone", 1), (("stone", 2), ("fuel", 8))),
        (("pure crystal", 1), (("quartz", 1), ("fuel", 8))),
        (("slime crystal", 1), (("slime ball", 1), ("fuel", 8))),
        (("tin ingot", 1), (("raw tin", 1), ("fuel", 8))),
    ),
    "mana constructor": (
        (("tin ingot", 1), (("lead ingot", 2),), 1),
        (("iron ingot", 1), (("tin ingot", 2),), 2),
        (("copper ingot", 1), (("iron ingot", 2),), 3),
        (("silver ingot", 1), (("copper ingot", 2),), 4),
        (("gold ingot", 1), (("silver ingot", 2),), 5),
    ),
    "mana converter": (
        (("albedo", 1), (("white dye", 1), ("nigredo", 2)), 3),
        (("amethyst", 1), (("quartz", 2),), 1),
        (("amethyst dirt", 2), (("fertilizer", 1), ("moist dirt", 2), ("amethyst", 1)), 4),
        (("citrine", 1), (("amethyst", 2),), 2),
        (("citrinitas", 1), (("yellow dye", 1), ("albedo", 2)), 4),
        (("mana constructor", 1), (("philosopher's stone", 1), ("bronze machine casing", 1)), 6),
        (("mana converter", 1), (("philosopher's stone", 1), ("bronze machine casing", 1)), 5),
        (("mana deconstructor", 1), (("philosopher's stone", 1), ("bronze machine casing", 1)), 6),
        (("nigredo", 1), (("black dye", 1),), 2),
        (("philosopher's stone", 1), (("rubido", 1), ("citrinitas", 1), ("albedo", 1), ("nigredo", 1), ("mercury ingot", 1)), 6),
        (("rubido", 1), (("red dye", 1), ("citrinitas", 2)), 5),
        (("ruby", 1), (("sapphire", 1),), 4),
    ),
    "mana deconstructor": (
        (("lead ingot", 1), (("tin ingot", 2),), 1),
        (("tin ingot", 1), (("iron ingot", 2),), 2),
        (("iron ingot", 1), (("copper ingot", 2),), 3),
        (("copper ingot", 1), (("silver ingot", 2),), 4),
        (("silver ingot", 1), (("gold ingot", 2),), 5),
    ),
    "manual press": (
        (("blue dye", 1), (("bluebell", 1), ("bowl", 1))),
        (("bronze dust", 2), (("copper dust", 3), ("tin dust", 1))),
        (("copper dust", 1), (("raw copper", 1),)),
        (("copper pit", 1), (("raw copper", 1), ("flint shovel", 1), ("coal", 1), ("clay", 1))),
        (("package", 1), (("paper", 4), ("water", 1))),
        (("paper", 1), (("wood", 2),)),
        (("rock", 1), (("pebble", 3),)),
        (("sand", 1), (("pebble", 2),)),
        (("snow", 2), (("ice", 1),)),
        (("tin dust", 1), (("raw tin", 1),)),
    ),
    "masonry bench": (
        (("amethyst brick", 2), (("amethyst", 1), ("stone brick", 2))),
        (("amethyst brick floor", 2), (("amethyst brick", 1),)),
        (("brick floor", 2), (("brick", 1),)),
        (("copper brick", 2), (("copper ingot", 1), ("stone brick", 2))),
        (("copper brick floor", 2), (("copper brick", 1),)),
        (("copper door", 1), (("copper brick", 1), ("copper brick floor", 1))),
        (("furnace", 4), (("copper ingot", 6), ("stone brick", 8))),
        (("furnace accelerator", 1), (("copper ingot", 3), ("stone brick", 4))),
        (("glass floor", 2), (("glass", 1),)),
        (("lavastone brick", 1), (("lavastone", 1),)),
        (("lavastone brick floor", 2), (("lavastone brick", 1),)),
        (("lavastone floor", 2), (("lavastone", 1),)),
        (("stone brick", 1), (("stone", 1),)),
        (("stone brick floor", 2), (("stone brick", 1),)),
        (("stone floor", 2), (("stone", 1),)),
    ),
    "mushroom shaper": (
        (("bluebell jar", 1), (("brick", 1), ("dirt", 2), ("bluebell", 1), ("glass", 1))),
        (("composter", 1), (("mushroom", 2), ("paper", 2), ("small barrel", 1))),
        (("mushroom block", 1), (("mushroom", 2), ("wood", 1))),
        (("mushroom door", 1), (("mushroom floor", 1), ("mushroom block", 1))),
        (("mushroom floor", 2), (("mushroom block", 1),)),
        (("mushroom table", 1), (("mushroom floor", 4), ("stick", 4))),
        (("plant bouquet", 1), (("bluebell", 1), ("carrot", 1), ("sapling", 1), ("spore", 1))),
    ),
    "packager bench": (
        (("amethyst", 8), (("amethyst block", 1),)),
        (("amethyst block", 1), (("amethyst", 8),)),
        (("amethyst rune", 1), (("amethyst", 2), ("stone brick floor", 1))),
        (("bronze ingot", 8), (("bronze block", 1),)),
        (("bronze block", 1), (("bronze ingot", 8),)),
        (("citrine", 8), (("citrine block", 1),)),
        (("citrine block", 1), (("citrine", 8),)),
        (("citrine rune", 1), (("citrine", 2), ("stone brick floor", 1))),
        (("coal", 8), (("coal block", 1),)),
        (("coal block", 1), (("coal", 8),)),
        (("copper block", 1), (("copper ingot", 8),)),
        (("copper ingot", 8), (("copper block", 1),)),
        (("gift", 1), (("package", 1), ("coal", 1))),
        (("lava rune", 1), (("lava", 2), ("stone brick floor", 1))),
        (("quartz block", 1), (("quartz", 8),)),
        (("quartz", 8), (("quartz block", 1),)),
        (("sapphire rune", 1), (("sapphire", 2), ("stone brick floor", 1))),
        (("water", 4), (("water block", 1),)),
        (("water block", 1), (("water", 4),)),
    ),
    "player": (
        (("snowball", 4), (("snow", 1),)),
        (("stick", 4), (("wood", 2),)),
        (("wood", 2), (("log", 1),)),
        (("wood door", 1), (("wood floor", 1), ("wood", 1))),
        (("wood floor", 2), (("wood", 1),)),
        (("workbench", 1), (("flint", 1), ("wood", 4))),
    ),
    "quartz altar": (
        (("quartz child", 1), (("glass", 5), ("life crystal", 1))),
    ),
    "sawbench": (
        (("bookshelf", 1), (("paper", 3), ("wood", 2))),
        (("handle", 1), (("blue dye", 1), ("stick", 4))),
        (("log floor", 2), (("log", 1),)),
        (("mushroom shaper", 1), (("composter", 1), ("mushroom", 12))),
        (("silver handle", 1), (("handle", 1), ("silver ingot", 1))),
        (("small barrel", 1), (("stick", 4), ("wood", 6))),
        (("small crate", 1), (("stick", 4), ("wood", 6))),
        (("stick", 2), (("wood", 1),)),
        (("wood crucible", 1), (("small barrel", 1), ("log", 2))),
        (("wood fence 0", 1), (("wood", 1), ("stick", 2))),
        (("wooden bed", 1), (("blue dye", 3), ("rabbit fur", 2), ("wood", 10))),
        (("wooden sieve", 1), (("thread", 3), ("small barrel", 1))),
        (("wooden table", 1), (("wood floor", 4), ("stick", 4))),
    ),
    "sewbench": (
        (("anklet of the tree", 1), (("acorn", 1), ("thread", 2), ("log", 1), ("brown dye", 1))),
        (("boots", 1), (("thread", 4), ("brown dye", 1))),
        (("small backpack", 1), (("thread", 4), ("white dye", 1))),
        (("thread", 1), (("rabbit fur", 1), ("stick", 1))),
    ),
    "slime shaper": (
        (("slime block", 2), (("slime crystal", 1), ("wood", 2))),
        (("slime door", 1), (("slime floor", 1), ("slime block", 1))),
        (("slime floor", 2), (("slime block", 1),)),
        (("slime table", 1), (("slime floor", 4), ("stick", 4))),
    ),
    "steam constructor": (
        (("bronze harvester", 4), (("bronze machine casing", 2), ("leaf", 4), ("steam fluid", 1))),
        (("construction arm", 1), (("bronze machine casing", 1), ("iron ingot", 1), ("gold ingot", 1), ("steam fluid", 1))),
        (("construction chamber", 1), (("bronze machine casing", 1), ("copper gear", 1), ("copper shaft", 1), ("steam fluid", 1))),
        (("copper boiler", 4), (("copper gear", 1), ("copper sheet", 5), ("copper ingot", 2), ("tin ingot", 2), ("steam fluid", 1))),
        (("copper tank", 1), (("copper sheet", 4), ("copper shaft", 1), ("steam fluid", 1))),
        (("crushing chamber", 1), (("bronze machine casing", 1), ("copper tank", 1), ("steam fluid", 1))),
        (("crushing wheel", 1), (("bronze machine casing", 1), ("copper gear", 1), ("copper shaft", 1), ("steam fluid", 1))),
        (("lavastone furnace accelerator", 1), (("furnace accelerator", 1), ("lavastone brick", 2), ("bronze machine casing", 1), ("steam fluid", 1))),
        (("lead furnace accelerator", 1), (("furnace accelerator", 1), ("lead ingot", 2), ("bronze machine casing", 1), ("steam fluid", 1))),
        (("silver tank", 1), (("copper tank", 1), ("silver ingot", 2), ("bronze machine casing", 1), ("steam fluid", 1))),
        (("steam constructor", 4), (("bronze machine casing", 2), ("copper gear", 4), ("steam fluid", 1))),
        (("steam crusher", 4), (("bronze machine casing", 2), ("tin gear", 2), ("steam fluid", 1))),
        (("steam drill", 4), (("gold ingot", 1), ("bronze gear", 1), ("burner drill", 4), ("steam fluid", 1))),
        (("steam furnace", 4), (("furnace", 4), ("lavastone brick", 4), ("copper wrench", 1), ("steam fluid", 1))),
        (("steam part assembler", 4), (("bronze machine casing", 2), ("basic belt 0", 4), ("steam fluid", 1))),
        (("steam pump", 4), (("bronze machine casing", 2), ("copper tank", 2), ("steam fluid", 1))),
    ),
    "steam crusher": (
        (("coal dust", 1), (("coal", 1), ("steam fluid", 1))),
        (("crushed caelium", 1), (("raw caelium", 1), ("steam fluid", 1))),
        (("crushed copper", 1), (("raw copper", 1), ("steam fluid", 1))),
        (("crushed iron", 1), (("raw iron", 1), ("steam fluid", 1))),
        (("crushed tin", 1), (("raw tin", 1), ("steam fluid", 1))),
        (("steel dust", 1), (("iron ingot", 1), ("coal coke", 1), ("steam fluid", 1))),
        (("stick", 16), (("log", 4), ("steam fluid", 1))),
        (("wood", 8), (("log", 4), ("steam fluid", 1))),
        (("wood floor", 16), (("log", 4), ("steam fluid", 1))),
    ),
    "steam drill": (
        (("amethyst", 1), (("steam fluid", 1), ("amethyst mineable", 1))),
        (("coal", 1), (("steam fluid", 1), ("coal mineable", 1))),
        (("raw copper", 1), (("steam fluid", 1), ("copper mineable", 1))),
        (("raw iron", 1), (("steam fluid", 1), ("iron mineable", 1))),
        (("raw tin", 1), (("steam fluid", 1), ("tin mineable", 1))),
    ),
    "steam furnace": (
        (("bronze ingot", 1), (("bronze dust", 1), ("steam fluid", 1))),
        (("caelium ingot", 1), (("caelium dust", 1), ("steam fluid", 1))),
        (("coal coke", 1), (("coal dust", 1), ("steam fluid", 1))),
        (("copper ingot", 1), (("copper dust", 1), ("steam fluid", 1))),
        (("glass", 1), (("sand", 2), ("steam fluid", 1))),
        (("gold ingot", 1), (("gold dust", 1), ("steam fluid", 1))),
        (("iron ingot", 1), (("iron dust", 1), ("steam fluid", 1))),
        (("lavastone", 1), (("stone", 2), ("steam fluid", 1))),
        (("lead ingot", 1), (("lead dust", 1), ("steam fluid", 1))),
        (("mercury ingot", 1), (("mercury dust", 1), ("steam fluid", 1))),
        (("pure crystal", 1), (("quartz", 1), ("steam fluid", 1))),
        (("silver ingot", 1), (("silver dust", 1), ("steam fluid", 1))),
        (("slime crystal", 1), (("slime ball", 1), ("steam fluid", 1))),
        (("steel ingot", 1), (("steel dust", 1), ("steam fluid", 1))),
        (("tin ingot", 1), (("tin dust", 1), ("steam fluid", 1))),
    ),
    "steam part assembler": (
        (("basic belt 0", 4), (("bronze machine casing", 1), ("copper shaft", 1), ("copper sheet", 1), ("steam fluid", 1))),
        (("basic merger 0", 1), (("basic belt 0", 2), ("tin gear", 1), ("steam fluid", 1))),
        (("basic splitter 0", 1), (("basic belt 0", 2), ("copper gear", 1), ("steam fluid", 1))),
        (("bronze gear", 1), (("bronze ingot", 3), ("steam fluid", 1))),
        (("bronze machine casing", 1), (("bronze ingot", 3), ("steam fluid", 1))),
        (("copper gear", 1), (("copper ingot", 3), ("steam fluid", 1))),
        (("copper shaft", 3), (("copper ingot", 2), ("steam fluid", 1))),
        (("tin gear", 1), (("tin ingot", 3), ("steam fluid", 1))),
    ),
    "steam pump": (
        (("water", 5), (("steam fluid", 1),)),
        (("slime ball", 2), (("water", 2), ("steam fluid", 1)))
    ),
    "tree constructor": (
        (("sapling", 1), (("wood", 1), ("stick", 2))),
        (("coal sapling", 1), (("sapling", 1), ("handle", 1), ("slime ball", 2))),
        (("copper sapling", 1), (("coal sapling", 1), ("glass", 1), ("amethyst", 2))),
        (("tin sapling", 1), (("copper sapling", 1), ("drill", 1), ("slime block", 2))),
        (("caelium sapling", 1), (("sapling", 1), ("coal sapling", 1), ("copper sapling", 1), ("tin sapling", 1))),
        (("sapphire sapling", 1), (("caelium sapling", 1), ("lava rune", 1), ("caelium ingot", 2)))
    ),
    "void converter": (
        (("sapling", 1), (("log", 1), ("wood", 1))),
        (("rabbit child", 1), (("blue dye", 1), ("carrot", 4))),
        (("tree constructor", 1), (("sapling", 4), ("small crate", 1))),
        (("quartz altar", 1), (("glass", 2), ("stone", 4))),
        (("caelium sieve", 1), (("caelium leaf", 1), ("wooden sieve", 1))),
        (("lava", 1), (("lavastone brick", 1), ("bronze ingot", 1))),
    ),
    "wood crucible": (
        (("water", 1), (("fuel", 4),)),
        (("slime ball", 1), (("fuel", 10), ("water fluid", 4))),
    ),
    "wooden sieve": (
        (("basic sift", 1), (("rock", 1), ("water fluid", 2))),
        (("leaf sift", 1), (("leaf", 1), ("water fluid", 1))),
    ),
    "workbench": (
        (("basic toolbench", 1), (("log", 2), ("flint", 2))),
        (("bowl", 1), (("stick", 1), ("wood", 1))),
        (("campfire", 1), (("flint", 2), ("stick", 6), ("wood", 4))),
        (("connector", 1), (("stone brick", 1),)),
        (("copper anvil", 1), (("copper block", 1), ("copper ingot", 2))),
        (("dye bench", 1), (("manual press", 1), ("blue dye", 1))),
        (("manual press", 1), (("flint hammer", 1), ("workbench", 1))),
        (("masonry bench", 1), (("flint pickaxe", 2), ("rock", 1), ("workbench", 1))),
        (("packager bench", 1), (("package", 1), ("masonry bench", 1))),
        (("sawbench", 1), (("flint axe", 2), ("rock", 1), ("workbench", 1))),
        (("sewbench", 1), (("copper needle", 1), ("rabbit fur", 2), ("workbench", 1))),
    ),
}
