from __future__ import annotations
from typing import Any, Dict, List, Optional, Union
from PySide6.QtCore import Qt, QPointF, QRectF, QDate
from PySide6.QtWidgets import QWidget, QVBoxLayout, QGraphicsItem, QGraphicsSceneHoverEvent
from PySide6.QtCharts import QChart, QChartView, QBarSeries, QPercentBarSeries, QBarSet, QBarCategoryAxis, QValueAxis
from PySide6.QtGui import QPainter, QColor, QPen, QBrush, QFont, QFontMetrics, QLinearGradient, QGradient
from qtmui.material.styles import useTheme
class TooltipItem:
    def __init__(self, parent): ...
    def clear(self): ...
    def add_line(self, text: str, color: QColor): ...
    def boundingRect(self): ...
    def paint(self, painter: QPainter, *args): ...
class HoverChartView:
    def __init__(self, chart, parent): ...
    def leaveEvent(self, event): ...
class ChartBar:
    def __init__(self, dir: str, type: str, series: Optional[Union[List[Dict[str, Any]], List[float], List[int]]], width: Optional[Union[str, int]], height: Optional[Union[str, int]], options: Optional[Dict[str, Any]], key: Optional[str], *args, **kwargs): ...
    def _normalize_series(self, raw): ...
    def _shrink_categories(self, full_categories): ...
    def _init_chart(self): ...
    def _on_bar_hovered(self, status: bool, index: int): ...
    def hide_tooltip(self): ...
    def _apply_theme(self): ...