# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 1.3.0
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.list_alerts_request import ListAlertsRequest

class TestListAlertsRequest(unittest.TestCase):
    """ListAlertsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAlertsRequest:
        """Test ListAlertsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAlertsRequest`
        """
        model = ListAlertsRequest()
        if include_optional:
            return ListAlertsRequest(
                search = '',
                filters = {
                    'key' : null
                    },
                sort = mixpeek.models.sort_option.SortOption(
                    field = 'created_at', 
                    direction = desc, ),
                case_sensitive = True
            )
        else:
            return ListAlertsRequest(
        )
        """

    def testListAlertsRequest(self):
        """Test ListAlertsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
