import asyncio
from typing import Callable, Union, Dict, Optional, List
from PySide6.QtWidgets import QHBoxLayout, QVBoxLayout, QFrame, QSizePolicy, QLabel, QWidget
from PySide6.QtCore import Qt, QTimer, QEvent
import uuid
from qtmui.hooks import State
from ..spacer import HSpacer
from ..widget_base import PyWidgetBase
from ...material.styles import useTheme
from ..typography import Typography
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
from ..utils.validate_params import _validate_param
class FormControlLabel:
    def __init__(self, control: Union[State, QWidget], checked: Union[State, bool], classes: Optional[Union[State, Dict]], componentsProps: Optional[Union[State, Dict]], disabled: Union[State, bool], disableTypography: Union[State, bool], inputRef: Optional[Union[State, object]], label: Optional[Union[State, str, QWidget, List[QWidget], Callable]], labelPlacement: Union[State, str], key: Optional[Union[State, str]], onChange: Optional[Union[State, Callable]], required: Union[State, bool], slotProps: Optional[Union[State, Dict]], slots: Optional[Union[State, Dict]], sx: Optional[Union[State, List, Dict, Callable, str]], value: Optional[Union[State, any]], highlight: Union[State, bool], fullWidth: Union[State, bool], spacing: Union[State, int], **kwargs): ...
    def _set_control(self, value): ...
    def _get_control(self): ...
    def _set_checked(self, value): ...
    def _get_checked(self): ...
    def _set_classes(self, value): ...
    def _get_classes(self): ...
    def _set_componentsProps(self, value): ...
    def _get_componentsProps(self): ...
    def _set_disabled(self, value): ...
    def _get_disabled(self): ...
    def _set_disableTypography(self, value): ...
    def _get_disableTypography(self): ...
    def _set_inputRef(self, value): ...
    def _get_inputRef(self): ...
    def _set_label(self, value): ...
    def _get_label(self): ...
    def _set_labelPlacement(self, value): ...
    def _get_labelPlacement(self): ...
    def _set_key(self, value): ...
    def _get_key(self): ...
    def _set_onChange(self, value): ...
    def _get_onChange(self): ...
    def _set_required(self, value): ...
    def _get_required(self): ...
    def _set_slotProps(self, value): ...
    def _get_slotProps(self): ...
    def _set_slots(self, value): ...
    def _get_slots(self): ...
    def _set_sx(self, value): ...
    def _get_sx(self): ...
    def _set_value(self, value): ...
    def _get_value(self): ...
    def _set_highlight(self, value): ...
    def _get_highlight(self): ...
    def _set_fullWidth(self, value): ...
    def _get_fullWidth(self): ...
    def _set_spacing(self, value): ...
    def _get_spacing(self): ...
    def _init_ui(self): ...
    def slot_set_stylesheet(self, value): ...
    def add_children(self, layout, children): ...
    def handle_change(self, event: dict): ...
    def render(self): ...
    def _set_stylesheet(self): ...