// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=ts"
// @generated from file plm/v1/task_progress.proto (package plm.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file plm/v1/task_progress.proto.
 */
export const file_plm_v1_task_progress: GenFile = /*@__PURE__*/
  fileDesc("ChpwbG0vdjEvdGFza19wcm9ncmVzcy5wcm90bxIGcGxtLnYxIqUBChNUYXNrUHJvZ3Jlc3NNZXNzYWdlEhIKCnJlcXVlc3RfaWQYASABKAkSEwoLaW5zdGFuY2VfaWQYAiABKAkSDwoHdGFza19pZBgDIAEoCRIQCghhZ2VudF9pZBgEIAEoCRIPCgdtZXNzYWdlGAUgASgJEhQKDGVsYXBzZWRfdGltZRgGIAEoAxIbChNlc3RpbWF0ZWRfdGltZV9sZWZ0GAcgASgDQpQBCgpjb20ucGxtLnYxQhFUYXNrUHJvZ3Jlc3NQcm90b1ABWjFnaXRodWIuY29tL2NvYm90YXIvcHJvdG9jb2wvbWVzc2FnZXMvcGxtL3YxO3BsbXYxogIDUFhYqgIPTWVzc2FnZXMuUGxtLlYxygIGUGxtXFYx4gISUGxtXFYxXEdQQk1ldGFkYXRh6gIHUGxtOjpWMWIGcHJvdG8z");

/**
 * @generated from message plm.v1.TaskProgressMessage
 */
export type TaskProgressMessage = Message<"plm.v1.TaskProgressMessage"> & {
  /**
   * @generated from field: string request_id = 1;
   */
  requestId: string;

  /**
   * @generated from field: string instance_id = 2;
   */
  instanceId: string;

  /**
   * @generated from field: string task_id = 3;
   */
  taskId: string;

  /**
   * @generated from field: string agent_id = 4;
   */
  agentId: string;

  /**
   * @generated from field: string message = 5;
   */
  message: string;

  /**
   * @generated from field: int64 elapsed_time = 6;
   */
  elapsedTime: bigint;

  /**
   * @generated from field: int64 estimated_time_left = 7;
   */
  estimatedTimeLeft: bigint;
};

/**
 * Describes the message plm.v1.TaskProgressMessage.
 * Use `create(TaskProgressMessageSchema)` to create a new message.
 */
export const TaskProgressMessageSchema: GenMessage<TaskProgressMessage> = /*@__PURE__*/
  messageDesc(file_plm_v1_task_progress, 0);

