from typing import Any, Callable
import uuid
from PySide6.QtWidgets import QLabel
from qtmui.material.section import Section
from ...common.ui_functions import clear_layout
from ..qss_name import *
from ...material.box import Box
from ...material.typography.typography import Typography
from ..qss_name import *
from qtmui.material.styles import useTheme
class RHFListView:
    def __init__(self, name: str, compornent: object, renderProps: Callable, minimumWidth: int, model: Any, onItemClicked: Callable): ...
    def render_compornent(self, config): ...
    def render_ui(self): ...
    def set_state(self, state): ...
    def stateSignal(self): ...
    def stateSignal(self, value): ...
    def state(self, state): ...