import uuid
from typing import Optional, Union, List, Callable, Any
from PySide6.QtWidgets import QFrame, QWidget, QHBoxLayout, QSizePolicy
from PySide6.QtCore import Signal, Qt
from qtmui.hooks import useState
from qtmui.material.styles import useTheme
from ..box import Box
from ..view import View
from ..avatar import Avatar
from ..py_iconify import PyIconify
class Step:
    def __init__(self, active: bool, alternativeLabel: bool, children: Optional[list], classes: Optional[dict], completed: bool, component: Optional[Union[str, Any]], disabled: bool, expanded: bool, error: bool, index: Optional[int], label: Optional[QWidget], key: Optional[str], last: bool, optionnal: bool, sx: Optional[Union[List[Union[Callable, dict, bool]], Callable, dict, bool]], *args, **kwargs): ...
    def _init_ui(self): ...
    def _set_icon_widget(self, state): ...
    def _set_theme(self): ...
    def generate_stylesheet(self): ...
    def set_active(self, active: bool): ...
    def get_active(self): ...
    def set_completed(self, completed: bool): ...
    def get_completed(self): ...
    def set_disabled(self, disabled: bool): ...
    def get_disabled(self): ...
    def set_expanded(self, expanded: bool): ...
    def get_expanded(self): ...
    def set_last(self, last: bool): ...
    def get_last(self): ...
    def set_index(self, index: int): ...
    def get_index(self): ...
    def update_ui(self): ...