AE_WITHDRAWN = "ae_withdrawn"
CONTINUING_UPDATE = "continuing/update"
DEATH_REPORT_NOT_FOUND = "DEATH_REPORT_NOT_FOUND"
DEFINITELY_RELATED = "definitely_related"
DISCHARGED = "discharged"
INPATIENT = "inpatient"
NOT_RECOVERED = "not_recovered"
NOT_RELATED = "not_related"
POSSIBLY_RELATED = "possibly_related"
PROBABLY_RELATED = "probably_related"
RECOVERED = "recovered"
RECOVERED_WITH_SEQUELAE = "recovered_with_sequelae"
RECOVERING = "recovering"
UNLIKELY_RELATED = "unlikely_related"

# roles
AE = "AE"
AE_REVIEW = "AE_REVIEW"
AE_ROLE = "ae_role"
AE_SUPER = "AE_SUPER"
TMG = "TMG"
TMG_REVIEW = "TMG_REVIEW"

ALREADY_REPORTED = "Already reported"
INVALID_REFERENCE = "invalid_reference"
MILD = "mild"
MODERATE = "moderate"
PRESENT_AT_BASELINE = "present_at_baseline"
SEVERE = "severe"
SEVERITY_INCREASED_FROM_G3 = "increase_from_g3"

# grades
GRADE0 = "0"
GRADE1 = "1"
GRADE2 = "2"
GRADE3 = "3"
GRADE4 = "4"
GRADE5 = "5"
