from __future__ import annotations
import asyncio
import contextlib
import inspect
import queue
import time
import weakref
from collections import defaultdict
from collections.abc import Awaitable, Iterable, Sequence
from functools import wraps
from threading import Lock, Thread
from typing import TYPE_CHECKING, Any, Concatenate, Generic, cast, overload
from qtmui.redux.basic_types import Action, ActionMiddleware, Args, AutoAwait, AutorunDecorator, AutorunOptions, AutorunOptionsType, AutorunReturnType, AwaitableOrNot, BaseAction, BaseEvent, ComparatorOutput, DispatchParameters, Event, EventHandler, EventMiddleware, FinishAction, FinishEvent, InitAction, MethodSelf, ReducerType, ReturnType, SelectorOutput, SnapshotAtom, State, StoreOptions, StrictEvent, SubscribeEventCleanup, ViewDecorator, ViewOptions, ViewReturnType, WithStateDecorator, is_complete_reducer_result, is_state_reducer_result
from qtmui.redux.serialization_mixin import SerializationMixin
from qtmui.redux.utils import call_func, signature_without_selector
class Store:
    def __init__(self, reducer: ReducerType[State, Any, Any], options: Any): ...
    def _call_listeners(self: Store[State, Action, Event], state: State): ...
    def _run_actions(self: Store[State, Action, Event]): ...
    def _run_event_handlers(self: Store[State, Action, Event]): ...
    def run(self: Store[State, Action, Event]): ...
    def clean_up(self: Store[State, Action, Event]): ...
    def wait_for_event_handlers(self: Store[State, Action, Event]): ...
    def dispatch(self: Store[State, Action, Event], *parameters): ...
    def dispatch(self: Store[State, Action, Event]): ...
    def dispatch(self: Store[State, Action, Event], *parameters): ...
    def _dispatch(self: Store[State, Action, Event], items: Sequence[Any]): ...
    def _subscribe(self: Store[State, Action, Event], listener: Callable[Any, Any]): ...
    def subscribe_event(self: Store[State, Action, Event], event_type: type[StrictEvent], handler: EventHandler[StrictEvent]): ...
    def _wait_for_store_to_finish(self: Store[State, Action, Event]): ...
    def _handle_finish_event(self: Store[State, Action, Event]): ...
    def autorun(self: Store[State, Action, Event], selector: Callable[Any, SelectorOutput], comparator: Any): ...
    def view(self: Store[State, Action, Event], selector: Callable[Any, SelectorOutput]): ...
    def with_state(self: Store[State, Action, Event], selector: Callable[Any, SelectorOutput]): ...
    def snapshot(self: Store[State, Action, Event]): ...
    def register_action_middleware(self: Store[State, Action, Event], action_middleware: ActionMiddleware): ...
    def register_event_middleware(self: Store[State, Action, Event], event_middleware: EventMiddleware): ...
    def unregister_action_middleware(self: Store[State, Action, Event], action_middleware: ActionMiddleware): ...
    def unregister_event_middleware(self: Store[State, Action, Event], event_middleware: EventMiddleware): ...