from __future__ import annotations
import os
import hashlib
from typing import Optional
from PySide6.QtWidgets import QFrame, QLabel, QVBoxLayout, QSizePolicy
from PySide6.QtCore import Qt, QUrl, Signal, QSize, QRect
from PySide6.QtGui import QPixmap, QPainter, QPalette
from PySide6.QtNetwork import QNetworkAccessManager, QNetworkRequest, QNetworkReply
_pixmap_cache: dict[str, QPixmap]
_network_manager: Optional[QNetworkAccessManager]
def get_network_manager(): ...
class Skeleton:
    def __init__(self, parent): ...
class Img:
    def __init__(self, src: str, srcSet: str, alt: str, width: int, height: int, objectFit: str, loading: str, sx: Any, **kwargs): ...
    def load(self): ...
    def handle_reply(self, reply: QNetworkReply): ...
    def _resolve_url(self, srcSet: str): ...
    def _apply_pixmap(self, pixmap: QPixmap): ...
    def _update_display(self): ...
    def resizeEvent(self, event): ...