
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util
import jneqsim.neqsim.process.logic
import jneqsim.neqsim.process.processmodel
import jneqsim.neqsim.process.safety
import jneqsim.neqsim.process.util.monitor
import typing



class ProcessScenarioRunner:
    def __init__(self, processSystem: jneqsim.neqsim.process.processmodel.ProcessSystem): ...
    def activateLogic(self, string: typing.Union[java.lang.String, str]) -> bool: ...
    def addLogic(self, processLogic: jneqsim.neqsim.process.logic.ProcessLogic) -> None: ...
    def clearAllLogic(self) -> None: ...
    def findLogic(self, string: typing.Union[java.lang.String, str]) -> jneqsim.neqsim.process.logic.ProcessLogic: ...
    def getLogicSequences(self) -> java.util.List[jneqsim.neqsim.process.logic.ProcessLogic]: ...
    def getSystem(self) -> jneqsim.neqsim.process.processmodel.ProcessSystem: ...
    def initializeSteadyState(self) -> None: ...
    @typing.overload
    def removeLogic(self, string: typing.Union[java.lang.String, str]) -> bool: ...
    @typing.overload
    def removeLogic(self, processLogic: jneqsim.neqsim.process.logic.ProcessLogic) -> None: ...
    def renewSimulationId(self) -> None: ...
    def reset(self) -> None: ...
    def resetLogic(self) -> None: ...
    def runScenario(self, string: typing.Union[java.lang.String, str], processSafetyScenario: jneqsim.neqsim.process.safety.ProcessSafetyScenario, double: float, double2: float) -> 'ScenarioExecutionSummary': ...
    def runScenarioWithLogic(self, string: typing.Union[java.lang.String, str], processSafetyScenario: jneqsim.neqsim.process.safety.ProcessSafetyScenario, double: float, double2: float, list: java.util.List[typing.Union[java.lang.String, str]]) -> 'ScenarioExecutionSummary': ...

class ScenarioExecutionSummary:
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addError(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def addLogicResult(self, string: typing.Union[java.lang.String, str], logicState: jneqsim.neqsim.process.logic.LogicState, string2: typing.Union[java.lang.String, str]) -> None: ...
    def addWarning(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def getErrors(self) -> java.util.List[java.lang.String]: ...
    def getExecutionTime(self) -> int: ...
    def getKPI(self) -> jneqsim.neqsim.process.util.monitor.ScenarioKPI: ...
    def getLogicResults(self) -> java.util.Map[java.lang.String, 'ScenarioExecutionSummary.LogicResult']: ...
    def getScenario(self) -> jneqsim.neqsim.process.safety.ProcessSafetyScenario: ...
    def getScenarioName(self) -> java.lang.String: ...
    def getWarnings(self) -> java.util.List[java.lang.String]: ...
    def isSuccessful(self) -> bool: ...
    def printResults(self) -> None: ...
    def setExecutionTime(self, long: int) -> None: ...
    def setKPI(self, scenarioKPI: jneqsim.neqsim.process.util.monitor.ScenarioKPI) -> None: ...
    def setScenario(self, processSafetyScenario: jneqsim.neqsim.process.safety.ProcessSafetyScenario) -> None: ...
    class LogicResult:
        def __init__(self, logicState: jneqsim.neqsim.process.logic.LogicState, string: typing.Union[java.lang.String, str]): ...
        def getFinalState(self) -> jneqsim.neqsim.process.logic.LogicState: ...
        def getStatusDescription(self) -> java.lang.String: ...

class ScenarioTestRunner:
    def __init__(self, processScenarioRunner: ProcessScenarioRunner): ...
    def batch(self) -> 'ScenarioTestRunner.BatchExecutor': ...
    def displayDashboard(self) -> None: ...
    @typing.overload
    def executeScenario(self, string: typing.Union[java.lang.String, str], processSafetyScenario: jneqsim.neqsim.process.safety.ProcessSafetyScenario, double: float, double2: float) -> ScenarioExecutionSummary: ...
    @typing.overload
    def executeScenario(self, string: typing.Union[java.lang.String, str], processSafetyScenario: jneqsim.neqsim.process.safety.ProcessSafetyScenario, string2: typing.Union[java.lang.String, str], double: float, double2: float) -> ScenarioExecutionSummary: ...
    def executeScenarioWithDelayedActivation(self, string: typing.Union[java.lang.String, str], processSafetyScenario: jneqsim.neqsim.process.safety.ProcessSafetyScenario, string2: typing.Union[java.lang.String, str], long: int, string3: typing.Union[java.lang.String, str], double: float, double2: float) -> ScenarioExecutionSummary: ...
    def getDashboard(self) -> jneqsim.neqsim.process.util.monitor.KPIDashboard: ...
    def getRunner(self) -> ProcessScenarioRunner: ...
    def getScenarioCount(self) -> int: ...
    def printHeader(self) -> None: ...
    def resetCounter(self) -> None: ...
    class BatchExecutor:
        def __init__(self, scenarioTestRunner: 'ScenarioTestRunner'): ...
        def add(self, string: typing.Union[java.lang.String, str], processSafetyScenario: jneqsim.neqsim.process.safety.ProcessSafetyScenario, string2: typing.Union[java.lang.String, str], double: float, double2: float) -> 'ScenarioTestRunner.BatchExecutor': ...
        def addDelayed(self, string: typing.Union[java.lang.String, str], processSafetyScenario: jneqsim.neqsim.process.safety.ProcessSafetyScenario, string2: typing.Union[java.lang.String, str], long: int, string3: typing.Union[java.lang.String, str], double: float, double2: float) -> 'ScenarioTestRunner.BatchExecutor': ...
        def execute(self) -> None: ...
        def executeWithoutWrapper(self) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.neqsim.process.util.scenario")``.

    ProcessScenarioRunner: typing.Type[ProcessScenarioRunner]
    ScenarioExecutionSummary: typing.Type[ScenarioExecutionSummary]
    ScenarioTestRunner: typing.Type[ScenarioTestRunner]
