import uuid
import threading
from typing import Optional, Union, Dict, List, Callable
from qtmui.common.ui_functions import clear_layout
from PySide6.QtWidgets import QMenu, QFrame, QVBoxLayout, QWidget, QScrollArea, QGraphicsDropShadowEffect
from PySide6.QtCore import Qt, QPoint, Signal
from PySide6.QtGui import QFocusEvent, QColor
from qtmui.hooks import State
from qtmui.material.styles import useTheme
from ..utils.validate_params import _validate_param
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
from .menu_scroll_area import MenuScrollArea
class Menu:
    def __init__(self, open: Union[State, bool], anchorEl: Optional[Union[State, QWidget, Callable]], autoFocus: Union[State, bool], children: Optional[Union[State, List[QWidget], QWidget]], classes: Optional[Union[State, Dict]], disableAutoFocusItem: Union[State, bool], id: Optional[Union[State, str]], MenuListProps: Optional[Union[State, Dict]], minWidth: Optional[Union[State, int]], maxWidth: Optional[Union[State, int]], maxHeight: Optional[Union[State, int]], lock: Optional[Union[State, threading.Lock]], onClose: Optional[Union[State, Callable]], PopoverClasses: Optional[Union[State, Dict]], slotProps: Optional[Union[State, Dict[str, Union[Dict, Callable]]]], slots: Optional[Union[State, Dict[str, str]]], sx: Optional[Union[State, List, Dict, Callable, str]], transitionDuration: Optional[Union[State, str, int, Dict[str, int]]], TransitionProps: Optional[Union[State, Dict]], variant: Union[State, str], **kwargs): ...
    def _set_open(self, value): ...
    def _get_open(self): ...
    def _set_anchorEl(self, value): ...
    def _get_anchorEl(self): ...
    def _set_autoFocus(self, value): ...
    def _get_autoFocus(self): ...
    def _validate_children(self, value): ...
    def _get_children(self): ...
    def _set_classes(self, value): ...
    def _get_classes(self): ...
    def _set_disableAutoFocusItem(self, value): ...
    def _get_disableAutoFocusItem(self): ...
    def _set_id(self, value): ...
    def _get_id(self): ...
    def _set_MenuListProps(self, value): ...
    def _get_MenuListProps(self): ...
    def _set_minWidth(self, value): ...
    def _get_minWidth(self): ...
    def _set_maxWidth(self, value): ...
    def _get_maxWidth(self): ...
    def _set_maxHeight(self, value): ...
    def _get_maxHeight(self): ...
    def _set_lock(self, value): ...
    def _get_lock(self): ...
    def _set_onClose(self, value): ...
    def _get_onClose(self): ...
    def _set_PopoverClasses(self, value): ...
    def _get_PopoverClasses(self): ...
    def _set_slotProps(self, value): ...
    def _get_slotProps(self): ...
    def _set_slots(self, value): ...
    def _get_slots(self): ...
    def _set_sx(self, value): ...
    def _get_sx(self): ...
    def _set_transitionDuration(self, value): ...
    def _get_transitionDuration(self): ...
    def _set_TransitionProps(self, value): ...
    def _get_TransitionProps(self): ...
    def _set_variant(self, value): ...
    def _get_variant(self): ...
    def _init_ui(self): ...
    def setShadowEffect(self, blurRadius, offset, color): ...
    def slot_set_stylesheet(self, value): ...
    def retranslateUi(self): ...
    def _set_stylesheet(self): ...
    def _set_children(self, children): ...
    def _set_scroll_children(self, children): ...