# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self


class CreatePaymentOrderRequest(BaseModel):
    """
    CreatePaymentOrderRequest
    """  # noqa: E501
    merchant_id: StrictStr = Field(description="The merchant ID.")
    merchant_order_code: Optional[StrictStr] = Field(default=None, description="A unique reference code assigned by the merchant to identify this order in their system.")
    psp_order_code: StrictStr = Field(description="A unique reference code assigned by the developer to identify this order in their system.")
    pricing_currency: Optional[StrictStr] = Field(default=None, description="The pricing currency that denominates `pricing_amount` and `fee_amount`. If left empty, both values will be denominated in `payable_currency`.  Currently, For a complete list of supported currencies, see [Supported chains and tokens](https://www.cobo.com/developers/v2/guides/overview/supported-chains-and-tokens). ")
    pricing_amount: Optional[StrictStr] = Field(default=None, description="The base amount of the order, excluding the developer fee (specified in `fee_amount`). Values must be greater than `0` and contain two decimal places.")
    fee_amount: StrictStr = Field(description="The developer fee for the order. It is added to the base amount (`pricing_amount`) to determine the final charge. For example, if `pricing_amount` is \"100.00\" and `fee_amount` is \"2.00\", the payer will be charged \"102.00\" in total, with \"100.00\" being settled to the merchant account and \"2.00\" settled to the developer account. Values must be greater than 0 and contain two decimal places.")
    payable_currency: StrictStr = Field(description="The ID of the cryptocurrency used for payment. Supported values:   - USDC: `ETH_USDC`, `ARBITRUM_USDC`, `SOL_USDC`, `BASE_USDC`, `MATIC_USDC`, `BSC_USDC`   - USDT: `TRON_USDT`, `ETH_USDT`, `ARBITRUM_USDT`, `SOL_USDT`, `BASE_USDT`, `MATIC_USDT`, `BSC_USDT` ")
    payable_amount: Optional[StrictStr] = Field(default=None, description="The total amount the payer needs to pay, denominated in the specified `payable_currency`. If this field is left blank, the system will automatically calculate the amount at order creation using the following formula: (`pricing_amount` + `fee_amount`) / current exchange rate.  Values must be greater than 0 and contain two decimal places. ")
    expired_in: Optional[StrictInt] = Field(default=None, description="The pay-in order will expire after approximately a certain number of seconds: - The order status becomes final and cannot be changed - The `received_token_amount` field will no longer be updated - Funds received after expiration will be categorized as late payments and can only be settled from the developer balance. - A late payment will trigger a `transactionLate` webhook event. ")
    amount_tolerance: Optional[StrictStr] = Field(default=None, description="The allowed amount deviation, with precision up to 1 decimal place.  For example, if `payable_amount` is `100.00` and `amount_tolerance` is `0.50`: - Payer pays 99.55 → Success (difference of 0.45 ≤ 0.5) - Payer pays 99.40 → Underpaid (difference of 0.60 > 0.5) ")
    currency: Optional[StrictStr] = Field(default='', description="This field has been deprecated. Please use `pricing_currency` instead.")
    order_amount: Optional[StrictStr] = Field(default=None, description="This field has been deprecated. Please use `pricing_amount` instead.")
    token_id: Optional[StrictStr] = Field(default=None, description="This field has been deprecated. Please use `payable_currency` instead.")
    use_dedicated_address: Optional[StrictBool] = Field(default=None, description="This field has been deprecated.")
    custom_exchange_rate: Optional[StrictStr] = Field(default=None, description="This field has been deprecated.")
    __properties: ClassVar[List[str]] = ["merchant_id", "merchant_order_code", "psp_order_code", "pricing_currency", "pricing_amount", "fee_amount", "payable_currency", "payable_amount", "expired_in", "amount_tolerance", "currency", "order_amount", "token_id", "use_dedicated_address", "custom_exchange_rate"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreatePaymentOrderRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreatePaymentOrderRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "merchant_id": obj.get("merchant_id"),
            "merchant_order_code": obj.get("merchant_order_code"),
            "psp_order_code": obj.get("psp_order_code"),
            "pricing_currency": obj.get("pricing_currency"),
            "pricing_amount": obj.get("pricing_amount"),
            "fee_amount": obj.get("fee_amount"),
            "payable_currency": obj.get("payable_currency"),
            "payable_amount": obj.get("payable_amount"),
            "expired_in": obj.get("expired_in"),
            "amount_tolerance": obj.get("amount_tolerance"),
            "currency": obj.get("currency") if obj.get("currency") is not None else '',
            "order_amount": obj.get("order_amount"),
            "token_id": obj.get("token_id"),
            "use_dedicated_address": obj.get("use_dedicated_address"),
            "custom_exchange_rate": obj.get("custom_exchange_rate")
        })
        return _obj


