# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from cobo_waas2.models.settlement_info import SettlementInfo
from typing import Optional, Set
from typing_extensions import Self


class GetSettlementInfoByIds200Response(BaseModel):
    """
    GetSettlementInfoByIds200Response
    """  # noqa: E501
    psp_token_balances: Optional[List[SettlementInfo]] = None
    token_balances: Optional[List[SettlementInfo]] = None
    __properties: ClassVar[List[str]] = ["psp_token_balances", "token_balances"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetSettlementInfoByIds200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in psp_token_balances (list)
        _items = []
        if self.psp_token_balances:
            for _item in self.psp_token_balances:
                if _item:
                    _items.append(_item.to_dict())
            _dict['psp_token_balances'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in token_balances (list)
        _items = []
        if self.token_balances:
            for _item in self.token_balances:
                if _item:
                    _items.append(_item.to_dict())
            _dict['token_balances'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetSettlementInfoByIds200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "psp_token_balances": [SettlementInfo.from_dict(_item) for _item in obj["psp_token_balances"]] if obj.get("psp_token_balances") is not None else None,
            "token_balances": [SettlementInfo.from_dict(_item) for _item in obj["token_balances"]] if obj.get("token_balances") is not None else None
        })
        return _obj


