# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self


class TokenizationSolWrappedTokenPermissionParams(BaseModel):
    """
    Role-based permission settings for Solana wrapped token. The owner is automatically set to the address that calls the initialize function (typically the issuing wallet) and cannot be specified here. Only the wrapper and pauser roles can be configured during initialization.
    """  # noqa: E501
    wrapper: Optional[List[StrictStr]] = Field(default=None, description="List of Solana wallet addresses that can perform wrap/unwrap operations. Multiple addresses can be assigned this role.")
    pauser: Optional[StrictStr] = Field(default=None, description="Solana wallet address that acts as a pauser authority for the token. This authority can pause token transfers.")
    freezer: Optional[StrictStr] = Field(default=None, description="Solana wallet address that acts as a freezer authority for the token. This authority can freeze token accounts.")
    updater: Optional[StrictStr] = Field(default=None, description="Solana wallet address that acts as an updater authority for the token. This authority can update token metadata.")
    __properties: ClassVar[List[str]] = ["wrapper", "pauser", "freezer", "updater"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TokenizationSolWrappedTokenPermissionParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TokenizationSolWrappedTokenPermissionParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "wrapper": obj.get("wrapper"),
            "pauser": obj.get("pauser"),
            "freezer": obj.get("freezer"),
            "updater": obj.get("updater")
        })
        return _obj


