from functools import lru_cache
import uuid
from typing import Optional, Union, Callable, List
from PySide6.QtWidgets import QFrame, QVBoxLayout, QWidget, QApplication, QSizePolicy
from PySide6.QtCore import Qt
from qtmui.hooks import State
from qtmui.material.styles import useTheme
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
from ..widget_base import PyWidgetBase
from ..utils.validate_params import _validate_param
class Portal:
    def __init__(self, children: Optional[Union[State, QWidget, List[QWidget]]], container: Optional[Union[State, QWidget, Callable]], disablePortal: Union[State, bool], *args, **kwargs): ...
    def _set_children(self, value): ...
    def _get_children(self): ...
    def _set_container(self, value): ...
    def _get_container(self): ...
    def _set_disablePortal(self, value): ...
    def _get_disablePortal(self): ...
    def _init_ui(self): ...
    def _set_stylesheet(self, component_styled): ...
    def _connect_signals(self): ...
    def _on_children_changed(self): ...
    def _on_container_changed(self): ...
    def _on_disablePortal_changed(self): ...
    def _on_destroyed(self): ...