from qtmui.material.list_view.list_view import ListView
class TextFieldAutocompleteMixin:
    def __init__(self, **kwargs): ...
    def autocomplete_on_text_changed(self, s): ...
    def autocomplete_render_search_menu_items(self, search_options_results): ...