from typing import Callable, Optional, Union
import uuid
from PySide6.QtCore import Qt, Property, Slot
from PySide6.QtWidgets import QWidget, QVBoxLayout, QSizePolicy, QLabel, QHBoxLayout, QFrame
from qtmui.hooks import State
from ..autocomplete.complete import Autocomplete
from qtmui.material.styles import useTheme
from ..qss_name import *
class RHFAutocompleteGroup:
    def __init__(self, label: Optional[Union[str, State, Callable]], name: str, value: object, onValueChanged: Callable, direction: str, children: list): ...
    def setup_ui(self): ...
    def unselected_all_field(self): ...
    def on_fields_value_changed(self, value, item): ...
    def set_value(self, value): ...
    def stateSignal(self): ...
    def stateSignal(self, value): ...
    def state(self, state): ...