from typing import Optional, Union, Dict, Callable, List
from PySide6.QtWidgets import QVBoxLayout, QWidget, QApplication, QFrame, QSizePolicy, QSplitter, QGraphicsDropShadowEffect, QSplitterHandle
from PySide6.QtCore import Qt, QPoint, QEvent
from PySide6.QtGui import QColor
from qtmui.material.styles import useTheme
from qtmui.i18n.use_translation import i18n
from qtmui.hooks import State, useEffect
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
from ..utils.validate_params import _validate_param
class Drawer:
    def __init__(self, parent: Optional[QWidget], title: Optional[Union[State, str, Callable]], anchor: Union[State, str], anchorEl: Optional[Union[State, QWidget]], children: Optional[Union[State, QWidget, List[QWidget]]], classes: Optional[Union[State, Dict]], elevation: Union[State, int], hideBackdrop: Union[State, bool], ModalProps: Optional[Union[State, Dict]], onClose: Optional[Union[State, Callable]], open: Union[State, bool], PaperProps: Optional[Union[State, Dict]], SlideProps: Optional[Union[State, Dict]], slotProps: Optional[Union[State, Dict]], slots: Optional[Union[State, Dict]], sx: Optional[Union[State, Dict, Callable, str]], transitionDuration: Optional[Union[State, int, Dict]], variant: Optional[Union[State, str]], minWidth: Optional[Union[State, int]], maxWidth: Optional[Union[State, int]], minHeight: Optional[Union[State, int]], maxHeight: Optional[Union[State, int]], *args, **kwargs): ...
    def _set_title(self, value): ...
    def _get_title(self): ...
    def _set_anchor(self, value): ...
    def _get_anchor(self): ...
    def _set_anchorEl(self, value): ...
    def _get_anchorEl(self): ...
    def _set_children(self, value): ...
    def _get_children(self): ...
    def _set_classes(self, value): ...
    def _get_classes(self): ...
    def _set_elevation(self, value): ...
    def _get_elevation(self): ...
    def _set_hideBackdrop(self, value): ...
    def _get_hideBackdrop(self): ...
    def _set_ModalProps(self, value): ...
    def _get_ModalProps(self): ...
    def _set_onClose(self, value): ...
    def _get_onClose(self): ...
    def _set_open(self, value): ...
    def _get_open(self): ...
    def _set_PaperProps(self, value): ...
    def _get_PaperProps(self): ...
    def _set_SlideProps(self, value): ...
    def _get_SlideProps(self): ...
    def _set_slotProps(self, value): ...
    def _get_slotProps(self): ...
    def _set_slots(self, value): ...
    def _get_slots(self): ...
    def _set_sx(self, value): ...
    def _get_sx(self): ...
    def _set_transitionDuration(self, value): ...
    def _get_transitionDuration(self): ...
    def _set_variant(self, value): ...
    def _get_variant(self): ...
    def _set_minWidth(self, value): ...
    def _get_minWidth(self): ...
    def _set_maxWidth(self, value): ...
    def _get_maxWidth(self): ...
    def _set_minHeight(self, value): ...
    def _get_minHeight(self): ...
    def _set_maxHeight(self, value): ...
    def _get_maxHeight(self): ...
    def __setupStates(self): ...
    def _init_ui(self): ...
    def __setupSize(self, value): ...
    def _set_stylesheet(self): ...
    def setShadowEffect(self, blurRadius, offset, color): ...
    def reTranslation(self): ...
    def _show(self, state: bool): ...
    def _close(self): ...
    def hideEvent(self, event): ...
    def update_position(self): ...
    def eventFilter(self, source, event): ...