"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from glean.api_client.types import BaseModel, UNSET_SENTINEL
from glean.api_client.utils import FieldMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetdocvisibilityRequestTypedDict(TypedDict):
    doc_ids: NotRequired[List[str]]
    r"""List of doc-ids which will have their hide status fetched."""


class GetdocvisibilityRequest(BaseModel):
    doc_ids: Annotated[
        Optional[List[str]],
        pydantic.Field(alias="docIds"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""List of doc-ids which will have their hide status fetched."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["docIds"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
