from enum import Enum


class SyncEntityType(str, Enum):
    ALBUMASSETBACKFILLV1 = "AlbumAssetBackfillV1"
    ALBUMASSETCREATEV1 = "AlbumAssetCreateV1"
    ALBUMASSETEXIFBACKFILLV1 = "AlbumAssetExifBackfillV1"
    ALBUMASSETEXIFCREATEV1 = "AlbumAssetExifCreateV1"
    ALBUMASSETEXIFUPDATEV1 = "AlbumAssetExifUpdateV1"
    ALBUMASSETUPDATEV1 = "AlbumAssetUpdateV1"
    ALBUMDELETEV1 = "AlbumDeleteV1"
    ALBUMTOASSETBACKFILLV1 = "AlbumToAssetBackfillV1"
    ALBUMTOASSETDELETEV1 = "AlbumToAssetDeleteV1"
    ALBUMTOASSETV1 = "AlbumToAssetV1"
    ALBUMUSERBACKFILLV1 = "AlbumUserBackfillV1"
    ALBUMUSERDELETEV1 = "AlbumUserDeleteV1"
    ALBUMUSERV1 = "AlbumUserV1"
    ALBUMV1 = "AlbumV1"
    ASSETDELETEV1 = "AssetDeleteV1"
    ASSETEXIFV1 = "AssetExifV1"
    ASSETFACEDELETEV1 = "AssetFaceDeleteV1"
    ASSETFACEV1 = "AssetFaceV1"
    ASSETMETADATADELETEV1 = "AssetMetadataDeleteV1"
    ASSETMETADATAV1 = "AssetMetadataV1"
    ASSETV1 = "AssetV1"
    AUTHUSERV1 = "AuthUserV1"
    MEMORYDELETEV1 = "MemoryDeleteV1"
    MEMORYTOASSETDELETEV1 = "MemoryToAssetDeleteV1"
    MEMORYTOASSETV1 = "MemoryToAssetV1"
    MEMORYV1 = "MemoryV1"
    PARTNERASSETBACKFILLV1 = "PartnerAssetBackfillV1"
    PARTNERASSETDELETEV1 = "PartnerAssetDeleteV1"
    PARTNERASSETEXIFBACKFILLV1 = "PartnerAssetExifBackfillV1"
    PARTNERASSETEXIFV1 = "PartnerAssetExifV1"
    PARTNERASSETV1 = "PartnerAssetV1"
    PARTNERDELETEV1 = "PartnerDeleteV1"
    PARTNERSTACKBACKFILLV1 = "PartnerStackBackfillV1"
    PARTNERSTACKDELETEV1 = "PartnerStackDeleteV1"
    PARTNERSTACKV1 = "PartnerStackV1"
    PARTNERV1 = "PartnerV1"
    PERSONDELETEV1 = "PersonDeleteV1"
    PERSONV1 = "PersonV1"
    STACKDELETEV1 = "StackDeleteV1"
    STACKV1 = "StackV1"
    SYNCACKV1 = "SyncAckV1"
    SYNCCOMPLETEV1 = "SyncCompleteV1"
    SYNCRESETV1 = "SyncResetV1"
    USERDELETEV1 = "UserDeleteV1"
    USERMETADATADELETEV1 = "UserMetadataDeleteV1"
    USERMETADATAV1 = "UserMetadataV1"
    USERV1 = "UserV1"

    def __str__(self) -> str:
        return str(self.value)
