"""Tests for the n8n client.

Generated by GRIMLOCK MCP Factory
"""

import httpx
import pytest
import respx

from n8n_mcp.clients.n8n import N8nClient


class TestN8nClient:
    """Tests for N8nClient."""

    def test_init_with_env_vars(self, mock_env: None) -> None:
        """Test client initialization with environment variables."""
        client = N8nClient()
        assert client.base_url == "https://test-n8n.app.n8n.cloud"
        assert client.api_key == "test-api-key-12345"

    def test_init_with_explicit_values(self) -> None:
        """Test client initialization with explicit values."""
        client = N8nClient(
            base_url="https://custom.n8n.cloud",
            api_key="custom-key",
        )
        assert client.base_url == "https://custom.n8n.cloud"
        assert client.api_key == "custom-key"

    def test_base_url_trailing_slash_stripped(self) -> None:
        """Test that trailing slash is stripped from base URL."""
        client = N8nClient(base_url="https://test.n8n.cloud/")
        assert client.base_url == "https://test.n8n.cloud"

    def test_get_headers(self, mock_env: None) -> None:
        """Test that headers include API key."""
        client = N8nClient()
        headers = client._get_headers()
        assert headers["X-N8N-API-KEY"] == "test-api-key-12345"
        assert headers["Content-Type"] == "application/json"
        assert headers["Accept"] == "application/json"


class TestListWorkflows:
    """Tests for list_workflows method."""

    @pytest.mark.asyncio
    async def test_list_workflows_success(
        self,
        mock_env: None,
        mock_httpx_client: respx.MockRouter,
        sample_workflows_response: dict,
    ) -> None:
        """Test successful workflow listing."""
        mock_httpx_client.get(
            "https://test-n8n.app.n8n.cloud/api/v1/workflows"
        ).mock(return_value=httpx.Response(200, json=sample_workflows_response))

        client = N8nClient()
        workflows = await client.list_workflows()

        assert len(workflows) == 3
        assert workflows[0]["name"] == "Email Notification Workflow"
        assert workflows[0]["active"] is True
        assert workflows[2]["active"] is False

    @pytest.mark.asyncio
    async def test_list_workflows_empty(
        self,
        mock_env: None,
        mock_httpx_client: respx.MockRouter,
        sample_empty_workflows_response: dict,
    ) -> None:
        """Test listing workflows when none exist."""
        mock_httpx_client.get(
            "https://test-n8n.app.n8n.cloud/api/v1/workflows"
        ).mock(return_value=httpx.Response(200, json=sample_empty_workflows_response))

        client = N8nClient()
        workflows = await client.list_workflows()

        assert workflows == []

    @pytest.mark.asyncio
    async def test_list_workflows_auth_error(
        self,
        mock_env: None,
        mock_httpx_client: respx.MockRouter,
    ) -> None:
        """Test authentication error handling."""
        mock_httpx_client.get(
            "https://test-n8n.app.n8n.cloud/api/v1/workflows"
        ).mock(return_value=httpx.Response(401, json={"message": "Unauthorized"}))

        client = N8nClient()
        with pytest.raises(httpx.HTTPStatusError):
            await client.list_workflows()


class TestGetWorkflow:
    """Tests for get_workflow method."""

    @pytest.mark.asyncio
    async def test_get_workflow_success(
        self,
        mock_env: None,
        mock_httpx_client: respx.MockRouter,
        sample_workflow_detail_response: dict,
    ) -> None:
        """Test successful workflow retrieval."""
        mock_httpx_client.get(
            "https://test-n8n.app.n8n.cloud/api/v1/workflows/1"
        ).mock(return_value=httpx.Response(200, json=sample_workflow_detail_response))

        client = N8nClient()
        workflow = await client.get_workflow("1")

        assert workflow["id"] == "1"
        assert workflow["name"] == "Email Notification Workflow"
        assert len(workflow["nodes"]) == 2

    @pytest.mark.asyncio
    async def test_get_workflow_not_found(
        self,
        mock_env: None,
        mock_httpx_client: respx.MockRouter,
    ) -> None:
        """Test workflow not found error."""
        mock_httpx_client.get(
            "https://test-n8n.app.n8n.cloud/api/v1/workflows/999"
        ).mock(return_value=httpx.Response(404, json={"message": "Workflow not found"}))

        client = N8nClient()
        with pytest.raises(httpx.HTTPStatusError):
            await client.get_workflow("999")


class TestListExecutions:
    """Tests for list_executions method."""

    @pytest.mark.asyncio
    async def test_list_executions_success(
        self,
        mock_env: None,
        mock_httpx_client: respx.MockRouter,
        sample_executions_response: dict,
    ) -> None:
        """Test successful execution listing."""
        mock_httpx_client.get(
            "https://test-n8n.app.n8n.cloud/api/v1/executions"
        ).mock(return_value=httpx.Response(200, json=sample_executions_response))

        client = N8nClient()
        executions = await client.list_executions()

        assert len(executions) == 5
        assert executions[0]["status"] == "success"
        assert executions[2]["status"] == "error"

    @pytest.mark.asyncio
    async def test_list_executions_with_filters(
        self,
        mock_env: None,
        mock_httpx_client: respx.MockRouter,
        sample_executions_response: dict,
    ) -> None:
        """Test execution listing with filters."""
        mock_httpx_client.get(
            "https://test-n8n.app.n8n.cloud/api/v1/executions"
        ).mock(return_value=httpx.Response(200, json=sample_executions_response))

        client = N8nClient()
        executions = await client.list_executions(
            workflow_id="1",
            status="success",
            limit=10,
        )

        # Just verify it returns successfully (filtering happens server-side)
        assert isinstance(executions, list)


class TestCheckWorkflows:
    """Tests for check_workflows method."""

    @pytest.mark.asyncio
    async def test_check_workflows_success(
        self,
        mock_env: None,
        mock_httpx_client: respx.MockRouter,
        sample_workflows_response: dict,
        sample_executions_response: dict,
    ) -> None:
        """Test successful workflow check."""
        mock_httpx_client.get(
            "https://test-n8n.app.n8n.cloud/api/v1/workflows"
        ).mock(return_value=httpx.Response(200, json=sample_workflows_response))

        mock_httpx_client.get(
            "https://test-n8n.app.n8n.cloud/api/v1/executions"
        ).mock(return_value=httpx.Response(200, json=sample_executions_response))

        client = N8nClient()
        result = await client.check_workflows()

        assert result["total_workflows"] == 3
        assert result["active_workflows"] == 2
        assert result["inactive_workflows"] == 1
        assert result["workflows_with_errors"] == 1  # Workflow 2 has errors
        assert len(result["workflows"]) == 3

    @pytest.mark.asyncio
    async def test_check_workflows_empty(
        self,
        mock_env: None,
        mock_httpx_client: respx.MockRouter,
        sample_empty_workflows_response: dict,
        sample_empty_executions_response: dict,
    ) -> None:
        """Test check with no workflows."""
        mock_httpx_client.get(
            "https://test-n8n.app.n8n.cloud/api/v1/workflows"
        ).mock(return_value=httpx.Response(200, json=sample_empty_workflows_response))

        mock_httpx_client.get(
            "https://test-n8n.app.n8n.cloud/api/v1/executions"
        ).mock(return_value=httpx.Response(200, json=sample_empty_executions_response))

        client = N8nClient()
        result = await client.check_workflows()

        assert result["total_workflows"] == 0
        assert result["active_workflows"] == 0
        assert result["inactive_workflows"] == 0
        assert result["workflows_with_errors"] == 0
        assert result["workflows"] == []

    @pytest.mark.asyncio
    async def test_check_workflows_execution_stats(
        self,
        mock_env: None,
        mock_httpx_client: respx.MockRouter,
        sample_workflows_response: dict,
        sample_executions_response: dict,
    ) -> None:
        """Test that execution stats are correctly calculated."""
        mock_httpx_client.get(
            "https://test-n8n.app.n8n.cloud/api/v1/workflows"
        ).mock(return_value=httpx.Response(200, json=sample_workflows_response))

        mock_httpx_client.get(
            "https://test-n8n.app.n8n.cloud/api/v1/executions"
        ).mock(return_value=httpx.Response(200, json=sample_executions_response))

        client = N8nClient()
        result = await client.check_workflows()

        # Find workflow 1 in results
        wf1 = next(w for w in result["workflows"] if w["id"] == "1")
        assert wf1["recent_executions"]["success"] == 2
        assert wf1["recent_executions"]["error"] == 0

        # Find workflow 2 in results
        wf2 = next(w for w in result["workflows"] if w["id"] == "2")
        assert wf2["recent_executions"]["success"] == 1
        assert wf2["recent_executions"]["error"] == 2

        # Verify error_workflows includes workflow 2
        error_wf = result["error_workflows"][0]
        assert error_wf["id"] == "2"
        assert error_wf["errors"] == 2
