from typing import Any, Dict, List, Optional, Union

from com.inductiveautomation.ignition.common import BasicDataset
from java.lang import Object
from java.util import AbstractList

class QueryResults(AbstractList):
    class Row(Object):
        def getKeys(self) -> List[Union[str, unicode]]: ...
        def getKeyValue(self, aKey: Union[str, unicode]) -> Object: ...

    def __init__(
        self,
        dataset: BasicDataset,
        parent: Optional[Any] = ...,
        parentRow: Optional[int] = ...,
    ) -> None: ...
    def addNestedQueryResults(
        self, key: Union[str, unicode], results: QueryResults
    ) -> None: ...
    def get(self, index: int) -> QueryResults.Row: ...
    def getCoreResults(self) -> BasicDataset: ...
    def getNestedQueryResults(
        self,
    ) -> Dict[Union[str, unicode], List[QueryResults]]: ...
    def lookup(self, rowIndex: int, keyName: Union[str, unicode]) -> Object: ...
    def size(self) -> int: ...
