# coding: utf-8

"""
    Trust Layer API

    API documentation for Trust Layer front-facing endpoints (Catalogs, Versions, Proofs).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.default_response_recommended4_anchors_inner import DefaultResponseRecommended4AnchorsInner

class TestDefaultResponseRecommended4AnchorsInner(unittest.TestCase):
    """DefaultResponseRecommended4AnchorsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DefaultResponseRecommended4AnchorsInner:
        """Test DefaultResponseRecommended4AnchorsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DefaultResponseRecommended4AnchorsInner`
        """
        model = DefaultResponseRecommended4AnchorsInner()
        if include_optional:
            return DefaultResponseRecommended4AnchorsInner(
                blockchain = '',
                transaction_id = '',
                transaction_ts = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                confirmations = 56,
                blockchain_merkle_hash = ''
            )
        else:
            return DefaultResponseRecommended4AnchorsInner(
                blockchain = '',
                transaction_id = '',
                transaction_ts = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                confirmations = 56,
                blockchain_merkle_hash = '',
        )
        """

    def testDefaultResponseRecommended4AnchorsInner(self):
        """Test DefaultResponseRecommended4AnchorsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
