# coding: utf-8

"""
    Trust Layer API

    API documentation for Trust Layer front-facing endpoints (Catalogs, Versions, Proofs).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.default_response_recommended1 import DefaultResponseRecommended1

class TestDefaultResponseRecommended1(unittest.TestCase):
    """DefaultResponseRecommended1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DefaultResponseRecommended1:
        """Test DefaultResponseRecommended1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DefaultResponseRecommended1`
        """
        model = DefaultResponseRecommended1()
        if include_optional:
            return DefaultResponseRecommended1(
                status = '',
                message = '',
                job_id = '',
                catalog_id = '',
                version_id = None,
                changes = { }
            )
        else:
            return DefaultResponseRecommended1(
                status = '',
                message = '',
                job_id = '',
                catalog_id = '',
                version_id = None,
                changes = { },
        )
        """

    def testDefaultResponseRecommended1(self):
        """Test DefaultResponseRecommended1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
