from __future__ import annotations
import time
from typing import Any, Callable, TypeVar
from qtmui.redux import BaseAction
from .effects import cancel, delay, fork, take
def takeEvery(action_type: type[A], worker: Callable[Any, Any]): ...
def takeLatest(action_type: type[A], worker: Callable[Any, Any]): ...
def debounceLatest(action_type: type[A], seconds: float, worker: Callable[Any, Any]): ...
def throttle(action_type: type[A], seconds: float, worker: Callable[Any, Any]): ...