import uuid
from typing import Optional, Union, Dict, List, Callable
from PySide6.QtWidgets import QFrame, QVBoxLayout, QHBoxLayout, QWidget, QSizePolicy
from PySide6.QtCore import Qt
from qtmui.hooks import State
from qtmui.material.styles import useTheme
from ..typography import Typography
from ..utils.validate_params import _validate_param
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
class ListItem:
    def __init__(self, key: Optional[Union[State, str]], alignItems: Union[State, str], children: Optional[Union[State, QWidget, List[Union[QWidget, str]]]], classes: Optional[Union[State, Dict]], component: Optional[Union[State, str]], components: Optional[Union[State, Dict]], componentsProps: Optional[Union[State, Dict]], ContainerComponent: Optional[Union[State, str]], ContainerProps: Optional[Union[State, Dict]], dense: Union[State, bool], disableGutters: Union[State, bool], disablePadding: Union[State, bool], divider: Union[State, bool], secondaryAction: Optional[Union[State, QWidget, List[QWidget]]], slotProps: Optional[Union[State, Dict]], slots: Optional[Union[State, Dict]], sx: Optional[Union[State, List, Dict, Callable, str]], **kwargs): ...
    def _set_key(self, value): ...
    def _get_key(self): ...
    def _set_alignItems(self, value): ...
    def _get_alignItems(self): ...
    def _set_children(self, value): ...
    def _get_children(self): ...
    def _set_classes(self, value): ...
    def _get_classes(self): ...
    def _set_component(self, value): ...
    def _get_component(self): ...
    def _set_components(self, value): ...
    def _get_components(self): ...
    def _set_componentsProps(self, value): ...
    def _get_componentsProps(self): ...
    def _set_ContainerComponent(self, value): ...
    def _get_ContainerComponent(self): ...
    def _set_ContainerProps(self, value): ...
    def _get_ContainerProps(self): ...
    def _set_dense(self, value): ...
    def _get_dense(self): ...
    def _set_disableGutters(self, value): ...
    def _get_disableGutters(self): ...
    def _set_disablePadding(self, value): ...
    def _get_disablePadding(self): ...
    def _set_divider(self, value): ...
    def _get_divider(self): ...
    def _set_secondaryAction(self, value): ...
    def _get_secondaryAction(self): ...
    def _set_slotProps(self, value): ...
    def _get_slotProps(self): ...
    def _set_slots(self, value): ...
    def _get_slots(self): ...
    def _set_sx(self, value): ...
    def _get_sx(self): ...
    def _init_ui(self): ...