from __future__ import annotations
from typing import Optional, Union, Callable
import threading
import time
from PySide6.QtWidgets import QVBoxLayout, QStackedWidget, QStackedLayout, QSizePolicy
from ..stack import Stack
from ..box import Box
from typing import TYPE_CHECKING
class Carousel:
    def __init__(self, carouselArrowIndex: CarouselArrowIndex, children: object, height: int, ratio: str, arrows: bool, dots: bool, fade: bool, rtl: bool, autoplay: bool, autoplayTime: int, beforeChange: Callable, ref: Optional[dict], *args, **kwargs): ...
    def _init_ui(self): ...
    def _autorun_next(self): ...
    def _set_current_index(self, index): ...
    def _render_top_widget(self): ...
    def resizeEvent(self, event): ...