import dataclasses
import ssl
from _typeshed import Incomplete
from typing import Any, ClassVar, Literal

__all__ = ['RedisClient', 'TLSConfig']

class TLSConfig:
    __dataclass_params__: ClassVar[dataclasses._DataclassParams] = ...
    __dataclass_fields__: ClassVar[dict] = ...
    __match_args__: ClassVar[tuple] = ...
    ca_certs: Incomplete
    cert_reqs: Incomplete
    certfile: Incomplete
    keyfile: Incomplete
    def __post_init__(self) -> None: ...
    def to_ssl_context(self) -> ssl.SSLContext: ...
    def __replace__(self, **changes): ...
    def __hash__(self) -> int: ...
    def __init__(self, ca_certs: str, certfile: str | None = ..., keyfile: str | None = ..., cert_reqs: Literal['required', 'optional', 'none'] = ...) -> None: ...
    def __eq__(self, other) -> bool: ...
    def __setattr__(self, name, value): ...
    def __delattr__(self, name): ...

class RedisClient:
    def __init__(self, host: str = ..., port: int = ..., password: str | None = ..., tls_config: TLSConfig | None = ..., socket_timeout: float | None = ..., socket_connect_timeout: float | None = ...) -> None: ...
    @classmethod
    def from_config(cls, config: RedisConfig) -> RedisClient: ...
    def connect(self) -> None: ...
    def _connect_standalone(self) -> None: ...
    def _connect_sentinel(self) -> None: ...
    def disconnect(self) -> None: ...
    def hset(self, name: str, mapping: dict[str, Any]) -> int: ...
    def hgetall(self, name: str) -> dict[str, Any]: ...
    def hdel(self, name: str, *keys: str) -> int: ...
    def set(self, name: str, value: str, ex: int | None = ...) -> bool: ...
    def get(self, name: str) -> str | None: ...
    def sadd(self, name: str, *values: str) -> int: ...
    def srem(self, name: str, *values: str) -> int: ...
    def smembers(self, name: str) -> set[str]: ...
    def publish(self, channel: str, message: str) -> int: ...
    def delete(self, *names: str) -> int: ...
    def exists(self, *names: str) -> int: ...
    def expire(self, name: str, seconds: int) -> bool: ...
    def __aenter__(self) -> RedisClient: ...
    def __aexit__(self, exc_type, exc_val, exc_tb) -> None: ...
    @property
    def is_connected(self): ...
    @property
    def is_sentinel_mode(self): ...
