class PVDataService:
    def __init__(self, max_history: int = ...) -> None: ...
    def append(self, power: float | None) -> None: ...
    def get_history(self) -> list[float]: ...
    def get_latest(self) -> float | None: ...
    def get_average(self) -> float | None: ...
    def clear(self) -> None: ...
    def __len__(self) -> int: ...
    @property
    def max_history(self): ...
    @property
    def count(self): ...
