"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class UgcType(str, Enum):
    ANNOUNCEMENTS_TYPE = "ANNOUNCEMENTS_TYPE"
    ANSWERS_TYPE = "ANSWERS_TYPE"
    COLLECTIONS_TYPE = "COLLECTIONS_TYPE"
    SHORTCUTS_TYPE = "SHORTCUTS_TYPE"
    WORKFLOWS_TYPE = "WORKFLOWS_TYPE"
    PROMPT_TEMPLATES_TYPE = "PROMPT_TEMPLATES_TYPE"
