from typing import Union, Callable, List
class Spacing:
    def __call__(self, *args): ...
def createUnarySpacing(spacingInput: SpacingOptions): ...
def create_spacing(spacingInput: SpacingOptions): ...