# SPDX-License-Identifier: Apache-2.0
# Copyright © 2025 Bijan Mousavi

"""Module definitions for spec/ontology/__init__.py."""

from __future__ import annotations

from agentic_flows.spec.ontology.artifact_types import ArtifactType
from agentic_flows.spec.ontology.ids import (
    ActionID,
    AgentID,
    ArtifactID,
    BundleID,
    ClaimID,
    ContentHash,
    ContractID,
    DatasetID,
    EnvironmentFingerprint,
    EvidenceID,
    FlowID,
    GateID,
    InputsFingerprint,
    PlanHash,
    RequestID,
    ResolverID,
    RuleID,
    StepID,
    ToolID,
    VersionID,
)
from agentic_flows.spec.ontology.ontology import (
    ArbitrationRule,
    ArtifactScope,
    CausalityTag,
    DatasetState,
    DeterminismClass,
    DeterminismLevel,
    EntropyExhaustionAction,
    EntropyMagnitude,
    EntropySeverity,
    EvidenceDeterminism,
    FlowState,
    ReasonCode,
    ReplayMode,
    StepType,
    VerificationPhase,
    VerificationRandomness,
)
from agentic_flows.spec.ontology.public import (
    EntropySource,
    EventType,
    NonDeterminismIntentSource,
    ReplayAcceptability,
)

__all__ = [
    "ActionID",
    "AgentID",
    "ArtifactID",
    "ArtifactType",
    "ArtifactScope",
    "ArbitrationRule",
    "BundleID",
    "CausalityTag",
    "ClaimID",
    "ContentHash",
    "ContractID",
    "DatasetID",
    "DatasetState",
    "DeterminismClass",
    "DeterminismLevel",
    "EntropyExhaustionAction",
    "EntropySeverity",
    "EnvironmentFingerprint",
    "EvidenceID",
    "EvidenceDeterminism",
    "EntropyMagnitude",
    "EntropySource",
    "EventType",
    "FlowID",
    "FlowState",
    "GateID",
    "InputsFingerprint",
    "PlanHash",
    "ReplayAcceptability",
    "ReplayMode",
    "RequestID",
    "ReasonCode",
    "ResolverID",
    "RuleID",
    "StepID",
    "StepType",
    "VerificationPhase",
    "VerificationRandomness",
    "NonDeterminismIntentSource",
    "ToolID",
    "VersionID",
]
