from typing import Generic, List, Sequence, Tuple, TypeVar, Union
from ._generic_slider import CC_SLIDER, SC_GROOVE, SC_HANDLE, SC_NONE, _GenericSlider
from ._range_style import RangeSliderStyle, update_styles_from_stylesheet
from PySide6 import QtGui
from PySide6.QtCore import Property, QEvent, QPoint, QPointF, QRect, QRectF, Qt, Signal
from PySide6.QtWidgets import QSlider, QStyle, QStyleOptionSlider, QStylePainter
class _GenericRangeSlider:
    def __init__(self, *args, **kwargs): ...
    def barIsRigid(self): ...
    def setBarIsRigid(self, val: bool): ...
    def barMovesAllHandles(self): ...
    def setBarMovesAllHandles(self, val: bool): ...
    def barIsVisible(self): ...
    def setBarVisible(self, val: bool): ...
    def hideBar(self): ...
    def showBar(self): ...
    def value(self): ...
    def sliderPosition(self): ...
    def setSliderPosition(self, pos: Union[float, Sequence[float]], index): ...
    def setStyleSheet(self, styleSheet: str): ...
    def event(self, ev: QEvent): ...
    def mouseMoveEvent(self, ev: QtGui.QMouseEvent): ...
    def _setPosition(self, val): ...
    def _bound(self, value, index): ...
    def _neighbor_bound(self, val, index): ...
    def _getBarColor(self): ...
    def _setBarColor(self, color): ...
    def _offsetAllPositions(self, offset: float, ref): ...
    def _fixStyleOption(self, option): ...
    def _optSliderPositions(self): ...
    def _handleRect(self, handle_index: int, opt: QStyleOptionSlider): ...
    def _barRect(self, opt: QStyleOptionSlider): ...
    def _drawBar(self, painter: QStylePainter, opt: QStyleOptionSlider): ...
    def _draw_handle(self, painter: QStylePainter, opt: QStyleOptionSlider): ...
    def _updateHoverControl(self, pos): ...
    def _updatePressedControl(self, pos): ...
    def _setClickOffset(self, pos): ...
    def _getControlAtPos(self, pos: QPoint, opt: QStyleOptionSlider): ...
    def _execute_scroll(self, steps_to_scroll, modifiers): ...
    def _has_scroll_space_left(self, offset): ...
    def _spreadAllPositions(self, shrink, gain, ref): ...