# This file is part of the mlhp project. License: See LICENSE

set( MLHP_CORE_SOURCES 
     algorithm.cpp 
     assembly.cpp 
     basis.cpp
     basisevaluation.cpp 
     boundary.cpp 
     dense.cpp 
     implicit.cpp 
     integrands.cpp 
     kdtree.cpp
     utilities.cpp 
     mesh.cpp 
     multilevelhpcore.cpp 
     numeric.cpp 
     parallel.cpp
     partitioning.cpp 
     polynomials.cpp
     postprocessing.cpp 
     quadrature.cpp 
     refinement.cpp
     sparse.cpp 
     spatial.cpp 
     topologycore.cpp 
     triangulation.cpp 
)

set( MLHP_CORE_INCLUDES 
     algorithm.hpp 
     alias.hpp 
     arrayfunctions.hpp 
     assembly.hpp 
     assembly_impl.hpp 
     basis.hpp 
     basis_impl.hpp 
     basisevaluation.hpp 
     basisevaluation_impl.hpp
     boundary.hpp 
     compilermacros.hpp 
     dense.hpp 
     dense_impl.hpp
     derivativeHelper.hpp 
     derivativeHelper_impl.hpp 
     forwarddeclare.hpp
     implicit.hpp 
     implicit_impl.hpp 
     integrands.hpp 
     integrandtypes.hpp 
     kdtree.hpp
     mapping.hpp 
     memory.hpp 
     mesh.hpp 
     mesh_impl.hpp 
     multilevelhpcore.hpp 
     ndarray.hpp
     ndarray_impl.hpp 
     numeric.hpp 
     parallel.hpp 
     partitioning.hpp
     polynomials.hpp 
     postprocessing.hpp 
     postprocessing_impl.hpp
     quadrature.hpp 
     refinement.hpp 
     sparse.hpp 
     spatial.hpp 
     spatial_impl.hpp
     topologycore.hpp
     triangulation.hpp
     utilities.hpp 
     utilities_impl.hpp 
)
