import inspect
import weakref
from typing import Callable, List, Optional, Any
from PySide6.QtCore import QTimer, QObject
from .use_state import State
from ._effect_context import _get_current_effects
class _EffectRunner:
    def __init__(self, callback: Callable, deps: List[State]): ...
    def _setup(self): ...
    def run(self): ...
    def destroy(self): ...
def useEffect(callback: Callable, dependencies: List[State]): ...
def useLayoutEffect(callback: Callable, dependencies: List[State]): ...