import dataclasses
import enum
from typing import Any, ClassVar

__all__ = ['WriteResult', 'WriteStatus', 'ValidatedWriter']

class WriteStatus(enum.Enum):
    _new_member_: ClassVar[builtin_function_or_method] = ...
    _use_args_: ClassVar[bool] = ...
    _member_names_: ClassVar[list] = ...
    _member_map_: ClassVar[dict] = ...
    _value2member_map_: ClassVar[dict] = ...
    _hashable_values_: ClassVar[list] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _member_type_: ClassVar[type[object]] = ...
    _value_repr_: ClassVar[None] = ...
    SUCCESS: ClassVar[WriteStatus] = ...
    VALIDATION_FAILED: ClassVar[WriteStatus] = ...
    WRITE_FAILED: ClassVar[WriteStatus] = ...
    VERIFICATION_FAILED: ClassVar[WriteStatus] = ...
    @staticmethod
    def _generate_next_value_(name, start, count, last_values): ...
    @classmethod
    def __init__(cls, value) -> None: ...

class WriteResult:
    error_message: ClassVar[str] = ...
    __dataclass_params__: ClassVar[dataclasses._DataclassParams] = ...
    __dataclass_fields__: ClassVar[dict] = ...
    __match_args__: ClassVar[tuple] = ...
    def __replace__(self, **changes): ...
    def __hash__(self) -> int: ...
    def __init__(self, status: WriteStatus, point_name: str, value: Any, error_message: str = ...) -> None: ...
    def __eq__(self, other) -> bool: ...
    def __setattr__(self, name, value): ...
    def __delattr__(self, name): ...

class ValidatedWriter:
    def __init__(self, client: AsyncModbusClientBase, unit_id: int = ..., address_offset: int = ...) -> None: ...
    def write(self, point: WritePoint, value: Any, verify: bool = ...) -> WriteResult: ...
    def _encode(self, point: WritePoint, value: Any) -> list[int] | int | bool: ...
    def _write_to_device(self, point: WritePoint, encoded: list[int] | int | bool): ...
    def _read_back(self, point: WritePoint) -> Any: ...
    @staticmethod
    def _values_equal(expected: Any, actual: Any) -> bool: ...
