import inspect
from typing import Callable, Optional, List
import hashlib
from functools import lru_cache, partial
from PySide6.QtCore import QObject, Signal
from .use_state import State, useState
class MemoHook:
    def __init__(self): ...
    def _hash_deps(self, deps: List): ...
    def use_memo(self, fn: Callable, deps: List): ...
    def exec(self, fn: Callable, deps: Optional[List[State]]): ...
def test_useMemo(value): ...
def test_useMemo_1(value): ...
def useMemo(callback: Callable, dependencies: Optional[List[State]]): ...