from functools import lru_cache
from typing import Any, Callable, Optional, Union, Dict, List
import uuid
from PyQt5.QtWidgets import QTabWidget, QTabBar, QWidget, QHBoxLayout, QLabel, QPushButton, QSizePolicy
from PyQt5.QtCore import Qt, QTimer
from PyQt5.QtGui import QIcon, QCursor
from ...material.system.color_manipulator import alpha
from ...base.widget_base import PyWidgetBase
from qtmui.hooks import State
from qtmui.hooks.use_theme import useTheme
from qtmui.i18n.use_translation import translate, i18n
from ...utils.validate_params import _validate_param
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
from ...components.typography import Typography
from ...components.py_iconify import PyIconify
from ...components.box import Box
from .tab import Tab
class Tabs:
    def __init__(self, justifyContent: Optional[Union[State, str, Any]], orientation: Optional[Union[State, str, Any]], value: Optional[Union[State, Any, Any]], onChange: Optional[Union[State, Callable, Any]], fullWidth: Union[State, bool], fixedHeight: Optional[Union[State, int, Any]], minWidth: Union[State, bool], children: Optional[Union[State, List[QWidget], QWidget, Any]], sx: Optional[Union[State, List, Dict, Callable, Any]], action: Optional[Union[State, Any, Any]], allowScrollButtonsMobile: Union[State, bool], aria_label: Optional[Union[State, str, Any]], aria_labelledby: Optional[Union[State, str, Any]], centered: Union[State, bool], classes: Optional[Union[State, Dict, Any]], component: Optional[Union[State, str, Any]], indicatorColor: Optional[Union[State, str, Any]], scrollButtons: Union[State, str, bool], selectionFollowsFocus: Union[State, bool], slotProps: Optional[Union[State, Dict, Any]], slots: Optional[Union[State, Dict, Any]], TabIndicatorProps: Optional[Union[State, Dict, Any]], TabScrollButtonProps: Optional[Union[State, Dict, Any]], textColor: Optional[Union[State, str, Any]], variant: Optional[Union[State, str, Any]], visibleScrollbar: Union[State, bool], **kwargs): ...
    def _set_justifyContent(self, value): ...
    def _get_justifyContent(self): ...
    def _set_orientation(self, value): ...
    def _get_orientation(self): ...
    def _set_value(self, value): ...
    def _get_value(self): ...
    def _set_onChange(self, value): ...
    def _get_onChange(self): ...
    def _set_fullWidth(self, value): ...
    def _get_fullWidth(self): ...
    def _set_fixedHeight(self, value): ...
    def _get_fixedHeight(self): ...
    def _set_minWidth(self, value): ...
    def _get_minWidth(self): ...
    def _set_children(self, value): ...
    def _get_children(self): ...
    def _set_sx(self, value): ...
    def _get_sx(self): ...
    def _set_action(self, value): ...
    def _get_action(self): ...
    def _set_allowScrollButtonsMobile(self, value): ...
    def _get_allowScrollButtonsMobile(self): ...
    def _set_aria_label(self, value): ...
    def _get_aria_label(self): ...
    def _set_aria_labelledby(self, value): ...
    def _get_aria_labelledby(self): ...
    def _set_centered(self, value): ...
    def _get_centered(self): ...
    def _set_classes(self, value): ...
    def _get_classes(self): ...
    def _set_component(self, value): ...
    def _get_component(self): ...
    def _set_indicatorColor(self, value): ...
    def _get_indicatorColor(self): ...
    def _set_scrollButtons(self, value): ...
    def _get_scrollButtons(self): ...
    def _set_selectionFollowsFocus(self, value): ...
    def _get_selectionFollowsFocus(self): ...
    def _set_slotProps(self, value): ...
    def _get_slotProps(self): ...
    def _set_slots(self, value): ...
    def _get_slots(self): ...
    def _set_TabIndicatorProps(self, value): ...
    def _get_TabIndicatorProps(self): ...
    def _set_TabScrollButtonProps(self, value): ...
    def _get_TabScrollButtonProps(self): ...
    def _set_textColor(self, value): ...
    def _get_textColor(self): ...
    def _set_variant(self, value): ...
    def _get_variant(self): ...
    def _set_visibleScrollbar(self, value): ...
    def _get_visibleScrollbar(self): ...
    def _init_ui(self): ...
    def set_tab_with_icon_at_position(self, index, title, icon, iconPosition): ...
    def _get_stylesheet(cls, _theme_mode: str): ...
    def _set_stylesheet(self): ...
    def set_current_tab_by_key(self, key): ...
    def retranslateUi(self): ...
    def on_tab_changed(self, index): ...
    def update_ui(self): ...
    def _on_destroyed(self): ...
    def disable_pointer_events(self): ...
    def paintEvent(self, event): ...
    def resizeEvent(self, event): ...