# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.82
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.filter_operator1 import FilterOperator1

class TestFilterOperator1(unittest.TestCase):
    """FilterOperator1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilterOperator1(self):
        """Test FilterOperator1"""
        # inst = FilterOperator1()

if __name__ == '__main__':
    unittest.main()
