# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.82
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.collection_detail import CollectionDetail

class TestCollectionDetail(unittest.TestCase):
    """CollectionDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CollectionDetail:
        """Test CollectionDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CollectionDetail`
        """
        model = CollectionDetail()
        if include_optional:
            return CollectionDetail(
                collection_id = '',
                collection_name = '',
                document_count = 56,
                enabled = True,
                last_indexed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return CollectionDetail(
                collection_id = '',
                collection_name = '',
        )
        """

    def testCollectionDetail(self):
        """Test CollectionDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
