from typing import Optional, Union, Dict, Callable, List
from PySide6.QtWidgets import QHBoxLayout, QVBoxLayout, QFrame, QSizePolicy, QWidget
from PySide6.QtCore import Qt
import uuid
from qtmui.hooks import State
from ...material.styles import useTheme
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
from ..utils.validate_params import _validate_param
class FormGroup:
    def __init__(self, children: Optional[Union[State, QWidget, List[QWidget], Callable]], classes: Optional[Union[State, Dict]], row: Union[State, bool], sx: Optional[Union[State, List, Dict, Callable, str]], **kwargs): ...
    def _set_children(self, value): ...
    def _get_children(self): ...
    def _set_classes(self, value): ...
    def _get_classes(self): ...
    def _set_row(self, value): ...
    def _get_row(self): ...
    def _set_sx(self, value): ...
    def _get_sx(self): ...
    def _init_ui(self): ...