import ssl
from http import HTTPStatus

from curl_cffi import CurlMime, requests

from discord_self._vendor.discord import utils
from discord_self._vendor.discord.channel import (
    DMChannel,
    ForumChannel,
    GroupChannel,
    PartialMessageable,
    TextChannel,
    VoiceChannel,
)
from discord_self._vendor.discord.embeds import Embed
from discord_self._vendor.discord.enums import (
    ChannelType,
    InteractionType,
    InviteType,
    NetworkConnectionType,
    RelationshipAction,
)
from discord_self._vendor.discord.errors import (
    CaptchaRequired,
    DiscordServerError,
    Forbidden,
    GatewayNotFound,
    HTTPException,
    LoginFailure,
    NotFound,
    RateLimited,
)
from discord_self._vendor.discord.file import File
from discord_self._vendor.discord.flags import MessageFlags
from discord_self._vendor.discord.http import (
    CIPHERS,
    INTERNAL_API_VERSION,
    HTTPClient,
    MultipartParameters,
    Ratelimit,
    Route,
    handle_message_parameters,
    json_or_text,
)
from discord_self._vendor.discord.mentions import AllowedMentions
from discord_self._vendor.discord.message import Attachment, Message
from discord_self._vendor.discord.poll import Poll
from discord_self._vendor.discord.threads import Thread
from discord_self._vendor.discord.tracking import ContextProperties
from discord_self._vendor.discord.types import (
    activity,
    application,
    audit_log,
    automod,
    billing,
    channel,
    command,
    directory,
    emoji,
    entitlements,
    experiment,
    guild,
    hub,
    integration,
    interactions,
    invite,
    library,
    member,
    message,
    oauth2,
    onboarding,
    payments,
    poll,
    profile,
    promotions,
    read_state,
    role,
    scheduled_event,
    sticker,
    store,
    subscriptions,
    team,
    template,
    threads,
    user,
    webhook,
    welcome_screen,
    widget,
)
from discord_self._vendor.discord.types.snowflake import Snowflake, SnowflakeList
from discord_self._vendor.discord.utils import MISSING

__all__ = [
    "AllowedMentions",
    "Attachment",
    "CIPHERS",
    "CaptchaRequired",
    "ChannelType",
    "ContextProperties",
    "CurlMime",
    "DMChannel",
    "DiscordServerError",
    "Embed",
    "File",
    "Forbidden",
    "ForumChannel",
    "GatewayNotFound",
    "GroupChannel",
    "HTTPClient",
    "HTTPException",
    "HTTPStatus",
    "INTERNAL_API_VERSION",
    "InteractionType",
    "InviteType",
    "LoginFailure",
    "MISSING",
    "Message",
    "MessageFlags",
    "MultipartParameters",
    "NetworkConnectionType",
    "NotFound",
    "PartialMessageable",
    "Poll",
    "RateLimited",
    "Ratelimit",
    "RelationshipAction",
    "Route",
    "Snowflake",
    "SnowflakeList",
    "TextChannel",
    "Thread",
    "VoiceChannel",
    "activity",
    "application",
    "audit_log",
    "automod",
    "billing",
    "channel",
    "command",
    "directory",
    "emoji",
    "entitlements",
    "experiment",
    "guild",
    "handle_message_parameters",
    "hub",
    "integration",
    "interactions",
    "invite",
    "json_or_text",
    "library",
    "member",
    "message",
    "oauth2",
    "onboarding",
    "payments",
    "poll",
    "profile",
    "promotions",
    "read_state",
    "requests",
    "role",
    "scheduled_event",
    "ssl",
    "sticker",
    "store",
    "subscriptions",
    "team",
    "template",
    "threads",
    "user",
    "utils",
    "webhook",
    "welcome_screen",
    "widget",
]
