from typing import Optional, Union, Dict, List, Callable
from PySide6.QtGui import QMouseEvent, QColor
from PySide6.QtCore import Signal
from PySide6.QtWidgets import QWidget, QHBoxLayout, QFrame, QSizePolicy, QVBoxLayout, QGraphicsDropShadowEffect, QPushButton
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
from qtmui.hooks import State
from qtmui.material.styles import useTheme
from qtmui.i18n.use_translation import translate, i18n
from .accordion_summary import AccordionSummary
from .accordion_details import AccordionDetails
from ..utils.validate_params import _validate_param
class Accordion:
    def __init__(self, children: Optional[Union[State, List]], classes: Optional[Union[State, Dict]], defaultExpanded: Optional[Union[State, bool]], disabled: Optional[Union[State, bool]], disableGutters: Optional[Union[State, bool]], elevation: Optional[Union[State, int]], expanded: Optional[Union[State, bool]], fullWidth: Optional[Union[State, bool]], key: Optional[Union[State, str]], onChange: Optional[Union[State, Callable]], slotProps: Optional[Union[State, Dict]], slots: Optional[Union[State, Dict]], square: Optional[Union[State, bool]], sx: Optional[Union[State, Dict, Callable, str]], TransitionComponent: Optional[Union[State, object]], TransitionProps: Optional[Union[State, Dict]], variant: Optional[Union[State, str]], *args, **kwargs): ...
    def _set_children(self, value): ...
    def _get_children(self): ...
    def _set_classes(self, value): ...
    def _get_classes(self): ...
    def _set_defaultExpanded(self, value): ...
    def _get_defaultExpanded(self): ...
    def _set_disabled(self, value): ...
    def _get_disabled(self): ...
    def _set_disableGutters(self, value): ...
    def _get_disableGutters(self): ...
    def _set_elevation(self, value): ...
    def _get_elevation(self): ...
    def _set_expanded(self, value): ...
    def _get_expanded(self): ...
    def _set_fullWidth(self, value): ...
    def _get_fullWidth(self): ...
    def _set_key(self, value): ...
    def _get_key(self): ...
    def _set_onChange(self, value): ...
    def _get_onChange(self): ...
    def _set_slotProps(self, value): ...
    def _get_slotProps(self): ...
    def _set_slots(self, value): ...
    def _get_slots(self): ...
    def _set_square(self, value): ...
    def _get_square(self): ...
    def _set_sx(self, value): ...
    def _get_sx(self): ...
    def _set_TransitionComponent(self, value): ...
    def _get_TransitionComponent(self): ...
    def _set_TransitionProps(self, value): ...
    def _get_TransitionProps(self): ...
    def _set_variant(self, value): ...
    def _get_variant(self): ...
    def _init_ui(self): ...
    def retranslateUi(self): ...
    def _get_theme_style(self): ...
    def _set_expanded_state(self, expanded): ...
    def _setShadowEffect(self, blurRadius, offset, color): ...
    def _set_default_state(self): ...
    def _set_controlled_state(self, value): ...
    def _toogle(self): ...
    def __set_stylesheet(self): ...