from typing import Dict, Any
import contextvars
class HookState:
    def __init__(self): ...
    def reset(self): ...
    def next_index(self): ...
    def get(self, index: int): ...
    def set(self, index: int, value: Any): ...
def get_hook_state(): ...
def set_current_hook_context(state: HookState): ...