from typing import Callable, Dict, Optional, Union
import uuid
from PySide6.QtWidgets import QFrame, QVBoxLayout, QWidget, QApplication
from PySide6.QtCore import Qt, QTimer
from qtmui.hooks import State
from ...common.ui_functions import clear_layout
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
from qtmui.material.styles import useTheme
from qtmui.material.widget_base import PyWidgetBase
class View:
    def __init__(self, hidden: Optional[Union[State, bool]], content: State, hightLight: bool, alignment: str, sx: Optional[Union[Callable, str, Dict]], *args, **kwargs): ...
    def _setupStates(self): ...
    def _updateHidden(self, val): ...
    def _onDestroyed(self, obj): ...
    def _deleteChildren(self): ...
    def _render_ui(self): ...
    def slot_set_stylesheet(self, value): ...
    def _set_stylesheet(self, component_styled): ...