from PySide6.QtCore import Qt, QCoreApplication
from PySide6.QtGui import QColor
from PySide6.QtWidgets import QTableView, QProxyStyle, QStyleOption, QHeaderView, QAbstractItemView
class FrozenColumn:
    def __init__(self, parent, context, lastCol: int): ...
    def setupUi(self): ...
    def configTable(self, selectionModel): ...
    def data(self, index, role): ...
    def cellButtonClicked(self, data): ...
    def getselectedRowsFast(self): ...