from typing import Callable, Optional, Union
import uuid
from PySide6.QtWidgets import QHBoxLayout, QFrame, QPushButton
from qtmui.hooks import State
from ...material.styles import useTheme
from ..widget_base import PyWidgetBase
class Option:
    def __init__(self, key: str, value: object, enabled: bool, label: Optional[Union[str, State, Callable]], selected: bool, children: object, *args, **kwargs): ...
    def __init_ui(self): ...
    def _set_stylesheet(self): ...
    def set_selected(self, state): ...
    def _set_selected(self, selected): ...
    def set_menu_item_visible(self, state): ...