[
  {
    "oid": "test_pg_gen_02290171-67f5-426b-9a4e-b83cd7d30acd_0-0",
    "name": "SleepInternal",
    "categoryType": "Application",
    "category": "BashShellApp",
    "dropclass": "dlg.apps.bash_shell_app.BashShellApp",
    "storage": "BashShellApp",
    "rank": [
      0,
      0
    ],
    "reprodata": {},
    "loop_ctx": "0",
    "weight": 5,
    "num_cpus": "1",
    "applicationArgs": {
      "sleep_time": {
        "defaultValue": "3",
        "description": "The amount of time to sleep",
        "encoding": "pickle",
        "id": "93be211c-e27c-49f0-9583-e0ebbb8a343a",
        "name": "sleep_time",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": true,
        "precious": false,
        "readonly": false,
        "type": "Integer",
        "usage": "NoPort",
        "value": 3
      },
      "event": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "b133f803-42f7-4c70-83b7-803bf8ec3035",
        "name": "event",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Object.",
        "usage": "InputOutput",
        "value": ""
      }
    },
    "constraintParams": {
      "execution_time": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "8f1c999d-23ce-4c2f-b177-5de2606ed4c5",
        "name": "execution_time",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "5"
      },
      "num_cpus": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "1ef6096d-c186-4ceb-8893-bfb4fe81c648",
        "name": "num_cpus",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "1"
      }
    },
    "componentParams": {
      "dropclass": {
        "defaultValue": "",
        "description": "Application class",
        "encoding": "pickle",
        "id": "fd3f862d-3f5b-445a-8d2a-4eceed74e5f4",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.apps.bash_shell_app.BashShellApp"
      },
      "group_start": {
        "defaultValue": "false",
        "description": "",
        "encoding": "pickle",
        "id": "d48b46e8-8816-40eb-99cb-9233938a76b6",
        "name": "group_start",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": true
      },
      "command": {
        "defaultValue": "sleep",
        "description": "",
        "encoding": "pickle",
        "id": "5436cf0e-a92c-4ab2-b4ae-1989c4558d28",
        "name": "command",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "sleep"
      }
    },
    "fields": [
      {
        "defaultValue": "",
        "description": "Application class",
        "encoding": "pickle",
        "id": "fd3f862d-3f5b-445a-8d2a-4eceed74e5f4",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.apps.bash_shell_app.BashShellApp"
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "8f1c999d-23ce-4c2f-b177-5de2606ed4c5",
        "name": "execution_time",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "5"
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "1ef6096d-c186-4ceb-8893-bfb4fe81c648",
        "name": "num_cpus",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "1"
      },
      {
        "defaultValue": "false",
        "description": "",
        "encoding": "pickle",
        "id": "d48b46e8-8816-40eb-99cb-9233938a76b6",
        "name": "group_start",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": true
      },
      {
        "defaultValue": "sleep",
        "description": "",
        "encoding": "pickle",
        "id": "5436cf0e-a92c-4ab2-b4ae-1989c4558d28",
        "name": "command",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "sleep"
      },
      {
        "defaultValue": "3",
        "description": "The amount of time to sleep",
        "encoding": "pickle",
        "id": "93be211c-e27c-49f0-9583-e0ebbb8a343a",
        "name": "sleep_time",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": true,
        "precious": false,
        "readonly": false,
        "type": "Integer",
        "usage": "NoPort",
        "value": 3
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "b133f803-42f7-4c70-83b7-803bf8ec3035",
        "name": "event",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Object.",
        "usage": "InputOutput",
        "value": ""
      }
    ],
    "execution_time": "5",
    "group_start": true,
    "command": "sleep",
    "sleep_time": 3,
    "event": "",
    "iid": "0-0",
    "lg_key": "02290171-67f5-426b-9a4e-b83cd7d30acd",
    "outputPorts": {},
    "inputPorts": {
      "b133f803-42f7-4c70-83b7-803bf8ec3035": {
        "type": "InputOutput",
        "name": "event",
        "source_id": ""
      }
    },
    "outputs": [
      {
        "test_pg_gen_e7685102-4ddf-45e1-bb82-fe9ad2c43bb0_0-0": "b133f803-42f7-4c70-83b7-803bf8ec3035"
      }
    ],
    "node": "10.128.0.12",
    "island": "10.128.0.11",
    "humanReadableKey": "1_0-0"
  },
  {
    "oid": "test_pg_gen_02290171-67f5-426b-9a4e-b83cd7d30acd_0-1",
    "name": "SleepInternal",
    "categoryType": "Application",
    "category": "BashShellApp",
    "dropclass": "dlg.apps.bash_shell_app.BashShellApp",
    "storage": "BashShellApp",
    "rank": [
      0,
      1
    ],
    "reprodata": {},
    "loop_ctx": "1",
    "weight": 5,
    "num_cpus": "1",
    "applicationArgs": {
      "sleep_time": {
        "defaultValue": "3",
        "description": "The amount of time to sleep",
        "encoding": "pickle",
        "id": "93be211c-e27c-49f0-9583-e0ebbb8a343a",
        "name": "sleep_time",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": true,
        "precious": false,
        "readonly": false,
        "type": "Integer",
        "usage": "NoPort",
        "value": 3
      },
      "event": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "b133f803-42f7-4c70-83b7-803bf8ec3035",
        "name": "event",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Object.",
        "usage": "InputOutput",
        "value": ""
      }
    },
    "constraintParams": {
      "execution_time": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "8f1c999d-23ce-4c2f-b177-5de2606ed4c5",
        "name": "execution_time",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "5"
      },
      "num_cpus": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "1ef6096d-c186-4ceb-8893-bfb4fe81c648",
        "name": "num_cpus",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "1"
      }
    },
    "componentParams": {
      "dropclass": {
        "defaultValue": "",
        "description": "Application class",
        "encoding": "pickle",
        "id": "fd3f862d-3f5b-445a-8d2a-4eceed74e5f4",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.apps.bash_shell_app.BashShellApp"
      },
      "group_start": {
        "defaultValue": "false",
        "description": "",
        "encoding": "pickle",
        "id": "d48b46e8-8816-40eb-99cb-9233938a76b6",
        "name": "group_start",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": true
      },
      "command": {
        "defaultValue": "sleep",
        "description": "",
        "encoding": "pickle",
        "id": "5436cf0e-a92c-4ab2-b4ae-1989c4558d28",
        "name": "command",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "sleep"
      }
    },
    "fields": [
      {
        "defaultValue": "",
        "description": "Application class",
        "encoding": "pickle",
        "id": "fd3f862d-3f5b-445a-8d2a-4eceed74e5f4",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.apps.bash_shell_app.BashShellApp"
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "8f1c999d-23ce-4c2f-b177-5de2606ed4c5",
        "name": "execution_time",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "5"
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "1ef6096d-c186-4ceb-8893-bfb4fe81c648",
        "name": "num_cpus",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "1"
      },
      {
        "defaultValue": "false",
        "description": "",
        "encoding": "pickle",
        "id": "d48b46e8-8816-40eb-99cb-9233938a76b6",
        "name": "group_start",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": true
      },
      {
        "defaultValue": "sleep",
        "description": "",
        "encoding": "pickle",
        "id": "5436cf0e-a92c-4ab2-b4ae-1989c4558d28",
        "name": "command",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "sleep"
      },
      {
        "defaultValue": "3",
        "description": "The amount of time to sleep",
        "encoding": "pickle",
        "id": "93be211c-e27c-49f0-9583-e0ebbb8a343a",
        "name": "sleep_time",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": true,
        "precious": false,
        "readonly": false,
        "type": "Integer",
        "usage": "NoPort",
        "value": 3
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "b133f803-42f7-4c70-83b7-803bf8ec3035",
        "name": "event",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Object.",
        "usage": "InputOutput",
        "value": ""
      }
    ],
    "execution_time": "5",
    "group_start": true,
    "command": "sleep",
    "sleep_time": 3,
    "event": "",
    "iid": "0-1",
    "lg_key": "02290171-67f5-426b-9a4e-b83cd7d30acd",
    "outputPorts": {},
    "inputPorts": {
      "b133f803-42f7-4c70-83b7-803bf8ec3035": {
        "type": "InputOutput",
        "name": "event",
        "source_id": ""
      }
    },
    "outputs": [
      {
        "test_pg_gen_e7685102-4ddf-45e1-bb82-fe9ad2c43bb0_0-1": "b133f803-42f7-4c70-83b7-803bf8ec3035"
      }
    ],
    "inputs": [
      {
        "test_pg_gen_e7685102-4ddf-45e1-bb82-fe9ad2c43bb0_0-0": "event"
      }
    ],
    "node": "10.128.0.12",
    "island": "10.128.0.11",
    "humanReadableKey": "2_0-1"
  },
  {
    "oid": "test_pg_gen_02290171-67f5-426b-9a4e-b83cd7d30acd_0-2",
    "name": "SleepInternal",
    "categoryType": "Application",
    "category": "BashShellApp",
    "dropclass": "dlg.apps.bash_shell_app.BashShellApp",
    "storage": "BashShellApp",
    "rank": [
      0,
      2
    ],
    "reprodata": {},
    "loop_ctx": "2",
    "weight": 5,
    "num_cpus": "1",
    "applicationArgs": {
      "sleep_time": {
        "defaultValue": "3",
        "description": "The amount of time to sleep",
        "encoding": "pickle",
        "id": "93be211c-e27c-49f0-9583-e0ebbb8a343a",
        "name": "sleep_time",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": true,
        "precious": false,
        "readonly": false,
        "type": "Integer",
        "usage": "NoPort",
        "value": 3
      },
      "event": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "b133f803-42f7-4c70-83b7-803bf8ec3035",
        "name": "event",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Object.",
        "usage": "InputOutput",
        "value": ""
      }
    },
    "constraintParams": {
      "execution_time": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "8f1c999d-23ce-4c2f-b177-5de2606ed4c5",
        "name": "execution_time",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "5"
      },
      "num_cpus": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "1ef6096d-c186-4ceb-8893-bfb4fe81c648",
        "name": "num_cpus",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "1"
      }
    },
    "componentParams": {
      "dropclass": {
        "defaultValue": "",
        "description": "Application class",
        "encoding": "pickle",
        "id": "fd3f862d-3f5b-445a-8d2a-4eceed74e5f4",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.apps.bash_shell_app.BashShellApp"
      },
      "group_start": {
        "defaultValue": "false",
        "description": "",
        "encoding": "pickle",
        "id": "d48b46e8-8816-40eb-99cb-9233938a76b6",
        "name": "group_start",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": true
      },
      "command": {
        "defaultValue": "sleep",
        "description": "",
        "encoding": "pickle",
        "id": "5436cf0e-a92c-4ab2-b4ae-1989c4558d28",
        "name": "command",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "sleep"
      }
    },
    "fields": [
      {
        "defaultValue": "",
        "description": "Application class",
        "encoding": "pickle",
        "id": "fd3f862d-3f5b-445a-8d2a-4eceed74e5f4",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.apps.bash_shell_app.BashShellApp"
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "8f1c999d-23ce-4c2f-b177-5de2606ed4c5",
        "name": "execution_time",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "5"
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "1ef6096d-c186-4ceb-8893-bfb4fe81c648",
        "name": "num_cpus",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "1"
      },
      {
        "defaultValue": "false",
        "description": "",
        "encoding": "pickle",
        "id": "d48b46e8-8816-40eb-99cb-9233938a76b6",
        "name": "group_start",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": true
      },
      {
        "defaultValue": "sleep",
        "description": "",
        "encoding": "pickle",
        "id": "5436cf0e-a92c-4ab2-b4ae-1989c4558d28",
        "name": "command",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "sleep"
      },
      {
        "defaultValue": "3",
        "description": "The amount of time to sleep",
        "encoding": "pickle",
        "id": "93be211c-e27c-49f0-9583-e0ebbb8a343a",
        "name": "sleep_time",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": true,
        "precious": false,
        "readonly": false,
        "type": "Integer",
        "usage": "NoPort",
        "value": 3
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "b133f803-42f7-4c70-83b7-803bf8ec3035",
        "name": "event",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Object.",
        "usage": "InputOutput",
        "value": ""
      }
    ],
    "execution_time": "5",
    "group_start": true,
    "command": "sleep",
    "sleep_time": 3,
    "event": "",
    "iid": "0-2",
    "lg_key": "02290171-67f5-426b-9a4e-b83cd7d30acd",
    "outputPorts": {},
    "inputPorts": {
      "b133f803-42f7-4c70-83b7-803bf8ec3035": {
        "type": "InputOutput",
        "name": "event",
        "source_id": ""
      }
    },
    "outputs": [
      {
        "test_pg_gen_e7685102-4ddf-45e1-bb82-fe9ad2c43bb0_0-2": "b133f803-42f7-4c70-83b7-803bf8ec3035"
      }
    ],
    "inputs": [
      {
        "test_pg_gen_e7685102-4ddf-45e1-bb82-fe9ad2c43bb0_0-1": "event"
      }
    ],
    "node": "10.128.0.12",
    "island": "10.128.0.11",
    "humanReadableKey": "3_0-2"
  },
  {
    "oid": "test_pg_gen_02290171-67f5-426b-9a4e-b83cd7d30acd_0-3",
    "name": "SleepInternal",
    "categoryType": "Application",
    "category": "BashShellApp",
    "dropclass": "dlg.apps.bash_shell_app.BashShellApp",
    "storage": "BashShellApp",
    "rank": [
      0,
      3
    ],
    "reprodata": {},
    "loop_ctx": "3",
    "weight": 5,
    "num_cpus": "1",
    "applicationArgs": {
      "sleep_time": {
        "defaultValue": "3",
        "description": "The amount of time to sleep",
        "encoding": "pickle",
        "id": "93be211c-e27c-49f0-9583-e0ebbb8a343a",
        "name": "sleep_time",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": true,
        "precious": false,
        "readonly": false,
        "type": "Integer",
        "usage": "NoPort",
        "value": 3
      },
      "event": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "b133f803-42f7-4c70-83b7-803bf8ec3035",
        "name": "event",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Object.",
        "usage": "InputOutput",
        "value": ""
      }
    },
    "constraintParams": {
      "execution_time": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "8f1c999d-23ce-4c2f-b177-5de2606ed4c5",
        "name": "execution_time",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "5"
      },
      "num_cpus": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "1ef6096d-c186-4ceb-8893-bfb4fe81c648",
        "name": "num_cpus",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "1"
      }
    },
    "componentParams": {
      "dropclass": {
        "defaultValue": "",
        "description": "Application class",
        "encoding": "pickle",
        "id": "fd3f862d-3f5b-445a-8d2a-4eceed74e5f4",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.apps.bash_shell_app.BashShellApp"
      },
      "group_start": {
        "defaultValue": "false",
        "description": "",
        "encoding": "pickle",
        "id": "d48b46e8-8816-40eb-99cb-9233938a76b6",
        "name": "group_start",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": true
      },
      "command": {
        "defaultValue": "sleep",
        "description": "",
        "encoding": "pickle",
        "id": "5436cf0e-a92c-4ab2-b4ae-1989c4558d28",
        "name": "command",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "sleep"
      }
    },
    "fields": [
      {
        "defaultValue": "",
        "description": "Application class",
        "encoding": "pickle",
        "id": "fd3f862d-3f5b-445a-8d2a-4eceed74e5f4",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.apps.bash_shell_app.BashShellApp"
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "8f1c999d-23ce-4c2f-b177-5de2606ed4c5",
        "name": "execution_time",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "5"
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "1ef6096d-c186-4ceb-8893-bfb4fe81c648",
        "name": "num_cpus",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "1"
      },
      {
        "defaultValue": "false",
        "description": "",
        "encoding": "pickle",
        "id": "d48b46e8-8816-40eb-99cb-9233938a76b6",
        "name": "group_start",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": true
      },
      {
        "defaultValue": "sleep",
        "description": "",
        "encoding": "pickle",
        "id": "5436cf0e-a92c-4ab2-b4ae-1989c4558d28",
        "name": "command",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "sleep"
      },
      {
        "defaultValue": "3",
        "description": "The amount of time to sleep",
        "encoding": "pickle",
        "id": "93be211c-e27c-49f0-9583-e0ebbb8a343a",
        "name": "sleep_time",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": true,
        "precious": false,
        "readonly": false,
        "type": "Integer",
        "usage": "NoPort",
        "value": 3
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "b133f803-42f7-4c70-83b7-803bf8ec3035",
        "name": "event",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Object.",
        "usage": "InputOutput",
        "value": ""
      }
    ],
    "execution_time": "5",
    "group_start": true,
    "command": "sleep",
    "sleep_time": 3,
    "event": "",
    "iid": "0-3",
    "lg_key": "02290171-67f5-426b-9a4e-b83cd7d30acd",
    "outputPorts": {},
    "inputPorts": {
      "b133f803-42f7-4c70-83b7-803bf8ec3035": {
        "type": "InputOutput",
        "name": "event",
        "source_id": ""
      }
    },
    "outputs": [
      {
        "test_pg_gen_e7685102-4ddf-45e1-bb82-fe9ad2c43bb0_0-3": "b133f803-42f7-4c70-83b7-803bf8ec3035"
      }
    ],
    "inputs": [
      {
        "test_pg_gen_e7685102-4ddf-45e1-bb82-fe9ad2c43bb0_0-2": "event"
      }
    ],
    "node": "10.128.0.12",
    "island": "10.128.0.11",
    "humanReadableKey": "4_0-3"
  },
  {
    "oid": "test_pg_gen_02290171-67f5-426b-9a4e-b83cd7d30acd_0-4",
    "name": "SleepInternal",
    "categoryType": "Application",
    "category": "BashShellApp",
    "dropclass": "dlg.apps.bash_shell_app.BashShellApp",
    "storage": "BashShellApp",
    "rank": [
      0,
      4
    ],
    "reprodata": {},
    "loop_ctx": "4",
    "weight": 5,
    "num_cpus": "1",
    "applicationArgs": {
      "sleep_time": {
        "defaultValue": "3",
        "description": "The amount of time to sleep",
        "encoding": "pickle",
        "id": "93be211c-e27c-49f0-9583-e0ebbb8a343a",
        "name": "sleep_time",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": true,
        "precious": false,
        "readonly": false,
        "type": "Integer",
        "usage": "NoPort",
        "value": 3
      },
      "event": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "b133f803-42f7-4c70-83b7-803bf8ec3035",
        "name": "event",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Object.",
        "usage": "InputOutput",
        "value": ""
      }
    },
    "constraintParams": {
      "execution_time": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "8f1c999d-23ce-4c2f-b177-5de2606ed4c5",
        "name": "execution_time",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "5"
      },
      "num_cpus": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "1ef6096d-c186-4ceb-8893-bfb4fe81c648",
        "name": "num_cpus",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "1"
      }
    },
    "componentParams": {
      "dropclass": {
        "defaultValue": "",
        "description": "Application class",
        "encoding": "pickle",
        "id": "fd3f862d-3f5b-445a-8d2a-4eceed74e5f4",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.apps.bash_shell_app.BashShellApp"
      },
      "group_start": {
        "defaultValue": "false",
        "description": "",
        "encoding": "pickle",
        "id": "d48b46e8-8816-40eb-99cb-9233938a76b6",
        "name": "group_start",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": true
      },
      "command": {
        "defaultValue": "sleep",
        "description": "",
        "encoding": "pickle",
        "id": "5436cf0e-a92c-4ab2-b4ae-1989c4558d28",
        "name": "command",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "sleep"
      }
    },
    "fields": [
      {
        "defaultValue": "",
        "description": "Application class",
        "encoding": "pickle",
        "id": "fd3f862d-3f5b-445a-8d2a-4eceed74e5f4",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.apps.bash_shell_app.BashShellApp"
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "8f1c999d-23ce-4c2f-b177-5de2606ed4c5",
        "name": "execution_time",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "5"
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "1ef6096d-c186-4ceb-8893-bfb4fe81c648",
        "name": "num_cpus",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "1"
      },
      {
        "defaultValue": "false",
        "description": "",
        "encoding": "pickle",
        "id": "d48b46e8-8816-40eb-99cb-9233938a76b6",
        "name": "group_start",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": true
      },
      {
        "defaultValue": "sleep",
        "description": "",
        "encoding": "pickle",
        "id": "5436cf0e-a92c-4ab2-b4ae-1989c4558d28",
        "name": "command",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "sleep"
      },
      {
        "defaultValue": "3",
        "description": "The amount of time to sleep",
        "encoding": "pickle",
        "id": "93be211c-e27c-49f0-9583-e0ebbb8a343a",
        "name": "sleep_time",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": true,
        "precious": false,
        "readonly": false,
        "type": "Integer",
        "usage": "NoPort",
        "value": 3
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "b133f803-42f7-4c70-83b7-803bf8ec3035",
        "name": "event",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Object.",
        "usage": "InputOutput",
        "value": ""
      }
    ],
    "execution_time": "5",
    "group_start": true,
    "command": "sleep",
    "sleep_time": 3,
    "event": "",
    "iid": "0-4",
    "lg_key": "02290171-67f5-426b-9a4e-b83cd7d30acd",
    "outputPorts": {},
    "inputPorts": {
      "b133f803-42f7-4c70-83b7-803bf8ec3035": {
        "type": "InputOutput",
        "name": "event",
        "source_id": ""
      }
    },
    "outputs": [
      {
        "test_pg_gen_e7685102-4ddf-45e1-bb82-fe9ad2c43bb0_0-4": "b133f803-42f7-4c70-83b7-803bf8ec3035"
      }
    ],
    "inputs": [
      {
        "test_pg_gen_e7685102-4ddf-45e1-bb82-fe9ad2c43bb0_0-3": "event"
      }
    ],
    "node": "10.128.0.12",
    "island": "10.128.0.11",
    "humanReadableKey": "5_0-4"
  },
  {
    "oid": "test_pg_gen_e7685102-4ddf-45e1-bb82-fe9ad2c43bb0_0-0",
    "name": "event",
    "categoryType": "Data",
    "category": "File",
    "dropclass": "dlg.data.drops.file.FileDROP",
    "storage": "File",
    "rank": [
      0,
      0
    ],
    "reprodata": {},
    "loop_ctx": "0",
    "weight": 5,
    "applicationArgs": {
      "event": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "102d6fc6-eea7-434b-9196-65a42a79cf13",
        "name": "event",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Object.",
        "usage": "InputOutput",
        "value": ""
      }
    },
    "constraintParams": {
      "data_volume": {
        "defaultValue": "5",
        "description": "Estimated size of the data contained in this node",
        "encoding": "pickle",
        "id": "f33173ca-3919-46a2-88a7-4b31e107caf3",
        "name": "data_volume",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Float",
        "usage": "NoPort",
        "value": 5
      }
    },
    "componentParams": {
      "dropclass": {
        "defaultValue": "",
        "description": "Data class",
        "encoding": "pickle",
        "id": "493f6624-cb40-4ffe-a81c-30a1a9434fd6",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.data.drops.file.FileDROP"
      },
      "group_end": {
        "defaultValue": "false",
        "description": "Is this node the end of a group?",
        "encoding": "pickle",
        "id": "f678e21d-6353-43c6-b488-49381c15a3c9",
        "name": "group_end",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": true
      },
      "check_filepath_exists": {
        "defaultValue": "true",
        "description": "Perform a check to make sure the file path exists before proceeding with the application",
        "encoding": "pickle",
        "id": "fabd950c-ba2c-4af6-abdb-ce0184a8a9cf",
        "name": "check_filepath_exists",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": true
      },
      "filepath": {
        "defaultValue": "",
        "description": "Path to the file for this node",
        "encoding": "pickle",
        "id": "81fed942-7b69-4f04-b1d2-645f9042a393",
        "name": "filepath",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      "dirname": {
        "defaultValue": "",
        "description": "Name of the directory containing the file for this node",
        "encoding": "pickle",
        "id": "04896f88-7ccd-4232-b3f4-63cbfdbb9cf2",
        "name": "dirname",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      "persist": {
        "defaultValue": "true",
        "description": "Specifies whether this data component contains data that should not be deleted after execution",
        "encoding": "pickle",
        "id": "64a53019-8c5b-4502-a972-e1c9a482fa6c",
        "name": "persist",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      }
    },
    "fields": [
      {
        "defaultValue": "",
        "description": "Data class",
        "encoding": "pickle",
        "id": "493f6624-cb40-4ffe-a81c-30a1a9434fd6",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.data.drops.file.FileDROP"
      },
      {
        "defaultValue": "5",
        "description": "Estimated size of the data contained in this node",
        "encoding": "pickle",
        "id": "f33173ca-3919-46a2-88a7-4b31e107caf3",
        "name": "data_volume",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Float",
        "usage": "NoPort",
        "value": 5
      },
      {
        "defaultValue": "false",
        "description": "Is this node the end of a group?",
        "encoding": "pickle",
        "id": "f678e21d-6353-43c6-b488-49381c15a3c9",
        "name": "group_end",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": true
      },
      {
        "defaultValue": "true",
        "description": "Perform a check to make sure the file path exists before proceeding with the application",
        "encoding": "pickle",
        "id": "fabd950c-ba2c-4af6-abdb-ce0184a8a9cf",
        "name": "check_filepath_exists",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": true
      },
      {
        "defaultValue": "",
        "description": "Path to the file for this node",
        "encoding": "pickle",
        "id": "81fed942-7b69-4f04-b1d2-645f9042a393",
        "name": "filepath",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      {
        "defaultValue": "",
        "description": "Name of the directory containing the file for this node",
        "encoding": "pickle",
        "id": "04896f88-7ccd-4232-b3f4-63cbfdbb9cf2",
        "name": "dirname",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      {
        "defaultValue": "true",
        "description": "Specifies whether this data component contains data that should not be deleted after execution",
        "encoding": "pickle",
        "id": "64a53019-8c5b-4502-a972-e1c9a482fa6c",
        "name": "persist",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "102d6fc6-eea7-434b-9196-65a42a79cf13",
        "name": "event",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Object.",
        "usage": "InputOutput",
        "value": ""
      }
    ],
    "data_volume": 5,
    "group_end": true,
    "check_filepath_exists": true,
    "filepath": "",
    "dirname": "",
    "persist": false,
    "event": "",
    "iid": "0-0",
    "lg_key": "e7685102-4ddf-45e1-bb82-fe9ad2c43bb0",
    "outputPorts": {},
    "inputPorts": {
      "102d6fc6-eea7-434b-9196-65a42a79cf13": {
        "type": "InputOutput",
        "name": "event",
        "source_id": "02290171-67f5-426b-9a4e-b83cd7d30acd"
      }
    },
    "port_map": {
      "event": "event"
    },
    "producers": [
      {
        "test_pg_gen_02290171-67f5-426b-9a4e-b83cd7d30acd_0-0": "event"
      }
    ],
    "consumers": [
      {
        "test_pg_gen_02290171-67f5-426b-9a4e-b83cd7d30acd_0-1": "event"
      }
    ],
    "node": "10.128.0.12",
    "island": "10.128.0.11",
    "humanReadableKey": "6_0-0"
  },
  {
    "oid": "test_pg_gen_e7685102-4ddf-45e1-bb82-fe9ad2c43bb0_0-1",
    "name": "event",
    "categoryType": "Data",
    "category": "File",
    "dropclass": "dlg.data.drops.file.FileDROP",
    "storage": "File",
    "rank": [
      0,
      1
    ],
    "reprodata": {},
    "loop_ctx": "1",
    "weight": 5,
    "applicationArgs": {
      "event": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "102d6fc6-eea7-434b-9196-65a42a79cf13",
        "name": "event",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Object.",
        "usage": "InputOutput",
        "value": ""
      }
    },
    "constraintParams": {
      "data_volume": {
        "defaultValue": "5",
        "description": "Estimated size of the data contained in this node",
        "encoding": "pickle",
        "id": "f33173ca-3919-46a2-88a7-4b31e107caf3",
        "name": "data_volume",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Float",
        "usage": "NoPort",
        "value": 5
      }
    },
    "componentParams": {
      "dropclass": {
        "defaultValue": "",
        "description": "Data class",
        "encoding": "pickle",
        "id": "493f6624-cb40-4ffe-a81c-30a1a9434fd6",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.data.drops.file.FileDROP"
      },
      "group_end": {
        "defaultValue": "false",
        "description": "Is this node the end of a group?",
        "encoding": "pickle",
        "id": "f678e21d-6353-43c6-b488-49381c15a3c9",
        "name": "group_end",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": true
      },
      "check_filepath_exists": {
        "defaultValue": "true",
        "description": "Perform a check to make sure the file path exists before proceeding with the application",
        "encoding": "pickle",
        "id": "fabd950c-ba2c-4af6-abdb-ce0184a8a9cf",
        "name": "check_filepath_exists",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": true
      },
      "filepath": {
        "defaultValue": "",
        "description": "Path to the file for this node",
        "encoding": "pickle",
        "id": "81fed942-7b69-4f04-b1d2-645f9042a393",
        "name": "filepath",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      "dirname": {
        "defaultValue": "",
        "description": "Name of the directory containing the file for this node",
        "encoding": "pickle",
        "id": "04896f88-7ccd-4232-b3f4-63cbfdbb9cf2",
        "name": "dirname",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      "persist": {
        "defaultValue": "true",
        "description": "Specifies whether this data component contains data that should not be deleted after execution",
        "encoding": "pickle",
        "id": "64a53019-8c5b-4502-a972-e1c9a482fa6c",
        "name": "persist",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      }
    },
    "fields": [
      {
        "defaultValue": "",
        "description": "Data class",
        "encoding": "pickle",
        "id": "493f6624-cb40-4ffe-a81c-30a1a9434fd6",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.data.drops.file.FileDROP"
      },
      {
        "defaultValue": "5",
        "description": "Estimated size of the data contained in this node",
        "encoding": "pickle",
        "id": "f33173ca-3919-46a2-88a7-4b31e107caf3",
        "name": "data_volume",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Float",
        "usage": "NoPort",
        "value": 5
      },
      {
        "defaultValue": "false",
        "description": "Is this node the end of a group?",
        "encoding": "pickle",
        "id": "f678e21d-6353-43c6-b488-49381c15a3c9",
        "name": "group_end",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": true
      },
      {
        "defaultValue": "true",
        "description": "Perform a check to make sure the file path exists before proceeding with the application",
        "encoding": "pickle",
        "id": "fabd950c-ba2c-4af6-abdb-ce0184a8a9cf",
        "name": "check_filepath_exists",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": true
      },
      {
        "defaultValue": "",
        "description": "Path to the file for this node",
        "encoding": "pickle",
        "id": "81fed942-7b69-4f04-b1d2-645f9042a393",
        "name": "filepath",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      {
        "defaultValue": "",
        "description": "Name of the directory containing the file for this node",
        "encoding": "pickle",
        "id": "04896f88-7ccd-4232-b3f4-63cbfdbb9cf2",
        "name": "dirname",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      {
        "defaultValue": "true",
        "description": "Specifies whether this data component contains data that should not be deleted after execution",
        "encoding": "pickle",
        "id": "64a53019-8c5b-4502-a972-e1c9a482fa6c",
        "name": "persist",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "102d6fc6-eea7-434b-9196-65a42a79cf13",
        "name": "event",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Object.",
        "usage": "InputOutput",
        "value": ""
      }
    ],
    "data_volume": 5,
    "group_end": true,
    "check_filepath_exists": true,
    "filepath": "",
    "dirname": "",
    "persist": false,
    "event": "",
    "iid": "0-1",
    "lg_key": "e7685102-4ddf-45e1-bb82-fe9ad2c43bb0",
    "outputPorts": {},
    "inputPorts": {
      "102d6fc6-eea7-434b-9196-65a42a79cf13": {
        "type": "InputOutput",
        "name": "event",
        "source_id": "02290171-67f5-426b-9a4e-b83cd7d30acd"
      }
    },
    "port_map": {
      "event": "event"
    },
    "producers": [
      {
        "test_pg_gen_02290171-67f5-426b-9a4e-b83cd7d30acd_0-1": "event"
      }
    ],
    "consumers": [
      {
        "test_pg_gen_02290171-67f5-426b-9a4e-b83cd7d30acd_0-2": "event"
      }
    ],
    "node": "10.128.0.12",
    "island": "10.128.0.11",
    "humanReadableKey": "7_0-1"
  },
  {
    "oid": "test_pg_gen_e7685102-4ddf-45e1-bb82-fe9ad2c43bb0_0-2",
    "name": "event",
    "categoryType": "Data",
    "category": "File",
    "dropclass": "dlg.data.drops.file.FileDROP",
    "storage": "File",
    "rank": [
      0,
      2
    ],
    "reprodata": {},
    "loop_ctx": "2",
    "weight": 5,
    "applicationArgs": {
      "event": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "102d6fc6-eea7-434b-9196-65a42a79cf13",
        "name": "event",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Object.",
        "usage": "InputOutput",
        "value": ""
      }
    },
    "constraintParams": {
      "data_volume": {
        "defaultValue": "5",
        "description": "Estimated size of the data contained in this node",
        "encoding": "pickle",
        "id": "f33173ca-3919-46a2-88a7-4b31e107caf3",
        "name": "data_volume",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Float",
        "usage": "NoPort",
        "value": 5
      }
    },
    "componentParams": {
      "dropclass": {
        "defaultValue": "",
        "description": "Data class",
        "encoding": "pickle",
        "id": "493f6624-cb40-4ffe-a81c-30a1a9434fd6",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.data.drops.file.FileDROP"
      },
      "group_end": {
        "defaultValue": "false",
        "description": "Is this node the end of a group?",
        "encoding": "pickle",
        "id": "f678e21d-6353-43c6-b488-49381c15a3c9",
        "name": "group_end",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": true
      },
      "check_filepath_exists": {
        "defaultValue": "true",
        "description": "Perform a check to make sure the file path exists before proceeding with the application",
        "encoding": "pickle",
        "id": "fabd950c-ba2c-4af6-abdb-ce0184a8a9cf",
        "name": "check_filepath_exists",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": true
      },
      "filepath": {
        "defaultValue": "",
        "description": "Path to the file for this node",
        "encoding": "pickle",
        "id": "81fed942-7b69-4f04-b1d2-645f9042a393",
        "name": "filepath",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      "dirname": {
        "defaultValue": "",
        "description": "Name of the directory containing the file for this node",
        "encoding": "pickle",
        "id": "04896f88-7ccd-4232-b3f4-63cbfdbb9cf2",
        "name": "dirname",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      "persist": {
        "defaultValue": "true",
        "description": "Specifies whether this data component contains data that should not be deleted after execution",
        "encoding": "pickle",
        "id": "64a53019-8c5b-4502-a972-e1c9a482fa6c",
        "name": "persist",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      }
    },
    "fields": [
      {
        "defaultValue": "",
        "description": "Data class",
        "encoding": "pickle",
        "id": "493f6624-cb40-4ffe-a81c-30a1a9434fd6",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.data.drops.file.FileDROP"
      },
      {
        "defaultValue": "5",
        "description": "Estimated size of the data contained in this node",
        "encoding": "pickle",
        "id": "f33173ca-3919-46a2-88a7-4b31e107caf3",
        "name": "data_volume",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Float",
        "usage": "NoPort",
        "value": 5
      },
      {
        "defaultValue": "false",
        "description": "Is this node the end of a group?",
        "encoding": "pickle",
        "id": "f678e21d-6353-43c6-b488-49381c15a3c9",
        "name": "group_end",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": true
      },
      {
        "defaultValue": "true",
        "description": "Perform a check to make sure the file path exists before proceeding with the application",
        "encoding": "pickle",
        "id": "fabd950c-ba2c-4af6-abdb-ce0184a8a9cf",
        "name": "check_filepath_exists",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": true
      },
      {
        "defaultValue": "",
        "description": "Path to the file for this node",
        "encoding": "pickle",
        "id": "81fed942-7b69-4f04-b1d2-645f9042a393",
        "name": "filepath",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      {
        "defaultValue": "",
        "description": "Name of the directory containing the file for this node",
        "encoding": "pickle",
        "id": "04896f88-7ccd-4232-b3f4-63cbfdbb9cf2",
        "name": "dirname",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      {
        "defaultValue": "true",
        "description": "Specifies whether this data component contains data that should not be deleted after execution",
        "encoding": "pickle",
        "id": "64a53019-8c5b-4502-a972-e1c9a482fa6c",
        "name": "persist",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "102d6fc6-eea7-434b-9196-65a42a79cf13",
        "name": "event",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Object.",
        "usage": "InputOutput",
        "value": ""
      }
    ],
    "data_volume": 5,
    "group_end": true,
    "check_filepath_exists": true,
    "filepath": "",
    "dirname": "",
    "persist": false,
    "event": "",
    "iid": "0-2",
    "lg_key": "e7685102-4ddf-45e1-bb82-fe9ad2c43bb0",
    "outputPorts": {},
    "inputPorts": {
      "102d6fc6-eea7-434b-9196-65a42a79cf13": {
        "type": "InputOutput",
        "name": "event",
        "source_id": "02290171-67f5-426b-9a4e-b83cd7d30acd"
      }
    },
    "port_map": {
      "event": "event"
    },
    "producers": [
      {
        "test_pg_gen_02290171-67f5-426b-9a4e-b83cd7d30acd_0-2": "event"
      }
    ],
    "consumers": [
      {
        "test_pg_gen_02290171-67f5-426b-9a4e-b83cd7d30acd_0-3": "event"
      }
    ],
    "node": "10.128.0.12",
    "island": "10.128.0.11",
    "humanReadableKey": "8_0-2"
  },
  {
    "oid": "test_pg_gen_e7685102-4ddf-45e1-bb82-fe9ad2c43bb0_0-3",
    "name": "event",
    "categoryType": "Data",
    "category": "File",
    "dropclass": "dlg.data.drops.file.FileDROP",
    "storage": "File",
    "rank": [
      0,
      3
    ],
    "reprodata": {},
    "loop_ctx": "3",
    "weight": 5,
    "applicationArgs": {
      "event": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "102d6fc6-eea7-434b-9196-65a42a79cf13",
        "name": "event",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Object.",
        "usage": "InputOutput",
        "value": ""
      }
    },
    "constraintParams": {
      "data_volume": {
        "defaultValue": "5",
        "description": "Estimated size of the data contained in this node",
        "encoding": "pickle",
        "id": "f33173ca-3919-46a2-88a7-4b31e107caf3",
        "name": "data_volume",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Float",
        "usage": "NoPort",
        "value": 5
      }
    },
    "componentParams": {
      "dropclass": {
        "defaultValue": "",
        "description": "Data class",
        "encoding": "pickle",
        "id": "493f6624-cb40-4ffe-a81c-30a1a9434fd6",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.data.drops.file.FileDROP"
      },
      "group_end": {
        "defaultValue": "false",
        "description": "Is this node the end of a group?",
        "encoding": "pickle",
        "id": "f678e21d-6353-43c6-b488-49381c15a3c9",
        "name": "group_end",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": true
      },
      "check_filepath_exists": {
        "defaultValue": "true",
        "description": "Perform a check to make sure the file path exists before proceeding with the application",
        "encoding": "pickle",
        "id": "fabd950c-ba2c-4af6-abdb-ce0184a8a9cf",
        "name": "check_filepath_exists",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": true
      },
      "filepath": {
        "defaultValue": "",
        "description": "Path to the file for this node",
        "encoding": "pickle",
        "id": "81fed942-7b69-4f04-b1d2-645f9042a393",
        "name": "filepath",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      "dirname": {
        "defaultValue": "",
        "description": "Name of the directory containing the file for this node",
        "encoding": "pickle",
        "id": "04896f88-7ccd-4232-b3f4-63cbfdbb9cf2",
        "name": "dirname",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      "persist": {
        "defaultValue": "true",
        "description": "Specifies whether this data component contains data that should not be deleted after execution",
        "encoding": "pickle",
        "id": "64a53019-8c5b-4502-a972-e1c9a482fa6c",
        "name": "persist",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      }
    },
    "fields": [
      {
        "defaultValue": "",
        "description": "Data class",
        "encoding": "pickle",
        "id": "493f6624-cb40-4ffe-a81c-30a1a9434fd6",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.data.drops.file.FileDROP"
      },
      {
        "defaultValue": "5",
        "description": "Estimated size of the data contained in this node",
        "encoding": "pickle",
        "id": "f33173ca-3919-46a2-88a7-4b31e107caf3",
        "name": "data_volume",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Float",
        "usage": "NoPort",
        "value": 5
      },
      {
        "defaultValue": "false",
        "description": "Is this node the end of a group?",
        "encoding": "pickle",
        "id": "f678e21d-6353-43c6-b488-49381c15a3c9",
        "name": "group_end",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": true
      },
      {
        "defaultValue": "true",
        "description": "Perform a check to make sure the file path exists before proceeding with the application",
        "encoding": "pickle",
        "id": "fabd950c-ba2c-4af6-abdb-ce0184a8a9cf",
        "name": "check_filepath_exists",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": true
      },
      {
        "defaultValue": "",
        "description": "Path to the file for this node",
        "encoding": "pickle",
        "id": "81fed942-7b69-4f04-b1d2-645f9042a393",
        "name": "filepath",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      {
        "defaultValue": "",
        "description": "Name of the directory containing the file for this node",
        "encoding": "pickle",
        "id": "04896f88-7ccd-4232-b3f4-63cbfdbb9cf2",
        "name": "dirname",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      {
        "defaultValue": "true",
        "description": "Specifies whether this data component contains data that should not be deleted after execution",
        "encoding": "pickle",
        "id": "64a53019-8c5b-4502-a972-e1c9a482fa6c",
        "name": "persist",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "102d6fc6-eea7-434b-9196-65a42a79cf13",
        "name": "event",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Object.",
        "usage": "InputOutput",
        "value": ""
      }
    ],
    "data_volume": 5,
    "group_end": true,
    "check_filepath_exists": true,
    "filepath": "",
    "dirname": "",
    "persist": false,
    "event": "",
    "iid": "0-3",
    "lg_key": "e7685102-4ddf-45e1-bb82-fe9ad2c43bb0",
    "outputPorts": {},
    "inputPorts": {
      "102d6fc6-eea7-434b-9196-65a42a79cf13": {
        "type": "InputOutput",
        "name": "event",
        "source_id": "02290171-67f5-426b-9a4e-b83cd7d30acd"
      }
    },
    "port_map": {
      "event": "event"
    },
    "producers": [
      {
        "test_pg_gen_02290171-67f5-426b-9a4e-b83cd7d30acd_0-3": "event"
      }
    ],
    "consumers": [
      {
        "test_pg_gen_02290171-67f5-426b-9a4e-b83cd7d30acd_0-4": "event"
      }
    ],
    "node": "10.128.0.12",
    "island": "10.128.0.11",
    "humanReadableKey": "9_0-3"
  },
  {
    "oid": "test_pg_gen_e7685102-4ddf-45e1-bb82-fe9ad2c43bb0_0-4",
    "name": "event",
    "categoryType": "Data",
    "category": "File",
    "dropclass": "dlg.data.drops.file.FileDROP",
    "storage": "File",
    "rank": [
      0,
      4
    ],
    "reprodata": {},
    "loop_ctx": "4",
    "weight": 5,
    "applicationArgs": {
      "event": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "102d6fc6-eea7-434b-9196-65a42a79cf13",
        "name": "event",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Object.",
        "usage": "InputOutput",
        "value": ""
      }
    },
    "constraintParams": {
      "data_volume": {
        "defaultValue": "5",
        "description": "Estimated size of the data contained in this node",
        "encoding": "pickle",
        "id": "f33173ca-3919-46a2-88a7-4b31e107caf3",
        "name": "data_volume",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Float",
        "usage": "NoPort",
        "value": 5
      }
    },
    "componentParams": {
      "dropclass": {
        "defaultValue": "",
        "description": "Data class",
        "encoding": "pickle",
        "id": "493f6624-cb40-4ffe-a81c-30a1a9434fd6",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.data.drops.file.FileDROP"
      },
      "group_end": {
        "defaultValue": "false",
        "description": "Is this node the end of a group?",
        "encoding": "pickle",
        "id": "f678e21d-6353-43c6-b488-49381c15a3c9",
        "name": "group_end",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": true
      },
      "check_filepath_exists": {
        "defaultValue": "true",
        "description": "Perform a check to make sure the file path exists before proceeding with the application",
        "encoding": "pickle",
        "id": "fabd950c-ba2c-4af6-abdb-ce0184a8a9cf",
        "name": "check_filepath_exists",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": true
      },
      "filepath": {
        "defaultValue": "",
        "description": "Path to the file for this node",
        "encoding": "pickle",
        "id": "81fed942-7b69-4f04-b1d2-645f9042a393",
        "name": "filepath",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      "dirname": {
        "defaultValue": "",
        "description": "Name of the directory containing the file for this node",
        "encoding": "pickle",
        "id": "04896f88-7ccd-4232-b3f4-63cbfdbb9cf2",
        "name": "dirname",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      "persist": {
        "defaultValue": "true",
        "description": "Specifies whether this data component contains data that should not be deleted after execution",
        "encoding": "pickle",
        "id": "64a53019-8c5b-4502-a972-e1c9a482fa6c",
        "name": "persist",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      }
    },
    "fields": [
      {
        "defaultValue": "",
        "description": "Data class",
        "encoding": "pickle",
        "id": "493f6624-cb40-4ffe-a81c-30a1a9434fd6",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.data.drops.file.FileDROP"
      },
      {
        "defaultValue": "5",
        "description": "Estimated size of the data contained in this node",
        "encoding": "pickle",
        "id": "f33173ca-3919-46a2-88a7-4b31e107caf3",
        "name": "data_volume",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Float",
        "usage": "NoPort",
        "value": 5
      },
      {
        "defaultValue": "false",
        "description": "Is this node the end of a group?",
        "encoding": "pickle",
        "id": "f678e21d-6353-43c6-b488-49381c15a3c9",
        "name": "group_end",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": true
      },
      {
        "defaultValue": "true",
        "description": "Perform a check to make sure the file path exists before proceeding with the application",
        "encoding": "pickle",
        "id": "fabd950c-ba2c-4af6-abdb-ce0184a8a9cf",
        "name": "check_filepath_exists",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": true
      },
      {
        "defaultValue": "",
        "description": "Path to the file for this node",
        "encoding": "pickle",
        "id": "81fed942-7b69-4f04-b1d2-645f9042a393",
        "name": "filepath",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      {
        "defaultValue": "",
        "description": "Name of the directory containing the file for this node",
        "encoding": "pickle",
        "id": "04896f88-7ccd-4232-b3f4-63cbfdbb9cf2",
        "name": "dirname",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": ""
      },
      {
        "defaultValue": "true",
        "description": "Specifies whether this data component contains data that should not be deleted after execution",
        "encoding": "pickle",
        "id": "64a53019-8c5b-4502-a972-e1c9a482fa6c",
        "name": "persist",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Boolean",
        "usage": "NoPort",
        "value": false
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "102d6fc6-eea7-434b-9196-65a42a79cf13",
        "name": "event",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Object.",
        "usage": "InputOutput",
        "value": ""
      }
    ],
    "data_volume": 5,
    "group_end": true,
    "check_filepath_exists": true,
    "filepath": "",
    "dirname": "",
    "persist": false,
    "event": "",
    "iid": "0-4",
    "lg_key": "e7685102-4ddf-45e1-bb82-fe9ad2c43bb0",
    "outputPorts": {},
    "inputPorts": {
      "102d6fc6-eea7-434b-9196-65a42a79cf13": {
        "type": "InputOutput",
        "name": "event",
        "source_id": "02290171-67f5-426b-9a4e-b83cd7d30acd"
      }
    },
    "port_map": {
      "event": "event"
    },
    "producers": [
      {
        "test_pg_gen_02290171-67f5-426b-9a4e-b83cd7d30acd_0-4": "event"
      }
    ],
    "consumers": [
      {
        "test_pg_gen_e39551d0-fb0f-424f-b614-43601e7cdf78_0": "event"
      }
    ],
    "node": "10.128.0.12",
    "island": "10.128.0.11",
    "humanReadableKey": "10_0-4"
  },
  {
    "oid": "test_pg_gen_e39551d0-fb0f-424f-b614-43601e7cdf78_0",
    "name": "SleepExternal",
    "categoryType": "Application",
    "category": "BashShellApp",
    "dropclass": "dlg.apps.bash_shell_app.BashShellApp",
    "storage": "BashShellApp",
    "rank": [
      0
    ],
    "reprodata": {},
    "loop_ctx": null,
    "weight": 5,
    "num_cpus": "1",
    "applicationArgs": {
      "sleep_time": {
        "defaultValue": "3",
        "description": "The amount of time to sleep",
        "encoding": "pickle",
        "id": "5ec6a650-1509-4c5a-b881-c490489816ac",
        "name": "sleep_time",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": true,
        "precious": false,
        "readonly": false,
        "type": "Integer",
        "usage": "NoPort",
        "value": 3
      },
      "event": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "b133f803-42f7-4c70-83b7-803bf8ec3035",
        "name": "event",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Object.event",
        "usage": "InputOutput",
        "value": ""
      }
    },
    "constraintParams": {
      "execution_time": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "20a89dc2-06f3-46ba-92a2-ceded21bd646",
        "name": "execution_time",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "5"
      },
      "num_cpus": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "9943f498-f481-4a80-934d-df8b4d8d65ef",
        "name": "num_cpus",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "1"
      }
    },
    "componentParams": {
      "dropclass": {
        "defaultValue": "",
        "description": "Application class",
        "encoding": "pickle",
        "id": "65b985fd-e1e6-40d9-9bdb-7c71a83c89f4",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.apps.bash_shell_app.BashShellApp"
      },
      "group_start": {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "af440add-e1e1-4e94-9c54-e574027e31aa",
        "name": "group_start",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "0"
      },
      "command": {
        "defaultValue": "sleep",
        "description": "",
        "encoding": "pickle",
        "id": "1cc5b056-7115-4cc0-b011-a8612894b15a",
        "name": "command",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "sleep"
      }
    },
    "fields": [
      {
        "defaultValue": "",
        "description": "Application class",
        "encoding": "pickle",
        "id": "65b985fd-e1e6-40d9-9bdb-7c71a83c89f4",
        "name": "dropclass",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": true,
        "type": "String",
        "usage": "NoPort",
        "value": "dlg.apps.bash_shell_app.BashShellApp"
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "20a89dc2-06f3-46ba-92a2-ceded21bd646",
        "name": "execution_time",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "5"
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "9943f498-f481-4a80-934d-df8b4d8d65ef",
        "name": "num_cpus",
        "options": [],
        "parameterType": "ConstraintParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "1"
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "af440add-e1e1-4e94-9c54-e574027e31aa",
        "name": "group_start",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Unknown",
        "usage": "NoPort",
        "value": "0"
      },
      {
        "defaultValue": "sleep",
        "description": "",
        "encoding": "pickle",
        "id": "1cc5b056-7115-4cc0-b011-a8612894b15a",
        "name": "command",
        "options": [],
        "parameterType": "ComponentParameter",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "String",
        "usage": "NoPort",
        "value": "sleep"
      },
      {
        "defaultValue": "3",
        "description": "The amount of time to sleep",
        "encoding": "pickle",
        "id": "5ec6a650-1509-4c5a-b881-c490489816ac",
        "name": "sleep_time",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": true,
        "precious": false,
        "readonly": false,
        "type": "Integer",
        "usage": "NoPort",
        "value": 3
      },
      {
        "defaultValue": "",
        "description": "",
        "encoding": "pickle",
        "id": "b133f803-42f7-4c70-83b7-803bf8ec3035",
        "name": "event",
        "options": [],
        "parameterType": "ApplicationArgument",
        "positional": false,
        "precious": false,
        "readonly": false,
        "type": "Object.event",
        "usage": "InputOutput",
        "value": ""
      }
    ],
    "execution_time": "5",
    "group_start": "0",
    "command": "sleep",
    "sleep_time": 3,
    "event": "",
    "iid": "0",
    "lg_key": "e39551d0-fb0f-424f-b614-43601e7cdf78",
    "outputPorts": {},
    "inputPorts": {
      "b133f803-42f7-4c70-83b7-803bf8ec3035": {
        "type": "InputOutput",
        "name": "event",
        "source_id": "e7685102-4ddf-45e1-bb82-fe9ad2c43bb0"
      }
    },
    "inputs": [
      {
        "test_pg_gen_e7685102-4ddf-45e1-bb82-fe9ad2c43bb0_0-4": "event"
      }
    ],
    "node": "10.128.0.12",
    "island": "10.128.0.11",
    "humanReadableKey": "11_0"
  }
]