from typing import Callable
from PySide6.QtWidgets import QVBoxLayout, QWidget, QLabel, QFrame, QToolButton
from PySide6.QtCore import QSize
from PySide6.QtGui import QColor, QMouseEvent, QPainter, QFont, QBrush
class StyledItem:
    def __init__(self, active, depth, config, theme, parent): ...
    def initUI(self): ...
    def paintEvent(self, event): ...
class StyledIcon:
    def __init__(self, size, parent): ...
    def initUI(self): ...
class StyledDotIcon:
    def __init__(self, active, parent): ...
    def initUI(self): ...
    def paintEvent(self, event): ...
class StyledSubheader:
    def __init__(self, text, theme, parent, disableGutters, disableSticky, onClick: Callable, config): ...
    def mousePressEvent(self, ev: QMouseEvent): ...
    def initUI(self): ...
class Example:
    def __init__(self): ...
    def initUI(self): ...