from typing import Callable, Optional, List, Union, Dict
import uuid
from PySide6.QtCore import QEvent, QModelIndex, Qt, QPersistentModelIndex, QTimer, Signal, QSize
from PySide6.QtWidgets import QPushButton, QHBoxLayout, QFrame, QVBoxLayout, QWidget
from qtmui.hooks import State
from qtmui.material.styles import useTheme
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
class Droppable:
    def __init__(self, onDrop: Callable, onDragMove: Callable, children: Optional[Union[State, List]], sx: Optional[Union[State, Dict, Callable, str]]): ...
    def enterEvent(self, event): ...
    def leaveEvent(self, event): ...
    def mouseReleaseEvent(self, event): ...
    def timeout(self): ...
    def left_click_event(self): ...
    def right_click_event(self): ...
    def double_click_event(self): ...
    def dragEnterEvent(self, e): ...
    def dragLeaveEvent(self, event): ...
    def dragMoveEvent(self, event): ...
    def dropEvent(self, event): ...
    def _set_stylesheet(self): ...