import asyncio
from typing import Optional, List, Callable, Union
from PySide6.QtCore import QTimer
from PySide6.QtWidgets import QWidget, QScrollArea
from .anim_controller import AnimationController
from qtmui.hooks import State
class AnimManager:
    def __init__(self, sx, **kwargs): ...
    def on_variants_changed(self, new_variants): ...
    def _children_animation(self): ...
    def _children_apply_initial(self, fn): ...
    def setup_child(self, child: QWidget): ...
    def getVariants(self): ...
    def find_scroll_area(self): ...
    def _animate_visible_children(self, scroll_pos: int): ...
    def _runAnimation(self): ...
    def _animCtlPlayTask(self): ...
    def showEvent(self, event): ...