from typing import List
from PySide6.QtWidgets import QGraphicsDropShadowEffect
from PySide6.QtGui import QColor, QPalette
from qtmui.material.system.color_manipulator import rgbaToQColor, hex_string_to_qcolor
class ShadownEffect:
    def __init__(self): ...
    def _setShadownEffect(self, shadow): ...
    def _blur_for_elevation(self, elevation: int): ...